### ISSUE TITLE
Allow to select the fields that will be exported 

### ISSUE THREAD

**Issue by dcu** [rwynn/monstache#1]
Similar to stripe's mosql.
In my case I don't want to export fields that contain sensitive data. For example PII data, keys, passwords, etc even if this data is hashed or encrypted.

**Comment by rwynn** [comment]
I am planning to integrate the Otto embedded JavaScript engine which will allow you to specify a mapping function per collection in the TOML config file.  This will allow you to drop, add, and modify fields.  Should be done by end of week.
