### ISSUE TITLE
Binary Files from Non GridFS Collections

### ISSUE THREAD

**Issue by nitineman** [rwynn/monstache#100]
Hi,

Im trying to onboard an application where multiple collections with its corresponding Binary File. The Monstache project seems exciting to go ahead for our purposes.

- The dummy document which we store in the actual Collection and in another Binary File collection which holds the reference (actual) document and the Metatdata and Binary File Array within the collection. 

- Can you please help with the way to ingest both the collections so that we can correlate the two documents and extract the text content of the Binary files into the elasticsearch for match/term/fuzzy etc based text searches as needed.

- Also will there be any support for Change Streams in the near future to selectively choose transactions/CRUD operations from the elected Collections of source MongoDB.

{
    "_id" : ObjectId("5b9063614d889f378ae055b3"),
    "tweetId" : "5b9063614d889f378ae055b3",
    "author" : "Player1 Lastname1",
    "directoryId" : NumberLong(1234567),
    "tweet" : "TestFullFetchInsert_Local for the Twitter fact_measure1 and geo1 for Pg1",
    "hashTagList" : [ 
        "Pg1", 
        "geo1", 
        "fact_measure1"
    ],
    "createdDateTimeStamp" : ISODate("2018-09-05T23:14:41.258Z"),
   	"fileAttachmentKey" : true,
    "**binaryFileMetadatas**" : [ 
        {
            "fileName" : "connect.sh",
            "fileDescription" : "FILE DESCRIPTION",
            "fileDisplayName" : "connect.sh",
            "fileType" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "fileMetadata" : "X-Parsed-By=org.apache.tika.parser.DefaultParser X-Parsed-By=org.apache.tika.parser.pkg.PackageParser Content-Type=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        }
    ],
"fileUploadId" : "5b7475136bcdbd7a9f8dfa24"
}

BELOW, BINARY File Collection with binaryfileList holding the MongoDB saved data. 

{
    "_id" : ObjectId("5b7475136bcdbd7a9f8dfa24"),
    "twitterModel" : {
        "_id" : ObjectId("5b7475136bcdbd7a9f8dfa1f"),
        "tweetId" : "123",
        "author" : "Player1 Lastname1",
        "dsId" : NumberLong(1234567),
        "comment" : "TestFullFetchFile0815_shelltext for the Twitter fact_measure1 and geo1 for Pg1",
        "hashTagList" : [ 
            "Pg1", 
        "geo1", 
        "fact_measure1"
        ],
        "createdDateTimeStamp" : ISODate("2018-08-15T18:46:43.651Z"),
        "createdDate" : "8-15-2018 11:46:43",
        "fileAttachmentKey" : true,
        "**binaryFileMetadatas**" : [ 
            {
                "fileName" : "connect.sh",
                "fileDescription" : "FILE DESCRIPTION",
                "fileDisplayName" : "connect.sh",
                "fileType" : "text/plain",
                "fileMetadata" : "X-Parsed-By=org.apache.tika.parser.DefaultParser X-Parsed-By=org.apache.tika.parser.txt.TXTParser Content-Encoding=ISO-8859-1 Content-Type=text/plain; charset=ISO-8859-1"
            }
        ]
    },
    "**binaryFileList**" : [ 
        { "$binary" : "ZWNobyBgZGF0ZWAsKY3VybDAtSCAnYXswLWlkOiAzNjgxJyAtSCAnZdHMtaWQ6IDE4NjMzhkjdhfGHJbcvbn21OTE0NTcnIC1IICdhcHAtdG9rZW46IEJ1SWNHY1BYR2kvaFJnRFd5MWRqMkk4cjZ4a1RMTWZZNlM3QVJQL25VYYE9OjhpanU4M2F3em1kZXZ4anR2MmtrOjE1MzQzODQ1Mzg4MjQ6MScgaHR0cDovL2xvY2FsaG9zdDo4NDQzL2ljb21tcy9kb21tZW50cy9kb3dubG9hZC81YjczYzdjYzZiY2RiZDdhOWY4ZGY5YzQvMAplY2hvIGBkYXRlYAo=", "$type" : "00" }
    ],
    "metaDataList" : [ 
        {
            "fileName" : "connect.sh",
            "fileDescription" : "FILE DESCRIPTION",
            "fileDisplayName" : "connect.sh",
            "fileType" : "text/plain",
            "fileMetadata" : "X-Parsed-By=org.apache.tika.parser.DefaultParser X-Parsed-By=org.apache.tika.parser.txt.TXTParser Content-Encoding=ISO-8859-1 Content-Type=text/plain; charset=ISO-8859-1"
        }
    ]
}

**Comment by nitineman** [comment]
Hi @rwynn ,

The only advantage I was checking out for was aggregate pipeline which will give flexible control on oplog watch on the desired collections and the CRUD operations.

Also, can you please suggest whether my understanding is correct - A 3 replica set MongoDB server with oplog setup on BareMetal hardware(non VM linux) administered by DBAs and not our DevOPS team can still be subscribed by an external application like monstache on the same DataCenter Linux VM.

For our ecosystem we can control installation and scaling up of ElasticSearch clusters from Application  DevOps team but not the MongoDB servers and its maintenance since that will be our Primary/Mainstay DB and only minimal App Team access will be provided by the DBA team.

**Comment by rwynn** [comment]
@nitineman you should be able to accomplish what you need by creating a golang plugin and implementing the `Map` function.  Within this function you have access to the `mgo.Session` which you can use to cross reference the 2nd collection and retrieve the binary.  You would just need to convert that binary to base64 and set it on the output of the `Map` function.  This is basically what monstache does with GridFS files.  

You can add the namespace of the first collection to the `file-namespaces` option in monstache.  This will tell monstache to create a pipeline named `attachment` that will process an field named `file` as a base64 encoded file.  So you can use the property name `file` for the base64 encoded value.  Also make sure to set the Pipeline field to `attachment` in this case.

You will also need to install the ingest-attachment plugin in Elasticsearch.

**Comment by nitineman** [comment]
Thanks  @rwynn I will take note of this and will come back in case of any further concerns.
