### ISSUE TITLE
Getting tailing oplog entries error when using resume mode. 

### ISSUE THREAD

**Issue by sbnajardhane** [rwynn/monstache#102]
Hi @rwynn ,
I am continuously getting this error in my Monstache error.log when resume mode is set to true. Though everything is working fine, last update time is being stored properly into the monstache.monstache collection, also the data is syncing properly.

ERROR 2018/09/17 12:03:27 Error tailing oplog entries: read tcp 127.0.0.1:35402->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 12:03:37 Error tailing oplog entries: read tcp 127.0.0.1:35408->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 12:03:47 Error tailing oplog entries: read tcp 127.0.0.1:35420->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 12:03:57 Error tailing oplog entries: read tcp 127.0.0.1:35422->127.0.0.1:27017: i/o timeout

This is my config.toml file
```
mongo-url = "mongodb://localhost:27018"  ## (connecting to mongo secondary, tried connection to mongo primary as well, stilll same error)
elasticsearch-urls = ["http://localhost:9200"]
workers = ["w1", "w2"]
gzip = true
index-as-update = true
fail-fast = false
prune-invalid-json = true
index-oplog-time = true
resume = true
replay = false
resume-name = "HA"
[logs]
info = "/path/to/logs/info.log"
warn = "/path/to/logs/warn.log"
error = "/path/to/logs/error.log"
```

Please suggest if I am doing something wrong.

**Comment by rwynn** [comment]
Is this with the very latest version of monstache?  There was some work on adjusting the default timeouts lately. 

Looks like this error is happening every 10 seconds.

**Comment by sbnajardhane** [comment]
I am using v4.9.0.
I have tried with the latest version v4.10.1 also, still getting the same error
tried with these configurations. (added at the end of config):
[mongo-dial-settings]
timeout=10
read-timeout=600
write-timeout=30

[mongo-session-settings]
socket-timeout=600
sync-timeout=600

**Comment by rwynn** [comment]
Can you try upping the 1st timeout to 600?  Then check how far apart the error log messages are?  

Then finally try setting the first 3 timeouts above to 0.

**Comment by sbnajardhane** [comment]
For first config timeout - 600, getting the error after 10s
```
ERROR 2018/09/17 18:20:18 Error tailing oplog entries: read tcp 127.0.0.1:51800->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:20:28 Error tailing oplog entries: read tcp 127.0.0.1:51804->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:20:38 Error tailing oplog entries: read tcp 127.0.0.1:51806->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:20:48 Error tailing oplog entries: read tcp 127.0.0.1:51812->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:20:58 Error tailing oplog entries: read tcp 127.0.0.1:51818->127.0.0.1:27017: i/o timeout
```

Same for the 2nd one
```
ERROR 2018/09/17 18:24:23 Error tailing oplog entries: read tcp 127.0.0.1:51984->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:24:33 Error tailing oplog entries: read tcp 127.0.0.1:51994->127.0.0.1:27017: i/o timeout
ERROR 2018/09/17 18:24:43 Error tailing oplog entries: read tcp 127.0.0.1:51988->127.0.0.1:27017: i/o timeout
```

**Comment by rwynn** [comment]
You mentioned “when resume mode is true”.  Do you not see this error if resume is false?

**Comment by sbnajardhane** [comment]
Yes, only if resume = true
not getting this error if I set resume to false.

**Comment by rwynn** [comment]
Ok I’ll look into it.  Thanks.

**Comment by rwynn** [comment]
@sbnajardhane please give the latest release a shot and let me know.  I was not immediately able to reproduce the issue with resume enabled.  But I did make some changes specifically in the resume case to remove some socket timeouts being set.

**Comment by sbnajardhane** [comment]
@rwynn  yes, it worked. thanks for the quick response. :+1:

**Comment by sbnajardhane** [comment]
@rwynn Help Required,
I am sure about how to use the workers.
Could you please explain more about the workers? How many workers should I create so that I am not underutilizing or over killing? (consider during peak time, 50 oplog/sec entries are getting created, so what should be the workers' config.) 
Also how to start multiple workers using systemd config?
