### ISSUE TITLE
Is it possible to access elasticsearch from Javascript middleware?

### ISSUE THREAD

**Issue by purno998** [rwynn/monstache#103]
From javascript we have access to some global functions like _findId_, _findOne_ to retrieve documents from MongoDB. Are there any similar functions to retrieve documents from Elasticseach as well? Or is there any way to access the Elasticsearch client from javascript?

**Comment by rwynn** [comment]
No it is not currently possible in JavaScript.  

You would need to use a go plugin and implement the Process function which gets access to everything.
