### ISSUE TITLE
Workers are not syncing data to elastic cluster

### ISSUE THREAD

**Issue by sbnajardhane** [rwynn/monstache#104]
@rwynn Help Required,
All Workers are not syncing to the elastic cluster. 
I have this config file and I have started 3 workers using
```
monstache -f config.toml -worker w1
monstache -f config.toml -worker w2
monstache -f config.toml -worker w3
```
So after starting 3 workers, the syncing process is working fine.
I am assuming that multiple workers will distribute the work between them and if any of the workers go down another two will continue syncing.
So, I killed w3 worker, w1 and w2 are running but not syncing to the elastic cluster.
I have observed that only worker w3 is syncing the data and other workers w1, w2 are not doing any job. Even if I kill w1, w2, is doesn't affects the syncing process of w3.
Same happend in case of cluster mode,
```
mongo-url = "mongodb://localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]

workers = ["w1", "w2", "w3"]
gzip = true
index-as-update = true
fail-fast = false
index-oplog-time = true 
resume = true
replay = false
resume-name = "HA"

[[mapping]]
namespace = "ss_db.ssfbusermapping"
index = "ssfbusermapping"
type = "_doc"

[mongo-dial-settings]
timeout=15
read-timeout=0
write-timeout=0
[mongo-session-settings]
socket-timeout=0
sync-timeout=0

```
I am sure about how to use the workers.
Could you please explain more about the workers? How many workers should I create so that I am not underutilizing or over killing? (consider during peak time, 50 oplog/sec entries are getting created, so what should be the workers' config.)
Also how to start multiple workers using systemd config?

**Comment by rwynn** [comment]
Sounds like you don’t need workers but high availability. Remove the workers config and just give all process the same cluster-name. 

For systemd you can just create a unit file per processes.

**Comment by rwynn** [comment]
If you do want to combine ha (cluster-name) with workers then you need to have multiple processes for each worker name.  You can have 3 worker A but at least one worker A must be running at any given time.

**Comment by sbnajardhane** [comment]
ok, High availability mode will work for me. Thanks
Will look into workers if required.
