### ISSUE TITLE
Error using sharded mongo

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#105]
@rwynn I need your help

I'm using your docker image and can't connect to the shards.
Bellow are the info and error logs.
**info:**
INFO 2018/09/19 17:49:32 Successfully connected to MongoDB version 3.2.16
INFO 2018/09/19 17:49:32 Successfully connected to Elasticsearch version 5.6.3
INFO 2018/09/19 17:49:32 Adding shard found at SVLMNIQDB04:27018?replicaSet=repSet01
INFO 2018/09/19 17:49:42 Shutting down with exit status 1 after panic.
**error:**
ERROR 2018/09/19 17:49:42 Unable to connect to mongodb shard using URL SVLMNIQDB04:27018?replicaSet=repSet01: no reachable servers

As you can see I successfully connect to both Mongo and ES, the problem is when monstache tries to connect to the shards.
I used ping to be sure that the machine could resolve the SVLMNIQDB04 URL. It can.
And the port is open.

So right now I don't know what I'm doing wrong.....

On a side note, I may have detected a bug:
I'm using a sharded mongo but my config file didn't had the mongo-config-url option.
I was able to connect to mongo and es, but when I tried to do a direct read, I got an error.
**Config.file:**
direct-read-namespaces = ["nPVR_STABLE.Recording", "nPVR_STABLE.User"]
**error:**
ERROR 2018/09/19 14:17:53 Error reading collection stats for nPVR_STABLE.User. Used to calibrate batch size.: Database [nPVR_STABLE] not found.
ERROR 2018/09/19 14:17:53 Error reading collection stats for nPVR_STABLE.Recording. Used to calibrate batch size.: Database [nPVR_STABLE] not found.

I'm assuming that it failed (and rightly so) because the mongo-config-url option was missing, but the error message only says that it can't find the collections when the collections are there.
Perhaps you should throw a different error ?

Can you help me?
Thanks

**Comment by rwynn** [comment]
Does a similar error happen if you try to connect directly to the mongod shard only by specifying it’s URL in mongo-url and clearing mongo-config-url?

**Comment by rwynn** [comment]
I wasn't able to replicate the issue immediately but I have the sharded cluster running in a single VM.  Did you execute the ping from inside the monstache Docker container?

This is what I'm getting.

```
vagrant@debian-8:~/mongo$ ~/go/bin/monstache -mongo-url localhost:27019 -mongo-config-url localhost:27017 -verbose
INFO 2018/09/20 04:04:21 Started monstache version 4.10.2
INFO 2018/09/20 04:04:21 Successfully connected to MongoDB version 3.6.4
INFO 2018/09/20 04:04:21 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/09/20 04:04:21 Adding shard found at 127.0.0.1:27018?replicaSet=s
INFO 2018/09/20 04:04:21 Adding shard found at 127.0.0.1:27020?replicaSet=s2
INFO 2018/09/20 04:04:21 Adding shard found at 127.0.0.1:27021?replicaSet=s3
INFO 2018/09/20 04:04:22 Listening for events
INFO 2018/09/20 04:04:22 Sending systemd READY=1
WARN 2018/09/20 04:04:22 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
TRACE 2018/09/20 04:05:51 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.5 (linux-amd64)
Content-Length: 148
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5ba31c9f94992930a7c35aa8","_type":"_doc","version":6603152947880656897,"version_type":"external"}}
{"foo":99}

TRACE 2018/09/20 04:05:52 HTTP/1.1 200 OK
Content-Length: 259
Content-Type: application/json; charset=UTF-8

{"took":910,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5ba31c9f94992930a7c35aa8","_version":6603152947880656897,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}

```

**Comment by BrunoPereira** [comment]
> I wasn't able to replicate the issue immediately but I have the sharded cluster running in a single VM. Did you execute the ping from inside the monstache Docker container?
No, I ping the shard from the server where the container is running.



> Does a similar error happen if you try to connect directly to the mongod shard only by specifying it’s URL in mongo-url and clearing mongo-config-url?
error.log:
Unable to connect to mongodb using URL mongodb://SVLMNIQDB04:27017: no reachable servers
So it might be a network problem to that specific port.
Tnx, I'll investigate


> On your side note: What happens if you connect to that same URL (I’m assuming you used the mongos url) using the mongo console and execute the collstats query.
mongos> db.runCommand({ collStats: "Recording" })
{
        "sharded" : false,
        "primary" : "repSet01",
        "ns" : "nPVR_STABLE.Recording",
......
The answer is quite big.... So using the console I can find the data.

**Comment by rwynn** [comment]
I'm by no means a Docker expert but I've used these params in the past to give the container the same network stack as the host:

```
docker run --rm --net=host
```

**Comment by BrunoPereira** [comment]
> I'm by no means a Docker expert but I've used these params in the past to give the container the same network stack as the host
> 
> ```
> docker run --rm --net=host
> ```

Usually, if you don't change it, the container has the same "exterior" connections as the server he's running.
And when I tried to connect to that port using telnet I couldn't , so it was a network problem.

**So, that problem is solved....now I have a new problem:**

docker run -v ~/monstache/:/tmp/ rwynn/monstache:rel3 -f /tmp/config.toml
panic: Unable to get collection names 
		for database local: can't use 'local' database through mongos

goroutine 206 [running]:
**error-log:**
ERROR 2018/09/20 17:51:54 Error reading collection stats for nPVR_STABLE.Recording. Used to calibrate batch size.: Database [nPVR_STABLE] not found.
ERROR 2018/09/20 17:51:54 Error reading collection stats for nPVR_STABLE.User. Used to calibrate batch size.: Database [nPVR_STABLE] not found.
ERROR 2018/09/20 17:51:54 Error reading collection stats for nPVR_STABLE.User. Used to calibrate batch size.: Database [nPVR_STABLE] not found.
ERROR 2018/09/20 17:51:54 Error reading collection stats for nPVR_STABLE.Recording. Used to calibrate batch size.: Database [nPVR_STABLE] not found.
**info-log:**
INFO 2018/09/20 17:51:54 Started monstache version 3.17.2
INFO 2018/09/20 17:51:54 Successfully connected to MongoDB version 3.2.16
INFO 2018/09/20 17:51:54 Successfully connected to Elasticsearch version 5.6.3
INFO 2018/09/20 17:51:54 Adding shard found at SVLMNIQDB04:27018?replicaSet=repSet01
INFO 2018/09/20 17:51:54 Adding shard found at SVLMNIQDB05:27018?replicaSet=repSet02
INFO 2018/09/20 17:51:54 Adding shard found at SVLMNIQDB06:27018?replicaSet=repSet03
INFO 2018/09/20 17:51:54 Listening for events

**config:**
namespace-regex = "^nPVR_STABLE.(Recording|User)$"
direct-read-namespaces = ["nPVR_STABLE.Recording", "nPVR_STABLE.User"]
exit-after-direct-reads = false

[[mapping]]
namespace = "nPVR_STABLE.Recording"
index = "test-npvr-recording"
type = "recording"

[[mapping]]
namespace = "nPVR_STABLE.User"
index = "test-npvr-recording"
type = "user"

So now I can connect to mongo config and all the shards, to elastic, but he still can't find the collections

PS: Tnx for your help

**Comment by rwynn** [comment]
No idea why it would be using the mongos connection to connect to local.  It should be using the mongod connections for each shard.

Without too much detail it should be finding the shards and creating a list of mgo sessions for those shards.  This list is then passed to a library called gtm that works reads from each shard.  These should be normal mongod instances with access to `local` database.

https://github.com/rwynn/monstache/blob/rel3/monstache.go#L3098

So by the time it gets to here:
https://github.com/rwynn/monstache/blob/rel3/monstache.go#L3145
all the sessions passed to StartMulti should be mongod not mongos.

Are you still supplying?
```
mongo-url = "URL to mongos"
mongo-config-url = "URL to the mongod config server with the config.shards collection"
```

**Comment by rwynn** [comment]
For example, I get the same error if I try to set both URLs to the mongos server.

```
vagrant@debian-8:/vagrant/monstache$ go run monstache.go -mongo-url localhost:27019 -mongo-config-url localhost:27019
INFO 2018/09/20 19:06:01 Started monstache version 4.10.2
INFO 2018/09/20 19:06:01 Successfully connected to MongoDB version 3.6.4
INFO 2018/09/20 19:06:01 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/09/20 19:06:01 Adding shard found at 127.0.0.1:27018?replicaSet=s
INFO 2018/09/20 19:06:01 Adding shard found at 127.0.0.1:27020?replicaSet=s2
INFO 2018/09/20 19:06:01 Adding shard found at 127.0.0.1:27021?replicaSet=s3
INFO 2018/09/20 19:06:01 Listening for events
panic: Unable to get collection names 
                for database local: Can't use 'local' database through mongos

goroutine 141 [running]:
github.com/rwynn/gtm.OpLogCollectionName(0xc0003e9860, 0xc0000915f0, 0xc000178d80, 0xc0003e9860)
        /home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:777 +0x2db
github.com/rwynn/gtm.(*Options).Fill(0xc0000915f0, 0xc0003e9860)
        /home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1385 +0x7e
github.com/rwynn/gtm.TailOps(0xc000068300, 0xc0001a4680, 0xc00019c028, 0x1, 0x1, 0xc0000915f0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:823 +0xe0
created by github.com/rwynn/gtm.Start
        /home/vagrant/go/src/github.com/rwynn/gtm/gtm.go:1601 +0x54b
exit status 2

// Fixed for me by changing 2nd URL to config server mongod

vagrant@debian-8:/vagrant/monstache$ go run monstache.go -mongo-url localhost:27019 -mongo-config-url localhost:27017
INFO 2018/09/20 19:06:41 Started monstache version 4.10.2
INFO 2018/09/20 19:06:41 Successfully connected to MongoDB version 3.6.4
INFO 2018/09/20 19:06:41 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/09/20 19:06:41 Adding shard found at 127.0.0.1:27018?replicaSet=s
INFO 2018/09/20 19:06:41 Adding shard found at 127.0.0.1:27020?replicaSet=s2
INFO 2018/09/20 19:06:41 Adding shard found at 127.0.0.1:27021?replicaSet=s3
INFO 2018/09/20 19:06:41 Listening for events
```

**Comment by rwynn** [comment]
I also think I might know what the database not found errors mean.  With sharding some of the shards might not have data yet in which case the database would not exist yet.  

This happened to me with 3 shards where only 1 actually had an data in the collection. 
The following actually **successfully** synced all 3 documents from the total of 3 shards.  But only 1 shard actually had data in it for `test.test` and the other 2 shards did not.  That corresponds to the 2 error messages about database not existing.

```
vagrant@debian-8:/vagrant/monstache$ go run monstache.go -mongo-url localhost:27019 -mongo-config-url localhost:27017 -direct-read-namespace test.test -exit-after-direct-reads
INFO 2018/09/20 19:16:53 Started monstache version 4.10.2
INFO 2018/09/20 19:16:53 Successfully connected to MongoDB version 3.6.4
INFO 2018/09/20 19:16:53 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/09/20 19:16:53 Adding shard found at 127.0.0.1:27018?replicaSet=s
INFO 2018/09/20 19:16:53 Adding shard found at 127.0.0.1:27020?replicaSet=s2
INFO 2018/09/20 19:16:53 Adding shard found at 127.0.0.1:27021?replicaSet=s3
INFO 2018/09/20 19:16:53 Listening for events
ERROR 2018/09/20 19:16:53 Error reading collection stats for test.test. Used to calibrate batch size.: Database [test] not found.
ERROR 2018/09/20 19:16:53 Error reading collection stats for test.test. Used to calibrate batch size.: Database [test] not found.
INFO 2018/09/20 19:16:56 Shutting down
exit status 1
```

**Comment by BrunoPereira** [comment]
@rwynn Can't thank you enough 
Like you suggested, the port from mongo-url was wrong....everything is running now.

On the side note, now that everything is running, I removed the mongo-config-url option and this is the result:
panic: Unable to get collection names 
		for database local: can't use 'local' database through mongos

goroutine 68 [running]:

Originally I was connecting directly to one of the shards, that's why I had all those problems.

As far as I'm concern, you can close this.
Once again, thanks.
