### ISSUE TITLE
monstache exits without error messages

### ISSUE THREAD

**Issue by alexdpoon** [rwynn/monstache#106]
I'm having an issue where monstache runs fine when it runs, but exits for no reason.  Sometimes it will run for 24+ hours without issue, and other times it will quit after 2 hours.   No error messages are outputted when the process exits, so it's really difficult to figure out the reason.  For now, I've had to turn on the http server and thing use an external http-based monitoring service to alert me when it goes down, then I manually start it up again with resume = true.

I'm running Elasticsearch and MongoDb on the same machine that monstache is running.  Versions are monstache v4.10.2, ES 6.4, MongoDb 3.6.6, and Centos7.

**Comment by alexdpoon** [comment]
This is my config file:

```
mongo-url = "mongodb://[REDACTED]@localhost:39898/[REDACTED]"
elasticsearch-urls = [ "http://localhost:19288/" ]
elasticsearch-max-conns = 10
replay = false
resume = true
resume-name = "local"
namespace-regex = "^[REDACTED]$"
gtm-channel-size = 200
file-highlighting = false
verbose = false
enable-http-server = true
```

The machine is not memory-constrained so I'm pretty sure the OS isn't killing it.

**Comment by rwynn** [comment]
What is the last thing it logs?  Do you have it running as a service?  How are you running it?

I don’t see any obvious places in the code where it would just Exit() without logging something informational first.  Even a panic in go should be logged in my experience.

**Comment by rwynn** [comment]
You said you restart it manually but couldn’t you just use systemd or something to auto restart it. The docs have a systemd section under advanced.

**Comment by rwynn** [comment]
@alexdpoon Are you still seeing this issue? Thanks.

**Comment by alexdpoon** [comment]
Strangely, it hasn't happened since my last post, 12 days ago.  But I haven't changed anything -- still running it manually from the command line.  Not sure why it's running solidly right now, but I'm happy.  I'll comment here if it starts quitting on me again.
