### ISSUE TITLE
MongoDB View Replication

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#107]
I have an interesting idea that I might try and work on... we are looking to make use of MongoDB views more in our applications, with the concept that our aggregate view constructs the document we wish to be present in Elasticsearch, thereby offloading a lot of work to the database and reducing the complexity of queries to ES.

The issue I see is that the opLog will only detail changes to the MongoDB collections that comprise the view. The idea I am toying with is that using a Monstache config setting we could define an array of collections that make up the view, and then when one of those collections are detected as having an update in the opLog we then go to the named MongoDB view. This would then in effect allow for the replication of complex views built up out of aggregates and could be quite a powerful concept for searching data in ES.

I'll refresh myself with the Monstache code to see if this is viable, and then fork, but if you have any pointers/suggestions/ideas would love to hear them.

**Comment by rwynn** [comment]
This can be done in recent versions of monstache using the new pipeline settings which allow you to return aggregation stages with a $match clause. 

You can even apply stages to a change stream but it seems certain stages are not allowed on change streams in my testing.

**Comment by rwynn** [comment]
Views would also work as you mentioned in any place a namespace is required. But I think I needed to make one change to gtm since setting the cursor timeout to 0 only works for collections not views. 

For the oplog changes you can code a Golang or JavaScript function to find the doc in the view corresponding to the doc that changed (insert/update) and return the doc from the view for indexing.

**Comment by Crispy1975** [comment]
I assume the new pipeline settings require MongoDB 3.6 so the change streams API is available?

**Comment by Crispy1975** [comment]
We now use a Golang plugin over the Javascript scripts we had before to do ETL, so that could be a reasonable place to get the view doc and return.

**Comment by rwynn** [comment]
I think you could possibly use the pipeline for the direct reads only pre 3.6. You only need 3.6 for the new change-stream-namespaces option. 

The pipeline for direct reads just uses the aggregation framework which is older than change streams.

**Comment by rwynn** [comment]
If you use the Golang plugin you halve access to the mgo session in the Map function. The Map function will be sent docs from the view directly in the case of direct reads or from the underlying collection in the case source was oplog.

In oplog case the namespace will be to the underlying collection. In this case use mgo session to find in the view, and return from view instead.

**Comment by Crispy1975** [comment]
That seems like a pretty good interim solution, we're on MongoDB 3.4 right now, so using the Golang plugin will probably give us the most immediate results. I will play with this a little today and see what I can get work (plus look at the pipeline stuff). :-)

**Comment by rwynn** [comment]
Just made this change in gtm to hopefully allow you to use views in your `direct-read-namespaces` setting. 

https://github.com/rwynn/gtm/commit/c21f986c933a5e23b3ccc1ed1c1ffa00b48e5a04

Obviously, you'll need to rebuild monstache with this update.  Good luck.

**Comment by Crispy1975** [comment]
Thanks, appreciated. :+1:

**Comment by Crispy1975** [comment]
Looks like a direct read won't work out of the box:
```shell
$ monstache -mapper-plugin-path transform.so -f ~/Projects/monstache.toml --direct-read-namespace test.testView
INFO 2018/09/20 14:47:45 Successfully connected to MongoDB version 3.4.17
INFO 2018/09/20 14:47:45 Successfully connected to Elasticsearch version 6.2.2
INFO 2018/09/20 14:47:45 Joined cluster blocal
INFO 2018/09/20 14:47:45 Starting work for cluster blocal
INFO 2018/09/20 14:47:45 Entering event loop
ERROR 2018/09/20 14:47:45 Error reading collection stats for test.testView. Used to calibrate batch size.: Namespace test.testView is a view, not a collection
```

**Comment by rwynn** [comment]
That should not be a fatal error though -only used to tune the batch size of the reads but not required.  Did it continue to read the view? I created a view of a large collection (20m docs)  where the view had a $match on 1 record.

Here was the output I got (it indexed the 1 doc from the view):

```
vagrant@debian-8:/vagrant/monstache$ time go run monstache.go -direct-read-namespace test.testview -exit-after-direct-reads -verbose
INFO 2018/09/20 15:17:56 Started monstache version 4.10.2
INFO 2018/09/20 15:17:56 Successfully connected to MongoDB version 3.6.4
INFO 2018/09/20 15:17:56 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/09/20 15:17:56 Listening for events
INFO 2018/09/20 15:17:56 Sending systemd READY=1
WARN 2018/09/20 15:17:56 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
ERROR 2018/09/20 15:17:56 Error reading collection stats for test.testview. Used to calibrate batch size.: Namespace test.testview is a view, not a collection
INFO 2018/09/20 15:17:57 Shutting down
TRACE 2018/09/20 15:17:57 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.5 (linux-amd64)
Content-Length: 189
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.testview","_id":"5b9688e12232b09649655c64","_type":"_doc","version":6603326142436868096,"version_type":"external"}}
{"d":"2018-09-10T15:06:48.9Z","i":10,"s":"foo"}

TRACE 2018/09/20 15:17:57 HTTP/1.1 200 OK
Content-Length: 263
Content-Type: application/json; charset=UTF-8

{"took":220,"errors":false,"items":[{"index":{"_index":"test.testview","_type":"_doc","_id":"5b9688e12232b09649655c64","_version":6603326142436868096,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
exit status 1

real    0m3.944s
user    0m2.148s
sys     0m0.792s
```

**Comment by rwynn** [comment]
Just added check to gtm to suppress that error on views.

**Comment by Crispy1975** [comment]
Ok, got the view replication working ok with new builds from master. All good there. However - and perhaps this is me not explaining properly - once started I want the view replication to continue. Right now it syncs all view docs on start-up and then does not continue. I have the plugin also monitoring the component collections and I can force the ES index to be written to by grabbing the view doc with the mgo session. That works. I am guessing this is the only way to proceed with MongoDB 3.4.

Perhaps this is where we need to upgrade to 3.6 for the change stream stuff, but not sure if that would be able to monitor views as to my knowledge they only produce data at the last run...

**Comment by rwynn** [comment]
Can you explain what you mean by continue? Monstache should already continue running and listen for changes in the underlying collections.  These changes should get mapped into the view and synced through your plugin.  

Did you mean periodically re-read the entire view?  I've hesitated from putting direct-read scheduling into monstache since monstache can be fired by an external scheduler.

**Comment by Crispy1975** [comment]
No, I mean just keep the ES index in sync with the MongoDB view. Unless I detect the collection changes in the plugin and then read the view and push that back to ES it cannot get the updated data in ES.

I had made the assumption that the direct read pipeline option would keep the view in sync, but that does not seem to be the case, I have to use a combination of that and the plugin?

**Comment by rwynn** [comment]
@Crispy1975 
Check the latest code in master.  You can now do the following without a plugin:

```
direct-read-namespaces = [ "test.testview" ]

[[mapping]]
namespace = "test.testview"
index="myindex"

[[mapping]]
namespace = "test.test"
index = "myindex"

[[replace]]
namespace = "test.test"
with-namespace = "test.testview"
```
That will read from the view and automatically replace changes to the collection with the corresponding (match on _id) document from the view.

Replace is a generic thing and you can even specify `src-field` and `match-field` on it.  Those both default to `_id`.

**Comment by Crispy1975** [comment]
Awesome, thanks @rwynn 

So with a view it could comprise multiple collections (`$lookup` making "joins"), this would work on the primary view collection, which is cool. But if I want to update the synced view in ES from one of the other composite collections that might be making the view using `$lookup` I obviously need to detect that in the plugin still?

**Comment by rwynn** [comment]
Yeah I guess you would need to do that in the plugin. There is a new Process method that the plugin supports that gives you access to everything (mgo, elastic, and the bulk processor). You could detect updates to the joined collections and either (1) update timestamps in Mongo to force indexing (2) do the indexing directly.

**Comment by rwynn** [comment]
By the way if you get this working would you possibly be able to contribute a section to the monstache-site docs website?  That would be really helpful if possible.

**Comment by Crispy1975** [comment]
Yeah, of course, will make a PR for the docs on Monday once I've had a chance to test more fully. :+1:

**Comment by Crispy1975** [comment]
The dilemma with `$lookup` is that if we have `colA` as the base collection in the view, and `colB` is "joined" by an `id`. When we detect `colB` being updated we don't have an `_id` in MongoDB for the view, so in a plugin we would probably get the view based on a quick read operation (assuming an index is in place for efficiency). Perhaps that is the way to go... define a field as the read field to be able to get back to the view doc `_id`...

**Comment by Crispy1975** [comment]
Maybe use a toml table, might be making the config a bit too complex, but perhaps something like this...
```
[[replace]]
namespace = "test.collA"
with-namespace = "test.viewA"
lookups = { collB = "somethingId", collC = "anotherId" }
```

With this we know that we have a view (`viewA`) who's base collection is `collA`, and that the `lookups` inline toml table defines the other component collections that are part of the view in this example. So when we see an opLog change for `collB` we can then use a read for `somethingId` on `viewA` and trigger the sync for that one document. It does add overhead with an additional read, but it's more efficient that updating a potentially very large set of data.

**Comment by rwynn** [comment]
Yes. I was thinking along the same lines. Want to make sure a change is colB can trigger an update on more than 1 doc in more than 1 view. 

I’m thinking about when colB is something like { code, description } and multiple docs within a view ref it.  And possibly multiple views.  

I will put something together when I get some time.

**Comment by rwynn** [comment]
I think I have something working now along these lines:

Given
```
db.createView("testview", "test", [ {$lookup: {from: "codes", localField: "code", foreignField: "_id", as: "code"}}])
```
Where `code` is an integer in `test.test` corresponding to the matching full doc in `test.codes`

You can configure like this
```
[[relate]]
namespace = "test.test"
with-namespace = "test.testview"
keep-src = false

[[relate]]
namespace = "test.codes"
with-namespace = "test.test"
src-field = "_id"
match-field = "code"
keep-src = false
```
First, when an oplog event occurs on `test.test` then that is routed through `test.testview` before indexing.  

Second, when an oplog event on `test.codes` occurs then that is looked up in `test.test` (find where code='updated code _id") and ALL matches are subsequently routed through `test.testview` before indexing.  

This can trigger a huge update if you change for example the `description` of a code since many documents may be referencing that code.  

Finally, you can have many `[[relate]]` configurations for a single namespace.  They will all be evaluated.  This is in case you have more than 1 view doing `$lookup` on `test.codes`.

**Comment by rwynn** [comment]
@Crispy1975 I've added the changes to support syncing the view when a $lookup changes.  When you get a chance let me know if this is something that would work.  Thanks.

**Comment by Crispy1975** [comment]
Thanks @rwynn I will test this out today - I was away yesterday - and let you know how I get on.

**Comment by Crispy1975** [comment]
Forgot to say that this worked very well for us. On larger collections/views the updates can be heavy as we expected, but it works very nicely. Thanks for the effort on this. :+1:

**Comment by rwynn** [comment]
@Crispy1975 Glad to hear it's working for you. Let me know if you spot any ways to improve on it.

**Comment by Crispy1975** [comment]
Sure will do, got some more testing to do and will report back if I find anything or have any suggestions. Thanks as always.

**Comment by Crispy1975** [comment]
Btw... if you still would like me to take a look at adding to the docs for this I am happy to do so.

**Comment by Crispy1975** [comment]
@rwynn adding this here as I have discovered what might be a bug in the new `relate` code, when setting the toml config there is no way to set the target `type`, ES seems to end up with a type of `_doc`, however we generally set our own index type, and with the latest ES6+ versions you are only allowed one type per index. This results in:

```
Rejecting mapping update to [myDb.myView] as the final mapping would have more than 1 type: [myType, _doc]
```
I had a look at the `monstache.go` code and doesn't look like type is being used in there?
