### ISSUE TITLE
Allow scripts to drop documents

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#11]
We are loving the library so far and it's making life very easy replicating from MongoDB. Would be great to be able to use the scripts to conditionally replicate also. Let me explain, we have a pseudo delete option which is represented by a date field in MongoDB, if this field is present then the document is "deleted". The scripts in monstache must return an object according to the docs, but it would be nice to perhaps return `false` or `null` to let monstache know not to bother sending the document to Elasticsearch for indexing... so in a script could do something like this...

```
[[script]]
namespace = "db.collection"
script = """
module.exports = function(doc) {
    if (!!doc && !!doc.deletedAt) {
        return false;
    }
    return doc;
}
"""
```

This would result in no document being sent to Elasticsearch and keeping the index smaller as we would never want to search documents that are deleted. We could of course filter these out in our Elasticsearch queries, but the searches would be faster not having to account for these documents in the first place. :)

**Comment by rwynn** [comment]
This is a really great idea.  It would be pretty simple to make the change you requested to honor a `null `or `false` as an ignore.  However, I will probably separate the filter function into a another function that is provided in the TOML config.  The reason is that if filter is a separate function I can pass the function to the tail code, ([gtm](https://github.com/rwynn/gtm) library) in this case, as an `OpFilter` and have the filtering happen before the event gets put on the Go channel that monstache listens to.  This will slightly improve the performance.  

I’m thinking something like this on the API side. 

```
[[filter]]
namespace = "db.collection"
script = """
module.exports = function(doc) {
    if (!!doc && !!doc.deletedAt) {
        return false;
    }
    return true;
}
"""
```

**Comment by Crispy1975** [comment]
Sounds good to me, even better to not have too complex a script and the possibility of multiple filters for different indexes. :)

**Comment by rwynn** [comment]
Actually on second thought it may be better the way you originally described :-). My thought is that the doc may initially come into monstache without the soft delete flag and would be indexed. Then an update adds the soft delete flag in mongo and the event comes across and is dropped in the filter which is wrong.  I think your approach handles this case while the filter commits the insert but ignores the update.  

I'm thinking the pseudo code is if mapper script returns false then if op is an insert ignore else if op is update then delete from ES.

**Comment by Crispy1975** [comment]
This is true... we would have to remove a soft deleted document from the ES index anyway as I don't see a way to do that effectively in monstache without adding things that would pollute its purpose. Ultimately it's for replication into ES and not general document management.

**Comment by rwynn** [comment]
@Crispy1975,
Not sure if you would be interested, but just pushed a version of monstache that supports golang plugins as an alternative to JavaScript.  Docs for this new feature can be found at [Golang Middleware](https://rwynn.github.io/monstache-site/transform-filter/#golang)

**Comment by Crispy1975** [comment]
@rwynn really interesting! Reading it right now.
