### ISSUE TITLE
Rejecting mapping update

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#112]
Hi,

I am getting the following error:

>     Rejecting mapping update to [test.pictures] as the final mapping would have more than 1 type: [_doc, pictureobject]

I understand that this is an issue related to ES6, as explained in this post:

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html

However, I do not understand where the error comes from:

I have a mongo object called PictureObject. This object is also shared with ES.

```
	[Nest.ElasticsearchType, BsonIgnoreExtraElements]
	public class PictureObject : DataStoreObject
	{
		[Nest.Ignore]							public string		OwnerId				{ get; set; }
		[Nest.Ignore, BsonIgnoreIfDefault]		public string		AlbumId				{ get; set; }
												public Flags		Flags				{ get; set; }
		[Nest.Text, BsonIgnoreIfDefault]		public string		Title				{ get; set; }
		[Nest.Text]								public string		Tags				{ get; set; }
		[Nest.Ignore]							public int			Width				{ get; set; }
		[Nest.Ignore]							public int			Height				{ get; set; }
		[Nest.Ignore]							public string		Hash				{ get; set; }
		[Nest.Number(Nest.NumberType.Integer)]	public int			VotesUp				{ get; set; }
		[Nest.Ignore]							public int			VotesDown			{ get; set; }
		[Nest.Ignore]							public int			Shows				{ get; set; }
		[Nest.Number(Nest.NumberType.Integer)]	public int			Views				{ get; set; }
		[Nest.Ignore, BsonIgnoreIfDefault]		public string		Link				{ get; set; }
		[Nest.Ignore]							public string		OriginUrl			{ get; set; }
		[Nest.Ignore]							public string		OriginTags			{ get; set; }
		[Nest.Ignore, BsonIgnoreIfDefault]		public string		OriginTitle			{ get; set; }
	}

```

As you can see, the class is decorated both with Mongo and ES attributes.

Then, I have the ES mapping:

```
				var I = Client.CreateIndex(INDEX_NAME, Ci => Ci
					.Settings(S => S
						.Analysis(A => A
							.CharFilters(Cf => Cf.Mapping("expressions",
								E => E.Mappings(
									"test ab => testab",
									"test bc => testbc"))
							)
							.TokenFilters(Tf => Tf.Synonym("synonyms",
								Descriptor => new SynonymTokenFilter
								{
									Synonyms = new[]
									{
										"syna1 => syna2, syna3",
										"synb1 => synb2, synb3"
									},
									Tokenizer = "whitespace"
								})
							)
							.Analyzers(Analyzer => Analyzer
								.Custom("index", C => C
									.CharFilters("html_strip", "expressions")
									.Tokenizer("standard")
									.Filters("synonyms", "standard", "lowercase", "stop")
								)
								.Custom("search", C => C
									.CharFilters("expressions")
									.Tokenizer("standard")
									.Filters("synonyms", "standard", "lowercase", "stop")
								)
							)
						)
					)
					.Mappings(Mapping => Mapping
						.Map<PictureObject>(Map => Map
							.AutoMap()
							.Properties(P => P
								.Text(T => T
									.Name(N => N.Title)
									.Analyzer("index")
									.SearchAnalyzer("search")
								)
								.Text(T => T
									.Name(N => N.Tags)
									.Analyzer("index")
									.SearchAnalyzer("search")
								)
							)
						)
					)
				);
```
 
At which point the PictureObject item gets in conflict with _doc? the whole index vs. type thing is super unclear to me.

**Comment by rwynn** [comment]
You can override the type that monstache uses when indexing.  By default, Monstache will use the type `_doc` for 6.2+.  

```
[[mapping]]
namespace="test.pictures"
type = "pictureobject"
```

Monstache defaults to` _doc` for 6.2+ because reasons... https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html

**Comment by thomasd3** [comment]
This does not work:
I have that mongo / elastic collection called test.pictures (lowercase in both)

Without creating the index with the code from my original post, Monstache does the sync but ONLY if I add:
				.DefaultMappingFor<PictureObject>(M => M
					.Ignore(_ => _._id)

in the settings, otherwise it claims there are conflicting _id fields, so I can't map _id in ES.

When I create the index, I had the error that started this post.

When I add the [[mapping]] section, NOTHING syncs at all, it's like Monstache is not even loaded.
  
During startup, the logs are different:

With the [[mapping]] section:

> 11:53:10 Started monstache version 4.11.1 
> 11:53:10 Successfully connected to MongoDB version 4.0.3 
> 11:53:10 Successfully connected to Elasticsearch version 6.4.2 
> 11:53:10 Listening for events 
> 

Without the [[mapping]] section:

> 11:58:11 Started monstache version 4.11.1 
> 11:58:11 Successfully connected to MongoDB version 4.0.3 
> 11:58:11 Successfully connected to Elasticsearch version 6.4.2 
> 11:58:11 Listening for events 
> 11:58:11 Sending systemd READY=1 
> 11:58:11 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset) 
> 

The last 2 lines are different.

I've also attached my config file here: https://pastebin.com/49tQ4pnJ if it helps

**Comment by rwynn** [comment]
See the warning in the docs for ordering of configuration options. 

https://rwynn.github.io/monstache-site/config/

All one liners should come before toml tables.
