### ISSUE TITLE
Copy only fields present in the index

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#115]
I manually create an ES index with the fields I need from my Mongo class.

Is there a way to prevent Monstache from adding all the other fields from Mongo? It can be large and doesn't serve any purpose in my case; I haven't been able to find how to prevent some fields to be synchronized and get Monstache to ignore them.

**Comment by rwynn** [comment]
It embeds a javascript interpreter with underscore included.  I'm not sure how recent the copy of underscore is, but the following should also work.

```
[script]]
namespace = "test.test"
script = """
module.exports = function(doc) {
    return _.pick(doc, "fields", "I", "want", "indexed");
}
"""
```

**Comment by thomasd3** [comment]
I will give it a try!

**Comment by thomasd3** [comment]
It works perfectly! thanks!
