### ISSUE TITLE
Not retrying after timeout

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#117]
I have had a situation where Mongo took a long time to start as it wasn't shut down properly.

and then, the Monstache log was showing:

    ERROR 2018/10/21 12:34:57 Unable to connect to MongoDB using URL mongodb://REDACTED@mongodb:27017: timed out after 15 seconds

but then never retried again. 

Mongo may report it is started, but it may not be ready to accept commands yet.

Is there a way to make Monstache keep retrying?

**Comment by rwynn** [comment]
@thomasd3 I've cleaned up the docs a bit on systemd and verified it working on Ubuntu 16.04.  I'll close this issue with the recommendation to use a process manager.

**Comment by abhijitbashetti** [comment]
Hi Ryan,

I am getting the same error...

ERROR 2019/01/18 12:28:21 Unable to connect to MongoDB using URL mongodb://REDACTED@localhost:27017: timed out after 15 seconds

**Comment by rwynn** [comment]
@abhijitbashetti what version of MongoDB?  Depending on how recent and how your user auth is setup then these [instructions](https://rwynn.github.io/monstache-site/advanced/#mongodb-atlas) may apply.
