### ISSUE TITLE
Feature Request: Elastic Client in MapperPluginInput struct

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#118]
Ok, so this is not a Bug, it's a feature request.

When I receive a event, I need to know what changes have been done to the document to do some actions.
Since the document has been change in Mongo already, the only place where I can get its previous version is on Elastic.

My suggestion is this:
**type MapperPluginInput struct** {
      Document   map[string]interface{} // the original document from MongoDB
      Database   string                 // the origin database in MongoDB
      Collection string                 // the origin collection in MongoDB
      Namespace  string                 // the entire namespace for the original document
      Operation  string                 // "i" for a insert or "u" for update
      Session    *mgo.Session           // MongoDB session handle
**ElasticClient**        *elastic.Client  //Elastic Client
}

The mongo client is already there....I just need the Elastic added....

Tnx

**Comment by rwynn** [comment]
@BrunoPereira can you not use the `Process` method for this?

Process has access to `*monstachemap.ProcessPluginInput` which makes the client and bulk processor available.

**Comment by BrunoPereira** [comment]
I need to map the Document to a different Index, do a series of computation, from calculating new fields depending on data, getting extra data from Mongo and do some actions depending on the previous Document state.

From what I understood, Process has  &monstachemap.ProcessPluginInput as Input, I can't seem to get the client data inside the map function.
Or m I missing something ???

I'm just trying to have an easy way to get the previous state (that I have in eastic) from a given object

**Comment by rwynn** [comment]
Since it sounds like you need lots of customization I would just implement `Map` and return `Skip` = true on the `output` to turn off the mapper. Then implement a `Process` function and do whatever you need to do in there. `Process` gets **all the same input fields** as `Map` **plus additional pointers** to the Elasticsearch client and bulk processor.  Do all the processing you need to do and then create a BulkRequest and `Add` it to the processor.    When you implement `Process` you take full control of the indexing yourself.  

https://rwynn.github.io/monstache-site/advanced/#golang

https://github.com/rwynn/monstache/blob/rel3/monstache.go#L2364

https://github.com/rwynn/monstache/blob/rel3/monstache.go#L2238

**Comment by BrunoPereira** [comment]
@rwynn tnx
That was a big help....

As a suggestion, on that part of the documentation, you could have a bullet for each function (inside the Middleware/Golang tag).
You could also add an example for every function using an appropriated use case for each.
Maybe have a section for what's common in every function and then on the appropriated bullet you would go into the specifics.

I had seen that part of the docs, but I didn't understood what the func Process did.... at least not until you send me back (that and the explanation above).... so the information is there, maybe a better layout?

**Comment by BrunoPereira** [comment]
@rwynn I need your help
I'm getting an error when using the Process function....

fatal error: concurrent map iteration and map write

goroutine 191 [running]:
runtime.throw(0xe24548, 0x26)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0016bbe10 sp=0xc0016bbde0 pc=0x6b4e02
runtime.mapiternext(0xc0016bbef0)
	/usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc0016bbe98 sp=0xc0016bbe10 pc=0x697be5
main.runProcessor(0xc00019a340, 0xc00014c750, 0xc00019a820, 0xc000349da0, 0x0, 0x0)
	/go/src/cache-app/monstache.go:2374 +0x14a fp=0xc0016bbf60 sp=0xc0016bbe98 pc=0xc6dcca
main.main.func8(0xc000275890, 0xc000192320, 0xc00019a340, 0xc00014c750, 0xc00019a820, 0xc0001a4000)
	/go/src/cache-app/monstache.go:3526 +0xbb fp=0xc0016bbfb0 sp=0xc0016bbf60 pc=0xc7b81b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0016bbfb8 sp=0xc0016bbfb0 pc=0x6e55d1
created by main.main
	/go/src/cache-app/monstache.go:3523 +0x15be

func Process(input *monstachemap.ProcessPluginInput) error {
	var index, typeName string
	record := input.Document
// do some stuff here ...adding stuff to record.... use the mongo client to get stuff...
req := elastic.NewBulkUpdateRequest()
	req.Id(record["_id"].(string))
	req.Index(index)
	req.Type(typeName)
	req.DocAsUpsert(true)
	req.Doc(record)
	input.ElasticBulkProcessor.Add(req)

	return nil
}

I did fallow the examples you mentioned .... can't figure this out.... can you help? 
tnx

**Comment by rwynn** [comment]
@BrunoPereira please try the latest release.  Added a fix for this race condition. Hope it helps.

**Comment by BrunoPereira** [comment]
@rwynn tnx
I'm having a different problem now....
STATS 2018/10/25 17:17:34 {"Flushed":5,"Committed":4,"Indexed":0,"Created":0,"Updated":14463,"Deleted":0,"Succeeded":0,"Failed":14463,"Workers":[{"Queued":0,"LastDuration":8576000000},{"Queued":0,"LastDuration":4611000000},{"Queued":0,"LastDuration":12468000000},{"Queued":0,"LastDuration":1213000000}]}
STATS 2018/10/25 17:17:51 {"Flushed":6,"Committed":5,"Indexed":0,"Created":0,"Updated":18248,"Deleted":0,"Succeeded":0,"Failed":18248,"Workers":[{"Queued":0,"LastDuration":1087000000},{"Queued":3923,"LastDuration":4611000000},{"Queued":0,"LastDuration":12468000000},{"Queued":0,"LastDuration":1213000000}]}
STATS 2018/10/25 17:18:21 {"Flushed":13,"Committed":21,"Indexed":0,"Created":0,"Updated":37589,"Deleted":0,"Succeeded":0,"Failed":37589,"Workers":[{"Queued":0,"LastDuration":217000000},{"Queued":0,"LastDuration":405000000},{"Queued":0,"LastDuration":241000000},{"Queued":0,"LastDuration":192000000}]}

As you can see, all events fail....
To debug this I'm sending some pretty simple objects, with just the ID and a title....

func addRecordToBulkElastic(bulkElastic *elastic.BulkProcessor, typeName string, record map[string]interface{}) {
	req := elastic.NewBulkUpdateRequest()
	req.Index("test-npvr-recording")
	req.Id(record["_id"].(string))
	req.Type(typeName)
	req.DocAsUpsert(true)
	test := make(map[string]interface{})
	test["_id"] = record["_id"]
	test["Title"] = record["Title"]

	req.Doc(test)
	bulkElastic.Add(req)

	return
}

I can reach the Elastic Search, it created the Index, but no elements where created.... all events fail.... I don't get any erro msg.
I'm not managing the BulkProcessor, just adding requests.... It look 2 me that the monstache main was doing that for me. I'm wrong about this? What m I missing??
tnx

**Comment by rwynn** [comment]
You should be able to see something in the Elasticsearch logs for the failed requests. 

Are you sure that the _id in MongoDB is simply a string and not an ObjectId?  For ObjectId you would use something like this code in monstache...

https://github.com/rwynn/monstache/blob/master/monstache.go#L522

**Comment by rwynn** [comment]
Also you should not have an _id on the `request.Doc()` that you index.  The _id only goes on `request.Id()`.  If you choose to reuse the document passed on input, e.g. `input.Document` then you should delete the _id field when indexing.

```
id := input.Document["_id"].(bson.ObjectId).Hex()
request.Id(id)
delete(input.Document, "_id")
request.Doc(input.Document)
```

**Comment by BrunoPereira** [comment]
The Id is a string... I have printed it in other occasions as debug...

I was testing it again and checking elastic logs and I had nothing there.... on the other hand I noticed this:
STATS 2018/10/25 19:22:07 {"Flushed":3,"Committed":2,"Indexed":0,"Created":0,"Updated":7233,"Deleted":0,"Succeeded":0,"Failed":7233,"Workers":[{"Queued":0,"LastDuration":1340000000},{"Queued":0,"LastDuration":8055000000},{"Queued":8796,"LastDuration":0},{"Queued":0,"LastDuration":0}]}
STATS 2018/10/25 19:22:37 {"Flushed":3,"Committed":2,"Indexed":0,"Created":0,"Updated":7233,"Deleted":0,"Succeeded":0,"Failed":7233,"Workers":[{"Queued":0,"LastDuration":1340000000},{"Queued":0,"LastDuration":8055000000},{"Queued":8796,"LastDuration":0},{"Queued":0,"LastDuration":0}]}
^CINFO 2018/10/25 19:26:04 Shutting down

I have the stats configured to log every 30s, but as you can see, after the 1st two, monstache didn't log anything until I interrupt it....
It looks 2 me like a deadlock ....

**Comment by rwynn** [comment]
I think it is because you are including an _id in the Document.  If I do that with curl I get this error message from Elasticsearch...

```
Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.
```

So you need to delete the "_id" field the map you pass to `.Doc()`.  This is what monstache does already here...

https://github.com/rwynn/monstache/blob/master/monstache.go#L891

Also, I would mimic what monstache does by checking for error on the request's ability to generate it's own `Source` before adding it.

https://github.com/rwynn/monstache/blob/master/monstache.go#L2256

**Comment by BrunoPereira** [comment]
@rwynn tnx
It was the ID. Just confirmed it....
But the stats not appearing in the log as expected is strange.... Don't know if you want to check that out....

**Comment by BrunoPereira** [comment]
tnx for the tips... I'll check the request before adding it to the BulkProcessor
