### ISSUE TITLE
Field [_id] is defined twice

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#120]
I have one last issue:

In mongodb, my objects have the _id field and I need this field in ES.

Unless I do this:

	var Settings = new ConnectionSettings(new Uri(ConnectionString))
		.DefaultIndex(_IndexName)
		.DefaultMappingFor<TestObject>(_ => _.Ignore(I => I._id))

I get the Field [_id] is defined twice error when creating the index.

What would be the best way for Mongo's _id to be copied to ES by Monstache? (possibly under another name, it doesn't have to stay as '_id'?

**Comment by rwynn** [comment]
Monstache by default uses the _id from MongoDB as the _id in Elasticsearch. You don’t need to define _id in Elasticsearch as it is core metadata field. It is not normal practice I think to have a copy of the _id in the source document. Do you really need it?

**Comment by rwynn** [comment]
Turn on verbose mode and you can see how _id is already being sent to Elasticsearch in bulk api calls.

**Comment by thomasd3** [comment]
yes, it's essential here since ES is used to return me a list of Mongo _id

I did this in my index:
			var Settings = new ConnectionSettings(new Uri(ConnectionString))
				.DefaultIndex(_IndexName)
				.DefaultMappingFor<TestObject>(_ => _.PropertyName(I => I._id, "Id"))

but Kibana doesn't show any "Id" field.

What I don't get is that the _id field, in Kibana, seems matches the Mongo _id.. so this looks normal
but during the query, the _id I get is like a guid and is not my id

**Comment by thomasd3** [comment]
Here is where the confusion comes from:

From Monstache:

{"took":344,"errors":false,"items":[{"index":{"_index":"test.object","_type":"testobject","_id":"zZZSyvU7-Kn94ct856uZ36I+uN7SuaXE3+AuzAt-t6c","_version":6618507962769997824,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1450,"_primary_term":1,"status":201}}]}


From Kibana, I look for a specific object

Tags:
    tag1 tag2 testtag
CreatedOn:
    October 26th 2018, 14:25:57.053
_id:
    FRaqDPIzWcVI2dl-oA9uUFHLVFQk8qIqqhySWSkM7Ds
_type:
    testobject
_index:
    test.object
_score:
    0


From the Nest query, getting the same object (it has a unique tag):

_id: 33389aa0-4abc-42b9-83fb-50cd94326e17

The _id returned is a guid, the _id from Mongo, copied by Monstache and shown by Kibana is not.

**Comment by rwynn** [comment]
I’m not family with Nest but usually the results query from elasticsearch looks like this with the _id in a metadata field and no id in the source...

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html

Maybe nest is doing something on top of the raw search result?

**Comment by thomasd3** [comment]
yes, Nest has definitely more data. Not sure why the _id in Documents is replaced by a guid though.. I asked on SO; if there is some clarification, I'll post here so it can help people with similar issues.

**Comment by rwynn** [comment]
Here is the [link](https://stackoverflow.com/questions/53084689/not-understanding-the-behavior-of-id-on-es) to Stackoverflow for those interested.

**Comment by thomasd3** [comment]
that was my thread on SO :)

**Comment by rwynn** [comment]
Yes, I was going over these issues and noticed that your question was never answered on SO. Did you figure out how to fix it?

**Comment by thomasd3** [comment]
yes, eventually it worked; not quite sure what I did at the time though. If anyone has the same problem, feel free to write me and I'll look up the code.
