### ISSUE TITLE
Unable to synch  db from begining

### ISSUE THREAD

**Issue by sameerkattel** [rwynn/monstache#122]
Though I have specified direct-read-namespaces = ["propertysearch.test"]
monstache is not doing the full sync

Here is my config 
```
# https://rwynn.github.io/monstache-site/config/

workers = [ "es1" , "es2" , "es3" ]

# connection settings
# connect to MongoDB using the following URL
 mongo-url = "mongodb://localhost:27017"
 mongo-config-url= "mongodb://localhost:31000"
 elasticsearch-urls = ["http://127.0.0.1:9200"]



# compress requests to Elasticsearch
gzip = true
# generate indexing statistics
stats = true
# index statistics into Elasticsearch
index-stats = true

# use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 10
elasticsearch-max-bytes=52428800  # 50 MB

# resume processing from a timestamp saved in a previous run
resume = true
# do not validate that progress timestamps have been saved
resume-write-unsafe = false
# override the name under which resume state is saved
resume-name = "monstache_sync"

namespace-regex = '^propertysearch\.test$'
direct-read-namespaces = ["propertysearch.test"]
# do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false

[[mapping]]
namespace = "propertysearch.test"
index = "final.propertysearch.test"
```

Here is the logs

> INFO 2018/11/02 20:35:31 Started monstache version 4.11.5
> INFO 2018/11/02 20:35:31 Successfully connected to MongoDB version 3.4.17
> INFO 2018/11/02 20:35:31 Successfully connected to Elasticsearch version 6.3.1
> INFO 2018/11/02 20:35:31 Adding shard found at 172.31.31.100:7720?replicaSet=shard-a
> INFO 2018/11/02 20:35:31 Adding shard found at 172.31.28.208:7720?replicaSet=shard-b
> INFO 2018/11/02 20:35:31 Listening for events

**Comment by rwynn** [comment]
I’m assuming you have 3 process running? One for each worker?

People have a lot of problems configuring workers. Have you tried without them?  Maybe I need more documentation. 

When you run in worker mode each process **ignores** documents that will be handled by other workers. So you need all of them running at the same time or you will not process everything.

**Comment by rwynn** [comment]
Are you seeing any documents in elasticsearch?  Some but not all?

**Comment by sameerkattel** [comment]
Yes I could only some documents and not all.

**Comment by rwynn** [comment]
Try removing any settings for workers. Or if you want workers watch this video showing how 3 workers are designed to be run in parallel. 

https://user-images.githubusercontent.com/260672/47312451-62c69a80-d60a-11e8-98ce-9d44683dc220.gif

**Comment by rwynn** [comment]
Lots of queued documents. Can you try with elasticsearch-max-seconds = 2?

**Comment by rwynn** [comment]
I usually see close to 1 million test docs sync per minute in a vm so something is not right. 

Maybe reduce all settings to just connection info and direct-read-namespaces.

**Comment by sameerkattel** [comment]
@rwynn I reduced all settings as you said and sync looks to be fine now. Though I am not sure what was wrong with my setting. I thought of the resume feature to be the culprit but there is no monstache db created in mongo . Thank you so much for the tool and quick response...Much Appreciate it!
