### ISSUE TITLE
FS files not indexed 

### ISSUE THREAD

**Issue by cmicallef** [rwynn/monstache#123]
Hi, 
I'm trying to  use monstache 4.11.5 to index the fs files in mongodb version 3.6 with a replica set of 3 on to elasticsearch 6.4.2 cluster with two nodes and ingest-plugin installed but monstache indexes the Metadata of the files but ignores the actual attachment and not finding any particular errors,  not sure if I missed something, the following is the configuration I set and running. 
I also created an index manually to test with an attachment on elasticsearch and using the ingest-plugin and can search in docx contents but I had converted the docx to base64 . Any tips appreciated Thanks

mongo-url = "mongodb://XXXXXX@192.168.XX.XX:27017,192.168.XX.XX:27017,192.168.XX.XX:27018/?authSource=XXX&readPreference=primary&replicaSet=XXXX"
elasticsearch-urls = ["http://192.168.XX.XX:9200", "http://192.168.XX.XX:9200"]
direct-read-namespaces = ["PhaseOneDB.DocxTest.files","fs.files"]
gzip = true
stats = true
index-stats = false
mongo-validate-pem-file = false
elasticsearch-max-conns = 4 
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
index-files = true
file-highlighting = true
file-namespaces = ["PhaseOneDB.DocxTest.files","fs.files"]
verbose = true
cluster-name = "cluster-name"
[logs]
info = "/opt/info/info.out"
error = "/opt/info/error.out"
exit-after-direct-reads = false

**Comment by rwynn** [comment]
Are you able to turn off gzip and keep verbose on so that you can see whether or not monstache is sending the base64 value in the request?  It would be in a field named file. 

Also, the first namespace looks probably ok but is fs.files correct?  So a db named fs with a collection named files?

**Comment by rwynn** [comment]
I think this might be a regression in how monstache reads the config file. I will take a look and try to get a fix out.

**Comment by rwynn** [comment]
I think you may be able to work around the issue by specifying the file namespace on the command line instead of in the config file. 

monstache -file-namespace PhaseOneDB.DocxTest.files
