### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by skatsarov** [rwynn/monstache#124]
Hello,

I am trying to connect the monstache to Mongo Replica Set over SSL but to no avail. Here is my configuration:

`NFO 2018/11/07 16:10:23 {
  "MongoURL": "mongodb://REDACTED@172.172.172.4:27017/?authMechanism=MONGODB-X509\u0026authSource='$external'",
  "MongoConfigURL": "",
  "MongoPemFile": "/root/client.pem",
  "MongoValidatePemFile": false,
  "MongoOpLogDatabaseName": "",
  "MongoOpLogCollectionName": "",
  "MongoDialSettings": {
    "Timeout": 15,
    "Ssl": true,
    "ReadTimeout": 0,
    "WriteTimeout": 0
  },
  "MongoSessionSettings": {
    "SocketTimeout": 0,
    "SyncTimeout": 0
  },
  "GtmSettings": {
    "ChannelSize": 512,
    "BufferSize": 32,
    "BufferDuration": "75ms"
  },
  "AWSConnect": {
    "AccessKey": "",
    "SecretKey": "",
    "Region": ""
  },
  "Logs": {
    "Info": "",
    "Warn": "",
    "Error": "",
    "Trace": "",
    "Stats": ""
  },
  "GraylogAddr": "",
  "ElasticUrls": [
    "https://172.172.172.10:9200"
  ],
  "ElasticUser": "REDACTED",
  "ElasticPassword": "REDACTED",
  "ElasticPemFile": "",
  "ElasticValidatePemFile": false,
  "ElasticVersion": "",
  "ResumeName": "default",
  "NsRegex": "^pep\\.individuals$",
  "NsDropRegex": "",
  "NsExcludeRegex": "",
  "NsDropExcludeRegex": "",
  "ClusterName": "",
  "Print": true,
  "Version": false,
  "Pprof": false,
  "DisableChangeEvents": false,
  "EnableEasyJSON": false,
  "Stats": true,
  "IndexStats": true,
  "StatsDuration": "",
  "StatsIndexFormat": "monstache.stats.2006-01-02",
  "Gzip": true,
  "Verbose": true,
  "Resume": true,
  "ResumeWriteUnsafe": false,
  "ResumeFromTimestamp": 0,
  "Replay": false,
  "DroppedDatabases": true,
  "DroppedCollections": true,
  "IndexFiles": true,
  "IndexAsUpdate": false,
  "FileHighlighting": true,
  "EnablePatches": false,
  "FailFast": false,
  "IndexOplogTime": false,
  "OplogTsFieldName": "oplog_ts",
  "OplogDateFieldName": "oplog_date",
  "OplogDateFieldFormat": "2006/01/02 15:04:05",
  "ExitAfterDirectReads": false,
  "MergePatchAttr": "json-merge-patches",
  "ElasticMaxConns": 4,
  "ElasticRetry": false,
  "ElasticMaxDocs": -1,
  "ElasticMaxBytes": 8388608,
  "ElasticMaxSeconds": 5,
  "ElasticClientTimeout": 0,
  "ElasticMajorVersion": 0,
  "ElasticMinorVersion": 0,
  "MaxFileSize": 0,
  "ConfigFile": "/root/conf.toml",
  "Script": null,
  "Filter": null,
  "Pipeline": null,
  "Mapping": null,
  "Relate": null,
  "FileNamespaces": null,
  "PatchNamespaces": null,
  "Workers": null,
  "Worker": "",
  "ChangeStreamNs": null,
  "DirectReadNs": [
    "pep.individuals"
  ],
  "DirectReadSplitMax": 0,
  "MapperPluginPath": "",
  "EnableHTTPServer": false,
  "HTTPServerAddr": ":8080",
  "TimeMachineNamespaces": null,
  "TimeMachineIndexPrefix": "log",
  "TimeMachineIndexSuffix": "2006-01-02",
  "TimeMachineDirectReads": false,
  "PipeAllowDisk": false,
  "RoutingNamespaces": null,
  "DeleteStrategy": 0,
  "DeleteIndexPattern": "*",
  "FileDownloaders": 10,
  "RelateThreads": 10,
  "PostProcessors": 0,
  "PruneInvalidJSON": false
}`

However, the application returns:

Unable to connect to MongoDB using URL mongodb://REDACTED@172.172.172.4:27017/?authMechanism=MONGODB-X509&authSource='$external': timed out after 15 seconds

In the Mongo log, I see the following entries:

`2018-11-07T17:10:10.306+0000 I NETWORK  [conn3] Error receiving request from client: SSLHandshakeFailed: no SSL certificate provided by peer; connection rejected. Ending connection from 172.172.172.100:58906 (connection id: 3)
2018-11-07T17:10:10.306+0000 I NETWORK  [conn3] end connection 172.172.172.100:58906 (2 connections now open)
2018-11-07T17:10:10.813+0000 E NETWORK  [conn4] no SSL certificate provided by peer; connection rejected
2018-11-07T17:10:10.813+0000 I NETWORK  [conn4] Error receiving request from client: SSLHandshakeFailed: no SSL certificate provided by peer; connection rejected. Ending connection from 172.172.172.100:58908 (connection id: 4)
2018-11-07T17:10:10.813+0000 I NETWORK  [conn4] end connection 172.172.172.100:58908 (2 connections now open)
2018-11-07T17:10:11.318+0000 E NETWORK  [conn5] no SSL certificate provided by peer; connection rejected`

I could not find any documents or example how to connect to Mongo replia with SSL. Any help will be appreciated.

**Comment by rwynn** [comment]
Here is the code that monstache is using when the PEM file is supplied.

https://github.com/rwynn/monstache/blob/master/monstache.go#L1990

Here are some examples that I found in the `mgo` driver  code.

https://github.com/globalsign/mgo/blob/db12ee52971557d77e937dbab379358347e3a05c/example_test.go

So, I think that monstache is currently only supporting the basic connect via SSL part with a private cert at the moment.  The part of making a `Login` call for X509 is not yet supported.

https://github.com/globalsign/mgo/blob/db12ee52971557d77e937dbab379358347e3a05c/example_test.go#L81

You may be able to modify monstache based on those examples.  Please let me know if you do get it working.

**Comment by skatsarov** [comment]
Hi,
Thank you for your reply. The provided information is quite helpful.

Now I am trying to login with plain user / password ( no X509 auth ) and still, it returns that monstache doest not connect over TLS.

Error receiving request from client: SSLHandshakeFailed: no SSL certificate provided by peer; connection rejected. Ending connection from 172.172.172.100:45016 (connection id: 193)

Here is part of my conf:

`INFO 2018/11/12 14:36:57 {
  "MongoURL": "mongodb://172.172.172.2:27017/",
  "MongoConfigURL": "",
  "MongoPemFile": "/root/mongo.pem",
  "MongoValidatePemFile": false,
  "MongoOpLogDatabaseName": "",
  "MongoOpLogCollectionName": "",
  "MongoDialSettings": {
    "Timeout": 20,
    "Ssl": true,
    "ReadTimeout": 0,
    "WriteTimeout": 0
  },
  "MongoSessionSettings": {
    "SocketTimeout": 0,
    "SyncTimeout": 0
  },
  "GtmSettings": {
    "ChannelSize": 512,
    "BufferSize": 32,
    "BufferDuration": "75ms"
  },
  "AWSConnect": {
    "AccessKey": "",
    "SecretKey": "",
    "Region": ""
  },
  "Logs": {
    "Info": "",
    "Warn": "",
    "Error": "",
    "Trace": "",
    "Stats": ""
  }`

Is it possible, to provide some kind of example for the configuration, how to set SSL/TLS connection ?

**Comment by rwynn** [comment]
Hi, are you putting credentials `mongodb://username:password@172...` in your URL? 

Maybe this link would be helpful for generating the PEM file? 

https://www.codeproject.com/Tips/1163375/Using-Mongo-with-SSL-and-GO

Basically, the monstache code is doing the same thing. 

https://github.com/rwynn/monstache/blob/master/monstache.go#L1991

**Comment by skatsarov** [comment]
Hello rwynn,

Again I would like to thank you for your assistance !!!

In this case, the problem was that I did not remove CA option from the mongo. Once I removed it, I was able to login over TLS.
Thanks again :)

**Comment by rwynn** [comment]
Glad to hear it’s working.
