### ISSUE TITLE
Document Deletion From Linked View

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#126]
Making pretty good progress with the new views `relate` stuff, however I've noticed that if you delete a document from the base collection comprising a replicated view, Monstache detects the action but attempts to delete the document from the collection index. This isn't there for us as we went with the following config options:

**Config**
```
[[relate]]
namespace = "mydb.my-collection"
with-namespace = "mydb.my-collection-view"
keep-src = false

[[mapping]]
namespace = "mydb.my-collection-view"
index = "mydb.my-collection-view"
type = "stuff"
```
So in this case, as you can see from the logs below, ES throws a 404 back as the document doesn't exist. Ideally the delete would also honour the `relate` mappings. 

**Trace:**
```
INFO 2018/11/08 14:48:10 Started monstache version 4.11.3
INFO 2018/11/08 14:48:10 Successfully connected to MongoDB version 3.4.17
INFO 2018/11/08 14:48:10 Successfully connected to Elasticsearch version 6.2.2
INFO 2018/11/08 14:48:10 Joined cluster local
INFO 2018/11/08 14:48:10 Starting work for cluster local
INFO 2018/11/08 14:48:10 Sending systemd READY=1
INFO 2018/11/08 14:48:10 Listening for events
WARN 2018/11/08 14:48:10 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)

STATS 2018/11/08 14:48:40 {"Flushed":15,"Committed":0,"Indexed":0,"Created":0,"Updated":0,"Deleted":0,"Succeeded":0,"Failed":0,"Workers":[{"Queued":0,"LastDuration":0},{"Queued":0,"LastDuration":0},{"Queued":0,"LastDuration":0},{"Queued":0,"LastDuration":0}]}

TRACE 2018/11/08 14:48:56 POST /_bulk HTTP/1.1
Host: elasticsearch:9200
User-Agent: elastic/6.2.11 (linux-amd64)
Content-Length: 143
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_index":"my-collection","_type":"_doc","_id":"5a313834430861520d232060","version":6621501838443151361,"version_type":"external"}}

TRACE 2018/11/08 14:48:56 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":126,"errors":false,"items":[{"delete":{"_index":"my-collection","_type":"_doc","_id":"5a313834430861520d232060","_version":6621501838443151361,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":5,"_primary_term":1,"status":404}}]}

STATS 2018/11/08 14:49:10 {"Flushed":31,"Committed":1,"Indexed":0,"Created":0,"Updated":0,"Deleted":1,"Succeeded":0,"Failed":1,"Workers":[{"Queued":0,"LastDuration":126000000},{"Queued":0,"LastDuration":0},{"Queued":0,"LastDuration":0},{"Queued":0,"LastDuration":0}]}
```

**Comment by rwynn** [comment]
Does this delete work if you provide a mapping for mydb.mycollection that is same as view (index and type) except for the namespace?

**Comment by rwynn** [comment]
Another thing to consider is adding both the view and coll namespace to the routing-namespaces config.

**Comment by Crispy1975** [comment]
I am pretty sure that `type` does not affect anything when used under `relate` as I was having the ES6+ issue where `_doc` was being used as the index mapping type.

I'll conduct some tests and see if I can get this working and report back...

**Comment by rwynn** [comment]
Yes [relate] does not accept type. Only mapping does. So you need a [mapping] with index and type for both namespaces (view and col). A delete will only be associated to the raw collection not the view.

**Comment by rwynn** [comment]
In the docs (last section under advanced) I explain the 2 mappings needed. I would need to think about the implications of allowing only one mapping when keep-arc is false for all relates on a namespace.

**Comment by Crispy1975** [comment]
@rwynn that seems to work perfectly... I will mark that down to user error on my part and not fully understanding the requirement of a mapping for both the view and collection, and being able to target the same index. Brilliant. :tada:
