### ISSUE TITLE
Can we transform event-centric data from MongoDB to entity-centric index in Elasticsearch?

### ISSUE THREAD

**Issue by burakkilic** [rwynn/monstache#127]
Hi,

First of all, thank you for the great library. 

I'm using Monstache to load data from our MongoDB to Elasticsearch. The reason for doing that is creating user acquisition funnels in Kibana on top of events data. 

As I saw in my researches, people advised transforming my data into an entity-centric index like in that presentation from Mark Harwood

https://www.elastic.co/videos/entity-centric-indexing-mark-harwood 

My question is, how can I transform my data into entity-centric index with Monstache?

**Comment by rwynn** [comment]
Hi @burakkilic,

I think you can achieve what is discussed in the talk using the golang plugin feature of monstache.  Specifically, I am thinking of a plugin that implements a `Process` function.  The `Process` function would get called any time some event data is inserted to MongoDB.  The `Process` function has access to the event data document from MongoDB as well as pointers to clients for MongoDB and Elasticsearch for reading/writing.  The Elasticsearch bulk indexer is provided to this function and any request `Add`ed to the processor will be indexed.

https://rwynn.github.io/monstache-site/advanced/#golang

https://github.com/rwynn/monstache/blob/master/monstachemap/plugin.go

There are probably a lot of different ways to approach it but you could maintain `user profile` documents in Elasticsearch and keep each profile updated as new events come in from MongoDB.  This might require fetching the `user profile` from Elasticsearch, doing logic using the new event, and then updating the `user profile` in Elasticsearch.   

If you create multiple Elasticsearch documents for a single entity, then you probably want to set the `Routing` on the document you index to be some identifier for that entity.  That will ensure that documents related to your entity are co-located on the same Elasticsearch shard.  When you query you then need to specify the routing to take advantage of that performance optimization.  

https://www.elastic.co/blog/customizing-your-document-routing
