### ISSUE TITLE
Case sensitivity in config file:

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#131]
I have collections in MongoDB that have capitalized names. ES uses only lowercase names.

I have 'Test.Pictures' in MongoDB and 'test.pictures' in ES.

In order to get things to work, my config file has the following:

namespace-regex = '^test\.pictures$'
direct-read-namespaces = [ "Test.Pictures" ]
change-stream-namespaces = [ "Test.Pictures" ]

[[mapping]]
 namespace="test.pictures"
 type = "pictureobject"   // this is PictureObject in MongoDB

 [[filter]]
 namespace = "test.pictures"
 script = """ [...]

 [[script]]
 namespace = "test.pictures"
 script = """ [...]

When I tried different casing, I had Monstache not doing anything; What fields refer to the MongoDB name and what fields refer to the ES name?

(thinking of it, I should really move all mongo stuff to lowercase and be done with it :))

**Comment by rwynn** [comment]
Namespace should match MongoDB exactly. Monstache will lowercase the index name by default.

**Comment by rwynn** [comment]
It’s lowered in func defaultIndexTypeMapping in Monstache.

**Comment by rwynn** [comment]
Yes regex must match mongo also. anywhere you see “namespace” in config file then match mongo. E.g. regex mapping filter script etc.

**Comment by thomasd3** [comment]
ok, great! thanks!
