### ISSUE TITLE
More flexible configuration options

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#133]
Hi @rwynn 

It looks to me that there's typo in the func parseCommandLineFlags()

line 1303 in the rel3 branch
flag.Var(&config.ElasticUrls, "**elasticsearch-url**", "A list of Elasticsearch URLs")
**Shouldn't be:**
flag.Var(&config.ElasticUrls, "**elasticsearch-urls**", "A list of Elasticsearch URLs")

Just to be the same as the one in the documentation and in the conf file....

On a side note... what about loading confs from Environment Variables?

**Comment by rwynn** [comment]
Hi @BrunoPereira,

It's actually supposed to be like that since the way you would use multiple urls on the command line is

```
monstache -elasticsearch-url URL1 -elasticsearch-url URL2

```

Since it is like that it didn't make sense to call it ...urls on the command line.  In TOML, you specify and array so it does make sense there.

I think it might be good to support loading some confs from Env.  Can you think of how it should work?

**Comment by BrunoPereira** [comment]
Now that you explain it it makes sense...

As far as Env vars, I'm using some in my plugin:
```
func init() {
....
if index, exists = os.LookupEnv("INDEX"); !exists {
		panic("The Environment Variable 'INDEX' that identifies the Elastic Search destination Index ain't defined ")
	}
```
You can't stop just because the Env Var is not defined, but "LookupEnv" gets the value and tests if it exists. 

Maybe you can load it to an aux var and if the env var exists, you assign the value to monstache config var.
So instead of using init, something like:
```
config.parseEnvironmentVariables()
config.parseCommandLineFlags()
```
I have doubts if you should load every conf parameter from Env vars or if only the ones related to the Mongo and Elastic connections

But if you are adding Env Vars, you should add the hierarchy on how the confs are loaded.
My suggestion is: Env > CML > conf file

**Comment by BrunoPereira** [comment]
@mapshen 
That way you end up with a hybrid where you need to configure things in BOTH Env Vars and config.file
And what happen if there's the same config in the CML ?
I think that approach can induce some confusion in the users.

In my opinion monstache would fully replace the var value depending on an Hierarchy defined in the doc.
I previously suggested that the hierarchy could be "Env > CML > conf file".
If this notation wasn't clear, I mean that Env Vars supersedes CML and CML supersedes conf.file

@rwynn 
I didn't want to start opening issues left and right, put 2 in 1 thread, and now the tittle doesn't have nothing to do with what's been discussed. Maybe we should move to a new thread, or we could edit the title and remove the post that have nothing 2 do with Env Vars.

**Comment by BrunoPereira** [comment]
@mapshen I'm opinionated.... an to me everyone is opinionated :)

I also like to have all the confs in one place. And I use the config.toml for that as well.
But I'm running monstache with different environments, different Mongos and different Elastics.
For me it would be great if I had a way to only change the relevant options for each environment.
Since I'm using docker, I can have those relevant options in the dockerfile (or yaml if you're using kubernetes).

There's a couple of things that we both agree:
- Env Vars would be a nice feature
- The way the configs are loaded (file, cml, env) need to be clear in terms or priority and who trumps who.

We disagree with the way it should be done.
You defend that the env vars partially replace some config parameter.
I defend that they should completely replace the value  

For me your approach has downsides (that I explained earlier), but I'm not the one implementing or deciding how this should be done.

**Comment by rwynn** [comment]
@BrunoPereira @mapshen can you please post a list of the configuration options you would like to see supported additionally as ENV vars?  

Currently the order of precedence is `command line` > `toml`.  

I think the ordering of this should be `command line` > `env` > `toml`.  

Env would only have a small set of vars available (URLs, user/pass, etc.).  

This should be testable with the `-print-config` flag.

**Comment by BrunoPereira** [comment]
@rwynn 
mongo-url
mongo-config-url
mongo-pem-file
mongo-oplog-database-name
mongo-oplog-collection-name

elasticsearch-user
elasticsearch-password
elasticsearch-urls
elasticsearch-pem-file

worker
direct-read-namespaces
namespace-regex

This ones looked 2 me like the ones that could change the most when using different environments.

About the order, could you clarify?
**command line** have priority over **>** **env**, env has priority over **> toml**.
Is that it?

**Comment by rwynn** [comment]
Yes, I meant > being priority higher.  If same in ENV and in TOML, then ENV wins.

What's the best general delimiter for an env variable.  White space, comma.  I'm thinking direct-read-namespaces would need multiple values delimited.

**Comment by mapshen** [comment]
@BrunoPereira we use Swarm and K8s and essentially our configuration files for stacks/pods are yaml files. In retrospect, the reason we ended up with configuring things in BOTH `env` and `config.file` for each service/application is that not all of them support loading configs from `env`, and that it supports for more use cases.

You did make a good point about the downside and it's great that we have `--print-config` to see the configs in use. However, the use case I have in mind is:

```
cluster-name = "col"

namespace-regex = '^db\.col$'
direct-read-namespaces = ["db.col"]
[[mapping]]
namespace = "db.col"
index = "col"
type = "page"
```
which I can't really think of a way for it (Array of Tables) to work with loading configs from `env` as we have customized types for each index. Right now, our solution is that, say if we use the Compose file, we do one `monstache` service per index and set the environment variable `db` and `col` for each service:

```
services:
  monstach-index1:
    image: "${docker_repo}:${version}"
    environment:
      db: db1
      col: col1
...
  monstach-index2:
    image: "${docker_repo}:${version}"
    environment:
      db: db2
      col: col2
...
```
A specific toml file is generated with env variables substituted when`monstache` starts up.

**Comment by BrunoPereira** [comment]
@rwynn 
From the list I mentioned, I think that direct-read-namespaces is the only one that could have multiple values.
My opinions on the deliminators:
-  " " space - this could be problematic, ppl can forget and add an extra space, have a "\t" tab instead and don't notice because of the IDE;
-  "," comma - it's the same as in the toml, the main option, maintains the coherence  
-  "|" pipe - you didn't mentioned this one, but I like the "|" pipe. It reminds me of the cml separator and the "||" OR in multiple languages.... different concepts but somehow appropriated in this case.

So, for me, the winner is "," comma . I value coherence.

@mapshen 
We're doing almost the same thing... :)
You have different clusters, I have different Envs.
I would say that you have 1 big instance with different clusters, I have different instances to physically separe the envs.

I have the same problem you have... and I'm doing the same, different instances with different toml depending on the database.collection .

In my opinion there's no reasonable way to have the vars using the toml tables defined in Env Vars.
That's why in my mind I just assumed that I would always have the toml and I could never replace it.
But if you have a solution ....

**Comment by mapshen** [comment]
@BrunoPereira we have different envs (dev/uat/prod) and each env has different clusters :) 

I conflated the two things, which is probably treated separately. The current solution is good enough to deal with different envs and @rwynn I would like to add `cluster-name` and `change-stream-namespaces` to @BrunoPereira suggested list. `change-stream-namespaces` can be treated the same way as `direct-read-namespaces`.

For the latter, we will change all the index types to the preferred "_id", since [mapping types are being removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_migrating_multi_type_indices_to_single_type), so that we don't have to worry about the `[[mapping]]` tables with Elasticsearch 6.x.

**Comment by rwynn** [comment]
@BrunoPereira and @mapshen 
The environment vars are in the latest release.  Thanks.

**Comment by mapshen** [comment]
@rwynn nice, thanks a lot! Will try it out and let you know.

**Comment by BrunoPereira** [comment]
@rwynn 
Sorry for not responding sooner, I only test it today.

It worked great in the fallowing ENV vars:
MONSTACHE_MONGO_CONFIG_URL
MONSTACHE_MONGO_URL
MONSTACHE_DIRECT_READ_NS
MONSTACHE_NS_REGEX
MONSTACHE_ES_URLS
MONSTACHE_MONGO_CONFIG_URL

Never the less, I did discover 1 minor problem:

If the **ENV** has MONSTACHE_MONGO_URL **defined 1st** and then MONSTACHE_MONGO_CONFIG_URL, I'm getting this error
**error:**
panic: Unable to get collection names
                for database local: can't use 'local' database through mongos

goroutine 92 [running]:
github.com/rwynn/gtm.OpLogCollectionName(0xc00021f6c0, 0xc000222820, 0xc000170240, 0xc00021f6c0)
        /go/src/github.com/rwynn/gtm/gtm.go:787 +0x2db

**Comment by rwynn** [comment]
@BrunoPereira thanks it was a copy paste issue and it should be fixed now.

**Comment by rwynn** [comment]
Yes, that is probably true.

**Comment by rwynn** [comment]
@mapshen just pushed out a new release to fix this.  BTW, it's actually `strings.SplitN(e, "=", 2)`.  The int arg is max substrings not max times to split.  Weird function since n = 0 always returns nil.

**Comment by mapshen** [comment]
works like a charm 👍
