### ISSUE TITLE
Syncing oplog before finishing the Direct Read 

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#135]
@rwynn 
I was under the impression that monstache (if configured for such), wouldn't start syncing the oplog before finishing the direct read.

I was doing tests with a production data and I was surprised when I had update operations almost immediately after starting monstache.
He was still doing the direct read, but it was syncing the oplog at the same time.
**config.toml**
```
# connect to MongoDB using the following URL
mongo-url = "mongodb://***********:27017"
mongo-config-url = "mongodb://***********:27019"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://***********:9200"]

# frequently required settings
# additionally, if you need to seed an index from a collection and not just listen for changes from the oplog
# you can copy entire collections from MongoDB to Elasticsearch
direct-read-namespaces = ["STABLE.Recording", "STABLE.User"]
# do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false 

# if you don't want to listen for changes to all collections in MongoDB but only a few
# e.g. only listen for inserts, updates, deletes, and drops from mydb.mycollection
# this setting does not initiate a copy, it is a filter on the change listener only
namespace-regex = "^STABLE.(Recording|User)$"

# compress requests to Elasticsearch
gzip = true
stats = true

# use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 4
elasticsearch-max-bytes=32000000
elasticsearch-max-seconds=5

#When elasticseach-retry is true a failed request to Elasticsearch will be retried with an exponential backoff policy. The policy is set with an initial timeout of 50 ms, an exponential factor of 2, and a max wait of 20 seconds.
elasticsearch-retry = true
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = false
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = false
# in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
replay = false
# saved in collection monstache.monstache
resume = true
resume-write-unsafe = true

# override the name under which resume state is saved (named by worker name)
resume-name = "monstache-stable"

# Monstache needs to ignore the deletes, we process them in Process
delete-strategy = 2

index-as-update = true
enable-http-server = false
pprof = true
```

**Comment by rwynn** [comment]
Yes it has always done direct reads and listening for changes in parallel. It does not assume those two are overlapping.

**Comment by BrunoPereira** [comment]
What if we have an update operation in the oplog from a record that hasn't been sync yet in the direct read.
Can monstache do the update first and the insert from the direct read after ? Or even have a delete operation in the oplog done before the insert is send to ES.
Won't this violate data consistency? 
And on a side note, how can I know that monstache has finished the direct read and is only syncing the oplog?

**Comment by rwynn** [comment]
That is why Monstache uses the timestamp from the oplog as the version number in elasticsearch. Elasticsearch will reject a change if the version number is lower than current. 

You cannot know when the direct reads are done unless you set exit-after-direct-reads. Is there a reason you need to care?

**Comment by BrunoPereira** [comment]
So I need to add the timestamp to the version since I'm processing the events (I'm using the Process function, so.... )

But that won't solve the problem from the delete, unless all deletes are soft ones.
If you send an hard delete ( oplog event) before the insert (direct read), Elastic won't have any copy with the timestamp and he won't discard the insert from the direct read.

I wanted to know if monstache had finished the direct reads just to have an indicator that that part was over and from that point on monstache was only reading from the oplog.

**Comment by rwynn** [comment]
Read this with attention to the last paragraph. 

https://www.elastic.co/blog/elasticsearch-versioning-support

**Comment by BrunoPereira** [comment]
That's other reason for me to know when the direct read is over.... to calculate how long monstache takes to do the direct reads because I need to keep the deletes on the Elastic (index.gc_deletes) for at least that long .... 

I would say that you should mention this (sync oplog and direct reads simultaneously) in the documentation.
Look at me, I that completely caught me off guard and I didn't plan for it

**Comment by rwynn** [comment]
If a doc is deleted while the direct reads are happening it won’t show up in the results. If it is read and then quickly deleted then those 2 events would be synced within a minute of one another. The order of which wouldn’t matter since the delete would carry a higher version number.

**Comment by rwynn** [comment]
To clarify further. The direct read is not a snapshot but rather a continuous query on the collection until no more results are found.

**Comment by BrunoPereira** [comment]
@rwynn 
If that's the strategy, ok, but my main point here is that you should mention that in the documentation.

I assumed wrongly (assumption is the mother of all fu.. ups) that the oplog sync would only stat after the direct read was over.
I was using ES to version the records, not the timestamps. You can see me surprise and the potencial snafu here.
I'm also using elastic.NewUpdateByQueryService in case I have updates, you can see the potencial snafu here.(I'm joining a bunch of Mongo records in to a single one in Elastic).

As you can see, that has a big impact on data consistency.
That was something I needed to know right from the start, to plan appropriately.

If I like your approach? That's not relevant. 
I don't know the reasons/constrains why you did it this way instead of another.
I respect your decisions and I thank you for all your work. 

PS: The oplog is sync by timestamp, right?

**Comment by rwynn** [comment]
I’ve always thought it necessary -  not a choice - to start tailing while doing direct reads. 

Consider direct reads start and doc is read at T0, doc is updated by user at T1 and direct reads finish at T2.  If you are not tailing at T0 then you miss an event and Elasticsearch gets out of sync.

**Comment by rwynn** [comment]
I will add it in the docs in a big bold box.  There is an option to completely turn off watching the oplog called `disable-change-events`.

**Comment by mapshen** [comment]
Don't see `disable-change-events` at https://rwynn.github.io/monstache-site/config?

**Comment by rwynn** [comment]
Yes I need to add it thanks.

**Comment by rwynn** [comment]
@BrunoPereira  @mapshen 

This behavior is now documented with a warning at https://rwynn.github.io/monstache-site/config/#direct-read-namespaces.

The `disable-change-events` option is also documented at https://rwynn.github.io/monstache-site/config/#disable-change-events.

**Comment by Hybrid-Force** [comment]
Understand why @rwynn start tailing oplog while direct reads is on going. By the way, I think another option is to 1) record the last oplog ts, 2) run direct reads, 3) then tail starting from that oplog ts from step 1).
