### ISSUE TITLE
Unable to overwrite dictionary field with empty dict

### ISSUE THREAD

**Issue by sbnajardhane** [rwynn/monstache#136]
@rwynn 

When I am updating dict fields in mongo with an empty object then those changes are not getting reflected into the ES?
```
db.user.update({id: "test"}, {$set: { "data_dict": {}}}
```
I have tried a couple of input and observe that it is like append operation and not the overwrite operation. So when the object is empty, the plugin is pushing an empty data to the existing record, Right?

 ```
db.user.update({id: "test"}, {$set: { "data_dict": null}}
```
This update is properly getting synced.
I cannot make the code change to use null as the application is already developed. 

Also, I have tried to add below script to make the empty object as null, but no luck
```
if (typeof data_dict != "undefined") {
    var is_empty = true;
        var obj = doc.data_dict;
        for(var key in obj) {
            if(obj.hasOwnProperty(key)) {
                is_empty = false;
                break;
            }
        }
        if (is_empty) {
            doc.data_dict = null;
        }
}
```

**Comment by rwynn** [comment]
Can you simply use index-as-update = false?

**Comment by sbnajardhane** [comment]
@rwynn 
will go with index-as-update = false, decided not to do any outside update on the elastic document
Will perform the application logic and save it into the mongodb. In this case, I will have a data backup.

[this issue](https://github.com/rwynn/monstache/issues/128) will also get resolve by changing index-as-update = false and still connecting to the secondary node.

**Comment by rwynn** [comment]
I would have thought the script to work. What does Monstache send (enable verbose) when you null the field in the script?

**Comment by rwynn** [comment]
I can confirm that simply setting to null in the script does not work (not included in the payload to Elasticsearch).  But I did find a work around.

```
[[script]]
script = """
module.exports = function(doc) {
  var o = _.clone(doc);
  o.test = null;
  return o;
}
"""
```

This seems like an implementation quirk of otto's Export function.

**Comment by sbnajardhane** [comment]
> I would have thought the script to work. What does Monstache send (enable verbose) when you null the field in the script?

In this case, the field is not included in the doc.

The above script is working fine for my case :+1: 
But I have decided to go with the index-as-update = false as this will solve our problem of reading stale data from mongo secondary.
