### ISSUE TITLE
Could this project adopt 'go.mod'?

### ISSUE THREAD

**Issue by chanpl** [rwynn/monstache#137]
I'm trying a build a binary in my company's environment. For security reason, I can't directly get packages from the Internet. Instead, an artifactory served this purpose.

However, in order to get go build working with artifactory, we must have go.mod and go.sum (and with proper setup in GOPROXY and GO111MODULE). May I ask for a go.mod and go.sum for this project?

**Comment by rwynn** [comment]
@chanpl please let me know if the recent changes will work for you.

**Comment by chanpl** [comment]
Thanks for your prompt action! It's working for me, appreciate your help.
