### ISSUE TITLE
Delay indexing with MongoDB view replication

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#138]
I created a MongoDB view from two collections.
db.createView("OrderView", "Order", [ {$lookup: {from: "Status", localField: "statusId", foreignField: "_id", as: "s"}} ])

monstahce config:
change-stream-namespaces = ["sklad_db.Order", "sklad_db.Status" ]
[[mapping]]
namespace = "sklad_db.Order"
index = "sklad_db"
[[mapping]]
namespace = "sklad_db.OrderView"
index = "sklad_db"
[[relate]]
namespace = "sklad_db.Order"
with-namespace = "sklad_db.OrderView"
keep-src = false
[[relate]]
namespace = "sklad_db.Status"
with-namespace = "sklad_db.Order"
src-field = "_id"
match-field = "statusId"
keep-src = false

I create a new document or edit an existing one in Order and it appears in the Elasticsearch index after 40-60 seconds. I tried to change all the settings but the indexing delay does not change. How to make MongoDB view indexed in real time without delay?

**Comment by rwynn** [comment]
Can you run with -verbose to see exactly when Monstache is sending the document? To see the latency from the update. 

You can also explicitly set elasticsearch-max-seconds to 1. Monstache will warn about performance when this value is less than 5s with direct-read-namespaces turned on. But if you need really low latency this is an option. 

Is it possible you have overridden the default refresh_interval in Elasticsearch from 1 second to a higher value?  The refresh interval will determine when Elasticsearch makes indexed docs available in search. The doc may be indexed but has just not been made available to appear yet.

**Comment by ail-13** [comment]
refresh_interval in Elasticsearch is set to 1. I tried to run with parameter -verbose and Monstache 
sends the document 43 seconds after it is created. If I use a MongoDB Collection instead of a View, then the Monstache is sending the document without delay. Maybe I need to write something else in the conf file? Or maybe I'm using non-compatible versions of MongoDB or Elasticsearch.

INFO 2018/12/06 19:02:35 Started monstache version 4.11.5
INFO 2018/12/06 19:02:35 Successfully connected to MongoDB version 3.6.3
INFO 2018/12/06 19:02:35 Successfully connected to Elasticsearch version 5.6.13
INFO 2018/12/06 19:02:35 Listening for events
INFO 2018/12/06 19:02:35 Sending systemd READY=1
WARN 2018/12/06 19:02:35 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)

**Comment by rwynn** [comment]
I think you may have run into an issue with a previous release of monstache.  Can you try version 4.12.3?  It should now report something along the lines of at startup...

```
...
INFO 2018/12/06 20:14:34 Started watching changes on test.test
```

There was a problem with monstache getting stuck.  Please let me know if you still have issues with the latest version.

**Comment by ail-13** [comment]
I installed v4.12.3 and everything works fine. Should I try to install v3.19.3 or I can stay on v4.12.3? I didn't touch the MongoDB and Elasticsearch versions. Wouldn't that be a problem?

**Comment by rwynn** [comment]
If you are using Elasticsearch 5.X then I would recommend v3.19.3.  I keep both monstache streams up to date with the latest fixes.  The major difference between the 2 streams (master vs rel3 branch) is that v3.X is built against `gopkg.in/olivere/elastic.v5` while v4.X is built against `github.com/olivere/elastic`.  The matrix is show here:

https://github.com/olivere/elastic#releases

It's basically about using the recommended Elasticsearch driver version to ensure best compatibility.

**Comment by ail-13** [comment]
I tried to use both v3.19.3 and v4.12.3. Both give the same result. Nothing happens after I create a document in the collection. A new document is not sent to the index at all.

INFO 2018/12/06 21:55:35 Started monstache version 3.19.3
INFO 2018/12/06 21:55:35 Successfully connected to MongoDB version 3.6.3
INFO 2018/12/06 21:55:35 Successfully connected to Elasticsearch version 5.6.13
INFO 2018/12/06 21:55:35 Listening for events
INFO 2018/12/06 21:55:35 Sending systemd READY=1
WARN 2018/12/06 21:55:35 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2018/12/06 21:55:35 Started watching changes on livesklad_db.Status
INFO 2018/12/06 21:55:35 Started watching changes on livesklad_db.Order

**Comment by ail-13** [comment]
Everything works fine when I try to index a Collection rather than a View.

change-stream-namespaces = ["sklad_db.Order", "sklad_db.Status", "sklad_db.History" ]
[[mapping]]
namespace = "sklad_db.History"
index = "sklad_db"
[[mapping]]
namespace = "sklad_db.Order"
index = "sklad_db"
[[mapping]]
namespace = "sklad_db.OrderView"
index = "sklad_db"
[[relate]]
namespace = "sklad_db.Order"
with-namespace = "sklad_db.OrderView"
keep-src = false
[[relate]]
namespace = "sklad_db.Status"
with-namespace = "sklad_db.Order"
src-field = "_id"
match-field = "statusId"
keep-src = false

When I create a document in the History collection, the document is immediately sent to the index

INFO 2018/12/06 22:09:47 Started monstache version 3.19.3
INFO 2018/12/06 22:09:47 Successfully connected to MongoDB version 3.6.3
INFO 2018/12/06 22:09:47 Successfully connected to Elasticsearch version 5.6.13
INFO 2018/12/06 22:09:47 Listening for events
INFO 2018/12/06 22:09:47 Sending systemd READY=1
WARN 2018/12/06 22:09:47 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2018/12/06 22:09:47 Started watching changes on livesklad_db.Status
INFO 2018/12/06 22:09:47 Started watching changes on livesklad_db.History
INFO 2018/12/06 22:09:47 Started watching changes on livesklad_db.Order
TRACE 2018/12/06 22:09:57 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.76 (linux-amd64)
Content-Length: 437
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_id":"5c099e348a2fac74ad9a5ef4","_index":"sklad_db","_type":"History","_version":6632005872455254016,"_version_type":"external"}}
{"text":"test","dateCreate":"2018-12-06T22:09:56.96Z"}

TRACE 2018/12/06 22:09:57 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":48,"errors":false,"items":[{"index":{"_index":"sklad_db","_type":"History","_id":"5c099e348a2fac74ad9a5ef4","_version":6632005872455254016,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true,"status":201}}]}

**Comment by rwynn** [comment]
You had a comment that everything was working fine after upgrading. Was that not the case?  

Intiallly you said there was a delay. Now it is not indexed at all?

**Comment by rwynn** [comment]
I tried to replicate this issue by creating a config file exactly as you posted.  I was not able to reproduce the problem.  

MongoDB: 3.6
Elasticsearch: 6.0
Monstache: 4.12.3

The following shows the log.  Monstache was sending the requests immediately upon making changes via the MongoDB console.

The 1st trace is upon inserting a new Order.  The 2nd trace is upon updating the Status (myStatus field) related to the Order.  

```
TRACE 2018/12/07 04:52:39 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.14 (linux-amd64)
Content-Length: 191
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"sklad_db","_id":"5c09f932a39cedca3b2ae879","_type":"OrderView","version":6632109651750027264,"version_type":"external"}}
{"s":[{"_id":0,"myStatus":"STAT"}],"statusId":0}

TRACE 2018/12/07 04:52:39 HTTP/1.1 200 OK
Content-Length: 262
Content-Type: application/json; charset=UTF-8

{"took":10,"errors":false,"items":[{"index":{"_index":"sklad_db","_type":"OrderView","_id":"5c09f932a39cedca3b2ae879","_version":6632109651750027264,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2018/12/07 04:52:39 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.14 (linux-amd64)
Content-Length: 191
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"sklad_db","_id":"5c09fc80a39cedca3b2ae87a","_type":"OrderView","version":6632109651750027264,"version_type":"external"}}
{"s":[{"_id":0,"myStatus":"STAT2"}],"statusId":0}

TRACE 2018/12/07 04:52:39 HTTP/1.1 200 OK
Content-Length: 262
Content-Type: application/json; charset=UTF-8

{"took":11,"errors":false,"items":[{"index":{"_index":"sklad_db","_type":"OrderView","_id":"5c09fc80a39cedca3b2ae87a","_version":6632109651750027264,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":200}}]}

```

Console stuff done

```
db.createView("OrderView", "Order", [ {$lookup: {from: "Status", localField: "statusId", foreignField: "_id", as: "s"}} ]);
db.Status.insert({_id: 0, myStatus: "STAT"});
db.Order.insert({statusId: 0})
db.Status.update({}, {$set: {myStatus: "STAT2"}});
```

**Comment by ail-13** [comment]
> You had a comment that everything was working fine after upgrading. Was that not the case?
> 
> Intiallly you said there was a delay. Now it is not indexed at all?

I created 2 documents and it worked fine, but then the documents are no longer sent to the index. First I used the v4.11.5 and the documents were sent to the index with a delay, then I tried v3.19.3 and v4.12.3 and documents are not sent to the index at all.
https://drive.google.com/open?id=1_F0Uh0xnQNVNJxet_tk2yptVAj-iftp5
I can't use Elasticsearch 6.X because I need the elasticsearch-analysis-morphology module and it currently supports Elasticsearch 5.X only.
Maybe I have configured incorrectly? Can you send me your conf file?
