### ISSUE TITLE
resume-name option (command line & config file) is ignored.

### ISSUE THREAD

**Issue by realmovestar** [rwynn/monstache#143]
resume-name option is not considered when determine config.ResumeName

https://github.com/rwynn/monstache/blob/54bfd4ec1fc19fab4d16a073bad9b5bf226e63c9/monstache.go#L2107-L2118

**Comment by rwynn** [comment]
Thanks for reporting this. Will fix in next release.

**Comment by rwynn** [comment]
@realmovestar this should be fixed now in the latest release.  Thanks.
