### ISSUE TITLE
Unable to create Elasticsearch client using AWS ES service

### ISSUE THREAD

**Issue by nakulm95** [rwynn/monstache#144]
I'm unable to connect to the AWS managed ES endpoint. Here is the output log:
`ERROR 2018/12/14 11:59:32 Unable to create Elasticsearch client: Head https://<host>:9200: Head <host>:9200: context deadline exceeded`
`INFO 2018/12/14 11:59:32 Shutting down with exit status 1 after panic.`

Configuration settings:
`elasticsearch-urls = ["<host>:9200"]`
`verbose = true`
`[aws-connect]`
`access-key = "<key>"`
`secret-key = "<key>"`
`region = "us-west-2"`

Any idea(s) as to why this could be happening? Thanks!

**Comment by rwynn** [comment]
What version of monstache?  Can you try putting the elasticsearch version in the config?

**Comment by rwynn** [comment]
Are you able to connect with another client?  Any other.

**Comment by rwynn** [comment]
You may also need to specify port :443 in your connection string.  I think the elasticsearch driver might default to 9200 but I think AWS may use the default https port.

**Comment by rwynn** [comment]
I did a quick test on my end and everything worked OK.  I was using the latest version of monstache at 4.12.4.  Monstache config below:

```
elasticsearch-urls = ["https://<endpoint_from_aws_overview_screen>:443"]

[aws-connect]
access-key = "123"
secret-key = "456"
region = "us-east-1"

```

I also used this guide to setup the domain and cluster...

https://medium.com/@ahuijsen/setting-up-permissions-for-elasticsearch-service-in-aws-2fef7cc02b4c

That basically involved creating a new IAM user with no permissions.  Then setting up the Elasticsearch domain and giving that user access as shown in the link.  

```
 {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<account-id>:user/es-user"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-east-1:<account-id>:domain/es-coffeebean-ninja/*"
    },
```

**Comment by nakulm95** [comment]
> You may also need to specify port :443 in your connection string. I think the elasticsearch driver might default to 9200 but I think AWS may use the default https port.

You are absolutely right, I didn't know about 443 so I was putting 9200. Once I changed it to 443, everything flowed through. Thanks!

**Comment by nakulm95** [comment]
> You may also need to specify port :443 in your connection string. I think the elasticsearch driver might default to 9200 but I think AWS may use the default https port.

You are absolutely right, I didn't know about 443 so I was putting 9200. Once I changed it to 443, everything flowed through. Thanks!
