### ISSUE TITLE
Watching changes on specific fields in [[relate]]

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#146]
Hello, is there any way to define in [[relate]] which fields it is necessary to watching?
I have 2 views:
db.createView("OrderView", "Order", [
    { $lookup: {from: "Cash", localField: "_id", foreignField: "orderId", as: "cash"}},
    { $addFields: {
        sum:  {
            $reduce: {
                input: "$cash",
                initialValue: 0,
                in: { $add : [ "$$value", "$$this.money" ] }
            }
        }
    }},
    { $project: { cash: 0 }}
]);
db.createView("CashView", "Cash", [ { $lookup: {from: "Item", localField: "itemId", foreignField: "_id", as: "item"}} ]);

and config:

[[mapping]]
namespace = "db.Order"
index = "db"
[[mapping]]
namespace = "db.OrderView"
index = "db"
type = "Order"
[[relate]]
namespace = "db.Order"
with-namespace = "db.OrderView"
keep-src = false
[[relate]]
namespace = "db.Cash"
with-namespace = "db.Order"
src-field = "orderId"
match-field = "_id"
keep-src = false

[[mapping]]
namespace = "db.Cash"
index = "db"
[[mapping]]
namespace = "db.CashView"
index = "db"
type = "Cash"
[[relate]]
namespace = "db.Cash"
with-namespace = "db.CashView"
keep-src = false
[[relate]]
namespace = "db.Item"
with-namespace = "db.Cash"
src-field = "_id"
match-field = "itemId"
keep-src = false

In this case, when I change the doc of Item, the related Cash also changes. But it also changes all Order documents related this Cash doc. Maybe there are some settings to watching only for specific fields changes in [[relate]]? Something like this
[[relate]]
namespace = "db.Cash"
with-namespace = "db.Order"
src-field = "orderId"
match-field = "_id"
keep-src = false
**fields = ["money"]**

**Comment by rwynn** [comment]
The only support for watching only specific fields is outlined here:

https://rwynn.github.io/monstache-site/advanced/#watching-changes-on-specific-fields-only

I'm not sure that gets you what you want.  This will only filter the original change that happened in MongoDB not any "forced" changes via `[[relate]]`.

**Comment by ail-13** [comment]
Ok, thanks
