### ISSUE TITLE
How to sync some specific fields of documents from mongo collection to elasticsearch

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#149]
hi Ryan,

    i want to sync some specific fields of some documents of one collection to elasticsearch5.x, how do i set the config file or other method to implement it
for example: 
my document has name,age,city,address,sex,jobtitle fields, but i only want to sync name,age,city these three fields to elasticsearch5.x, other fields not sync to elasticsearch5.x, thanks

**Comment by rwynn** [comment]
One way to do this is with a script, Scripts are run after the results are returned.

```
[[script]]
# this script does not declare a namespace
# it is global to all collections
script = """
module.exports = function(doc, ns) {
    // the doc namespace e.g. test.test is passed as the 2nd arg
    return _.pick(doc, "name", "age", "city");
}
"""
```

Another way which is more efficient but a little more difficult to setup is using an aggregation pipeline which runs at query time.  In this case MongoDB would be doing the projection instead of monstache.  

Monstache supports aggregation pipelines via the `[[pipeline]]` config.

https://rwynn.github.io/monstache-site/config/#pipeline

You would want to construct a pipeline that uses a [project](https://docs.mongodb.com/manual/reference/operator/aggregation/project/#pipe._S_project) stage.

Note that for change streams this pipeline would be operating on [change events](https://docs.mongodb.com/manual/reference/change-events/) and you would only want to only change the projection of the `fullDocument` field within that change event.

**Comment by sunweiconfidence** [comment]
thanks for your quick reply ,i will try it using your way
    another question is that whether current monstache version has fully use change stream to replace mongo oplog technology to implement Synchronizing mongo collection to elasticsearch6.x's index? thanks

**Comment by rwynn** [comment]
Monstache supports both (1) tailing the oplog collection in local db directly and (2) using the MongoDB 3.6 change streams API to access it. 

Option #1 is the only option if you cannot upgrade to MongoDB 3.6 or greater. 

Option #1 is the default in Monstache. To get Option #2 you need to specify change-stream-namespaces config. 

For ES 6 you should use monstache v4.X

Does that answer your question?

**Comment by sunweiconfidence** [comment]
Hi Ryan,
    thanks your answer, i will try it.

**Comment by sunweiconfidence** [comment]
Hi Ryan, i have a question need to confirm with you, whether rel3 branch support change stream if i have upgrade mongodb to greater than 3.6 version? thanks

**Comment by rwynn** [comment]
Rel 3 does support change streams.  The only difference between rel 3 and 4 is the support for Elasticsearch.

**Comment by sunweiconfidence** [comment]
@rwynn , thanks for your answer.

**Comment by rwynn** [comment]
With MongoDB 3.6 you can have a change stream on collections only. With 4.0 you can additionally have the stream on dbs or the entire deployment.

**Comment by uday-awv** [comment]
Hi Ryan,
I am also looking for this exact feature. I am facing one challenge with nested fields.
`[[script]]
# this script does not declare a namespace
# it is global to all collections
script = """
module.exports = function(doc, ns) {
    // the doc namespace e.g. test.test is passed as the 2nd arg
    return _.pick(doc, "name", "address.city");
}
"""`
Is there a easy way to pick up (or omit) the field "address.city" too from document? Thanks.

**Comment by sgonv** [comment]
I tried to do projection with pipeline, but it does not work.

My config.toml is like below,
```
change-stream-namespaces = ["somedb.collection"]

[[pipeline]]
namespace = "somedb.collection"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    console.log(1234)
    return [
      {
        $project: {
          "someObject.name": 1,
          "someObject.age": 1,
          "userId": 1
        }
      }
    ];
  } else {
    console.log(5678)
    return [];
  }
}
"""
```

When I started monstache with this config,
1234 was printed on my stdout.

After I inserted some data to my MongoDB, neither 1234 nor 5678 is printed and inserted data is not transfered to ES.

Is there any missing for my config? Or how can I debug my pipeline's incorrectness?

**Comment by rwynn** [comment]
Your pipeline function will only be executed once to get the pipeline to run. 

Your pipeline executes against a Change stream event.  

https://docs.mongodb.com/manual/reference/change-events/

Monstache needs the whole change doc to be passed through. Your pipeline should only alter the fullDocument field which is your document’s data.

**Comment by rwynn** [comment]
Note how this pipeline references fields of the change event spec. 

https://rwynn.github.io/monstache-site/advanced/#watching-changes-on-specific-fields-only

**Comment by sgonv** [comment]
Thanks for your immediate response.

So I changed my config like this, (Also referenced https://stackoverflow.com/questions/49153312/mongodb-change-stream-display-only-selected-fields)
```
[[pipeline]]
namespace = "somedb.collection"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $project: {
          "name": "fullDocument. someObject.name",
          "age": "fullDocument.someObject. age",
          "userId": "fullDocument.userId"
        }
      }
    ];
  } else {
    return [];
  }
}
```
But still it doesn't work.

In my understanding, If I set change-stream-namespaces, monstache automatically watch my collection. When CRUD occurred, change streams automatically invoked in MongoDB. And monstache automatically detect that change and apply pipeline to data, finally send data to ES.

Do I have to do something to invoke changing event?

If not, I don't know why my monstache doesn't notice my MongoDB's CRUD.

**Comment by sgonv** [comment]
Ah, finally I got answer.
https://vinta.ws/code/mongodb-change-stream-react-to-real-time-data-changes.html
This was helpful for me.
My config is finally like this,
```
[[pipeline]]
namespace = "somedb.collection"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $project: {
          _id: 1,
          "operationType": 1,
          "fullDocument.someObject.name": 1,
          "fullDocument.someObject.age": 1,
          "fullDocument.userId": 1,
          "ns": 1
        }
      }
    ]
  } else {
    return []
  }
}
"""
```
Projection was literally projection... So I have to make result of projection to form of change event response (https://docs.mongodb.com/manual/reference/change-events/)

Thanks!

**Comment by sgonv** [comment]
> Hi Ryan,
> I am also looking for this exact feature. I am facing one challenge with nested fields.
> 
> ```
> [[script]]
> # this script does not declare a namespace
> # it is global to all collections
> script = """
> module.exports = function(doc, ns) {
>     // the doc namespace e.g. test.test is passed as the 2nd arg
>     return _.pick(doc, "name", "address.city");
> }
> """
> ```
> Is there a easy way to pick up (or omit) the field "address.city" too from document? Thanks.

In my test, pick "address" was working, but pick "address.city" was not working.

**Comment by rwynn** [comment]
Pick function is simply this.  

https://underscorejs.org/#pick

So doesn’t work for nested attributes.
