### ISSUE TITLE
The delete event does not synced via [[relate]]

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#150]
Hello, I have 2 collection`s Order and Item, and 2 view`s OrderView and ItemView. ItemView based only on Item, OrderView based both Order and Item. When I create or change the doc in Item it also change in index OrderView and ItemView. But when I delete doc it only deleted from ItemView and does not change the relate record in OrderView.

change-stream-namespaces = [ "db.Item", "db.Order" ]
[[mapping]]
namespace = "db.Item"
index = "db"
[[mapping]]
namespace = "db.ItemView"
index = "db"
type = "Item"

[[relate]]
namespace = "db.Item"
with-namespace = "db.ItemView"
keep-src = false
[[relate]]
namespace = "db.Work"
with-namespace = "db.Item"
src-field = "_id"
match-field = "workId"
keep-src = false

[[mapping]]
namespace = "db.Order"
index = "db"

[[relate]]
namespace = "db.Order"
with-namespace = "db.OrderView"
keep-src = false
[[relate]]
namespace = "db.Item"
with-namespace = "db.Order"
src-field = "orderId"
match-field = "_id"
keep-src = false

The result of create doc in Item

TRACE 2018/12/22 15:53:55 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.76 (linux-amd64)
Content-Length: 443
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_id":"5c1e5e135da8950e20aaf442","_index":"db","_type":"Item","_version":6637846332193112064,"_version_type":"external"}}
{"code":177,"count":1,"date":"2018-12-22T13:09:00.927Z","orderId":"5c12639f2ac3393e40fbbabf","price":100}

TRACE 2018/12/22 15:53:55 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":18,"errors":false,"items":[{"index":{"_index":"db","_type":"Item","_id":"5c1e5e135da8950e20aaf442","_version":6637846332193112064,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"created":true,"status":201}}]}
TRACE 2018/12/22 15:53:55 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.76 (linux-amd64)
Content-Length: 1130
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_id":"5c12639f2ac3393e40fbbabf","_index":"db","_type":"Order","_version":6637846332193112064,"_version_type":"external"}}
{item":{"count":1, "summ":100},"dateCreate":"2018-12-13T13:50:23.08Z","statusId":"59480d588ef20c7313d7bf27"}

TRACE 2018/12/22 15:53:55 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":12,"errors":false,"items":[{"index":{"_index":"db","_type":"Order","_id":"5c12639f2ac3393e40fbbabf","_version":6637846332193112064,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"created":false,"status":200}}]}

And result of delete

TRACE 2018/12/22 15:56:01 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.76 (linux-amd64)
Content-Length: 147
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_id":"5c1e5e135da8950e20aaf442","_index":"db","_type":"Item","_version":6637846873358991360,"_version_type":"external"}}

TRACE 2018/12/22 15:56:01 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":24,"errors":false,"items":[{"delete":{"found":true,"_index":"db","_type":"Item","_id":"5c1e5e135da8950e20aaf442","_version":6637846873358991360,"result":"deleted","_shards":{"total":1,"successful":1,"failed":0},"status":200}}]}

Why does the delete event not change related documents? Maybe I missed some settings?

**Comment by rwynn** [comment]
Relate doesn’t support delete because the document is no longer in MongoDB to make the relationship query work. I guess it could possibly support this but only if the _id is used as the src-field of the thing being deleted. On deletes only the _id is returned. I think in your case it would not work cause orderId would be gone. If you had it reversed with itemId on Order then the relationship could still be made.

**Comment by rwynn** [comment]
Other option to support this is to get the data from Elasticsearch on a delete with a relate. That probably would take some thought on how to do that reliably.

**Comment by ail-13** [comment]
Then the easiest way for me is to do the delete through the app. Thanks for the explanation and for your quickly answer

**Comment by rwynn** [comment]
One trick may be to do a replace type update in mongo right before you delete with a timestamp added. By replace I mean db.update(docId, fulldocWithTsAdded). No $set cause that would not work. db.remove(docId). By doing a replace monstache will not fetch the soon to be deleted doc. How clean this would be is up to you.

**Comment by ail-13** [comment]
Thank you for your advice
