### ISSUE TITLE
Feature request: multiple ES docs from one mongo doc

### ISSUE THREAD

**Issue by Positivex** [rwynn/monstache#154]
Hi Ryan,

I have a use case where I need to create/update multiple Elasticsearch documents from one mongo document. Using a JS middleware it would look something like this:

	module.exports = function(doc, ns, updateDesc) {
		var docs = doc.locations.map(function(location) {
			...
			location._meta_monstache = { id: location.id };
			return location;
		})

		return docs;
	}
I didn't find anything like it in the documentation, is it possible with the current version?

**Comment by rwynn** [comment]
@Positivex to map an event to multiple indexed docs you can use a golang plugin and implement a `Process` function as described [here](https://rwynn.github.io/monstache-site/advanced/#golang).  The `Process` function gets access to the bulk indexer so you can  use that API to queue requests to get flushed in bulk.  For an example of how that API works see [doIndexing](https://github.com/rwynn/monstache/blob/v4.13.0/monstache.go#L2516).  

I will think about maybe supporting returning multiple docs for the javascript function, but I would rather all these more complex scenarios be implemented in a `Process` function.

**Comment by Positivex** [comment]
Nice, thank's for the answer!

**Comment by priyanksha** [comment]
@Positivex Can you share the implementation for the process function to implement multiple ES docs from one mongo doc. I am stuck in this.
