### ISSUE TITLE
version_conflict_engine_exception in MongoDB view replication

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#157]
Hello, I have to collections Document and Product. Document has many child Product. I created view
db.createView("DocumentView", "Document", [
    { $lookup: {from: "Product", localField: "_id", foreignField: "documentId", as: "p"}},
    { 
        $addFields: {
            sum: {
                $reduce: {
                    input: "$p",
                    initialValue: 0,
                    in: { $add : [ "$$value", "$$this.price" ] }
                }
            }
        }
    }
]

The conf

[[mapping]]
namespace = "db.Document"
index = "db"
[[mapping]]
namespace = "db.DocumentView"
index = "db"
type = "Document"

[[relate]]
namespace = "db.Document"
with-namespace = "db.DocumentView"
keep-src = false
[[relate]]
namespace = "db.Product"
with-namespace = "db.Document"
src-field = "documentId"
match-field = "_id"
keep-src = false

When I create doc in Document and after few seconds create child Product the monstache completely sync it all in Elasticsearch. But when I create doc in Document and child Product at one time, the field "sum" in Document is always 0. And I have many errors:
ERROR 2019/01/10 21:16:16 Bulk response item: {"_index":"db","_type":"Document","_id":"5c37b620ae6e1325972ec74e","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[Document][5c37b620ae6e1325972ec74e]: version conflict, current version [6644980023763664896] is higher or equal to the one provided [6644980023763664896]","index":"db"}}.
How can I solve it?

**Comment by rwynn** [comment]
Can you explain more what you mean by "at one time".  Does this mean two `insert` actions one right after another or does this mean MongoDB 4 transactions?

You might be able to work around it by setting `index-as-update=true`.   With this setting version numbers are not sent with requests and last one wins.  

For the default case, I might need to increment the version number in a relate scenario to fix these conflicts.  Defaults use the oplog timestamp as the version number for [optimistic concurrency control](https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html).

version_conflict_engine_exception is not always an error that needs attention.  Monstache uses version numbers to ensure that create/update/delete operations are applied in order in Elasticsearch even though Monstache may send these out of order to Elasticsearch.   When you replay events from the oplog you may see this error, but it simply means that Elasticsearch already has a newer version which is OK.  

In this scenario though `relate` is producing synthetic events (if Product changes pretend Document changed also) so special handling may be required.

**Comment by ail-13** [comment]
I use `insert `actions one right after another, first I insert one doc in Document and then several child docs in Product. Should I use the index-as-update=true setting? Or is there a better way?

**Comment by rwynn** [comment]
@ail-13 I think this issue should be fixed in `master` and `rel3` branches.  Would you be able to verify on your end?  I haven't cut a new release yet so you would need to build the binary yourself.  This should fix it without the need to use `index-as-update`.

**Comment by ail-13** [comment]
Yes, it works properly. Thanks! Can I use it or I should wait for new release?

**Comment by rwynn** [comment]
You can use it but I will cut a new release this week so that it's official.  Thanks.

**Comment by ail-13** [comment]
Thanks
