### ISSUE TITLE
mongo _id in integer format, inserted as scientific format in elasticsearch

### ISSUE THREAD

**Issue by hanjoyo** [rwynn/monstache#16]
hello @rwynn, thanx for the great work :+1:
I have some issue regarding _id in mongodb being sync to elasticsearch using monstache

__________________________________________________
- [ ] an integer _id type in mongodb will be submited in a scientific format in elasticsearch
here attached the oplog and monstache verbose log:
__________________________________________________
```
Oplog :
{ "ts" : Timestamp(1483929958, 2), "h" : NumberLong("-2994949912686646076"), "v" : 2, "op" : "i", "ns" : "mydb.user", "o" : { "_id" : 28263934, "name" : "Lean publishing", "lname" : "Lean.co.id", "email" : "Lean@mydb.it", "password" : "$1/5/VpWVexO3yaxBn/s/", "username" : "Lean" } }
Monstache verbose :
INFO 2017/01/09 09:46:01 request body: {"index":{"_index":"mydb","_type":"user","_id":"2.8263934e+07"}}
{"user_name":"Lean publishing","user_username":"Lean"}
```

__________________________________________________
- [x] a long _id type in mongodb will be submited just ok in elasticsearch
here attached the oplog and monstache verbose log:
__________________________________________________
```
Oplog :
{ "ts" : Timestamp(1483930001, 2), "h" : NumberLong("7988208314667247132"), "v" : 2, "op" : "i", "ns" : "mydb.user", "o" : { "_id" : NumberLong(28263935), "name" : "Lean publishing", "lname" : "Lean.co.id", "email" : "Lean@mydb.it", "password" : "$1/5/VpWVexO3yaxBn/s/", "username" : "Lean" } }
Monstache verbose :
INFO 2017/01/09 09:46:46 request body: {"index":{"_index":"mydb","_type":"user","_id":"28263935"}}
{"user_name":"Lean publishing","user_username":"Lean"}
```

**Comment by rwynn** [comment]
@hanjoyo thanks for the kind words.  Hope this commit fixes the issue for you.  The id should now be inserted without scientific notation.  Any integer values within the document itself, { count: 28263935 }, seem to still be inserted in this notation, but from reading it seems that this is valid JSON to do so.

**Comment by rwynn** [comment]
@hanjoyo 

Did you insert these documents using the mongodb shell?  According to this link https://docs.mongodb.com/v3.2/core/shell-types/ the mongodb shell treats all numbers as floating point values.  Thus, when you use the shell and want an int you would wrap the number in `NumberInt()`.

**Comment by hanjoyo** [comment]
hi @rywnn
sorry for my late reply
yes, your commit fixes my issue.
I used several ways to insert these documents: from mongo shell and also php code
thank you
