### ISSUE TITLE
how to handle DBref data that sync from mongo to es?

### ISSUE THREAD

**Issue by flyinghawker** [rwynn/monstache#160]
In some scenarios, there is dbref data that exsits in mongod model, how we can map that properly to es database. This should be very common case anyway.

**Comment by rwynn** [comment]
Since monstache doesn't have this ability yet you may be able to use a [pipeline](https://rwynn.github.io/monstache-site/advanced/#aggregation-pipelines) config or [native MongoDB view](https://docs.mongodb.com/manual/core/views/) with a [$lookup](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/) phase to accomplish the join on the server.  That might actually be more efficient.  Not sure if you can do that with a DBRef but a DBRef should really just be a special embedded object with a db, collection, and id.

**Comment by rwynn** [comment]
There might be some help [here](https://stackoverflow.com/questions/40622714/mongo-how-to-lookup-with-dbref).

**Comment by rwynn** [comment]
Another option if you are comfortable in golang is to create a monstache golang [plugin](https://rwynn.github.io/monstache-site/advanced/#golang) and implement a `Map` function that takes the DBRef from the Document map and replaces it with the referenced document using the [mgo API](https://godoc.org/github.com/globalsign/mgo#Database.FindRef).

**Comment by flyinghawker** [comment]
@rwynn 
Actually, I do research on this, first of all, DBref means relation that we may need join query in SQL, but elasticsearch seems not support it that perfectly, only nested and parent-child two options and the later one is closer to my requirement but still not enough. When index child, parent Id has to be clearly defined but actual case is that child document may have multiple parents. Eg. Multiple people could simultaneously add "Like" to one post, so as a child the post has multiple parents existing. Anyway, this seems another issue, I will add this question in stackoverflow. Thanks.

**Comment by rwynn** [comment]
@flyinghawker have you already read the following part of the documentation? 

https://rwynn.github.io/monstache-site/advanced/#joins 

https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html

You may need to combine separate concepts in monstache to accomplish the task.  e.g. scripts to override the destination index, transform the document, route the document, etc.

**Comment by flyinghawker** [comment]
@rwynn Yeah, actually I have just finished the reading about the new feature in es 6.X, but still, it only supports one parent -> many children relation, that means I may need to increase the redundancy to meet the requirement. Still, this is Elasticsearch related issue. Thanks anyway.
