### ISSUE TITLE
Unable to connect to elasticsearch using docker image

### ISSUE THREAD

**Issue by sbnajardhane** [rwynn/monstache#162]
Hi @rwynn 

I have created a container using the latest monstache docker image. Running Elasticsearch as a docker image, version 6.5 
Below is my connection settings.
```
mongo-url = "mongodb://mongo_node:27017"
elasticsearch-urls = ["http://elasticsearch_node:9200"]
```
I am able to connect to the mongo node successfully but not able to connect to the elasticsearch. 
I have verified that elasticsearch is up and running and above url is accessable. I am able to get results  ```curl -XGET http://elasticsearch_node:9200``` from my other containers. So elasticsearch is working fine.
Don't know why I am not able to connect to the elasticsearch using monstache docker.
Is there anything I am doing wrong?

**Comment by rwynn** [comment]
@sbnajardhane I'm not sure what it could be.  I just ran the tests after updating the Elasticsearch version number fo 6.5.4 and I didn't see any errors with the docker compose run.

https://github.com/rwynn/monstache/tree/v4.13.2/docker/test

Only changed the following:

```
image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
to
image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
```

Then ran `run-tests.sh`.

**Comment by sbnajardhane** [comment]
The tests helped me to resolve the issue, made some mistake in docker compose.
Resolved. 
Thannks
