### ISSUE TITLE
Sync stops working

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#163]
Hello, the sync stops working after an random time. A few days everything can work properly and then the sync of any changes stops working. Sometimes it happens several times a day. And sync can stop working only for several collections and can all at once. And Monstache begins to heavily load the CPU. After restarting Monstache everything is working properly. I found nothing in the logs, and I can't trace the pattern. Once it happened after removing a large number of documents at once (~10000), but maybe I'm wrong because I could not repeat it. What could be the problem?
![image](https://user-images.githubusercontent.com/45662718/51472671-321e0a80-1d8b-11e9-8c34-7e068fbdb281.png)

**Comment by rwynn** [comment]
Do you have any timeouts specified in your config?

**Comment by rwynn** [comment]
Maybe the `relate` config is triggering many updates to happen?  You mentioned 10k deletes.  Relate configs may cause 10k queries in this case.

**Comment by ail-13** [comment]
Several collections have a one-to-many `relate`. How can I fix it? Should I remove the collection with [[relate]] settings with a delay in parts or is there any settins wich can fix this?

**Comment by rwynn** [comment]
You might try breaking the one-to-many `relate` out into another config file and run 2 monstache processes.
For example if you normally have something like...
```
direct-read-namespaces = ["thingdb.thingview"] # read direct from the view of the collection to seed index

change-stream-namespaces = ["thingdb.thing", "thingdb.state"] # change events happen on the underlying collections not views

[[mapping]]
namespace = "thingdb.thing" # map change events on the thing collection to the things index
index = "things"

[[mapping]]
namespace = "thingdb.thingview" # map direct reads of the thingview to the same things index
index = "things"

[[relate]]
namespace = "thingdb.thing"  # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "thingdb.thingview"
keep-src = false # ignore the original thing that changed and instead just use the lookup of that thing via the view

[[relate]]
namespace = "thingdb.states" # when a state changes trigger a thing change event since thing is associated to a state
with-namespace = "thingdb.thing"
src-field = "_id" # use the _id field of the state that changed to lookup associated things
match-field = "s" # only trigger change events for the things where thing.s (match-field) = state._id (src-field).
keep-src = false
```

Then you could break that into 

```
direct-read-namespaces = ["thingdb.thingview"] # read direct from the view of the collection to seed index

change-stream-namespaces = ["thingdb.thing"] # change events happen on the underlying collections not views

[[mapping]]
namespace = "thingdb.thing" # map change events on the thing collection to the things index
index = "things"

[[mapping]]
namespace = "thingdb.thingview" # map direct reads of the thingview to the same things index
index = "things"

[[relate]]
namespace = "thingdb.thing"  # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "thingdb.thingview"
keep-src = false # ignore the original thing that changed and instead just use the lookup of that thing via the view

```

```

change-stream-namespaces = ["thingdb.state"] # change events happen on the underlying collections not views

[[mapping]]
namespace = "thingdb.thing" # map change events on the thing collection to the things index
index = "things"

[[mapping]]
namespace = "thingdb.thingview" # map direct reads of the thingview to the same things index
index = "things"

[[relate]]
namespace = "thingdb.thing"  # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "thingdb.thingview"
keep-src = false # ignore the original thing that changed and instead just use the lookup of that thing via the view

[[relate]]
namespace = "thingdb.states" # when a state changes trigger a thing change event since thing is associated to a state
with-namespace = "thingdb.thing"
src-field = "_id" # use the _id field of the state that changed to lookup associated things
match-field = "s" # only trigger change events for the things where thing.s (match-field) = state._id (src-field).
keep-src = false
```

the 2nd would be dedicated only to the potentially expensive 1 to many updates

**Comment by ail-13** [comment]
Thanks, I will try that. But it seems I had the same problem on another server. There is no [[[relate]]] in the settings, there is only one large collection of about 4 million documents. Approximately every 30 minutes ~5-10K documents are removed from the collection and new records are inserted. This works properly, but if I try to delete and insert more documents (e.g. > 20K) then the Monstache process stops working. It loads the CPU by almost 100% and does not synchronize anything. To make it work I have to restart Monstach.

The conf
change-stream-namespaces = ["db.Catalog"]
direct-read-namespaces = ["db.Catalog"]
[[mapping]]
namespace = "db.Catalog"
index = "db"

What can I try to do in this case?

**Comment by mapshen** [comment]
Could it be that you happen to require having a larger oplog size? 

https://docs.mongodb.com/manual/core/replica-set-oplog/#workloads-that-might-require-a-larger-oplog-size

**Comment by rwynn** [comment]
@mapshen brings up a good point about the oplog size.  

I have definitely replicated monstache getting stuck in previous releases, but I thought we were had solved that issue.  It seemed to be getting caused by a setting of "no timeout" on the mgo driver.  Once I realized that I made it impossible to set "no timeout" in monstache.  By the way, are you using the latest monstache version on these servers or maybe a previous one?

Anyway, I tried to replicate the behavior you describe by doing the following, but so far haven't witnessed the sync stop.

```
# Start monstache with
monstache -verbose -change-stream-namespace test.test
```

```
# Run a script to insert 10K records and then delete half of them every 60s for ~60 minutes
$ cat mongo.js 
var db = db.getSiblingDB('test'),
    test = db.test;
for (var j=0; j<60; ++j) {
        for (var i=0; i<10000; ++i) test.insert({i: i});
        test.remove({i: {$mod: [2, 0]}});
        sleep(60*1000);
}
$ mongo mongo.js
```

**Comment by rwynn** [comment]
@ail-13 I have noticed that deleting 60K records at a time does seem to lock up monstache when using the `change-stream-namespaces` option.  I noticed it didn't seem to happen when I used traditional oplog tailing (the default) instead of the new change streams API.  

Unless you need the pipeline stages to be available for change events, I would say that maybe you could try switching off change-stream-namespaces.

**Comment by ail-13** [comment]
Upgrading to the latest version did not resolve the issue. After 20-25 hours the sync stopped working again. Now Monstache loads CPU almost 100% and nothing changes in the Elasticsearch index.

**Comment by ail-13** [comment]
Maybe it will help somehow, every time before stopping Monstache the following entries appear in the MongoDB logs:
![image](https://user-images.githubusercontent.com/45662718/51588920-7bd73400-1ef6-11e9-86ed-38aa6ae94154.png)

**Comment by ail-13** [comment]
I think I found the problem. On both servers I have nodejs applications that works with MongoDB data. And restart this application stops Monstache.

**Comment by ail-13** [comment]
Is there any way to fix this?

**Comment by ail-13** [comment]
> I think I found the problem. On both servers I have nodejs applications that works with MongoDB data. And restart this application stops Monstache.

it was a coincidence, I specifically tried to restart nodejs application and the problem did not happen again

**Comment by rwynn** [comment]
I would move away from `change-stream-namespaces` for a bit if you use that.  I've noticed some issues around the feature that I will report to the mgo driver team.  Monstache uses an alternative method of tailing the oplog if change streams are not defined.

**Comment by ail-13** [comment]
On one of the servers I changed `change-stream-namespaces` to `namespace-regex` and it looks like my problem is solved. But on the second server I use change stream pipeline and I can't refuse it. Maybe there's some other way to watching changes on specific fields only without the use of `change-stream-namespaces`?

**Comment by rwynn** [comment]
Yes, I think the direct oplog tailing is pretty solid now.  For change streams I have an open PR (just created) with the mgo driver that I believe fixes the issues.

https://github.com/globalsign/mgo/pull/326

I'm hoping to guide that through the merge process at which point in time I would cut another release of monstache.

If you wanted to try this fix now you could do a quick build yourself assuming you have go 1.11 installed...

```
cd ~
git clone https://github.com/rwynn/monstache.git
git clone https://github.com/rwynn/mgo.git
cd ~/mgo
git checkout change-stream-rollup
cd ~/monstache
vi go.mod
```
Add the following line to the end of go.mod

```
replace github.com/globalsign/mgo => ~/mgo
```

That tells go to build with the change-stream-rollup branch of my fork instead of globalsign mgo.  Really handy feature of go modules.

Finally install monstache to $GOPATH/bin

```
cd ~/monstache
go install
```
Let me know how that goes.

**Comment by ail-13** [comment]
That didn't solve the problem((

**Comment by rwynn** [comment]
Just published v4.13.4.  If that doesn't fix the issue for you then I would probably need you to send me a failing test that I can run and recreate the issue.

**Comment by ail-13** [comment]
I tested with v3.13.3, now install v3.13.4 and try again. The problem does not appear immediately, so it will take some time, something around 10 - 20 hours. I'll write about the results. Thanks

**Comment by ail-13** [comment]
Upgrade to v3.20.4 solved the problem on one of the servers. On this server, I only use `change-stream-namespaces`, `direct-read-namespaces`, and `[[mapping]]` settings. On the second server, I additionally use `[[pipeline]]` (to watch changes on specific fields) and `[[relate]]`. And on this server I got another problem. When I insert many docs ( ~30k) into the collection it is properly synced. But such records are starting appear in the mongodb.log after Monstache completes the sync.
![image](https://user-images.githubusercontent.com/45662718/51991597-795b7800-24bc-11e9-8624-15ad3a494890.png)
And these records can appear endlessly. At the same time, there is a load on the CPU although no operations are performed on the server. I tried to wait more than an hour and it does not stop and the load is not reduced. To stop this I need to restart Monstache.
![image](https://user-images.githubusercontent.com/45662718/51992293-cd1a9100-24bd-11e9-820e-7147262a76dc.png)
If I use version v3.20.0 then this problem does not occur and after the sync there are no entries in the mongodb logs and the CPU load is reduced to 0.

**Comment by rwynn** [comment]
@ail-13 you can try the new release.  Hope that might improve the situation.

**Comment by ail-13** [comment]
But if I insert less docs (less than ~10k) then there is no cyclic recording in mongodb log. That is if I `insert`, `change`, `delete` a small number of documents then there are no cyclic requests to mongodb at all and the CPU load is about 0, but if I once inserted more than ~30k docs then there is a cyclic record in the mogodb log and the CPU load rises even if I do nothing. If I restart Monstache then the CPU load is reduced to 0 again and I can `insert`, `modify`, `delete` and everything work properly (there is no cyclic recording in mongodb log and the load is about 0), until I insert more than ~30k documents. This problem occurs in v3.20.4 and there is no this problem in v3.20.0. But in v3.20.0 the sync is stop working and I couldn't find what causes this problem. Now try the new release v3.21.0. I'll write you the result. Thanks

**Comment by ail-13** [comment]
I tried v3.21.0 and I think it just got worse((
No action is performed on the server, and the CPU load up to 50%
https://drive.google.com/file/d/1fxLNO8WCQN_rqLnDrCSf5oSU_8FmJjg2/view

**Comment by rwynn** [comment]
I'm not sure what the problem could be.  I am not able to replicate any problems in a simple test with the latest.

If I run monstache with 

```
monstache -change-stream-namespace test.test -verbose
```

Then run this file to add some load with `mongo mongo.js`:

```
var db = db.getSiblingDB('test'),
    test = db.test;
for (var j=0; j<60; ++j) {
        for (var i=0; i<40000; ++i) test.insert({i: i});
        test.remove({i: {$mod: [2, 0]}});
        sleep(9*1000);
}

```

Then monstache does sync all the inserts and deletes.  And the system looks like this:

![streaming](https://user-images.githubusercontent.com/260672/52056778-2b348c00-2531-11e9-9e6b-efa74134f6b9.png)

Then when I stop the script the system looks like this..

![idle](https://user-images.githubusercontent.com/260672/52056799-3687b780-2531-11e9-9186-d4f21c33f633.png)

**Comment by ail-13** [comment]
I found out what my problem is. I have two related collections: Document and Product. Document has many child Product.  I created view
db.createView("DocumentView", "Document", [
{ $lookup: {from: "Product", localField: "_id", foreignField: "documentId", as: "p"}},
{
$addFields: {
sum: {
$reduce: {
input: "$p",
initialValue: 0,
in: { $add : [ "$$value", "$$this.price" ] }
}
}
}
}
]

And I set up `[[relate]]` setting in the conf file
[[relate]]
namespace = "db.Document"
with-namespace = "db.DocumentView"
keep-src = false
[[relate]]
namespace = "db.Product"
with-namespace = "db.Document"
src-field = "documentId"
match-field = "_id"
keep-src = false

When I used v3.20.0 the "sum" field in the Document was not updated when I `insert` the Product docs(I wrote about it #157 ). And now with version v3.21.0 the "sum" field is updated, but after `insert` a large number of Product docs I get looping mongodb logs and increasing CPU idle load. I removed Product `[[relate]]` from Document settings and after `insert` ~30k docs in Product, the CPU load immediately dropped to 0. And now there is no cyclic record in mongodb logs. Thanks!

**Comment by rwynn** [comment]
@ail-13 thanks.  does that mean though that your Document `sum` field is now out of sync when you insert a new Product?  

I think what happens when you insert 30k products with the old config is that for each of those 30K a query happens for doc._id == product.documentId.  Then for each of those doc matches an additional query is performed on the view where doc._id == doc_view._id to get the aggregated result to index.  So in response to 30K inserts you have an avalanche of 60K queries to MongoDB.  

I'm not sure there is a good way to solve this in monstache without queuing these updates in some way so that they are spread out slowly over time or combined into less queries using an $in query.  But this may end up requiring more memory in the monstache process and there is no telling if you are going to insert another 60K Products, and then 60K products again and again.  

The other alternative has always been to drop the relate as you have and then do a periodic sync of the db.Document collection which would go through the view.  This would make your aggregated results less realtime but would definitely avoid these crazy number of queries.

**Comment by ail-13** [comment]
I dropped the `[[relate]]` for Document and I will watch changes of Product in my app. I think it is the best solution in this case. Thanks again for your advices!
