### ISSUE TITLE
Inserting array of documents

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#164]
I'm using a JS script to transform incoming Mongo documents. This script takes one mongo JSON and maps it to several objects stored in an array. How would I insert all the objects in this array separately?

**Comment by rwynn** [comment]
You cannot currently do that in Javascript in monstache.  You would need to implement a `Process` function in a golang plugin.  Inside `Process` you would use the bulk indexer to `Add` as many index requests as you need.

**Comment by IchorPop** [comment]
Thanks for the quick reply! Would you be able to give a small example of this? I'm somewhat new to golang and not sure how to structure a plugin like this even after looking at the documentation.

**Comment by rwynn** [comment]
@IchorPop something like this maps a single document in `test.test` in MongoDB to multiple docs indexed in Elasticsearch...

``` golang
import (
        "github.com/olivere/elastic"
        "github.com/rwynn/monstache/monstachemap"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
        output = &monstachemap.MapperPluginOutput{ Document: map[string]interface{}{} }
        // if event happened in test.test skip it otherwise proceed to index the event
        // test.test is handled in the Process function
        if input.Namespace == "test.test" {
                output.Skip = true
        } else {
                output.Passthrough = true

        }
        return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
        if input.Namespace != "test.test" {
                return
        }
        // example assumes every document in test.test like { children: [{name: "Joe"}, {name: "Mike"}] }
        // indexes each child separately in the test index
        bulk := input.ElasticBulkProcessor
        doc := input.Document
        children := doc["children"].([]interface{})
        for _, child := range children {
                req := elastic.NewBulkIndexRequest()
                req.Index("test")
                req.Type("child")
                req.Doc(child)
                if _, err = req.Source(); err == nil {
                        bulk.Add(req)
                } else {
                        return
                }
        }
        return
}

```

The instructions for building and running with this plugin are [here](https://rwynn.github.io/monstache-site/advanced/#golang).

This simple example doesn't take into account Elasticsearch _id.  So each time an event happens new documents would be indexed.  If you want to replace existing docs in Elasticsearch you would need to incorporate and set an ID on each req.  `req.Id(child.id)`.

**Comment by IchorPop** [comment]
Thank you for this, very helpful.

**Comment by kartikjain** [comment]
This really needs to go in documentation. Thanks for sharing
