### ISSUE TITLE
Order of JSON document with Golang plugins

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#165]
I'm writing a Golang plugin for transformation of Mongo documents and came across this roadblock: `Document` within `MapperPluginInput` is of the type `map[string]interface{}`, which loses the original ordering of the JSON document. Is there a way to retrieve the JSON string when writing a Go plugin for transformation or somehow get the 'correct' order?

**Comment by rwynn** [comment]
Unfortunately any ordering of the fields is lost when using the map[string]interface{}.  Is there any way you could work around that?  What are you trying to accomplish?

**Comment by IchorPop** [comment]
Thanks, yes there is a work around. I was hoping to translate an old transformation script that used ordering information about the JSON document.
