### ISSUE TITLE
how can i setup this with the mongodb cloud atlas

### ISSUE THREAD

**Issue by buildsnapwiz** [rwynn/monstache#166]
Getting this error while setting up this for the mongodb cloud atlas.

ERROR 2019/01/24 12:48:25 Unable to connect to MongoDB using URL REDACTED@cluster0-xxxxx.mongodb.net/db:27017: timed out after 15 seconds

**Comment by rwynn** [comment]
Duplicate of #158

**Comment by rwynn** [comment]
Have you followed the [instructions of Atlas](https://rwynn.github.io/monstache-site/advanced/#mongodb-atlas)?
