### ISSUE TITLE
monstache plugin

### ISSUE THREAD

**Issue by botgitfool** [rwynn/monstache#167]
Hi

I am using docker to run elastic, mongo and monstache. Plugin.so is build using golang:1.8-wheezy. When I passed plugin into monstache container, I am getting this error

Attaching to monstache
monstache          | fatal error: runtime: no plugin module data
monstache          | 
monstache          | goroutine 1 [running]:
monstache          | runtime.throw(0xf02b9f, 0x1e)
monstache          | 	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00013abc8 sp=0xc00013ab98 pc=0x6d9122
monstache          | plugin.lastmoduleinit(0xc00020a000, 0xc00000e630, 0x7f400fbf8180, 0x8, 0x17c3ac0)
monstache          | 	/usr/local/go/src/runtime/plugin.go:20 +0xb4f fp=0xc00013ace8 sp=0xc00013abc8 pc=0x6da50f
monstache          | plugin.open(0x7ffdc1160f7e, 0x4, 0x0, 0x0, 0x0)
monstache          | 	/usr/local/go/src/plugin/plugin_dlopen.go:87 +0x3bc fp=0xc00013afa0 sp=0xc00013ace8 pc=0xd1a49c
monstache          | plugin.Open(0x7ffdc1160f7e, 0x7, 0x0, 0x0, 0x0)
monstache          | 	/usr/local/go/src/plugin/plugin.go:32 +0x35 fp=0xc00013afd8 sp=0xc00013afa0 pc=0xd19ca5
monstache          | main.(*configOptions).loadPlugins(0xc0001ec000, 0xc0001ec000)
monstache          | 	/app/monstache.go:1489 +0x73 fp=0xc00013b160 sp=0xc00013afd8 pc=0xd282e3
monstache          | main.main()
monstache          | 	/app/monstache.go:3598 +0x1bd fp=0xc00013bf98 sp=0xc00013b160 pc=0xd3a5bd
monstache          | runtime.main()
monstache          | 	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc00013bfe0 sp=0xc00013bf98 pc=0x6db817
monstache          | runtime.goexit()
monstache          | 	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00013bfe8 sp=0xc00013bfe0 pc=0x709a31
monstache          | 
monstache          | goroutine 5 [select]:
monstache          | github.com/globalsign/mgo.newcoarseTimeProvider.func1(0x17d7840, 0xc000020ae0)
monstache          | 	/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20181015135952-eeefdecb41b8/coarse_time.go:51 +0x129
monstache          | created by github.com/globalsign/mgo.newcoarseTimeProvider
monstache          | 	/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20181015135952-eeefdecb41b8/coarse_time.go:48 +0x102
monstache          | 
monstache          | goroutine 7 [syscall]:
monstache          | os/signal.signal_recv(0x0)
monstache          | 	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
monstache          | os/signal.loop()
monstache          | 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
monstache          | created by os/signal.init.0
monstache          | 	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
monstache exited with code 2

step:
1 go get github.com/rwynn/monstache/monstachemap
2  go build -buildmode=plugin -o test.so test.go
3 docker-compose up -d

Content of test.go is 

package main
import (
    //"github.com/rwynn/monstache/monstachemap" // or gopkg.in/rwynn/monstache.v3/monstachemap for Elasticsearch 2 or 5
    "github.com/rwynn/monstache/monstachemap"
    "strings"
)
// a plugin to convert document values to uppercase
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
    doc := input.Document
    for k, v := range doc {
        switch v.(type) {
        case string:
            doc[k] = strings.ToUpper(v.(string))
        }
    }
    output = &monstachemap.MapperPluginOutput{Document: doc}
    return
}

docker yml is
  monstache:
        image: rwynn/monstache:4.13.2
        container_name: monstache
        command: -f ./monstache.test.config.toml -mapper-plugin-path test.so
        volumes:
          - ./monstache.test.config.toml:/monstache.test.config.toml 
          - ./test.so:/test.so

Thank you

**Comment by rwynn** [comment]
I think you will need go version 1.11 to do the build since that is what the monstache images are built with.  You can read the instructions [here](https://rwynn.github.io/monstache-site/advanced/#golang).  

You can also build it with docker by following along [here](https://github.com/rwynn/monstache/tree/master/docker/plugin)

**Comment by botgitfool** [comment]
working now, thank you
