### ISSUE TITLE
why not sync attachment file to main document together to elasticsearch?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#169]
hi Ryan,

    i think you can add the sync attachment file to main document together using pipeline, what do you think？ any disadvantage if actually do it like what i say, thanks

**Comment by rwynn** [comment]
@sunweiconfidence I'm not I understand your request.  Is this about syncing gridfs file?  Is that what you mean by sync attachment file?

**Comment by sunweiconfidence** [comment]
yes. gridfs file i want To ask ，thanks

**Comment by rwynn** [comment]
@sunweiconfidence monstache only sends 1 document to Elasticsearch per gridfs file.  For each file in the `fs.files` collection (the metadata) it downloads the file content from the `fs.chunks` collection (via the driver API) to assemble the file and then finally **in one document** sends both the metadata and the contents.  Are you saying there is a way to do this more efficiently?

**Comment by sunweiconfidence** [comment]
hi Ryan,

yes, maybe you can try to send 1 main document to elasticsearch then use pipeline to add the attachments field to this document like below example in elasticsearch:
{
    "_source": {
        "Title": "test1",
        "City": "beijing",
        "attachments": [
            {
                "attachment": {
                    "author": "tester",
                    "content": "Buga\nbex\ntax\nssy\ndro",
                    "content_length": 34,
                    "content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "date": "2019-01-30T03:23:00Z",
                    "language": "lt"
                },
                "filename": "test in attachment.docx"
            }
        ],
        "modifyTimeStamp": "1544756739831",
        "newTimeStamp": ""
    }
}

pipeline, you can run below clause with a pipeline name before you insert doc to elasticsearch:
{
  "description" : "Implementation pipeline",
  "processors": [
          {
            "foreach": {
               "field": "attachments",
               "processor": {
                  "attachment": {
                     "target_field": "_ingest._value.attachment",
                     "field": "_ingest._value.data",                   
                     "ignore_missing":true
                  }
               }
            }
         },
         {
            "foreach": {
               "field": "attachments",
               "processor": {
                  "remove": {
                     "field": "_ingest._value.data"
                  }
               }
            }
         }
      ]
}

**Comment by rwynn** [comment]
@sunweiconfidence 

monstache allows you to use your own custom `pipeline` via a script or Golang plugin.  The instructions for this are in [Middleware](https://rwynn.github.io/monstache-site/advanced/#middleware).  For scripts you need to add a `_meta_monstache` object to the doc returned with a `pipeline` attribute set on it.   I think you could use this feature to send documents to the pipeline you describe above.  You would need to create this pipeline yourself in Elasticsearch before running monstache.  In both scripts and golang plugins you are able to query MongoDB for additional data (the scripts are a bit more limited in this regard, but the golang plugins have full access to the mgo client).   The golang plugins could download GridFS files and put there content into an `attachments` array.  

the `file-namespaces` feature of monstache specifically implements the technique described [here](https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment-extracted-chars.html) and is designed to work with binary files (hence the base64 encoding that monstache does on the content) as shown in the example.  Also, the `file-namespaces` feature is designed to map 1 gridfs file to 1 document in Elasticsearch.  If each gridfs file is part of a collection associated with some other entity then it is assumed that one would save the gridfs file with metadata indicating it's parent document.  This metadata would get indexed in Elasticsearch and allow one to later re-associated the binary file to it's parent.

**Comment by sunweiconfidence** [comment]
@rwynn 
i will try pipeline using script or golang plugin, thanks

**Comment by sunweiconfidence** [comment]
@rwynn 
whether golang plugin support build in windows 10?

**Comment by rwynn** [comment]
I believe that currently golang plugins [work only with linux and macOS](https://golang.org/pkg/plugin/).  On windows you could try using Windows Subsystem for Linux.

**Comment by sunweiconfidence** [comment]
hi Ryan,

When do you plan to add the script for full access to mgo client to download GridFS files and put there content into an attachments array? currently i use windows server, whether you can give me an advice that i can implement it by myself? thanks

**Comment by rwynn** [comment]
@sunweiconfidence until golang supports plugins on windows what you can do is fork monstache and implement a `Process` function yourself inside the `monstache.go` file.  Then re-implement the `loadPlugins` function to set the variable to point to your function.

```golang

func MyProcess(input*monstachemap.ProcessPluginInput) error {
    // your impl
}

func (config *configOptions) loadPlugins() *configOptions {
    processPlugin = MyProcess
}

```

**Comment by sunweiconfidence** [comment]
@rwynn  you mean i can overwrite the below loadPlugins method in rel3 branch after i fork to local, am i right? in MyProcess method, i need to implement using mgo client to read fs.files and fs.chunks and assemble it into a new base64 string, then send it to elasticsearch through pipeline create above, and loadPlugins only keep one line you write,  not need your previous code, what i understand is right? thanks

**Comment by rwynn** [comment]
Yes that is correct. The input parameter should give you access to all you need including document inserted/updated/deleted and also references to mgo client and elasticsearch bulk indexer.

**Comment by sunweiconfidence** [comment]
@rwynn 
one question is that whether have existing golang code can directly assemble it from fs.files and fs.chunks according to your  knowledge, 
another question is that below code, i think should delete if condition clause 
func mapData(session *mgo.Session, config *configOptions, op *gtm.Op) error {
	if config.MapperPluginPath != "" {
		return mapDataGolang(session, op)
	}
	return mapDataJavascript(op)
}

in addition to this, is it necessary to keep all MapperPluginPath related code? thanks

**Comment by rwynn** [comment]
see this code for how to download a gridfs file into a base64...

https://github.com/rwynn/monstache/blob/v4.15.1/monstache.go#L1009

You can adjust the MapperPluginPath code as necessary.  You can remove it or change.

**Comment by sunweiconfidence** [comment]
@rwynn  ok, thanks for your timely reply.
