### ISSUE TITLE
Using Completion Suggester in ElasticSearch

### ISSUE THREAD

**Issue by carlo4002** [rwynn/monstache#170]
There is a way to map an specific field in MondoDB to completion suggester in order to make queries in ES that respond to search-as-you-type Functionality ?

**Comment by rwynn** [comment]
After the mapping of data is as you want it, the next step would be to adjust your queries to Elasticsearch to provide search as you type: https://www.elastic.co/guide/en/elasticsearch/guide/current/_query_time_search_as_you_type.html.

**Comment by rwynn** [comment]
As far as the mapping is concerned I think you would want to map the field you would like to search as you type on as a `text` field as opposed to a `keyword` field.

**Comment by rwynn** [comment]
There is also the option of index time search as you type if you prefer that over query time.  But there is nothing special that monstache needs to do to provide this.  It just sends data.  To do index time search as you type put this configuration in an index template for the index that monstache targets.

https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html

**Comment by rwynn** [comment]
If what you are looking for is something like this: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-suggesters-completion.html 
then use [middleware](https://rwynn.github.io/monstache-site/advanced/#middleware) in monstache to add your suggestions to the document before indexing.

**Comment by carlo4002** [comment]
Okay thank you I will take a look. Just one question more, I am trying index only 1 field of my documents (field name is name) . My config looks like that:

```config
mongo-url = "mongodb://user:pass@localhost:27017/db"
elasticsearch-urls = ["http://198.214.20.1:9200"]


direct-read-namespaces = ["db.bus"]
change-stream-namespaces = ["db.bus"]


gzip = true
stats = true
index-stats = true
mongo-validate-pem-file = false
elasticsearch-max-conns = 4 
dropped-collections = true
dropped-databases = true
replay = false
resume = false
resume-write-unsafe = false
resume-name = "default"
index-files = false
file-highlighting = true
verbose = true
exit-after-direct-reads = false

[[pipeline]]
namespace = "db.bus"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $match: {
          $or: [
		{ "updateDescription": {$exists: false} },
            { "updateDescription.updatedFields.name": {$exists: true}}
          ]
        }
      }
    ];
  } else {
    return [];
  }
}
"""

```

And I get this error
 
```bash
root@mongodb2:~/build/linux-amd64# ./monstache -f config.conf  >  monstache.log
panic: Pipeline function must return an array of objects

goroutine 82 [running]:
main.buildPipe.func1(0xc0001ee140, 0x10, 0xc000312000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/release/monstache/monstache.go:3517 +0x7e7
github.com/rwynn/gtm.DirectReadSegment(0xc000068b40, 0xc0000208c0, 0xc0001ee140, 0x10, 0xc0001d0680, 0xc0003cf800, 0xc000024c50, 0x0, 0x0)
	/home/vagrant/go/pkg/mod/github.com/rwynn/gtm@v0.0.0-20190124025931-7f79e86e8369/gtm.go:1112 +0xb48
created by github.com/rwynn/gtm.DirectReadPaged
	/home/vagrant/go/pkg/mod/github.com/rwynn/gtm@v0.0.0-20190124025931-7f79e86e8369/gtm.go:1406 +0x5ea

```

Since this is a copy paste from the documentation, I do not understand what I am missing. Can you clarify me that ?

Version monstache 4.13.4
Version Mongo 3.6.9
Version Elasticsearch 6.2.3

**Comment by rwynn** [comment]
Thanks for the error report.  I believe it should be fixed in latest version.

**Comment by marcellalves** [comment]
@rwynn 

> If what you are looking for is something like this: [elastic.co/guide/en/elasticsearch/reference/2.4/search-suggesters-completion.html](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-suggesters-completion.html)
> then use [middleware](https://rwynn.github.io/monstache-site/advanced/#middleware) in monstache to add your suggestions to the document before indexing.

I'm going to need to add suggestions to a document, but I'm not a GO developer. Would you provide an example of chanching a mapping to a property to set type completion?

Example: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-suggesters-completion.html

Thanks in advance.
