### ISSUE TITLE
Using build.sh to build plugin from multiple .go files

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#172]
I'm using the `sh build.sh` command to build a middleware plugin file. It seems that currently the `build.sh` file only accepts one .go file. Is there a way to build the plugin file from multiple go files in the directory instead?

**Comment by rwynn** [comment]
Probably many ways.  Simple one is I think you can edit the Dockerfile and change the last line to...

```
RUN go build -buildmode=plugin -o $PLUGIN.so
```

It should then build any files in the plugin directory with package `main`.  For more info see `go help build`.

**Comment by IchorPop** [comment]
Does this line `docker run --rm -d monstache-plugin tail -f /app/docker/plugin/$plugin.go` in build.sh need to be modified as well to accept multiple files?
