### ISSUE TITLE
How to force indexing on start?

### ISSUE THREAD

**Issue by jahirfiquitiva** [rwynn/monstache#173]
Hello

I would like to know if there's a way to force `monstache` to re-index a collection or set of collections on start. So it can update `elasticsearch` index, in case some changes were done before `monstache` was running.

Thanks in advance

**Comment by rwynn** [comment]
https://rwynn.github.io/monstache-site/config/#direct-read-namespaces

**Comment by jahirfiquitiva** [comment]
Thank you so much!
