### ISSUE TITLE
Monstache exits after doing a copy when running in the background

### ISSUE THREAD

**Issue by asanepal** [rwynn/monstache#175]
Hello,
I set up monstache to run in the background using system configs as described on the Monstache tutorial. However, after doing a full copy it doesn't act on the new insertions in Mongo. I strictly followed the instructions mentioned in the Monstache tutorial. I request you to share your thoughts on this. Thank you for the wonderful plugin.

**Comment by rwynn** [comment]
Hi, can you share any configurations applied to monstache, the MongoDB and Elasticsearch version?  
Some things to look out for.  Make sure you don't have monstache configured to exit after direct reads (this defaults to false).

```toml
# the default setting
exit-after-direct-reads=false
```
Make sure you don't have any filters or regexes applied that would prevent the document from being indexed.

Make sure that MongoDB is setup as a replica set and not a standalone.  If you have configured MongoDB as a replica set then you should see something like when you connect to it via `mongo`.

```
rs1:PRIMARY> db.getSiblingDB('local').oplog.rs.count()
11475998
```
Notice the replica set name in the prompt and the existence of documents in the `local.oplog.rs` collection.  This collection is referred to as the oplog.  If you don't have this then you would need to follow the instructions [here](https://rwynn.github.io/monstache-site/start/#usage). 

If you have an old version of MongoDB that pre-dates replica sets, then you would have only master/slave replication.  If that is the case then you can still use Monstache but you would need to tell it to use a different collection for the oplog.  

```toml
mongo-oplog-collection-name = "oplog.$main"
```

You would also need to ensure that the  `--master` flag is passed to mongod.

Finally, you might turn on `verbose` to see if monstache is sending a request when a document changes.  It might be that the request is failing for some reason in Elasticsearch.

```toml
verbose=true
```

**Comment by asanepal** [comment]
Hi,
Thank you for the quick response. I used basic configs. Here is my config file. The same config is working fine when run in the foreground. It is able to do a copy and then do tailing for oplogs. But when I run monstache as a service in the background using systemd, it does a copy and exits as described in the above problem description. 
However, I am yet to check on all your thoughts shared above. Meanwhile I will try out what you suggested and get back by early next week. Thank you much.


mongo-url = "XXXXXXX"
elasticsearch-urls = ["XXXXXXXXXXXXXXXXXX"]
gzip = true
direct-read-namespaces = ["Test.rs_copy"]
elasticsearch-max-conns = 4
elasticsearch-max-bytes=52428800
elasticsearch-retry=true
verbose = true
exit-after-direct-reads = false
[logs]
info = "monstache/info.log"
warn = "monstache/warn.log"
error = "monstache/error.log"
trace = "monstache/trace.log"
stats = "monstache/stats.log"

**Comment by rwynn** [comment]
Hi, not sure then what it could be.  I tried to replicate the issue yesterday but was not able to.  When I setup a service as documented [here](https://rwynn.github.io/monstache-site/advanced/#systemd) for Ubuntu 16.04 then monstache continued to run after direct-reads were completed.

You might check the max bytes settings since as it is will fill up a buffer of size 52 MB before flushing.  And there will be 4x52MB since you have 4 connections.  That may be a little high since it is almost 7 times the default.

**Comment by rwynn** [comment]
You might take a look at [this](https://unix.stackexchange.com/questions/339638/difference-between-systemd-and-terminal-starting-program/339645#339645) for some clues.  

The only other thing I can think of would be if you have security enabled on MongoDB but the user you're connecting with cannot access the oplog.  See [these instructions](https://rwynn.github.io/monstache-site/advanced/#mongodb-authentication) if you have security enabled.

**Comment by asanepal** [comment]
Hello, Thanks for your thoughts. Looks like Monstache is not authorized to read oplog on my machine. I am closing the issue for now. Thank you again.
