### ISSUE TITLE
Error null_pointer_exception in sync process

### ISSUE THREAD

**Issue by carlo4002** [rwynn/monstache#178]
Hello, Once I sync with prod data, I got this error for my collections

`ERROR 2019/02/21 15:24:44 Bulk response item: {"_index":"geostore.school","_type":"_doc","_id":"5ae0ece56155816cacfd999a","status":500,"error":{"type":"null_pointer_exception","reason":""}}`

There are some _ids that get repeated. As you can see the reason is unknown.

Version of ElasticSeach 6.2.3.2
Monstache v4.15

**Comment by rwynn** [comment]
I’ve not seen that before. Since this is coming back in the response do you have a stack trace in the Elasticsearch logs?

**Comment by carlo4002** [comment]
No, In Elasticsearch part, I do not have any trace for this error.

**Comment by rwynn** [comment]
I don’t think this issue is caused by monstache. Please reopen if you get more information about the root cause.

**Comment by carlo4002** [comment]
Hello, Now that I can come back to this issue, actually I found something weird in the logs of monstache 
`ERROR 2019/03/04 16:24:47 Bulk response item: {"_index":"geostore_poi.school","_type":"_doc","_id":"5ae0ecde6155816cacfd491c","status":404,"error":{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"geostore_poi.school","index":"geostore_poi.school"}}
`
It happens for some documents, not for all. I create the index using a template

**Comment by carlo4002** [comment]
Well after playing a little bit more, It seems that this is a problem related to elasticsearch. I was testing with Elassandra that use Elasticsearch version 6.2.3 and I was getting this error. I checked with elasticsearch version 6.6.1 and I do not have this problem. So that is why I think it is not monstache but elasticsearch
