### ISSUE TITLE
realtime sync between mongodb and ES not working

### ISSUE THREAD

**Issue by chakrapani123** [rwynn/monstache#179]
Hello,

I am trying to set-up this synch and wondering if this error message and sync failure are inter-related as realtime sync tails oplogs events or if i a missing any additional flags .

**error message:**

`ERROR 2019/02/21 15:04:01 Error tailing oplog entries: not authorized for query on local.oplog.rs`

**connection settings**
```
# connection settings

# connect to MongoDB using the following URL
mongo-url = "xx"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["xx"]

# frequently required settings

# if you don't want to listen for changes to all collections in MongoDB but only a few
# e.g. only listen for inserts, updates, deletes, and drops from mydb.mycollection
# this setting does not initiate a copy, it is a filter on the oplog change listener only
namespace-regex = '^patcherdev\.oemjobs$'

# additionally, if you need to seed an index from a collection and not just listen for changes from the oplog
# you can copy entire collections or views from MongoDB to Elasticsearch
direct-read-namespaces = ["patcherdev.oemjobs"]

#disable-change-events = false

# if you want to use MongoDB change streams instead of legacy oplog tailing add the following
# in this case you don't need regexes to filter collections.
# change streams require MongoDB version 3.6+
# change streams can only be combined with resume, replay, or cluster-name options on MongoDB 4+
# if you have MongoDB 4+ you can listen for changes to an entire database or entire deployment
# to listen to an entire db use only the database name.  For a deployment use an empty string.
 # change-stream-namespaces = ["mydb.mycollection", "db.collection", "test.test"]

# additional settings

# compress requests to Elasticsearch
#gzip = true
# generate indexing statistics
#stats = true
# index statistics into Elasticsearch
#index-stats = true
# use the following PEM file for connections to MongoDB
#mongo-pem-file = ""
# disable PEM validation
#mongo-validate-pem-file = false
# use the following user name for Elasticsearch basic auth
#elasticsearch-user = ""
# use the following password for Elasticsearch basic auth
#elasticsearch-password = ""
# use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 4
# use the following PEM file to connections to Elasticsearch
#elasticsearch-pem-file = ""
# validate connections to Elasticsearch
#elastic-validate-pem-file = false
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
#dropped-collections = true
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
#dropped-databases = true
# do not start processing at the beginning of the MongoDB oplog
# if you set the replay to true you may see version conflict messages
# in the log if you had synced previously. This just means that you are replaying old docs which are already
# in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
#replay = true
# resume processing from a timestamp saved in a previous run
#resume = true
# do not validate that progress timestamps have been saved
#resume-write-unsafe = false
# override the name under which resume state is saved
#resume-name = "default"
# exclude documents whose namespace matches the following pattern
#namespace-exclude-regex = '^patcherdev\.jobs$'
# turn on indexing of GridFS file content
#index-files = false
# turn on search result highlighting of GridFS content
#file-highlighting = false
# index GridFS files inserted into the following collections
#file-namespaces = ["users.fs.files"]
# print detailed information including request traces
#verbose = true
# enable clustering mode
#cluster-name = ''
# do not exit after full-sync, rather continue tailing the oplog
#exit-after-direct-reads = false
```

### ES : 6.4

thanks
chakri

**Comment by rwynn** [comment]
Have you already followed the instructions here? https://rwynn.github.io/monstache-site/advanced/#mongodb-authentication

**Comment by chakrapani123** [comment]
its a security risk to provide admin access in production environment ..is there any specific role for oplog that i can leverage instead?

thanks
Chakri

**Comment by rwynn** [comment]
You actually don't need admin access.  You just need the part where it adds the ability to `read` the database named `local`. 

For example, the instructions in the Altas documentation: https://docs.atlas.mongodb.com/faq/#does-service-fullname-expose-the-oplog

**Comment by rwynn** [comment]
Monstache also supports but does not default to use change streams as a way to listen for changes.  

If you switch to use change streams then your user would need different privileges to read those change streams.

https://docs.mongodb.com/manual/changeStreams/#access-control

Note: Change streams only work on collections in MongoDB 3.6+ and on deployments and databases in MongoDB 4.0+.

**Comment by chakrapani123** [comment]
streams approach may not work for me as my db version is 3.4

**Comment by chakrapani123** [comment]
i use community edition build for my db and atlas i believe might be enterprise..but i get the idea that user that you leverage should have readaccess to local db..which i configured for my user and still i run into access issues for oplog

here is a snippet of my user roles in admin db:
`	{
		"_id" : "admin.svcmarvin",
		"user" : "svcmarvin",
		"db" : "admin",
		"roles" : [
			{
				"role" : "readAnyDatabase",
				"db" : "admin"
			},
			{
				"role" : "read",
				"db" : "local"
			},
			{
				"role" : "oplogger",
				"db" : "admin"
			},
			{
				"role" : "readWrite",
				"db" : "local"
			},
			{
				"role" : "clusterAdmin",
				"db" : "admin"
			}
		]
	}`

**Comment by rwynn** [comment]
What auth mechanisms are supported for your user?

```
rs1:PRIMARY> db.getUser('monstache');
{
        "_id" : "admin.monstache",
        "user" : "monstache",
        "db" : "admin",
        "roles" : [
                {
                        "role" : "userAdminAnyDatabase",
                        "db" : "admin"
                },
                {
                        "role" : "read",
                        "db" : "local"
                },
                {
                        "role" : "readWriteAnyDatabase",
                        "db" : "admin"
                }
        ],
        "mechanisms" : [
                "SCRAM-SHA-1",
                "SCRAM-SHA-256"
        ]
}
```
If you have `SCRAM-SHA-1` available are you adding it to the connection string?

```
monstache -mongo-url mongodb://monstache:monstache@localhost?authMechanism=SCRAM-SHA-1
```

**Comment by chakrapani123** [comment]
unfortunately, i dont have SCRAM-SHA-1 enabled on my cluster

**Comment by chakrapani123** [comment]
here is my connect string 

mongodb://user:password@host1:port1,host2:port2/dbname?replicaset=rset

**Comment by rwynn** [comment]
Check the setup in the test folder

https://github.com/rwynn/monstache/tree/master/docker/test

That is able to tail the oplog and is mongodb 3.4.

**Comment by rwynn** [comment]
I think it assigns a built in role named “backup”?

**Comment by rwynn** [comment]
Or maybe it ended up using a root user. Anyway someone with more knowledge about Mongodb auth should be able to help you not use an admin account.

**Comment by rwynn** [comment]
mongodb://<dbuser>:<dbpassword>@ds012345-a0.mlab.com:56789,ds012345-a1.mlab.com:56790/local?replicaSet=rs-ds012345&authSource=admin

**Comment by chakrapani123** [comment]
ok..here is what i found..apparently if ur user is created in say testdb instead of admin db then even if u provide read access to local in admin db it still throws access errors on oplog...however if you add read access to user in ur testdb and then add read access to local db in that db then it works..

here is my snippet now:

```	{
		"_id" : "testdev.svcmarvin",
		"user" : "svcmarvin",
		"db" : "testdev",
		"roles" : [
			{
				"role" : "dbAdmin",
				"db" : "testdev"
			},
			{
				"role" : "read",
				"db" : "local"
			},
			{
				"role" : "readWrite",
				"db" : "testdev"
			}
		]
	}```

instead of 

```
{ "_id" : "admin.svcmarvin", "user" : "svcmarvin", "db" : "admin", "roles" : [ { "role" : "readAnyDatabase", "db" : "admin" }, { "role" : "read", "db" : "local" }, { "role" : "oplogger", "db" : "admin" }, { "role" : "readWrite", "db" : "local" }, { "role" : "clusterAdmin", "db" : "admin" } ] }
```

it works now..

**Comment by rwynn** [comment]
Glad to hear you got it working!  I was just about to post that I modified the test folder as follows:

```
diff --git a/docker/test/docker-compose.test.yml b/docker/test/docker-compose.test.yml
index 24de29d..822d9ab 100644
--- a/docker/test/docker-compose.test.yml
diff --git a/docker/test/docker-compose.test.yml b/docker/test/docker-compose.test.yml
diff --git a/docker/test/docker-compose.test.yml b/docker/test/docker-compose.test.yml
index 24de29d..822d9ab 100644
--- a/docker/test/docker-compose.test.yml
+++ b/docker/test/docker-compose.test.yml
@@ -75,8 +75,8 @@ services:
       # MONGO_USER_ADMIN_PASSWORD: password
       # MONGO_USER_APP_NAME: app-user
       # MONGO_USER_APP_PASSWORD: password
-      # MONGO_USER_OPLOGGER_NAME: oplogger-user
-      # MONGO_USER_OPLOGGER_PASSWORD: password
+      MONGO_USER_OPLOGGER_NAME: oplogger-user
+      MONGO_USER_OPLOGGER_PASSWORD: password
       # MONGO_USER_BACKUP_NAME: backup-user
       # MONGO_USER_BACKUP_PASSWORD: password
     ports:
diff --git a/docker/test/mongodb/scripts/mongo-users-setup.sh b/docker/test/mongodb/scripts/mongo-users-setup.sh
index 1f031bc..d6f7579 100755
--- a/docker/test/mongodb/scripts/mongo-users-setup.sh
+++ b/docker/test/mongodb/scripts/mongo-users-setup.sh
@@ -52,7 +52,7 @@ fi
 # create oplogger user
 if [ ! -z "${MONGO_USER_OPLOGGER_NAME+x}" ] && [ ! -z "${MONGO_USER_OPLOGGER_PASSWORD+x}" ] ; then
   # mongo admin --eval "db.createUser({ user: '$MONGO_USER_APP_NAME', pwd: '$MONGO_USER_APP_PASSWORD', roles: [{ role: 'readWrite', db: '$MONGO_DB_NAME' }, { role: 'read', db: 'local' }]});"
-  mongo admin --eval "db.createUser({ user: '$MONGO_USER_OPLOGGER_NAME', pwd: '$MONGO_USER_OPLOGGER_PASSWORD', roles: [{ role: 'read', db: 'local' }]});"
+  mongo admin --eval "db.createUser({ user: '$MONGO_USER_OPLOGGER_NAME', pwd: '$MONGO_USER_OPLOGGER_PASSWORD', roles: [ { role: 'readWriteAnyDatabase', db: 'admin'}, { role: 'read', db: 'local' }]});"
   # mongo "local" -u "$MONGO_USER_ROOT_NAME" -p "$MONGO_USER_ROOT_PASSWORD" --eval "db.createUser({ user: '$MONGO_USER_OPLOGGER_NAME', pwd: '$MONGO_USER_OPLOGGER_PASSWORD', roles: [{ role: 'read', db: 'local' }]});"
 
   # mongo "admin" -u "$MONGO_USER_ROOT_NAME" -p "$MONGO_USER_ROOT_PASSWORD" --eval "db.createUser({ user: '$MONGO_USER_OPLOGGER_NAME', pwd: '$MONGO_USER_OPLOGGER_PASSWORD', roles: [{ role: 'read', db: 'local' }]});"
diff --git a/docker/test/monstache.test.config.toml b/docker/test/monstache.test.config.toml
index 9fabeb9..f019d2d 100644
--- a/docker/test/monstache.test.config.toml
+++ b/docker/test/monstache.test.config.toml
@@ -1,6 +1,6 @@
 gzip = true
 
-mongo-url = "mongodb://root-user:password@mongo-0:27017"
+mongo-url = "mongodb://oplogger-user:password@mongo-0:27017"

```

And the tests still passed.  So it looks like a user with `{ role: 'readWriteAnyDatabase', db: 'admin'}, { role: 'read', db: 'local' }` is a good setting.  I think `readWriteAnyDatabase` sounds too open but actually doesn't give access to the system collections or auth.  This could be useful if you don't know exactly which databases you want to sync.

**Comment by chakrapani123** [comment]
thanks for taking time to resolve my issue. totally agree..although, readwriteanydatabase might be to open and just read  might be helpful not to raise any security flags..but again..like u said..it might still have limited access...thanks for clarifying that

thanks once again

**Comment by rwynn** [comment]
No problem. For future if you do decide to use the resume or cluster-name options of monstache that is the only time Monstache will attempt to write anything. It saves a small amount of state in a configurable db that defaults to the name “monstache”
