### ISSUE TITLE
data transformation guidelines 

### ISSUE THREAD

**Issue by chakrapani123** [rwynn/monstache#181]
hello again,

i have a unique situation with my transformation where in each single document has an array list and since i am interested in visualisations across each object in array i would have to split array into n objects

for example using javascript notation

module.exports = function(doc){
doc.foo.forEach(s){
return s.info;
}
}

so i have say 1 document with 10 objects in array for foo so i need to split single document into 10 documents . i know you can leverage logstash filters do that but wondering if there is a way to do transformation from 1 to many documents instead of 1-1 transformations?

thanks
chakri

**Comment by rwynn** [comment]
There is a way to do it in monstache, but you need to write a golang plugin and implement a `Process` function in the plugin.  Inside this function you need to split the document and index it's parts using the bulk processor that is passed into the function.  

https://rwynn.github.io/monstache-site/advanced/#middleware

If you go this route look at the monstache code (a single file) which should give you an idea of how to user the bulk indexer.  It's pretty simple, there is an `Add` method you need to call.

**Comment by chakrapani123** [comment]
hello,

thanks for sharing these details..are there any specific pre-reqs for tests i tried with basic single file and inserts & updates & deletes are failing..wondering if there is any specific ES requirement for testing it out?

thanks
Chakri

**Comment by rwynn** [comment]
Can you share the plugin? What is the error message?

**Comment by chakrapani123** [comment]
hello,

i just followed instructions on advanced page to have baseline set-up and here is my plugin 

```
package main

import (
	"strings"

	"github.com/rwynn/monstache/monstachemap" // or gopkg.in/rwynn/monstache.v3/monstachemap for Elasticsearch 2 or 5
)

// a plugin to convert document values to uppercase
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	doc := input.Document
	for k, v := range doc {
		switch v.(type) {
		case string:
			doc[k] = strings.ToUpper(v.(string))
		}
	}
	output = &monstachemap.MapperPluginOutput{Document: doc}
	return
}
```

here is what i did to test it 

- installed mongo 3.6.10
- installed es 6.2.4
- compiled and started monstache

go build -buildmode=plugin -o myplugin.so myplugin.go
monstache -mapper-plugin-path myplugin.so

and ran  the following:

go test -v -delay 10

here are my error messages:

```
MongoDB Url: 127.0.0.1:27017
Elasticsearch Url: http://96.116.62.172:9200
=== RUN   TestParseElasticsearchVersion
--- PASS: TestParseElasticsearchVersion (0.00s)
=== RUN   TestOpIdToString
--- PASS: TestOpIdToString (0.00s)
=== RUN   TestPruneInvalidJSON
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: +Inf for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: -Inf for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: NaN for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid time.Time value: -0001-11-10 23:00:00 +0000 UTC for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: +Inf for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: -Inf for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid float64 value: NaN for document _id: docId-1
WARN 2019/02/25 18:07:36 Dropping invalid time.Time value: -0001-11-10 23:00:00 +0000 UTC for document _id: docId-1
--- PASS: TestPruneInvalidJSON (0.00s)
=== RUN   TestSetElasticClientScheme
--- PASS: TestSetElasticClientScheme (0.00s)
=== RUN   TestParseSecureMongoUrl
--- PASS: TestParseSecureMongoUrl (0.00s)
=== RUN   TestInsert
--- FAIL: TestInsert (10.24s)
    monstache_test.go:225: elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
=== RUN   TestUpdate
--- FAIL: TestUpdate (10.20s)
    monstache_test.go:252: elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
=== RUN   TestDelete
--- FAIL: TestDelete (10.20s)
    monstache_test.go:289: elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
=== RUN   TestDropDatabase
--- FAIL: TestDropDatabase (10.19s)
    monstache_test.go:324: elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
=== RUN   TestDropCollection
--- FAIL: TestDropCollection (10.19s)
    monstache_test.go:363: elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
FAIL
exit status 1
FAIL	github.com/rwynn/monstache	52.676s
```

**Comment by rwynn** [comment]
Can you try with verbose = true on monstache and instead of running the tests just manually insert update and delete documents.

**Comment by rwynn** [comment]
The tests insert docs in the “test” collection of the “test” db in MongoDB. They then look for these docs in an index named “test.test” under the type “_doc” in Elasticsearch. This is how Monstache indexes by default.

**Comment by chakrapani123** [comment]
ok..let me try to create them manually in mongo and elasticsearch

**Comment by chakrapani123** [comment]
sorry..all the while..i was testing on index "test" instead of "test.test"..its working now

**Comment by chakrapani123** [comment]
btw..is there a standard struct for processoutputplugin ? in plugins.go all i noticed is just mapperpluginoutput

**Comment by chakrapani123** [comment]
of if u have any pseudocode for process plugin that helps too..i was able to break document and based on elasticbukprocessor i just need to create an array of docs..which i was able to ..but wondering if there is a standardstcut for processpluginoutput ?

**Comment by rwynn** [comment]
The `Map` function only returns an `error`.  In `Map` after you break the document into an array you then need to use the bulk processor from the input argument to `Add` requests for each element in the array.  

Check this function for how you would `Add` a request.

https://github.com/rwynn/monstache/blob/v4.15.0/monstache.go#L2567

**Comment by chakrapani123** [comment]
not sure what i am missing..here is my plugin code

```
package main
import (
    "github.com/rwynn/monstache/monstachemap" 

    "fmt"
    "reflect"
    "github.com/olivere/elastic"

)

func Process(input *monstachemap.ProcessPluginInput) (err error) {
    doc := input.MapperPluginInput.Document
    bulk := input.ElasticBulkProcessor
    var jobs Job
    //var outputjob []Job
    if input.MapperPluginInput.Collection == "jobs" {

    for k, v := range doc {
          if k  == "_id" {
            jobs.ID = v
          } else if k == "owner" {
            jobs.Owner = v
          } else if k == "status" {
            jobs.Status = v
          } else if k == "email_address" {
            jobs.EmailAddress = v
          } else if k == "start_time" {
            jobs.StartTime = v
          } else if k == "finish_time" {
            jobs.FinishTime = v
          }
          switch reflect.TypeOf(v).Kind() {
          case reflect.Slice:
            for i := 0 ; i < reflect.ValueOf(v).Len() ; i++ {

             s := reflect.ValueOf(v).Index(i).Elem()
             jobs.HostInfo = s
             fmt.Println("jobs info" , jobs)
             //outputjob = append(outputjob,jobs)
             req := elastic.NewBulkIndexRequest()
             req.Doc(jobs)
             //req.Id(jobs.ID)

             if _, err = req.Source() ; err == nil {
               bulk.Add(req)
             }

            }
          }
  }
}
    //
    return
}


type Job struct {
	ID           interface{}
	Owner        interface{}
	Status       interface{}
	EmailAddress interface{}
	StartTime    interface{}
	FinishTime   interface{}
	Error        interface{}
	HostInfo     interface{}
}
```

I split array of hosts and added each host to bulk.add() . I don't get any errors during plugin compilation but don't see index being created in ES.

**Comment by rwynn** [comment]
This code seems to work OK for me given a field named `host_info` that is an array.  You also need to set the index and type name on the request.  

```golang

package main

import (
	"errors"
	"github.com/olivere/elastic"
	"github.com/rwynn/monstache/monstachemap"
)

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	doc := input.Document
	bulk := input.ElasticBulkProcessor
	hostInfo, ok := doc["host_info"].([]interface{})
	if !ok {
		return errors.New("host info not an array")
	}
	for _, h := range hostInfo {
		var job Job
		job.HostInfo = h
		job.ID = doc["_id"]
		job.Owner = doc["owner"]
		// more fields ...
		req := elastic.NewBulkIndexRequest()
		req.Index("jobs")
		req.Type("job")
		req.Doc(job)
		if _, err = req.Source(); err == nil {
			bulk.Add(req)
		} else {
			return err
		}
	}
	return
}

type Job struct {
	ID           interface{}
	Owner        interface{}
	Status       interface{}
	EmailAddress interface{}
	StartTime    interface{}
	FinishTime   interface{}
	Error        interface{}
	HostInfo     interface{}
}


```

**Comment by rwynn** [comment]
Here is a more robust version that does filtering:

```golang
package main

import (
	"errors"
	"github.com/olivere/elastic"
	"github.com/rwynn/monstache/monstachemap"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	if input.Collection == "jobs" {
		// skip the event since we will process it in the Process function
		output = &monstachemap.MapperPluginOutput{Document: input.Document, Skip: true}
	} else {
		// pass the original event through letting monstache index it
		output = &monstachemap.MapperPluginOutput{Passthrough: true}
	}
	return
}

func processJob(input *monstachemap.ProcessPluginInput) (err error) {
	doc := input.Document
	bulk := input.ElasticBulkProcessor
	hostInfo, ok := doc["host_info"].([]interface{})
	if !ok {
		return errors.New("host info not an array")
	}
	for _, h := range hostInfo {
		var job Job
		job.HostInfo = h
		job.ID = doc["_id"]
		job.Owner = doc["owner"]
		// more fields ...
		req := elastic.NewBulkIndexRequest()
		req.Index("jobs")
		req.Type("job")
		req.Doc(job)
		if _, err = req.Source(); err == nil {
			bulk.Add(req)
		} else {
			return err
		}
	}
	return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	if input.Collection == "jobs" && (input.Operation == "i" || input.Operation == "u") {
		return processJob(input)
	}
	return
}

type Job struct {
	ID           interface{}
	Owner        interface{}
	Status       interface{}
	EmailAddress interface{}
	StartTime    interface{}
	FinishTime   interface{}
	Error        interface{}
	HostInfo     interface{}
}

```

**Comment by chakrapani123** [comment]
awesome..i see..the latest one..eliminates duplicate index before/after transformation ..works for me..testing real time sync as well..will update shortly

**Comment by chakrapani123** [comment]
here is something interesting 

without above plugin - monstache works as expected with real time sync and no conversions

with above plugin - conversions work but due to real time sync ..i see last entries being updated by every polling cycle i assume its every minute as i notice new entry in index every minute for the last entry

any other tweaks needed in settings to avoid that?

thanks
Chakri

**Comment by chakrapani123** [comment]
please ignore my previous comment..looks like there is poller that does that on db part of our application package

**Comment by chakrapani123** [comment]
hello Again..i was able to migrate/transform all our collections..thanks once again for taking time to support my request..i was wondering if there is any documentation on hosting it on multi-tenant cloud like kubernetes ?

**Comment by rwynn** [comment]
I don't have any kubernetes specific docs.  There are [docker containers](https://hub.docker.com/r/rwynn/monstache/tags/) for each version of monstache.  Also, monstache has a built in [server](https://rwynn.github.io/monstache-site/advanced/#http-server) that you enable with `-enable-http-server`.  I've been told kubernetes can use this to check the health of the container.  

You might be able to get help on a kubernetes forum.

**Comment by chakrapani123** [comment]
will figure out a way to do it ..somehow..and one last thing..is there a way to remove duplicate entries for updates as well as i see duplicate entries for every update..so

my collection has say 2 documents and 2 updates on each document so i see 8 records in ES instead of 2 .. is there a way to correlate based of mongo document id and drop duplicates?

thanks
Chakri

**Comment by chakrapani123** [comment]
wondering if instead of doing bulk insert..if we can leverage upsert?

**Comment by rwynn** [comment]
Monstache will normally use the id of the document in MongoDB for the id of the document in Elasticsearch.  So updates overwrite.  What I mean is that without a plugin if you continously update one document in MongoDB you will only have 1 corresponding document in Elasticsearch.  

However, since you are doing your own indexing in Elasticsearch with the plugin then you need a way to give those documents an id such that they will be overwritten on the next update.  

You can perhaps always concatenate the id of the main document with the some part of your hostinfo.  Do that make sense?  Then you need to add that id to the request using `req.Id(yourId)`.  You will also want to set the version using `req.Version()` to account for concurrent updates.  Monstache does this normally using the timestamp from the oplog which you can get from the `input` sent to the plugin.  

The way it's working now is that the code in your plugin is not sending any id so Elasticsearch is automatically generating one each time.

**Comment by chakrapani123** [comment]
i tried to extract id from original doc and set it in request..but looks like its dropping my filters and i have added version as well by converting timestamp to unix (int type) and thats failing due to version conflict...

here is my code snippet

```package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/olivere/elastic"
	"github.com/rwynn/monstache/monstachemap"
	//  "reflect"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	if input.Collection == "jobs" || input.Collection == "dbjobs" {
		// skip the event since we will process it in the Process function
		output = &monstachemap.MapperPluginOutput{Document: input.Document, Skip: true}
	} else {
		// pass the original event through letting monstache index it
		output = &monstachemap.MapperPluginOutput{Passthrough: true}
	}
	return
}

func processPatcherJob(input *monstachemap.ProcessPluginInput) (err error) {
	doc := input.Document
	bulk := input.ElasticBulkProcessor
	hostInfo, ok := doc["hosts"].([]interface{})
	if !ok {
		return errors.New("host info not an array")
	}
	for _, h := range hostInfo {
		var job Job
		var linuxpatches LinPatchInfo
		job.HostInfo = h

		jobid, ok := doc["_id"].(bson.ObjectId)

		if !ok {
			fmt.Println("not bson object")
		}

		starttime, ok := doc["start_time"].(time.Time)
		if !ok {
			fmt.Println("starttime not time")
		}
		finishtime, ok := doc["finish_time"].(time.Time)
		if !ok {
			fmt.Println("finishtime not time")
		}

		job.ID = jobid.Hex()
		//job.ID = doc["_id"]
		job.Owner = doc["owner"]
		job.Status = doc["status"]
		job.EmailAddress = doc["email_address"]
		job.StartTime = starttime
		job.FinishTime = finishtime
		job.LinInfo = linuxpatches
		req := elastic.NewBulkIndexRequest()

		patchinfo, ok := job.HostInfo.(map[string]interface{})

		if !ok {
			fmt.Println("hosts list is not a map[string]interface{}")
		}

		for pk, pv := range patchinfo {
			if pk == "linpatches" {
				linpatchinfo, ok := pv.([]interface{})
				if !ok {
					fmt.Println("linpatches in hostinfo is not an interface")
				}
				for _, lv := range linpatchinfo {
					patchstatsinfo, ok := lv.(map[string]interface{})
					if !ok {
						fmt.Println("patchset list is not an interface")
					}
					for sk, sv := range patchstatsinfo {
						if sk == "name" {
							job.LinInfo.Name = sv
						}
						if sk == "status" {
							job.LinInfo.Status = sv
						}
						if sk == "harden" {
							job.LinInfo.Harden = sv
						}
					}
				}
			}
		}
		//fmt.Println("jobs info", linuxpatches, "linpatches", job.LinInfo)
		req.Index("patcherjobs")
		req.Id(job.ID)
		req.Version(starttime.Unix())
		req.Type("job")
		req.Doc(job)
		if _, err = req.Source(); err == nil {
			bulk.Add(req)
		} else {
			return err
		}
	}
	return
}

func processDbPatcherJob(input *monstachemap.ProcessPluginInput) (err error) {
	doc := input.Document
	bulk := input.ElasticBulkProcessor
	hostInfo, ok := doc["hosts"].([]interface{})
	if !ok {
		return errors.New("db host info not an array")
	}
	for _, h := range hostInfo {
		var job Job
		var linuxpatches LinPatchInfo
		job.HostInfo = h

		jobid, ok := doc["_id"].(bson.ObjectId)
		if !ok {
			fmt.Println("not bson object")
		}
		starttime, ok := doc["start_time"].(time.Time)
		if !ok {
			fmt.Println("starttime not time")
		}
		finishtime, ok := doc["finish_time"].(time.Time)
		if !ok {
			fmt.Println("finishtime not time")
		}

		job.ID = jobid.Hex()
		job.Owner = doc["owner"]
		job.Status = doc["status"]
		job.EmailAddress = doc["email_address"]
		job.StartTime = starttime
		job.FinishTime = finishtime
		job.LinInfo = linuxpatches
		req := elastic.NewBulkIndexRequest()

		//fmt.Println("jobs info", linuxpatches, "linpatches", job.LinInfo)
		req.Index("dbpatcherjobs")
		req.Type("job")
		req.Id(job.ID)
		req.Version(starttime.Unix())
		req.Doc(job)
		if _, err = req.Source(); err == nil {
			bulk.Add(req)
		} else {
			return err
		}
	}
	return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	fmt.Println("input docs", input)
	if input.Collection == "jobs" && (input.Operation == "i") {
		return processPatcherJob(input)
	}
	if input.Collection == "dbjobs" && (input.Operation == "i") {
		return processDbPatcherJob(input)
	}
	return
}

type Job struct {
	ID           string
	Owner        interface{}
	Status       interface{}
	EmailAddress interface{}
	StartTime    time.Time
	FinishTime   time.Time
	HostInfo     interface{}
	LinInfo      LinPatchInfo `json:",omitempty"`
}

type LinPatchInfo struct {
	Name   interface{}
	Status interface{}
	Harden interface{}
}
```

**Comment by rwynn** [comment]
I think you would need a unique id for every document that you index.  Not the same id.

So each time through the loop you need to generate a unique id based on 2 fields.  

```golang
import "fmt"

for i, h := range hostInfo {
   // ...
   req.Id(fmtSprintf("%s_%d", job.ID, i))
```

This just appends the position in the array and assumes that you only appending to host info not reordering it with your updates.  A better solution might be to append something unique from host_info.  

Also, you can use the timestamp from the oplog. For the version number.  You want the version to increment on each update.  

```golang
req.Version(input.Timestamp)
```

**Comment by chakrapani123** [comment]
also, i tried to compile it for other OS other than the one i am working on (darwin) ...with the following command and it seems to fail.for buildplugin

GOOS=linux GOARCH=amd64 go build -buildmode=plugin -o pluginlinux.so pluginlinux.go -v

named files must be .go files

wondering if plugins can be compiled for multiple OS flavors ?

if i follow simple build command i get my macos executable for that

plugin.so: Mach-O 64-bit dynamically linked shared library x86_64

thoughts?

**Comment by chakrapani123** [comment]
GOOS=linux GOARCH=amd64 go build -buildmode=plugin -o pluginlinux.so pluginlinux.go
# command-line-arguments
loadinternal: cannot find runtime/cgo
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chakrapani123** [comment]
go version : 
go version go1.11.5 darwin/amd64

**Comment by chakrapani123** [comment]
i used docker image to build plugin and leveraged go1.11.5 for plugin build and when i run it..seems like a dependency issue..but i got past the above errors..pls ignore them

**Comment by chakrapani123** [comment]
still getting version conflicts..not sure why 

version conflict, current version [-1] is different than the one provided

also, i had to convert input.Timestamp to int64 as its bson.MongoTimestamp type and did the following to convert to int64 input.Timestamp.Time().Unix()

setting version throws off the plugin for some reason and docs count falls to 0 due to that

req.Id(fmt.Sprintf("%s_%d", job.ID, i))
req.Version(versiontstamp)

**Comment by rwynn** [comment]
You can convert the version like this.  MongoTimestamp is just an int64 with a special type for some reason.  I also forgot to tell you to set the `VersionType`.  This is all in the monstache.go source code for your reference.  

```golang
req.Version(int64(input.Timestamp))
req.VersionType("external")
```

**Comment by chakrapani123** [comment]
hello again..thanks a lot for taking time to address my issues..this has been a great tool that addressing critical reporting needs. i have tried various tools like transporter to mongo-es connector and nothing came close to this one and the support i got it's really great. i was able to host this on Cloud foundry by building it with native os and it works great . thanks again for all your help

**Comment by rwynn** [comment]
@chakrapani123 glad you got everything working and thanks.  If you like monstache please spread the word as, like you said, there are lots of tools in this space.
