### ISSUE TITLE
Logging from JS plugin + Break JS plugin into multiple files

### ISSUE THREAD

**Issue by shanky061** [rwynn/monstache#182]
1. While logging from JS plugin using `console.log` it just prints the log onto `stdout` not to any log file. Is it possible to log directly into log files, how ?
2. Is it possible to break a JS plugin file into modules ? ( `require` doesn't work.)
3. Can we save two documents (with different content) in ES to different index corresponding to a mongo doc update using JS plugin ?

**Comment by rwynn** [comment]
@shanky061 you are correct it is not possible to accomplish 1-3 currently with a JS plugin in monstache.  Those are possible only by switching to a golang plugin.  

Here is an example of a golang plugin that takes a single document inserted or updated in a `jobs` collection and indexes multiple docs into Elasticsearch based on the contents of a `host_info` array in the document.

https://github.com/rwynn/monstache/issues/181#issuecomment-468719179

The docs for building and running monstache with that plugin are [here](https://rwynn.github.io/monstache-site/advanced/#golang).

**Comment by shanky061** [comment]
Is there any future scope for any improvements in JS plugins feature set ?

For now we aren't considering to add a new language in our stack.

**Comment by rwynn** [comment]
I don't have any plans to expand the feature set of javascript plugins, but I would be open to pull requests to add a small set of features.  The javascript plugin was mostly just intended for simple transformations.

**Comment by rwynn** [comment]
One crazy idea would be to point monstache to an http proxy (instead of direct to elasticsearch) that you build with nodejs.  Then map the bulk index requests that monstache sends using an environment you are comfortable with and send the results to Elasticsearch using the official client.  

https://github.com/elastic/elasticsearch-js

You would need to implement a few endpoints in your proxy like `/` which monstache uses to get the version of Elasticsearch.

**Comment by shanky061** [comment]
Adding this new proxy service adds complexity and a new component to maintain. This does not seem right approach. For now this is deprioritized, I might end up doing it in Go later since that is the right way to do it. Thanks anyway.
