### ISSUE TITLE
Index on Elasticsearch only certain Mongo collections

### ISSUE THREAD

**Issue by max2thousand** [rwynn/monstache#183]
Hello,
 I'm trying to index only certain collections on ElasticSearch, by using the "change-stream-namespaces", but it continues to index all collections.
I'm using mongodb 4.0.4 and ES 6.5.

Do you have any suggestions to do that?

**Comment by rwynn** [comment]
What do you have change-stream-namespaces set to?  It should be an array of db.col strings in your case. It should then only sync the collections you specify.

**Comment by max2thousand** [comment]
That's exactly what I did.
This is the array:
change-stream-namespaces = ["sardpen.struttura", "sardpen.storico_struttura", "sardpen.impresa", "sardpen.comuni", "sardpen.iunDetails", "sardpen.storico_impresa",
"sardpen.struttura_bonificata", "sardpen.impresa_bonificata", "sardpen.tipo_dotazione", "sardpen.tipo_periodo", "sardpen.tipo_servizio", "sardpen.tipo_struttura", "sardpen.tipo_tariffa"]
But it still indexes all the other collections I got in this database.

**Comment by rwynn** [comment]
Can you run with -print-config just to verify it’s getting applied. I will look into it.

**Comment by max2thousand** [comment]
Ok, this is the output. I cannot find the conf I've put in the file. I will attach the conf file as well.

This is the command line invocation:
➜ ./monstache -f config.toml -print-config

and this is the output
 {
  "EnableTemplate": false,
  "EnvDelimiter": ",",
  "MongoURL": "mongodb://localhost:27017",
  "MongoConfigURL": "",
  "MongoPemFile": "",
  "MongoValidatePemFile": false,
  "MongoOpLogDatabaseName": "",
  "MongoOpLogCollectionName": "",
  "MongoDialSettings": {
    "Timeout": 15,
    "Ssl": false,
    "ReadTimeout": 30,
    "WriteTimeout": 30
  },
  "MongoSessionSettings": {
    "SocketTimeout": 0,
    "SyncTimeout": 30
  },
  "MongoX509Settings": {
    "ClientCertPemFile": "",
    "ClientKeyPemFile": ""
  },
  "GtmSettings": {
    "ChannelSize": 512,
    "BufferSize": 32,
    "BufferDuration": "75ms"
  },
  "AWSConnect": {
    "AccessKey": "",
    "SecretKey": "",
    "Region": ""
  },
  "Logs": {
    "Info": "",
    "Warn": "",
    "Error": "",
    "Trace": "",
    "Stats": ""
  },
  "GraylogAddr": "",
  "ElasticUrls": [
    "http://localhost:9200"
  ],
  "ElasticUser": "",
  "ElasticPassword": "",
  "ElasticPemFile": "",
  "ElasticValidatePemFile": false,
  "ElasticVersion": "",
  "ElasticHealth0": 15,
  "ElasticHealth1": 5,
  "ResumeName": "apollo",
  "NsRegex": "",
  "NsDropRegex": "",
  "NsExcludeRegex": "",
  "NsDropExcludeRegex": "",
  "ClusterName": "apollo",
  "Print": true,
  "Version": false,
  "Pprof": false,
  "DisableChangeEvents": false,
  "EnableEasyJSON": false,
  "Stats": true,
  "IndexStats": true,
  "StatsDuration": "",
  "StatsIndexFormat": "monstache.stats.2006-01-02",
  "Gzip": true,
  "Verbose": true,
  "Resume": true,
  "ResumeWriteUnsafe": false,
  "ResumeFromTimestamp": 0,
  "Replay": false,
  "DroppedDatabases": true,
  "DroppedCollections": true,
  "IndexFiles": false,
  "IndexAsUpdate": false,
  "FileHighlighting": true,
  "EnablePatches": false,
  "FailFast": false,
  "IndexOplogTime": false,
  "OplogTsFieldName": "oplog_ts",
  "OplogDateFieldName": "oplog_date",
  "OplogDateFieldFormat": "2006/01/02 15:04:05",
  "ExitAfterDirectReads": false,
  "MergePatchAttr": "json-merge-patches",
  "ElasticMaxConns": 4,
  "ElasticRetry": false,
  "ElasticMaxDocs": -1,
  "ElasticMaxBytes": 8388608,
  "ElasticMaxSeconds": 1,
  "ElasticClientTimeout": 0,
  "ElasticMajorVersion": 0,
  "ElasticMinorVersion": 0,
  "MaxFileSize": 0,
  "ConfigFile": "config.toml",
  "Script": null,
  "Filter": null,
  "Pipeline": null,
  "Mapping": null,
  "Relate": null,
  "FileNamespaces": null,
  "PatchNamespaces": null,
  "Workers": null,
  "Worker": "",
  "ChangeStreamNs": null,
  "DirectReadNs": null,
  "DirectReadSplitMax": 0,
  "MapperPluginPath": "",
  "EnableHTTPServer": false,
  "HTTPServerAddr": ":8080",
  "TimeMachineNamespaces": null,
  "TimeMachineIndexPrefix": "log",
  "TimeMachineIndexSuffix": "2006-01-02",
  "TimeMachineDirectReads": false,
  "PipeAllowDisk": false,
  "RoutingNamespaces": null,
  "DeleteStrategy": 0,
  "DeleteIndexPattern": "*",
  "ConfigDatabaseName": "monstache",
  "FileDownloaders": 0,
  "RelateThreads": 10,
  "RelateBuffer": 1000,
  "PostProcessors": 0,
  "PruneInvalidJSON": false
}

This is the config.toml:

# connection settings

# connect to MongoDB using the following URL
mongo-url = "mongodb://localhost:27017"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://localhost:9200"]

# frequently required settings

# if you don't want to listen for changes to all collections in MongoDB but only a few
# e.g. only listen for inserts, updates, deletes, and drops from mydb.mycollection
# this setting does not initiate a copy, it is a filter on the oplog change listener only
#namespace-regex = '^sardpen.*$'

# additionally, if you need to seed an index from a collection and not just listen for changes from the oplog
# you can copy entire collections or views from MongoDB to Elasticsearch
#direct-read-namespaces = ["mydb.mycollection", "db.collection", "test.test"]

# if you want to use MongoDB change streams instead of legacy oplog tailing add the following
# in this case you don't need regexes to filter collections.
# change streams require MongoDB version 3.6+
# change streams can only be combined with resume, replay, or cluster-name options on MongoDB 4+
# if you have MongoDB 4+ you can listen for changes to an entire database or entire deployment
# to listen to an entire db use only the database name.  For a deployment use an empty string.
#change-stream-namespaces = ["mydb.mycollection", "db.collection", "test.test"]

# additional settings

# compress requests to Elasticsearch
gzip = true
# generate indexing statistics
stats = true
# index statistics into Elasticsearch
index-stats = true
# use the following PEM file for connections to MongoDB
#mongo-pem-file = "/path/to/mongoCert.pem"
# disable PEM validation
mongo-validate-pem-file = false
# use the following user name for Elasticsearch basic auth
#elasticsearch-user = "someuser"
# use the following password for Elasticsearch basic auth
#elasticsearch-password = "somepassword"
# use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 4
# use the following PEM file to connections to Elasticsearch
#elasticsearch-pem-file = "/path/to/elasticCert.pem"
# validate connections to Elasticsearch
elastic-validate-pem-file = false
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = true
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = true
# do not start processing at the beginning of the MongoDB oplog
# if you set the replay to true you may see version conflict messages
# in the log if you had synced previously. This just means that you are replaying old docs which are already
# in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
replay = false
# resume processing from a timestamp saved in a previous run
resume = true
# do not validate that progress timestamps have been saved
resume-write-unsafe = false
# override the name under which resume state is saved
resume-name = "default"
# exclude documents whose namespace matches the following pattern
#namespace-exclude-regex = '^mydb\.ignorecollection$'
# turn on indexing of GridFS file content
index-files = false
# turn on search result highlighting of GridFS content
file-highlighting = true
# index GridFS files inserted into the following collections
file-namespaces = ["users.fs.files"]
# print detailed information including request traces
verbose = true
# enable clustering mode
cluster-name = 'apollo'
# do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false

[[mapping]]
namespace = 'sardpen.struttura_bonificata'
index = 'struttura_bonificata'
type = '_doc'

[[mapping]]
namespace = 'sardpen.struttura'
index = 'struttura'
type = '_doc'

[[mapping]]
namespace = 'sardpen.impresa'
index = 'impresa'
type = '_doc'

[[mapping]]
namespace = 'sardpen.comuni'
index = 'comuni'
type = '_doc'

[[mapping]]
namespace = 'sardpen.iunDetails'
index = 'iunDetails'
type = '_doc'

[[mapping]]
namespace = 'sardpen.storico_impresa'
index = 'storico_impresa'
type = '_doc'

[[mapping]]
namespace = 'sardpen.impresa_bonificata'
index = 'impresa_bonificata'
type = '_doc'

[[mapping]]
namespace = 'sardpen.tipo_dotazione'
index = 'tipo_dotazione'
type = '_doc'

[[mapping]]
namespace = 'sardpen.tipo_periodo'
index = 'tipo_periodo'
type = '_doc'

[[mapping]]
namespace = 'sardpen.tipo_servizio'
index = 'tipo_servizio'
type = '_doc'

[[mapping]]
namespace = 'sardpen.tipo_struttura'
index = 'tipo_struttura'
type = '_doc'

[[mapping]]
namespace = 'sardpen.tipo_tariffa'
index = 'tipo_tariffa'
type = '_doc'

change-stream-namespaces = ["sardpen.struttura", "sardpen.storico_struttura", "sardpen.impresa", "sardpen.comuni", "sardpen.iunDetails", "sardpen.storico_impresa",
"sardpen.struttura_bonificata", "sardpen.impresa_bonificata", "sardpen.tipo_dotazione", "sardpen.tipo_periodo", "sardpen.tipo_servizio", "sardpen.tipo_struttura", "sardpen.tipo_tariffa"]

Let me know, thanks!

**Comment by rwynn** [comment]
If not getting applied then check this from docs

Keep simple one-line configs above any TOML table definitions in your config file. A TOML table is only ended by another TOML table or the end of the file. Anything below a TOML table will be interpreted to be part of the table by the parser unless it is ended. See the following Issue 58 for more information.

**Comment by rwynn** [comment]
Yep you need it above your mappings.

**Comment by max2thousand** [comment]
Ah ok, perfect!
