### ISSUE TITLE
how to dynamiclly detect new config file and add it to daemon service?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#185]
hi Ryan,

i have several collections in one database, every collection i want to sync to one different elastic search's index, if currently i have one collection configured in config.toml, and make it as a Systemd or daemon service, then requirement change, i want to add another collection of same db in another config file, such as config1.toml, how do i manage config.toml and config1.toml as a Systemd service in the mean time? 
the Systemd support windows system?

**Comment by rwynn** [comment]
You would probably use a regular windows service. Systemd is not supported on windows. 

You can dynamically change the index name in both JavaScript or Golang plugins. The output of the Map function in a Golang plugin includes an Index field. And JavaScript uses a _meta_monstache object embedded in the return doc in a script. You can use this if you want to dynamically change the index according to some pattern based on the MongoDB namespace.

**Comment by sunweiconfidence** [comment]
@rwynn, how to make it as a regular windows service? if window service is running, i want to add several config.toml with different prefix like config1.toml,config2.toml, whether monstache can monitor a folder with these config files in it to implement dynamically detect has new config files generated and start new processes? thanks

**Comment by rwynn** [comment]
@sunweiconfidence monstache does not support monitoring a folder for config files or restarting itself.  You would need to manage this logic from outside of monstache and restart it as necessary.  

I'm not familiar with creating windows services.  You would need to search for a tool that can convert any windows binary to a windows service that you can start/stop/restart after making the config changes.

**Comment by sunweiconfidence** [comment]
@rwynn ok, thanks for your help.
