### ISSUE TITLE
rwynn/mgo module causes build error

### ISSUE THREAD

**Issue by chanpl** [rwynn/monstache#186]
Hi rwynn,

Our company's artifactory is recently pointing to GoCenter for better security and immutability. However, I found your own rwynn/mgo module has problem in publishing to GoCenter (See: https://gocenter.jfrog.com/github.com~2Frwynn~2Fmgo/versions). If this is not allowed by GoCenter, can we just use _github.com/globalsign/mgo_ directly?

Basically, I'm asking to remove this line from go.mod:

`replace github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8 => github.com/rwynn/mgo v0.0.0-20190130173337-9b1257fb3190`

**Comment by rwynn** [comment]
Hi @chanpl, 

I would like to remove the `replace` directive but currently it serves the purpose of fixing what I consider some critical issues/limitations with change streams in globalsign/mgo.  The replace is just a fork of globalsign/mgo where I have applied the following PR that is yet to be merged:

https://github.com/globalsign/mgo/pull/326

The reason I did not change the import statements is that I would hope this PR gets merged and the fork is not necessary going in the future. 

Do you know why this could be failing in GoCenter?  The go tooling does not have a problem with it so I'm curious why it doesn't work with GoCenter.

One option for you until this gets sorted out would be to use a specific version of monstache before this change.   It think that would be `v4.13.3` or `v3.20.3`.

**Comment by chanpl** [comment]
Hi @rwynn 

I am sorry that I don't know why that was failing in GoCenter, but I am asking, hopefully will be answered. It's also good to hear that you're planning to drop the replace. Since the root cause of error in GoCenter  is still unknown, it might be failing again after merging. But this shouldn't a reason to block the merge :-)

Thanks man, `v4.13.3` works for me at this moment.

**Comment by chanpl** [comment]
Hi @rwynn 

From JFrog's reply: https://github.com/jfrog/gocenter/issues/7

I guess, we need to include "github.com/globalsign/mgo" in the go.mod. I also try to get the module locally, it returns the same error:

`$ export GO111MODULE=on`
`$ go get github.com/rwynn/mgo@v0.0.0-20190203195949-55e8fd85e7e2
go: finding github.com/rwynn/mgo v0.0.0-20190203195949-55e8fd85e7e2
go: github.com/rwynn/mgo@v0.0.0-20190203195949-55e8fd85e7e2: parsing go.mod: unexpected module path "github.com/globalsign/mgo"
go: error loading module requirements`

**Comment by rwynn** [comment]
Do you mean change it to match location of this repo instead?  

I think it’s already pointed to globalsign since I didn’t change go.mod.

**Comment by rwynn** [comment]
@chanpl when you get a chance can you try to build `master` again?  I think it might be ok now since I changed the `go.mod` file in the replace directive's target to be module path `github.com/rwynn/mgo` instead of globalsign.

**Comment by chanpl** [comment]
Hi @rwynn,

The latest commit in `master` is working now, could you release a new version for that?

Actually, it didn't work at first because GoCenter only uploads commit hash for the first time. After that, they just detect new tags. Thanks for the help from JFrog, the latest commit of `rwynn/mgo` is now also available on GoCenter. Detail: https://github.com/jfrog/gocenter/issues/7

**Comment by rwynn** [comment]
@chanpl please try the latest release.  Thanks.

**Comment by chanpl** [comment]
Hi @rwynn 
Yea, it works, thanks.
