### ISSUE TITLE
why not add kafka to improve high concurrency write to elasticsearch?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#191]
@rwynn kafka is a high available mq, when do you plan to add kafka as a middleware to let mongo change streams to firstly push to kafka, then sync to elasticsearch whether current program can support Million concurrent write to elasticsearch? thanks

**Comment by rwynn** [comment]
That is something to investigate but I don't have plans currently.  Would you be able to try it out in a fork and submit a PR with your results?

Even without a fork of monstache you can implement sending to Kafka with a go plugin and the `Process` function.  Use an `init` function in the plugin to establish a connection to Kafka and then send the docs to Kafka in `Process`.  It just wouldn't be "built into" monstache.  

Is there a reason Elasticsearch cannot be scaled to meet the indexing requirements? By the way Monstache can send more concurrent requests by upping the `elasticsearch-max-conns` config.  This will put a lot of load on Elasticsearch and with a large cluster is it not enough? The indexing throughput in Elasticsearch is governed by multiple factors including number of nodes, node sizes, and config.  I've tried to note some of these in my response to https://github.com/rwynn/monstache/issues/190.

**Comment by sunweiconfidence** [comment]
@rwynn i will try to fork the project and modify the code, if can't finish in this way, i will try to implement by go plugin form
currently i don't meet with big data issue to must scale to meet the indexing requirement, but in future our system will reach a large data, so i want to prepare in advance

**Comment by rwynn** [comment]
@sunweiconfidence you might want to take a look at [Debezium](https://debezium.io/docs/connectors/mongodb/) if you are interested in MongoDB -> Kafka.

Closing this for now since I don't plan on Kafka support in Monstache.  I might at some point create a different go daemon that simply does MongoDB -> Kafka.

**Comment by rwynn** [comment]
@sunweiconfidence I just released a new project related to your question.  You may find it useful.  

https://github.com/rwynn/route81

Route81 publishes MongoDB event data in real time to Kafka so that you can have multiple consumers of the data.  You would need to handle the reading from Kafka and publishing to Elasticsearch or any other system.

**Comment by sunweiconfidence** [comment]
@rwynn, thanks, i will try this, i have a question is that how you deal with mongodb's fs.files and fs.chunks to kafka?, fs.files and fs.chunks are attachment file

**Comment by rwynn** [comment]
Not sure the best way to do it. 

Currently only the GridFS metadata will be sent to Kafka. Consumers could use the metadata to retrieve the file from MongoDB. 

Alternative would be for route81 to publish whole file content in message or chunks in separate messages. However not sure it would be a good practice to send large binary data as Kafka message. Maybe more scalable to have consumer assemble file with metadata already being published.

**Comment by rwynn** [comment]
@sunweiconfidence please open an issue on route81 if you want to discuss this further.  I looked into it briefly today and after inserting a document via GridFS I did see both a .files and .chunks topic was being populated by route81.  The chunks actually had a message with the data base 64 encoded in it.  So it looks like route81 is actually already sending the chunks to Kafka.
