### ISSUE TITLE
prune-invalid-json omits an entire doc with an invalid date

### ISSUE THREAD

**Issue by aleks-m** [rwynn/monstache#193]
I have one Mongo document with an incorrect date (which is just an empty string):
```
"available_from" : "",
```
With `prune-invalid-json = true` I get this error:
```
ERROR 2019/03/27 10:37:19 Bulk response item: {"_index":"foobar","_type":"foobarbaz","_id":"5b730999b7fab5000173d9d5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [available_from]","caused_by":{"reason":"Invalid format: \"\"","type":"illegal_argument_exception"}}}
```
and as a result I don't see that document in Elastic at all. 

Is it possible to omit just that field, not an entire document?

**Comment by rwynn** [comment]
Prune invalid json does exactly that - delete fields in the doc which would fail being encoded to Json. However it wouldn’t touch an empty string.  
 
See TestPruneInvalidJSON function in the Monstache test file. 

You could use a simple Golang plugin to right a Map function and delete the field if it is an empty string.

**Comment by rwynn** [comment]
You might be able to use 

https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html#ignore-malformed-setting

**Comment by rwynn** [comment]
You can use an index template to allow malformed on that field for all indexes or indexes of a pattern.  You would need to apply this before running monstache to index.  

```
PUT _template/template_foobar
{
  "index_patterns": ["foobar"],
  "mappings": {
    "foobarbaz": {
      "properties": {
        "available_from": {
          "type": "date",
          "ignore_malformed": true
        }
      }
    }
  }
}
```

**Comment by aleks-m** [comment]
Thanks for info!
