### ISSUE TITLE
Preferred way to build middleware with go mod?

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#197]
Just decided to upgrade to the latest builds from a pre `modules` version and getting a lot of issues with builds first of all complaining over mismatched modules:
```
16:30 $ monstache -mapper-plugin-path ./transform.so -f ~/configs/monstache.toml 
ERROR 2019/03/29 16:30:26 Unable to load mapper plugin ./transform.so: plugin.Open("./transform"): plugin was built with a different version of package github.com/mailru/easyjson/jlexer
INFO 2019/03/29 16:30:26 Shutting down with exit status 1 after panic.
```
After updating the `go.mod` file to match module versions I cannot get around this error:
```
plugin was built with a different version of package github.com/rwynn/monstache/monstachemap
```
Is there a preferred way to build middleware plugins? Would make it a lot easier in the docker builds also as I am experiencing the same there errors there.

**Comment by Crispy1975** [comment]
I figured out the easiest way is to build the plugin from within the `monstache` directory. Things are working as expected. :+1:

**Comment by rwynn** [comment]
I was going to say make sure you are outside of GOPATH otherwise you have to explicitly force go module build with an env variable. Glad you got it working.

**Comment by rwynn** [comment]
I usually suggest copying the go.mod from the release tag of monstache you want to build against into a folder off gopath with just your plugin. You can add new dependency to the go.mod for your plugin I think but not alter the ones monstache is built against.

**Comment by Crispy1975** [comment]
Tried copying the `go.mod` with the plugin repo outside of the go path but then had the monstachemap error. Odd. Probably something simple I am missing somewhere.

**Comment by rwynn** [comment]
What version of go are you building with? 1.12 if possible. Do you have any lingering versions of monstache in gopath that it might be picking up?

**Comment by rwynn** [comment]
With go modules I now have a gopath that just contains bin and pkg. The src folder is no longer needed since all code should be versioned under pkg.

**Comment by Crispy1975** [comment]
I think that could well be the issue... I'm on 1.11.5 here, and still have some non-module projects going on. I'll upgrade Go and clean out the paths and see of that improves things.

**Comment by rwynn** [comment]
I just realized that if you build the plugin in it's own directory outside gopath then in addition to copying the go.mod from monstache you probably also have to do a 

```
cd plugin
go get github.com/rwynn/monstache@v4.16.0
```

Since monstache doesn't depend on itself, it's version is not in the go.mod.  But that command above will add the version to go.mod so that the plugin has a reference to it.  

I think otherwise, the `go build` command might go and pull something from github that is most recent.  That is probably also why if you build it in the same directory as monstache it works.  But you shouldn't need to.

**Comment by rwynn** [comment]
You may also need to change the package name at the top in go.mod in the the plugins copy.
