### ISSUE TITLE
Lots of "Dropping invalid float64 value: NaN for document" but no fields are dropped

### ISSUE THREAD

**Issue by gabrielmcf** [rwynn/monstache#199]
I'm using the `prune-invalid-json` option and receiving lots of warnings saying there is an invalid float64 in my document. I've seen that it could be a wrong date or something like that. I've double checked my MongoDB document but all dates and floats are valid. More strange than that is that, checking the document id the error prints to me it does not seems to have dropped any field!

Is there a way to know which field is triggering this error? I've also tried to parse one of those documents using JSON.parse through otto but it does everything flawlessly. My configuration can be seen below:

```
    mongo-url = "<REDACTED>"
    elasticsearch-urls = ["<REDACTED>"]
    workers = ["T1"]
    namespace-regex = "^offers_data.offers$"
    mongo-oplog-collection-name = "oplog.$main"
    resume = true
    routing-namespaces = ["offers_data.offers"]

    verbose = true
    stats = true
    pprof = false
    prune-invalid-json = true

    elasticsearch-max-bytes = 1024000000
    elasticsearch-max-conns = 512

    [gtm-settings]
    channel-size = 4096
    buffer-size = 512
    buffer-duration = "150ms"
```

**Comment by gabrielmcf** [comment]
I've made further investigations and noticed that it breaks with this date string: `"2019-09-22T00:00:00Z"`
This date comes as an object from Mongo and, whith a JSON.stringify on it, it returns me the string above. If I try to do a `new Date("2019-09-22T00:00:00Z")` in monstache it gives me the error I mentioned but when I do the same thing running a script in otto it works.

**Comment by rwynn** [comment]
Can you try without `prune-invalid-json` and see if the document is serialized correctly by golang's json serializer?  

Also, the float message comes when infinity or NaN are used in the MongoDB document.  Those do not serialize cleaning to JSON for storing in Elasticsearch.

https://github.com/rwynn/monstache/blob/v4.16.1/monstache.go#L656

**Comment by rwynn** [comment]
https://play.golang.org/p/gD4hFRuMS-R

**Comment by gabrielmcf** [comment]
Hi @rwynn, thank you for you answer! I've tried before without the `prune-invalid-json` option and it doesn't do anything. The index is not even created as it get stucked in a infinite loop, as told in another thread.

I've some update on this issue. I had already seen the bit of code that does that and have acomplished to do the field parsing, using the following method: `var date1 = new Date(JSON.stringify(doc.departure_date).replace(/\"/g,""))`. The field comes as an object, for some reason. In mongo, one of the problematic fields, looks like that: `"departure_date" : ISODate("2019-04-15T00:00:00Z")`  and it does get parsed to Elasticsearch and looks like that: `"departure_date": "2019-06-17T00:00:00Z"`. It's mapping looks like this: 
```
        "departure_date": {
          "full_name": "departure_date",
          "mapping": {
            "departure_date": {
              "type": "date",
              "format": "yyyy-MM-dd HH:mm:ss||epoch_millis||yyyy-MM-dd'T'HH:mm:ss.SS'Z'||yyyy-MM-dd'T'HH:mm:ss.SSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'"
            }
          }
        }
```
When I do a typeof on this field on mongo I get an `undefined`.
I'm still on investigation but would thank any help!

**Comment by rwynn** [comment]
Just a note. It shouldn’t get stuck in an infinite loop anymore as Monstache now checks serializing the doc is successful before adding to the bulk processor. Now it should be logging an error when that marshaling fails.

**Comment by gabrielmcf** [comment]
But it seems to be doing this... When I remove the `prune-invalid-json` option it prints infinite `json: unsupported value: NaN` errors and saves nothing to the index. I'm using docker version `4.16.1`.

**Comment by rwynn** [comment]
Yes that error message is not related to date fields. That message happens when there is a field in your doc that is literally set to the value NaN.  Or at least the mgo driver is reading it as such.

**Comment by gabrielmcf** [comment]
As I've mentioned some of those dates does seems strange in Mongo, returning undefined for typeof.

**Comment by rwynn** [comment]
I'm not sure if this is related to the problem you're seeing but I've noticed this with using otto and monstache:

- Monstache reads the document as a go Map from use the mgo Driver.  This will result in a go Map with a `time.Time` value for a key that is a Date() in MongoDB.  
- Monstache passes the map into your javascript function using otto if script is configured
- In the function, one might expect the key with the go `time.Time` value to be a javascript `Date`.  But otto doesn't do this deep conversion to javascript of the arguments.  Instead the value for the key will be a javascript type `object` which I think is a wrapper around the go `time.Time` value.  You can actually call some golang functions on it like for example, `var seconds = doc["timeField"].Unix()`. 

So if you are performing operations on the field as if it was a javascript Date then that might be the cause of the NaN being produced?

**Comment by gabrielmcf** [comment]
You mean I can use golang functions in the script outside the `module.exports = function(doc)` declaration?

**Comment by rwynn** [comment]
No you can not use golang anywhere except by writing a golang plugin, compiling it, and passing it's file location as an argument to monstache.  

I'm saying the otto integration is not quite perfect.  In some cases it just presents javascript objects which are wrappers of an underyling go object.  I don't think most people (including myself) expect it to work that way.  I would expect a proper Javascript Date object to be what results in the javascript function.   

I try to point users towards using a golang plugin instead of scripts now since the integration is better.  The performance is also better.  

What happens when you don't use any scripts and keep `prune-invalid-json` on?  Do you get any errors then?

**Comment by gabrielmcf** [comment]
I've tested without the scripts (including the filter one) and it works! It's probably what you said, some confusing conversion from golang to javascript made by otto. I will look after writing a go plugin but I'm quite unfamiliar with go to do it now, although I would love to learn it!
Thank you for all your help, if I accomplish anything new be sure that I will post it here! I think we can close this issue now, if there is nothing to be done on monstache side.

**Comment by rwynn** [comment]
Thanks.  If you are able to post your script (with field names modified) I can take a look and see if anything jumps out as a possibility to generate an NaN.  Especially, if you are doing arithmetic operations or parseInt, etc.

**Comment by gabrielmcf** [comment]
Well, I've found the problem, it was exactly what you said but related to another field that didn't appeared before. The workaround I've found was the same I told you above:
```
var date1 = new Date(JSON.stringify(doc.departure_date).replace(/\"/g,""))
```
Now I have no more annoying warnings in my monstache! Thank you very much for all the help and clarifications!
