### ISSUE TITLE
mongo 4.0+ transactions not supported

### ISSUE THREAD

**Issue by Akstasy** [rwynn/monstache#200]
Hello.

I'm using mongo 4.0+ transaction feature but it seems like monstache is not treating committed operations. I did not find anything related to this subject in the monstache documentation. 

Here is how the magic happens: 

mongo: `
use dbname
db.person.insertOne({ data: 42 })  
`
<= data is now both in mongo and elastic

mongo: 
`
session = db.getMongo().startSession( { readPreference: { mode: "primary" } } );
person = session.getDatabase("dbname").person;
session.startTransaction( { readConcern: { level: "snapshot" }, writeConcern: { w: "majority" } } );
try {
   person.insertOne( { data: 84 });
   session.commitTransaction();
} catch (error) {
   print(error)
   session.abortTransaction();
}
session.endSession();
`  
<= data is only in mongo side

Versions:
monstache version 4.16.1
MongoDB version 4.0.6
Elasticsearch version 6.3.0

Thank you for your highlight.

**Comment by rwynn** [comment]
Are you enabling the change streams api in Monstache?  Via config like 

change-stream-namespaces = [ “” ]

**Comment by Akstasy** [comment]
Simple and efficient. Thank you.
