### ISSUE TITLE
Running monstache in resume mode does not save the timestamp when a direct-read is completed

### ISSUE THREAD

**Issue by sameerkattel** [rwynn/monstache#203]
I always have to insert data into mongodb when a direct read is completed to see the resume timestamp saved in mongodb.  Not sure if this behavior is intentional.  Or else I think it would be better to save the resume timestamp periodically during direct reads as well.

**Comment by rwynn** [comment]
It is intentional because direct read timestamp are not when real events occurred. It may be impossible to resume from them if using change streams.

**Comment by sameerkattel** [comment]
Wondering if it is possible to use the timestamp retrieved from ObjectId when using mondodb generated _id. 

Thank you @rwynn  for the wonderful tool.

**Comment by rwynn** [comment]
@sameerkattel can you try with the latest release and see if this fixes the issue for you.  It should now save a timestamp after the direct reads are completed even with no update activity.
