### ISSUE TITLE
unknown field 'DirectReadConcur' in struct literal of type gtm.Options

### ISSUE THREAD

**Issue by lolgolflol** [rwynn/monstache#205]
after I use command "go install" I got this error.

I found  gtm package where Options struct, it does not have attribute DirectReadConcur
but In monstache.go:3915 call struct and set DirectReadConcur attribute
```
./monstache.go:3915:19: unknown field 'DirectReadConcur' in struct literal of type gtm.Options
```

**Comment by rwynn** [comment]
You have to build with go modules.  Dependency is on the development  branch of gtm.

**Comment by lolgolflol** [comment]
thank you, it's passed  but  I got a new  error:
```
gtm.go:1321:24: unknown field 'StartAtOperationTime' in struct literal of type mgo.ChangeStreamOptions
gtm.go:1328:11: cannot use s (type *mgo.Session) as type watchable in assignment:
	*mgo.Session does not implement watchable (missing Watch method)
gtm.go:1330:11: cannot use s.DB(n.database) (type *mgo.Database) as type watchable in assignment:
*mgo.Database does not implement watchable (missing Watch method)
```
I don't know what I do wrong.

**Comment by rwynn** [comment]
I think the problem is that you are not using a go modules enabled build. With e.g go 1.12 you should only need to “go install” from the monstache directory and all required dependencies will be pulled from the go.mod file. 
Clone monstache outside you go path to force a module build.

**Comment by rwynn** [comment]
Btw the problem you mentioned with the import is also taken care of with go modules. You will notice a “replace” directive in go.mod.

**Comment by lolgolflol** [comment]
Ok, I am done. this is a new knowledge for me. I used go1.10  it doesn't have the module feature that why I can not install. thank you. Right now I change go1.12 it's work.
