### ISSUE TITLE
Monstache reflection time in elastic search delay

### ISSUE THREAD

**Issue by Sathishvelmurugan** [rwynn/monstache#208]
I have using monstache for realtime sync from mongodb to elasticsearch.

but the reflection time of changes in mongodb to elasticsearch is high. 

My configuration file :

mongo-url = "mongodb://localhost:27017/?replicaSet=rs0"
elasticsearch-url = "http://localhost:9200"

namespace-regex ='^vgroo\.(products|shops|shopaccounts|\$cmd)$'
direct-read-namespaces = ["vgroo.products","vgroo.shops","vgroo.shopaccounts"]

gtm-channel-size = 200

gzip = true
stats = true
index-stats = true

elasticsearch-max-conns = 4
elasticsearch-max-seconds = 1
elasticsearch-max-bytes = 8000000

dropped-collections = false
dropped-databases = false

replay = false
resume = true
resume-write-unsafe = true
resume-name = "default"
index-files = false
file-highlighting = false
verbose = true
exit-after-direct-reads = false

index-as-update=true
index-oplog-time=true

how to get immediate reflection from mongodb to elastic?

**Comment by rwynn** [comment]
Can you confirm all your settings are being applied by running with -print-config. Especially the 1s flush on Elasticsearch.

**Comment by Sathishvelmurugan** [comment]
I got this output while running with -print-config

  "ElasticMaxBytes": 8388608,
  "ElasticMaxSeconds": 5,
  "ElasticClientTimeout": 0,
  "ElasticMajorVersion": 0,
  "ElasticMinorVersion": 0,
  "MaxFileSize": 0,
  "ConfigFile": "/etc/monstache/monstache.toml",
  "Script": null,
  "Filter": null,
  "Pipeline": null,
  "Mapping": null,
  "Relate": null,
  "FileNamespaces": null,
  "PatchNamespaces": null,
  "Workers": null,
  "Worker": "",
  "ChangeStreamNs": null,
  "DirectReadNs": [
    "jheaps.products",
    "jheaps.shops",
    "jheaps.shopaccounts"
  ],
  "DirectReadSplitMax": 0,
  "DirectReadConcur": 0,
  "MapperPluginPath": "",
  "EnableHTTPServer": false,
  "HTTPServerAddr": ":8080",
  "TimeMachineNamespaces": null,
  "TimeMachineIndexPrefix": "log",
  "TimeMachineIndexSuffix": "2006-01-02",
  "TimeMachineDirectReads": false,
  "PipeAllowDisk": false,
  "RoutingNamespaces": null,
  "DeleteStrategy": 0,
  "DeleteIndexPattern": "*",
  "ConfigDatabaseName": "monstache",
  "FileDownloaders": 0,
  "RelateThreads": 10,
  "RelateBuffer": 1000,
  "PostProcessors": 0,
  "PruneInvalidJSON": false
}

**Comment by rwynn** [comment]
It doesn’t appear that your settings are taking effect. Ensure that if you have any TOML tables in your config file that they are ALL at the end of the file. 

See warning at top of page here. 
https://rwynn.github.io/monstache-site/config/

**Comment by Sathishvelmurugan** [comment]
Is it possible to set elastic flush in milliseconds? because delete operation takes only milliseconds in mysite..

**Comment by rwynn** [comment]
You cannot use ms. But you can set elasticsearch-max-docs to 1. It will flush immediately. Not great for direct reads though - better to flush those in bulk.
