### ISSUE TITLE
Monstache update document from mongdb fail !

### ISSUE THREAD

**Issue by nguyenhoangnhon** [rwynn/monstache#209]
My system includes Elastic Search 7.0 and Monstache beta 5.0. I have issues while I try to update documents from MongoDB .Here is my log. Please help me fix it.
 (Note: full-sync when begining is successfull)

TRACE 2019/04/24 03:39:08 HTTP/1.1 400 Bad Request
Content-Length: 425
Content-Type: application/json; charset=UTF-8
Warning: 299 Elasticsearch-7.0.0-b7e28a7 "[types removal] Specifying types in bulk requests is deprecated."

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [-3] for version type [EXTERNAL];2: illegal version value [-3] for version type [EXTERNAL];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [-3] for version type [EXTERNAL];2: illegal version value [-3] for version type [EXTERNAL];"},"status":400}
ERROR 2019/04/24 03:39:08 299 Elasticsearch-7.0.0-b7e28a7 "[types removal] Specifying types in bulk requests is deprecated."
ERROR 2019/04/24 03:39:08 elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Validation Failed: 1: illegal version value [-3] for version type [EXTERNAL];2: illegal version value [-3] for version type [EXTERNAL]; [type=action_request_validation_exception]
ERROR 2019/04/24 03:39:08 elastic: bulk processor "monstache" was unable to perform work: elastic: Error 400 (Bad Request): Validation Failed: 1: illegal version value [-3] for version type [EXTERNAL];2: illegal version value [-3] for version type [EXTERNAL]; [type=action_request_validation_exception]

**Comment by rwynn** [comment]
Hi @nguyenhoangnhon I tried to replicate the issue today with the Monstache 5.0.0 release yesterday, but it was working OK for me.

```
INFO 2019/04/24 14:44:57 Started monstache version 5.0.0
INFO 2019/04/24 14:44:57 Successfully connected to MongoDB version 4.0.9
INFO 2019/04/24 14:44:57 Successfully connected to Elasticsearch version 6.7.1
INFO 2019/04/24 14:44:57 Listening for events
INFO 2019/04/24 14:44:57 Sending systemd READY=1
WARN 2019/04/24 14:44:57 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2019/04/24 14:44:57 Watching changes on the deployment
TRACE 2019/04/24 14:45:03 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.14 (linux-amd64)
Content-Length: 147
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cc0766f5e31dadc4b438feb","_type":"_doc","version":6683472066131263489,"version_type":"external"}}
{"foo":1}

TRACE 2019/04/24 14:45:03 HTTP/1.1 200 OK
Content-Length: 258
Content-Type: application/json; charset=UTF-8

{"took":13,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cc0766f5e31dadc4b438feb","_version":6683472066131263489,"result":"c$eated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":6,"status":201}}]}
TRACE 2019/04/24 14:45:06 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.14 (linux-amd64)
Content-Length: 147
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cc0766f5e31dadc4b438feb","_type":"_doc","version":6683472079016165377,"version_type":"external"}}
{"foo":2}

TRACE 2019/04/24 14:45:06 HTTP/1.1 200 OK
Content-Length: 258
Content-Type: application/json; charset=UTF-8

{"took":13,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cc0766f5e31dadc4b438feb","_version":6683472079016165377,"result":"u$
dated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":6,"status":200}}]}


```

Above is an insert followed by an update. The `_version` field should always be set to the timestamp from the MongoDB oplog.   So not sure why you would be seeing `-3` as a value for that field as your logs indicate.

**Comment by rwynn** [comment]
@nguyenhoangnhon I also tried with Elasticsearch 7 and didn't see any major issues.

```
TRACE 2019/04/24 14:55:54 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.14 (linux-amd64)
Content-Length: 147
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cc0766f5e31dadc4b438feb","_type":"_doc","version":6683474857860005889,"version_type":"external"}}
{"foo":2}

TRACE 2019/04/24 14:55:54 HTTP/1.1 200 OK
Content-Length: 258
Content-Type: application/json; charset=UTF-8
Warning: 299 Elasticsearch-7.0.0-b7e28a7 "[types removal] Specifying types in bulk requests is deprecated."

{"took":16,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cc0766f5e31dadc4b438feb","_version":6683474857860005889,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2,"_primary_term":7,"status":200}}]}
ERROR 2019/04/24 14:55:54 299 Elasticsearch-7.0.0-b7e28a7 "[types removal] Specifying types in bulk requests is deprecated."

```

A minor issue is that monstache logs the warning message about deprecation of the _type field as an ERROR instead of a WARNING.  But the indexing does succeed and the version number is not a negative number.

**Comment by nguyenhoangnhon** [comment]
Hi Rwynn,
I am using MongDB 3.6 on Ubuntu18.04 . When I using Monstache 4.0, everthing is oke but when I use Monstache 5.0.0 beta , there is issue. I think that , Monstache 5.0.0 is incompatible with MongoDB 3.6

**Comment by rwynn** [comment]
Hi @nguyenhoangnhon thanks for reporting the issue with monstache 5 and MongoDB 3.6.  I've committed a couple of fixes to the `rel5` and `rel6` branches of monstache.  You would need to build from either of those branches using `go install` with golang 1.12 until I create new releases.  

The `rel6` branch is designed to work with Elasticsearch 7 so I think you should use that to remove deprecation warnings about types.  The `rel5` branch would work but would log messages complaining that type is deprecated.  

So, in total: Clone monstache and then switch to the `rel6` branch.  Use the `go install` command with golang 1.12 which will produce a monstache binary.  The version will be 6.0.  This should be compatible with your setup of MongoDB 3.6 and Elasticsearch 7.  

When I get a chance I will push new releases of monstache 5.1 and 6.0 with these changes.
