### ISSUE TITLE
Sync specific field with object in pick function

### ISSUE THREAD

**Issue by Sathishvelmurugan** [rwynn/monstache#210]
Hi ryan,
   I have created script file like this 
[[script]]
namespace = "vgroo.shops"
script = """
module.exports = function(doc, ns) {
    return _.pick(doc, "_id", "User", "ShopAccountId.Name");
}
"""

But last field picking was not working how to pick specific object in that field using pick function?

**Comment by rwynn** [comment]
Hi you can read about the underscore pick function here. http://underscorejs.org/  

I don’t think it supports nested field names. So you will need to work around that.

**Comment by Sathishvelmurugan** [comment]
Is there any other way to sync specific field with nested object?

**Comment by rwynn** [comment]
Yes you just write JavaScript code to Map the input to the output you need and then return the doc to sync.
