### ISSUE TITLE
Latest build after 4.17 is not working for OSX

### ISSUE THREAD

**Issue by kartikjain** [rwynn/monstache#215]
Hi

I installed v4.17.1 on ubuntu 18.04 last week and it was working fine.
Today I installed the latest version 6.x on macOS and it isnt working.
It is disconnecting from mongodb. 
While I spent 1 day trying to figure out what was the issue installing 4.17.1 on Mac os worked instantly.
Please check once the latest version on Mac os

Thanks

**Comment by rwynn** [comment]
Hi @kartikjain.  Can you share the error message and the versions of Elasticsearch and MongoDB you are using?  

All the monstache versions have the same features and bug fixes.  The difference in the versions is compatibility with MongoDB and Elasticsearch.

In general I suggest to use monstache as follows:

| Monstache version      | Git branch (used to build plugin) |  Docker tag | Description | Elasticsearch | MongoDB
| ----------- | ----------- |------------|---------|---|---
| 3      | rel3       |  rel3 | mgo community go driver | Versions 2 and 5 | Version 3
| 4   | master        | rel4 (note this used to be latest) | mgo community go driver | Version 6 | Version 3
| 5      | rel5       |  rel5 | MongoDB, Inc. go driver | Version 6| Version 4
| 6      | rel6       |  rel6, latest | MongoDB, Inc. go driver | Version 7 | Version 4

**Comment by rwynn** [comment]
For example, the latest test run for monstache 6 is passing when run against MongoDB 4 and Elasticsearch 7.

https://travis-ci.org/rwynn/monstache/builds/527094360
