### ISSUE TITLE
String is recognized as data

### ISSUE THREAD

**Issue by DanBrk** [rwynn/monstache#216]
Hi,
I'm using Monstache 4.12.5 and syncing data from MongoDB 4.0.

I get the following error: 
> {"type":"illegal_argument_exception","reason":"failed to parse date field [7C463E4901D63D5CE05390C00A0AFD80_2] with format [strict_date_optional_time||epoch_millis]

In MongoDB the field is of type 'String', but the first document contains value 
> "MessageId" : "2019-04-11T12:47:23.761Z" 

The problem is that it is string and not ISODATE , but Monstache convert it into the index as 
> "MessageId" : {
>           "type" : "date"
>         }
> 

How should it work ?

**Comment by rwynn** [comment]
Hi @DanBrk monstache doesn't send any type information to Elasticsearch.  Only the data.  

What you are seeing is Elasticsearch doing [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html) and within that [date detection](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#date-detection).  To prevent the string data from being mapped as a date at index creation time, you can use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) to be explicit about the types you want for your fields.  

You need to create the index template before the index is created / re-create existing indexes.

**Comment by DanBrk** [comment]
Thanks for the answer.
I have another problem with Date detection. Date value that appear in MongoDb as 2019-03-27 09:59:22.100Z fails with.
> failed to parse date field [2019-03-27T09:59:22.1Z] with format [strict_date_optional_time||epoch_millis]"

Is there a workaround for this ?

**Comment by ozdroid** [comment]
i have the same problem after upgrade to elasticsearch 7.0.0 & monstache 6.0.1

> Thanks for the answer.
> I have another problem with Date detection. Date value that appear in MongoDb as 2019-03-27 09:59:22.100Z fails with.
> 
> > failed to parse date field [2019-03-27T09:59:22.1Z] with format [strict_date_optional_time||epoch_millis]"
> 
> Is there a workaround for this ?

**Comment by rwynn** [comment]
I was not able to replicate by inserting a new date in MongoDB...

```
rs1:PRIMARY> db.test.insert({d: new Date()})
WriteResult({ "nInserted" : 1 })

```

```
vagrant@vagrant:/vagrant/monstache$ go run monstache.go -verbose
INFO 2019/05/06 14:10:49 Started monstache version 6.0.1
INFO 2019/05/06 14:10:49 Successfully connected to MongoDB version 4.0.9
INFO 2019/05/06 14:10:49 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/05/06 14:10:49 Listening for events
INFO 2019/05/06 14:10:49 Sending systemd READY=1
WARN 2019/05/06 14:10:49 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2019/05/06 14:10:49 Watching changes on the deployment
TRACE 2019/05/06 14:11:08 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.0 (linux-amd64)
Content-Length: 155
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cd0407c30725b669569f26d","version":6687916347965308931,"version_type":"external"}}
{"d":"2019-05-06T14:11:08.625Z"}

TRACE 2019/05/06 14:11:09 HTTP/1.1 200 OK
Content-Length: 259
Content-Type: application/json; charset=UTF-8

{"took":330,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cd0407c30725b669569f26d","_version":6687916347965308931,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

Does this happen only when the milliseconds end with zeros?

**Comment by rwynn** [comment]
I also tried with an explicit date with no millis and it seemed to work OK...

```
rs1:PRIMARY> db.test.insert({d: new Date("2016-05-18T16:00:00Z")})
WriteResult({ "nInserted" : 1 })
```

```
TRACE 2019/05/06 14:23:32 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.0 (linux-amd64)
Content-Length: 151
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cd0436430725b669569f272","version":6687919543420977153,"version_type":"external"}}
{"d":"2016-05-18T16:00:00Z"}

TRACE 2019/05/06 14:23:32 HTTP/1.1 200 OK
Content-Length: 258
Content-Type: application/json; charset=UTF-8

{"took":12,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cd0436430725b669569f272","_version":6687919543420977153,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":5,"_primary_term":1,"status":201}}]}

```

**Comment by rwynn** [comment]
When I look at the index that got created by Elasticsearch upon sending the first document I see...

```
vagrant@vagrant:/vagrant/monstache$ curl localhost:9200/test.test?pretty
{
  "test.test" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "d" : {
          "type" : "date"
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1557151868951",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "-sQovSFDSFu_jL5LEOwwnQ",
        "version" : {
          "created" : "7000099"
        },
        "provided_name" : "test.test"
      }
    }
  }
}

```

**Comment by rwynn** [comment]
I am able to replicate but only if I insert the date as a string instead of a date in MongoDB and only if the date string includes only 1 digit for ms. 

```
rs1:PRIMARY> db.test.insert({d: "2019-05-06T13:34:12.8Z"})
WriteResult({ "nInserted" : 1 })
```

```
TRACE 2019/05/06 14:33:45 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.0 (linux-amd64)
Content-Length: 153
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cd045c930725b669569f273","version":6687922176235929601,"version_type":"external"}}
{"d":"2019-05-06T13:34:12.8Z"}

TRACE 2019/05/06 14:33:45 HTTP/1.1 200 OK
Content-Length: 541
Content-Type: application/json; charset=UTF-8

{"took":23,"errors":true,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cd045c930725b669569f273","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [d] of type [date] in document with id '5cd045c930725b669569f273'","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [2019-05-06T13:34:12.8Z] with format [strict_date_optional_time||epoch_millis]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}}}]}
ERROR 2019/05/06 14:33:45 Bulk response item: {"_index":"test.test","_type":"_doc","_id":"5cd045c930725b669569f273","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [d] of type [date] in document with id '5cd045c930725b669569f273'","caused_by":{"caused_by":{"reason":"Failed to parse with all enclosed parsers","type":"date_time_parse_exception"},"reason":"failed to parse date field [2019-05-06T13:34:12.8Z] with format [strict_date_optional_time||epoch_millis]","type":"illegal_argument_exception"}}}
```

Given this I think the workaround would need to be in your Elasticsearch configuration to change the [format](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) of dates to one which ignores the ms or allows only 1 digit in ms.

**Comment by rwynn** [comment]
Seems like you can fix this by using the following explicit format for your date field....

```
curl -X PUT "localhost:9200/_template/template_1" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["test.test"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_source": {
      "enabled": false
    },
    "properties": {
      "d": {
        "type": "date",
        "format": "date_optional_time"
      }
    }
  }
}
'
```

```
vagrant@vagrant:/vagrant/monstache$ curl localhost:9200/test.test?pretty
{
  "test.test" : {
    "aliases" : { },
    "mappings" : {
      "_source" : {
        "enabled" : false
      },
      "properties" : {
        "d" : {
          "type" : "date",
          "format" : "date_optional_time"
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1557153835891",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "kgzk1dN7SK-SvuuCCfEHVg",
        "version" : {
          "created" : "7000099"
        },
        "provided_name" : "test.test"
      }
    }
  }
}
```

```
TRACE 2019/05/06 14:44:05 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.0 (linux-amd64)
Content-Length: 153
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5cd0483530725b669569f275","version":6687924839115653121,"version_type":"external"}}
{"d":"2019-05-06T13:34:12.8Z"}

TRACE 2019/05/06 14:44:05 HTTP/1.1 200 OK
Content-Length: 258
Content-Type: application/json; charset=UTF-8

{"took":19,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5cd0483530725b669569f275","_version":6687924839115653121,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}

```

This works because by default Elasticsearch uses the format `strict_date_optional_time||epoch_millis` and the strict part means that it will fail without all the ms.

**Comment by ozdroid** [comment]
it works prefect in monstache 4.15.1 old version.  but the lastest version happens when i export mongodb collection  and import data again via Studio 3T, 
i am wondering if the monstache date format problem. becasuse the date in mongo is standard 
IOS Time format
for example : i check the date type field  in mongo is  “2019-04-11T12:47:23.761Z” ，it work perfect. if date end with  "00Z"，for example “2019-04-11T12:47:23.700Z“ ，error happen. the date been change to “2019-04-11T12:47:23.7Z“ , 3 digit in ms -> 1 digit in ms

**Comment by rwynn** [comment]
I think you can see part of the problem [here](https://play.golang.org/p/w3hscGSMoNK).  I'm not sure why it's generating different json between 4.X and 5/6 though as you report. 

There is also a timing issue here.  For example, if you insert a date with 3 digit for ms first, then index gets created with a `date` field since Elasticsearch recognizes it.  Subsequent 1 digit ms will then fail since Elasticsearch cannot parse.  However, if you first insert a 1 digit ms, then Elasticsearch will map as a `string` field and all subsequent will succeed.

**Comment by rwynn** [comment]
It seems like go uses the `RFC3339Nano` format for json:
https://github.com/golang/go/blob/master/src/time/time.go#L1281

**Comment by rwynn** [comment]
Overriding the format away from golang default seems to work ok.  Need to see if this is possible in monstache.

https://play.golang.org/p/CZjBH7SHPnj

**Comment by rwynn** [comment]
Fix for this is checked into all the branches.  Until I have time for a new release you can `go install` in the root directory to build a new binary.

**Comment by ozdroid** [comment]
it works , thanks for your answer

**Comment by DanBrk** [comment]
I rebuilt the new checked in version and it works for me as well.  Thanks a lot.
