### ISSUE TITLE
Error Connecting to IBMCloudService

### ISSUE THREAD

**Issue by marcelhdl** [rwynn/monstache#219]
Hi rwynn,

im currently getting an error, when trying to connect to the MongoDB.

```
Unable to connect to MongoDB using URL mongodb://REDACTED@1ec816d9-0e3b-42d2-83a1-cfe6c14646de-0.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558,1ec816d9-0e3b-42d2-83a1-cfe6c14646de-1.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558/ibmclouddb?authSource=admin&replicaSet=replset: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
Addr: 1ec816d9-0e3b-42d2-83a1-cfe6c14646de-0.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(1ec816d9-0e3b-42d2-83a1-cfe6c14646de-0.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558[-240]) unable to decode message length: EOF
Addr: 1ec816d9-0e3b-42d2-83a1-cfe6c14646de-1.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(1ec816d9-0e3b-42d2-83a1-cfe6c14646de-1.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:32558[-239]) unable to decode message length: EOF

INFO 2019/05/14 14:58:59 Shutting down with exit status 1 after panic.
```

My config:

```
# connection settings

# connect to MongoDB using the following URL
#DEV
mongo-url = "mongodb://user:password@host1:port1,host2:port2/ibmclouddb?authSource=admin&replicaSet=replset"

# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://host:port"]

print-config = true
# additional settings
[mongo-dial-settings]
ssl = true
timeout = 30
# compress requests to Elasticsearch
#gzip = true
# generate indexing statistics
stats = true
# index statistics into Elasticsearch
index-stats = true
# use the following PEM file for connections to MongoDB
mongo-pem-file = "cert.crt"
# disable PEM validation
mongo-validate-pem-file = true
# use the following user name for Elasticsearch basic auth
elasticsearch-user = "User"
# use the following password for Elasticsearch basic auth
elasticsearch-password = "Password"

[[mapping]]
namespace = "AftersalesContentTranslate"
index = "aftersales_content_translate"

verbose = true

```

**Comment by rwynn** [comment]
Hi @marcelhdl lets correct the order of the content in your config to put all toml tables at the end.  Otherwise, the file will not be parsed correctly.  

```
# all single lines settings first
verbose = true

# end with toml tables since the only thing that signals end of a table is another table or end of file
[[mapping]]
namespace = "AftersalesContentTranslate"
index = "aftersales_content_translate"

[mongo-dial-settings]
ssl = true
timeout = 30
```

You can always verify that monstache is reading your settings correctly using the `print-config` flag.

```
monstache -f myconfig.toml -print-config
```

**Comment by rwynn** [comment]
@marcelhdl Also, can you share the version of monstache that you are using?  The documentation has not been updated to include `v5` and `v6` which use a new mongodb driver.   

For `v5` and `v6` all settings for MongoDB are now in the [driver connection string](https://github.com/mongodb/mongo-go-driver/blob/v1.0.0/x/network/connstring/connstring.go)

**Comment by marcelhdl** [comment]
Thanks for the rapid anwser.
I am new to TOML :D
Im using version 6.
So what am I supposed to do? Should I specify the pem file and so on in the Composed string?

**Comment by rwynn** [comment]
Yes, I think with the new driver you would need to add parameters to you `mongo-url`...

```
?sslcertificateauthorityfile=cert.crt&sslinsecure=true
```

You would only need the insecure setting for self signed certificates.  

I just looked at that link I sent you and found a setting that looked correct: 
https://github.com/mongodb/mongo-go-driver/blob/v1.0.0/x/network/connstring/connstring.go#L615

You might find more in there that you want to use.

You don't need the `mongo-dial-settings` anymore with versions 5 and 6.

**Comment by rwynn** [comment]
Btw monstache `v6` is setup to go against Elasticsearch 7.  If you need Elasticsearch 6 support then use monstache `v5`.  The only difference between the 2 is how the indexing is performed.

**Comment by marcelhdl** [comment]
Fixed, now the Elastic Node ist not found:
mongo-connector/monstache -f mongo-connector/monstache_config.toml
INFO 2019/05/15 07:38:01 Started monstache version 5.0.4
INFO 2019/05/15 07:38:01 Successfully connected to MongoDB version 3.4.17
ERROR 2019/05/15 07:38:16 Unable to create Elasticsearch client: health check timeout: Head http://4096a822-2c92-47d4-81cc-23c1759a4d33.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:31251: EOF: no Elasticsearch node available
INFO 2019/05/15 07:38:16 Shutting down with exit status 1 after panic.

Should I do like with the MongoDB?

**Comment by marcelhdl** [comment]
Also fixed! thx! I needed to add the user and the password in the connection string in elastic also.
