### ISSUE TITLE
Can i config monstache to sync only new changes in mongo. Not all documents?

### ISSUE THREAD

**Issue by vmatviychuk** [rwynn/monstache#220]
Can i config monstache to sync only new changes in mongo. Not all documents?
I tried to add timestamp, but that doesn't work. me configuration:
mongo-url =
elasticsearch-urls =
namespace-regex = '^dev_.*\..*$'
direct-read-namespaces = ["dev....]
gzip = true
index-oplog-time = true
elasticsearch-max-conns = 3
replay = true
resume = true
resume-from-timestamp = 1557813616
resume-name = "default"
Thank you for your reply

**Comment by rwynn** [comment]
@vmatviychuk if you turn off `replay` and `resume` then monstache starts watching changes at the end of the oplog (new changes only).

**Comment by rwynn** [comment]
@vmatviychuk if you want to `resume` later but want to start the next run from then end of the oplog then you can delete the collection `monstache.monstache` which removes the persisted timestamp to resume from.  It will be re-populated when you run monstache with `resume=true`.

**Comment by vmatviychuk** [comment]
Thank you very much

**Comment by vmatviychuk** [comment]
another question.  tried with recomendations. Thank you very much. Now thats works when in real time when we use this case:
@vmatviychuk if you turn off replay and resume and omit resume-from-timestamp then monstache starts watching changes at the end of the oplog (new changes only).
But i tried to disable monstache and added new fields in mongo collection. After. i started service monstache and and did not see the new changes. Monster loaded the server 100% and I think I started sorting through all documents how to make monstersh see only new changes whether service is enabled or not

**Comment by vmatviychuk** [comment]
Thank you for reply
