### ISSUE TITLE
Can i config monstache to sync only new changes in mongo?

### ISSUE THREAD

**Issue by vmatviychuk** [rwynn/monstache#221]
Another question. tried with recomendations. Thank you very much. Now thats works when in real time when we use this case:
@vmatviychuk if you turn off replay and resume and omit resume-from-timestamp then monstache starts watching changes at the end of the oplog (new changes only).
But i tried to disable monstache and added new fields in mongo collection. After. i started service monstache and and did not see the new changes. Monster loaded the server 100% and I think I started sorting through all documents how to make monstersh see only new changes whether service is enabled or not

**Comment by rwynn** [comment]
Can you share you configuration?  If you have `direct-read-namespaces` specified that tells monstache to read each collection given entirely and sync it.  That may be the problem.  That setting should only be used when you need to seed Elasticsearch indexes for the first time.

**Comment by vmatviychuk** [comment]
`# connection settings

# connect to MongoDB using the following URL
mongo-url = "mongodb://"

# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = [""]

# frequently required settings

# if you don't want to listen for changes to all collections in MongoDB but only a few
# e.g. only listen for inserts, updates, deletes, and drops from mydb.mycollection
# this setting does not initiate a copy, it is a filter on the change listener only

namespace-regex = '^dev_.*\..*$'

# additionally, if you need to seed an index from a collection and not just listen for changes from the oplog
# you can copy entire collections from MongoDB to Elasticsearch

direct-read-namespaces =["dev_1", "dev_2", "dev_3", "dev_4", "dev_6", ]

# additional settings

# compress requests to Elasticsearch
gzip = true
index-oplog-time = true
# generate indexing statistics
#stats = true
# index statistics into Elasticsearch
#index-stats = true
# use the following PEM file for connections to MongoDB
#mongo-pem-file = "/path/to/mongoCert.pem"
# disable PEM validation
#mongo-validate-pem-file = false
# use the following user name for Elasticsearch basic auth
#elasticsearch-user = "someuser"
# use the following password for Elasticsearch basic auth
#elasticsearch-password = "somepassword"
# use 4 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 3 
# use the following PEM file to connections to Elasticsearch
#elasticsearch-pem-file = "/path/to/elasticCert.pem"
# validate connections to Elasticsearch
#elastic-validate-pem-file = true
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
#dropped-collections = true
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
#dropped-databases = true
# do not start processing at the beginning of the MongoDB oplog
# if you set the replay to true you may see version conflict messages
# in the log if you had synced previously. This just means that you are replaying old docs which are already
# in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
replay = false
# resume processing from a timestamp saved in a previous run
resume = false
#resume-from-timestamp = 1557813616
#resume = false
# do not validate that progress timestamps have been saved
#resume-write-unsafe = false
# override the name under which resume state is saved
resume-name = "default"
# exclude documents whose namespace matches the following pattern
#namespace-exclude-regex = '^mydb\.ignorecollection$'
# turn on indexing of GridFS file content
#index-files = true
# turn on search result highlighting of GridFS content
#file-highlighting = true
# index GridFS files inserted into the following collections
#file-namespaces = ["users.fs.files"]
# print detailed information including request traces
#verbose = true
# enable clustering mode
#cluster-name = 'apollo'
# do not exit after full-sync, rather continue tailing the oplog
#exit-after-direct-reads = false

#[logs]
`

**Comment by vmatviychuk** [comment]
[config.txt](https://github.com/rwynn/monstache/files/3183115/config.txt)

**Comment by vmatviychuk** [comment]
yes, we use option direct read namespaces

**Comment by rwynn** [comment]
You would need to **disable** `direct-read-namespaces` after you have used it once to do a full sync.  This is what is causing load on Elasticsearch.  It tells monstache to read the entire collection and sync it.  If you remove then it will only sync new changes.   If you have `resume` enabled then it will resume syncing after the timestamp saved in the last run.  

Also, if you feel `direct-read-namespaces` puts too much load on Elasticsearch, you can set

```
direct-read-concur = 1
```
That tells monstache to only sync 1 direct read namespace at a time.  By default it syncs all concurrently.

You might have 2 configurations.  1 that does a full sync and exits with

```
# this is only used once or periodically to do a full sync
direct-read-namespaces = ['a', 'b', c']
direct-read-concur = 1
exit-after-direct-reads = true
```

And another that does not include `direct-read-namespaces` and runs all the time and does not exit.

```
resume = true
```

Another way to do it is to use the environment variable `MONSTACHE_DIRECT_READ_NS` instead of putting the direct reads in the config file.  Only set the env variable when you want to do a full sync.

```
MONSTACHE_DIRECT_READ_NS=db.col1,db2.col1
```

**Comment by vmatviychuk** [comment]
Thank you very musch. Thats works. i used the second configuration
