### ISSUE TITLE
More documents in ElasticSearch index than in MongoDB collection

### ISSUE THREAD

**Issue by jpgklassen** [rwynn/monstache#222]
After running Monstache to sync my MongoDB collection with ElasticSearch, I counted all the documents in the MongoDB collection and in the ElasticSearch index and they do not add up.

In MongoDB: `db.collection.count()` returns 1229320.

In ElasticSearch: `GET http://localhost:9200/db.collection/_count` returns 1229405.

Why are the counts different?

**Comment by rwynn** [comment]
hi @jpgklassen what version of monstache, MongoDB, and Elasticsearch are you running?  

It seems that some deletes in MongoDB may have not been processed.  It could have been related to errors if monstache was running or if monstache was not running when the deletes happened they may have been skipped.

To prevent skipping of events, you can run monstache with `resume=true`.  In this mode monstache will periodically save the timestamp of its progress in MongoDB in the collection `monstache.monstache`.  When you start monstache with `resume=true` it will read this timestamp if it exists and then start the changestream back from that previous point in time.  If the timestamp is not found it starts looking for new changes.

I guess I would recommend that you delete your Elasticsearch index
```
curl -XDELETE http://localhost:9200/db.collection
```
And rerun monstache with these settings...

```
resume=true
direct-read-namespaces = ['db.collection']
```

If you stop monstache you should see a timestamp saved to the collection `monstache.monstache`.  If you start it again with resume enabled it should process any events that happended to MongoDB while it was stopped.

**Comment by rwynn** [comment]
Also, make sure you have not set `index-as-update` to true.  The default is false. 

When this setting is turned on you cannot use optimistic concurrency provided by Elasticsearch.  By default version numbers are sent that provided certain guarantees that old data cannot re-enter Elasticsearch.

**Comment by jpgklassen** [comment]
Hi @rwynn,

Thanks so much for your quick reply! I am using monstache version 6.0.4, MongoDB version 4.0.6, and ElasticSearch version 7.0.1. I tried deleting the ElasticSearch index like you said, and when I ran monstache the count went right back up to 1229405. I am using the settings `resume = true`, `direct-read-namespaces = ['db.collection']`, and `index-as-update` is not set so I assume it is false (the default).

Any more ideas why the ElasticSearch count keeps going higher than the MongoDB count?

**Comment by rwynn** [comment]
Hi @jpgklassen I'm not sure what it could be. I tried to replicate but got counts that matched on my end.  

Attached is a golang test that might help detect the difference.  It scrolls through all the documents in an Elasticsearch index and finds the corresponding document in MongoDB. It will fail if one is not found.  It assumes that the _id in MongoDB is an ObjectID.  If not you might have to update the test to parse the string id from Elasticsearch into the correct id type in MongoDB. There are some environment variables to control the mongodb db and collection and the Elasticsearch index to compare.  

You should be able to run the attached with 

```
go test -count=1 compare_test.go
```

after copying the `go.mod` file from the `rel6` branch of monstache next to the file.


[compare_test.zip](https://github.com/rwynn/monstache/files/3194250/compare_test.zip)

**Comment by AndreaBaldiniRM** [comment]
Hi @rwynn,
after full sync MongoDB - ElasticSearch, without any other insert/delete/update, I have different counts:

In MongoDB: 7923408.

In ElasticSearch: 7923410.

From log file I have this message:
ERROR 2021/05/17 21:58:56 key "operationTime" was not found

After some search, I know that all documents id from ElasticSearch are also in MongoDB.

ElasticSearch version: 7.10
MongoDB version: 3.4

Why are the counts different?
Thx

**Comment by AndreaBaldiniRM** [comment]
Hi @rwynn,
I found the issue, it was wrong the MongoDB count.
MongoDB to return the count value in a fast way can use some metadata that can be not exact.
Forcing MongoDB to recalculate the count I have same value.

**Comment by jpgklassen** [comment]
@AndreaBaldiniRM Ah that explains it, thank you! How did you force MongoDB to recalculate the count?

**Comment by rwynn** [comment]
Maybe `countDocuments` instead of `count`?
```js
db.orders.countDocuments({})
```
https://www.mongodb.com/docs/manual/reference/method/db.collection.countDocuments/#mechanics
