### ISSUE TITLE
Geo types handling

### ISSUE THREAD

**Issue by uday-awv** [rwynn/monstache#223]
I have field of type geo [Point](https://docs.mongodb.com/manual/reference/geojson/#point) in mongodb. When it is replicated to elasticsearch I am losing geo query features of elasticsearch because destination is not of type [geo_point](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html) 
I see elastic mapping as below
```
{
  "originLocation": {
    "properties": {
      "coordinates": {
        "type": "float"
      },
      "type": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  }
```
`originLocation.type` is text with "Point" as value and `originLocation.coordinates` type is float. 
If I manually set type before index is created, elastic geo-queries work.
```
PUT my_index
{
  "mappings": {
    "properties": {
      "originLocation": {
        "properties": {
          "coordinates": {
            "type": "geo_point"
          }
        }
      }
    }
  }
}
```

Is it possible to handling this automatically using monstache without me manuall setting type in index?
Thanks.

**Comment by rwynn** [comment]
Hi @uday-awv monstache doesn't try to do mappings for you.  I would suggest you use an index template.  You can use an index template e.g. such that any field named `coordinates` is a geo_point.  

You create index templates up front and then when an index is created that matches the template index pattern the settings will be applied to that new index.  This requires you to have the template in place before the index is first created.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by uday-awv** [comment]
Cool. Thanks for awesome suggestion. That was very helpful.
