### ISSUE TITLE
elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Validation Failed: 1: type is missing; [type=action_request_validation_exception]

### ISSUE THREAD

**Issue by junwu9333** [rwynn/monstache#226]
monstache is not able to sync data from mongodb to elastic search with error: elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Validation Failed: 1: type is missing; [type=action_request_validation_exception]

please help

**Comment by rwynn** [comment]
monstache v6 is only supposed to be used with Elasticsearch v7 which does not require types.  If you don't have Elasticsearch v7 then you need to use monstache v5 or earlier.

What versions of Elasticsearch and MongoDB are you using?

**Comment by junwu9333** [comment]
Thanks for quick response.   we use ES 6 and MongoDB 4

**Comment by rwynn** [comment]
@junwu9333 then monstache `v5` is what you would need.  Does you still get the error with monstache v5?

**Comment by junwu9333** [comment]
I updated to ES7 and it works very well. thank you very much!

**Comment by rwynn** [comment]
Thanks, and sorry I haven't had time to update the documentation yet regarding v5 and v6.  The only difference between the two is that v5 supports ES6 and v6 supports ES7.
