### ISSUE TITLE
Document monstache version compatibility

### ISSUE THREAD

**Issue by rwynn** [rwynn/monstache#227]
| Monstache version      | Git branch (used to build plugin) |  Docker tag | Description | Elasticsearch | MongoDB
| ----------- | ----------- |------------|---------|---|---
| 3      | rel3       |  rel3 | mgo community go driver | Versions 2 and 5 | Version 3
| 4   | master        | rel4 (note this used to be latest) | mgo community go driver | Version 6 | Version 3
| 5      | rel5       |  rel5 | MongoDB, Inc. go driver | Version 6| Version 4
| 6      | rel6       |  rel6, latest | MongoDB, Inc. go driver | Version 7 | Version 4

**Comment by gabrielmcf** [comment]
Is there a version for ES 7 and Mongo 3?

**Comment by rwynn** [comment]
You can use monstache v6 with ES 7 and Mongo 3.  

If you have Mongo 3.6 then you need specify **collections** for `change-stream-namespaces` and that should work fine.  

```
change-stream-namespaces = [ 'db.col', 'db2.col2' ]
```
The default is to tail the entire deployment which won't work.  Also tailing entire databases with not work.  These are Mongo 4 features.

If you have Mongo before 3.6 then you need to specify the following to enable direct access to the oplog.  In this case you cannot use change-stream-namespaces.  

```
enable-oplog = true
```
