### ISSUE TITLE
Error starting change stream

### ISSUE THREAD

**Issue by TemaKozyrev** [rwynn/monstache#229]
Hello, i use monstache v6, mongo v4.0 and elastic v7.1
i get this error, after run binary
`Error starting change stream. Will retry.: (QueryFeatureNotAllowed) $changeStream on an entire database is not allowed in the current feature compatibility version. See http://dochub.mongodb.org/core/4.0-feature-compatibility for more information.`

https://docs.mongodb.com/manual/release-notes/4.0/#change-stream-methods

**Comment by rwynn** [comment]
That’s weird because the docs state “Starting in MongoDB 4.0, you can open a change stream cursor for a single database (excluding admin, local, and config database) to watch for changes to all its non-system collections.”. 

Are you sure you have 4.0 with WiredTiger storage engine setup as a replica set? How are you configuring change-stream-namespaces in monstache?

**Comment by rwynn** [comment]
This is the output I get when running monstache against MongoDB 4.0.  So I'm not able to replicate the issue on my end.

```
~/go/bin$ ./monstache 
INFO 2019/05/29 12:03:21 Started monstache version 6.0.6
INFO 2019/05/29 12:03:21 Successfully connected to MongoDB version 4.0.9
INFO 2019/05/29 12:03:21 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/05/29 12:03:21 Listening for events
INFO 2019/05/29 12:03:21 Watching changes on the deployment
```

**Comment by rwynn** [comment]
Also, don't see an error if I target a specific db...

```
~/go/bin$ ./monstache -change-stream-namespace test.test
INFO 2019/05/29 14:35:02 Started monstache version 6.0.6
INFO 2019/05/29 14:35:02 Successfully connected to MongoDB version 4.0.9
INFO 2019/05/29 14:35:02 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/05/29 14:35:02 Listening for events
INFO 2019/05/29 14:35:02 Watching changes on collection test.test
```

And I cannot seem to upgrade MongoDB past 4.0.9 using the community edition APT repo from MongoDB.

```
deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
```

```
~/go/bin$ sudo apt install mongodb-org
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mongodb-org is already the newest version (4.0.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rwynn** [comment]
Actually I was able to upgrade to 4.0.10 now (forgot to apt update), but I still don't get any errors like you mentioned.

```
~/go$ bin/monstache -change-stream-namespace test
INFO 2019/05/29 14:57:13 Started monstache version 6.0.6
INFO 2019/05/29 14:57:13 Successfully connected to MongoDB version 4.0.10
INFO 2019/05/29 14:57:13 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/05/29 14:57:13 Listening for events
INFO 2019/05/29 14:57:13 Watching changes on database test
```

**Comment by rwynn** [comment]
Is it possible that you upgraded from a pre 4.0 version of MongoDB?  If so you might need to follow the instructions on this page?

db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )

https://docs.mongodb.com/manual/release-notes/4.0-upgrade-replica-set/

**Comment by premjha9625** [comment]
Hi @rwynn i am getting this error when i am adding "change-stream-namespaces" property in monstache.toml 

Error starting change stream. Will retry: (BadValue) Change stream must be followed by a match and then a project stage

how to resolve it?
