### ISSUE TITLE
MongoDB opLog Error?

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#23]
Hey, we have seen this in our logs a couple of time:
```
ERROR 2017/05/13 03:09:34 getMore executor error: CappedPositionLost: CollectionScan died due to position in capped collection being deleted. Last seen record id: RecordId(6419450938863389914)
```
I assume this is due to the `opLog` moving quick that `monstache` was able to catch the changes? Unless there is another possible explanation?

**Comment by rwynn** [comment]
What is the size of the oplog?  You may want to increase it. It's a capped collection so old entries will be forced out by new at a certain point. Seems like monstache was possibly still processing older data that got truncated.

**Comment by Crispy1975** [comment]
The opLog size is the MongoDB default right now, but we perform a lot of updates which affects multiple documents, this will normally translate to a high number of opLog entries. My guess is that monstache isn't getting the time to scan them all before they are flushed.

**Comment by rwynn** [comment]
@Crispy1975, do you know if monstache stops tailing the oplog after receiving this error?  If so, I can possibly make a change to log the error and continue processing if so.

**Comment by Crispy1975** [comment]
We're using it in the cluster mode, it seems to continue ok as the logs report that the process pauses and resumes, as do the other running instances on the other servers. It doesn't appear to be fatal.

**Comment by rwynn** [comment]
I think the issue may be mitigated somewhat by cluster mode.  I'm not sure if a process that encounters this error will actually produce more events after it has encountered this error (even though it may appear in logs to resume).  To fix that I released a new version of monstache that includes an upgraded gtm library.  The gtm code that I think was problematic is this line:

https://github.com/rwynn/gtm/blob/c5642730dfa1ae9ceaebf33baa28d19a24bb0714/gtm.go#L384

The latest version of gtm does not return at this point and thus the loop continues to query the oplog and feed events.  This change is included in monstache 3.0.1.

**Comment by Crispy1975** [comment]
Thanks as always @rwynn we'll give the new version a go in out staging environments today. Will report back on findings. :+1:

**Comment by rwynn** [comment]
@Crispy1975 lots of improvments in 3.0.6 with regards to direct-read performance.  A daily, or slightly more often, run of monstache with direct reads and exit-after-direct-reads can catch up in situations where the oplog position is being lost.  The only caveat at the moment is if you are using json merge patches.  Direct reads currently reset merge patches which may not be want you want.

**Comment by Crispy1975** [comment]
@rwynn we decided not to use the patches in the end, so this could work well for us. :+1:

**Comment by Crispy1975** [comment]
Closing this one out, but referencing the new issue here: https://github.com/rwynn/monstache/issues/27
