### ISSUE TITLE
Monstache fails to create index and throws changeStream error

### ISSUE THREAD

**Issue by nithinkashyapn** [rwynn/monstache#230]
Hey,

I am trying to setup `monstache` to index all of my `MongoDB` collections to separate indexes. But, It throws the following error in `error.log`

```
ERROR 2019/05/29 12:17:39 Error starting change stream. Will retry.: (Location40573) The $changeStream stage is only supported on replica sets
```

My `config.toml` looks like this

```
mongo-url ="mongodb://nithin:XXXX@localhost:27017"
elasticsearch-urls = ["https://localhost:9200"]
elasticsearch-user = "nithin"
elasticsearch-password = "XXXX"
elasticsearch-max-conns = 10
replay = true
resume = true
resume-name = "default"
index-as-update = true
verbose = true

[logs]
info = "/var/logs/monstache/info.log"
warn = "/var/logs/monstache/warn.log"
error = "/var/logs/monstache/error.log"
trace = "/var/logs/monstache/trace.log"
```

The `info.log` throws output as this

```
INFO 2019/05/29 12:16:11 Started monstache version 6.0.6
INFO 2019/05/29 12:16:11 Successfully connected to MongoDB version 3.6.3
INFO 2019/05/29 12:16:11 Successfully connected to Elasticsearch version 6.7.1
INFO 2019/05/29 12:16:11 Listening for events
INFO 2019/05/29 12:16:11 Sending systemd READY=1
INFO 2019/05/29 12:16:11 Watching changes on the deployment
```

Is there anything wrong with the setup?

My indexes on hitting `ES` at `/_cat/indices?v` does not show any new indexes. Should i do any mappings? All I've done is setup `Mongo` and `ES` on `localhost` and then inserted a few `docs` into a test `collection` on `Mongo`.

Thanks

**Comment by rwynn** [comment]
* You need a replica set configuration if you don't already have one.  See here for instructions. https://rwynn.github.io/monstache-site/start/#usage
* Monstache defaults to watch changes on the entire deployment, a feature only available in MongoDB 4.0.  Since it appears you have 3.6 you can only watch specific collections.  Thus you need a config like..

```
change-stream-namespaces = [ 'db.col1', 'db2.col2' ]
```

**Comment by rwynn** [comment]
Also, a third issue is that you need to use Monstache v5 for compat with Elasticsearch 6. 

https://github.com/rwynn/monstache/issues/227

**Comment by nithinkashyapn** [comment]
Hey,

So if i upgrade to `MongoDB 4.0` I need not create multiple namespaces and all collections would automatically get indexed?

I'll set up a replica set and downgrade to `monstache v5`. I was testing out [OpenDistro](https://opendistro.github.io/for-elasticsearch/) and forgot to verify if it was `v7` or `v6`.

Thanks

**Comment by rwynn** [comment]
Yes with MongoDB 4.0 it will default to watching changes on the whole deployment.

**Comment by nithinkashyapn** [comment]
Thank you.
