### ISSUE TITLE
Golang handling deletes

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#235]
Hi,

Currently I'm using the Process function to transform inserts and index into Elastic, but I can't seem to figure out how to handle deletes separately. Can anyone give a simple example of how to do this within Process (something simple, maybe if it's an insert change all text to uppercase then index and if it's a delete change all case to lower case then index)?

**Comment by rwynn** [comment]
One thing to note is that on a delete event MongoDB only provides the _id of the doc that was deleted not the entire doc.   You would need to account for this in your Process function as that will be all that’s passed in.

**Comment by IchorPop** [comment]
Thanks for the quick reply rwynn! In that case I will need to handle it on the mongo side rather than in Process I guess.

**Comment by rwynn** [comment]
```golang
func Process(input*monstachemap.ProcessPluginInput) error {
   if input.Operation == "d" {
      deletedID := input.Document["_id"]
      // if you expect the _id to be a MongoDB ObjectID. It could be int64, string, whatever you saved with
      // needs  import	"go.mongodb.org/mongo-driver/bson/primitive"
      objectID, ok := deletedId.(primitive.ObjectID)
      if ok {
          id := objectID.Hex()
      }
   }
  return nil
}
```

The input contains `*elastic.Client` and `*elastic.BulkProcessor` in fields `ElasticClient` and `ElasticBulkProcessor`.  With the _id you can use the [API](https://godoc.org/github.com/olivere/elastic) to do whatever you need to do.  E.g. you might fetch the document from Elasticsearch by id, modify it, and add a new request to the bulk processor for indexing. 

The easiest place to start looking at the API is to start with the methods available on [Client](https://godoc.org/github.com/olivere/elastic#Client)

Your imports with respect to MongoDB and Elasticsearch will depend on the version of monstache you are using.  See the `go.mod` in the branch of monstache you are using.
