### ISSUE TITLE
Direct read ordering

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#238]
Hi,

A simple question perhaps: what is the ordering of documents that direct-read-namespaces uses to read from a mongo collection? Is it based on sorted IDs or timestamps?

**Comment by rwynn** [comment]
An _id sort is only done to break the entire collection into segments of _id min and _id max. Then each segment is read concurrently without a sort on it.

**Comment by IchorPop** [comment]
Hi rwynn. Thanks for the quick reply. Does this then mean that if direct-read-split-max is set to -1, then the documents from a collection are read in the order they are inserted into the mongo collection?

**Comment by rwynn** [comment]
Hi, they might but not sure. With what you said it would simply be a db.col.find({});  no sort. So depends on how mongo treats that.

**Comment by rwynn** [comment]
You can use a monstache pipeline config with a $sort stage to add ordering on direct reads. 

Like you said you would need to combine this with direct-read-split-max -1 to have the sort go over the entire collection. You probably want to have an index on whatever you sort by.
