### ISSUE TITLE
Logs to stdout

### ISSUE THREAD

**Issue by yetithefoot** [rwynn/monstache#239]
Not sure if it's monstache or Docker related question. I run monstache in a container, logs are written into `/app/logs/info.log`, `/app/logs/warn.log` and `/app/logs/error.log` files. When I run `docker logs` there is no output that comes from container. What is the recommended way to fetch merged `monstache` logs as stdout?

**Comment by rwynn** [comment]
Monstache writes to stdout by default for all log levels without any config.  Do you have any logging config specified? If so you can just remove it and it won’t log to files.

**Comment by rwynn** [comment]
```
$ docker run --rm --network host rwynn/monstache:latest -verbose
$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED              STATUS              PORTS               NAMES
f25c94ac73ec        rwynn/monstache:latest   "/bin/monstache -ver…"   About a minute ago   Up About a minute                       mystifying_kepler
$ docker logs f25c94ac73ec
INFO 2019/06/11 20:04:38 Started monstache version 6.0.6
INFO 2019/06/11 20:04:38 Successfully connected to MongoDB version 4.0.10
INFO 2019/06/11 20:04:38 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/06/11 20:04:38 Listening for events
INFO 2019/06/11 20:04:38 Sending systemd READY=1
WARN 2019/06/11 20:04:38 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2019/06/11 20:04:38 Watching changes on the deployment
```

So I think you just need to remove any config you have specified with regards to logs.
