### ISSUE TITLE
HA mode - MongoDB permissions

### ISSUE THREAD

**Issue by miklosbarabas** [rwynn/monstache#24]
Hi!

Im starting monstache with the following command:
`./monstache -cluster-name myHA -worker MyW1 -f my-config.toml`

And I receive the following error:
`panic: Unable to enable cluster mode: not authorized on monstache to execute command { createIndexes: "cluster", indexes: [ { name: "expireAt_1", ns: "monstache.cluster", key: { expireAt: 1 }, background: true, expireAfterSeconds: 30 } ] }`

The MongoDB user were created like this:
```
db.createUser(
 {
  user: "user",
  pwd: "pass",
  roles: [
    { role: "readWrite", db: "monstache" }
  ]
 }
)
```

I'm using MongoDB 2.6.3, and if i connect directly to the db with the same user credentials, I am able to create collections as well as indices.

Wouldn't it be beneficial to add to the documentation the proper mongodb permissions for monstache to be used in HA mode?

(offtopic: https://rwynn.github.io/monstache-site/options/#toml-table-default-nil-3 -> this should be changed to 'logs' instead of 'log')

Btw, what you guys are doing is pretty good, keep it up!!!

Thx for the help in advance!
M

**Comment by rwynn** [comment]
@miklosbarabas,

Thanks for using monstache and for your suggestions about documenting required permissions and corrections.

Monstache does require readWrite permission on the monstache db for the resume feature.  Additionally, it creates indexes on the cluster collection in this db when using the clustering mode (as you noticed).  

Can you post a sanitized version of your connection string?  I have been able to successfully use monstache with authorization enabled while testing it in Atlas.

I guess the relevant docs here come mostly from the go driver, mgo.  

https://godoc.org/gopkg.in/mgo.v2#Dial

and from mongodb itself

https://docs.mongodb.com/manual/reference/connection-string/

You may already be familiar with these.

**Comment by miklosbarabas** [comment]
@rwynn: thx for the quick reply!

Now I realized that this is happening because I created a separate DB for monstache (with the name monstache) but I was authenticating against the admin DB, and I had a different user for that db as well with the same user/pass, so I slipped over it.
Sorry for wasting your time:)

I close this ticket as it is not an issue.
