### ISSUE TITLE
Supported stages by Pipeline function in Golang Plugin

### ISSUE THREAD

**Issue by ortizbje** [rwynn/monstache#242]
Hi, 

I want to implement a Golang plugin with a Pipeline function in Monstache version 4. The pipeline is a bit complicated with a lot of stages including '$project', '$lookup', '$unwind' and '$group' stages. I think the plugin will work with 'direct reads' but does 'change streams' support pipelines with '$lookup' stages for example ? If it doesn't, I would have liked to access the *mgo.Session pointer but is it possible in the Pipeline function ?

Thanks in advance,
Juan.

**Comment by rwynn** [comment]
Here is an example of a pipeline applied to a change stream from https://docs.mongodb.com/manual/changeStreams/

```
const pipeline = [
  { $match: { 'fullDocument.username': 'alice' } },
  { $addFields: { newField: 'this is an added field!' } }
];

const collection = db.collection('inventory');
const changeStream = collection.watch(pipeline);
changeStream.on('change', next => {
  // process next document
});
```

Monstache only syncs the result of the pipeline that goes into `fullDocument` field.  And for monstache to work your pipeline must return the final result in the form shown here:

https://docs.mongodb.com/manual/reference/change-events/#change-stream-output

What I mean is that it expects everything intact from the original change event with your changes only to the `fullDocument` field.

**Comment by rwynn** [comment]
I remember reading that some pipeline operations may not be supported on change streams.  I cannot find the docs regarding that right now.  But you can try in the console using code like above.

**Comment by rwynn** [comment]
If you cannot use your pipeline on the change stream to return the results you want you can create a MongoDB view with the pipeline instead.  Then create a `Map` function in your plugin and use the `mgo.Session` and the doc that changed to produce a query into the view.  Return the results in the shape you want as the output of the `Map` function.

**Comment by rwynn** [comment]
If you do use a view you may be able to use the `relate` shortcut which can automatically run a document through a view so you don't have to code it.  

https://rwynn.github.io/monstache-site/advanced/#mongodb-view-replication

**Comment by ortizbje** [comment]
I used the mongodb view with the `relate` shortcut and after a few tests everything seems well synchronized. Thank you for your reply and advice.

**Comment by ortizbje** [comment]
Hi @rwynn I wanted your opinon. Finally, the solution with `relate` does not suit my use case because for some joined collections, the match-field is in an array. So I implemented a `Process` function in the Plugin to produce a query into the view when a doc of a joined collection changes. But the plugin doesn't seem to work, I don't know what i'm missing. Here's the plugin if you can check : 

```go
package main

import (
	"github.com/olivere/elastic"
	"github.com/rwynn/monstache/monstachemap"
	"go.mongodb.org/mongo-driver/bson"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	if input.Collection == "Col1" || input.Collection == "Col2" || input.Collection == "Col3" {
		// skip the event since we will process it in the Process function
		output = &monstachemap.MapperPluginOutput{Document: input.Document, Skip: true}
	} else {
		// pass the original event through letting monstache index it
		output = &monstachemap.MapperPluginOutput{Passthrough: true}
	}
	return
}

func BulkAdd(input *monstachemap.ProcessPluginInput, matchFields []string) (err error) {
	s := input.Session.Copy()
	bulk := input.ElasticBulkProcessor
	doc := input.Document
	idN := doc["_id"]
	eventViewCol := s.DB("testdb").C("view")
	
	for _,v := range matchFields {
		q := eventViewCol.Find(bson.M{v: idN})
		iter := q.Iter()
		docEvent := make(map[string]interface{})
		for iter.Next(docEvent) {
			req := elastic.NewBulkIndexRequest()
			req.Index("event")
			//req.Type("event")
			req.Id(idN.(string))
			req.Version(int64(input.Timestamp))
			req.VersionType("external")
			req.Doc(docEvent)
			if _, err = req.Source(); err == nil {
				bulk.Add(req)
			} else {
				return err
			}
		}
		iter.Close()
	}
	s.Close()
	return
}

func processJob(input *monstachemap.ProcessPluginInput) (err error) {
	var matchFields []string

	switch input.Collection {
	case "Col1":
		matchFields = append(matchFields, "matchField1")
		matchFields = append(matchFields, "matchField2")

		err = BulkAdd(input, matchFields)
	case "Col2":
		matchFields = append(matchFields, "matchField3")
		matchFields = append(matchFields, "matchField4")

		err = BulkAdd(input, matchFields)
	case "Col3":
		matchFields = append(matchFields, "matchField5")
		err = BulkAdd(input, matchFields)
	}
	return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	if (input.Collection == "Col1" || input.Collection == "Col2" || input.Collection == "Col3") && (input.Operation == "i" || input.Operation == "u" || input.Operation == "d") {
		return processJob(input)
	}
	return
}
```

**Comment by rwynn** [comment]
What version of monstache are you using?  You will have different imports depending on that.  

It looks like your code is using the mgo driver but the imports are for the MongoDB golang driver.  

Also, whatever you put into `req.Doc` cannot have an `_id` field in it. You will need to remove the _id because the _id cannot be in the source doc.  It goes only in `req.Id` as you have.

**Comment by ortizbje** [comment]
Indeed I was using wrong imports for my version(rel4). Now all works for me. I'll post the plugin code if it helps anyone. Thanks @rwynn for your help and this powerful tool :)

```go
package main

import (
	"github.com/olivere/elastic"
	"github.com/rwynn/monstache/monstachemap"
	"github.com/globalsign/mgo/bson"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	if input.Collection == "Col1" || input.Collection == "Col2" || input.Collection == "Col3" {
		// skip the event since we will process it in the Process function
		output = &monstachemap.MapperPluginOutput{Document: input.Document, Skip: true}
	} else {
		// pass the original event through letting monstache index it
		output = &monstachemap.MapperPluginOutput{Passthrough: true}
	}
	return
}

func BulkAdd(input *monstachemap.ProcessPluginInput, matchFields []string) (err error) {
	s := input.Session.Copy()
	bulk := input.ElasticBulkProcessor
	doc := input.Document
	idN := doc["_id"]
	eventViewCol := s.DB("testdb").C("view")
	
	for _,v := range matchFields {
		q := eventViewCol.Find(bson.M{v: idN})
		iter := q.Iter()
		docEvent := make(map[string]interface{})
		for iter.Next(docEvent) {
			eventId := docEvent["_id"].(bson.ObjectId)
			delete(docEvent, "_id")

			req := elastic.NewBulkIndexRequest()
			req.Index("event")
			req.Type("_doc")
			req.Id(eventId.Hex())
			req.Version(int64(input.Timestamp))
			req.VersionType("external")
			req.Doc(docEvent)
			if _, err = req.Source(); err == nil {
				bulk.Add(req)
			} else {
				return err
			}
		}
		iter.Close()
	}
	s.Close()
	return
}

func processJob(input *monstachemap.ProcessPluginInput) (err error) {
	var matchFields []string

	switch input.Collection {
	case "Col1":
		matchFields = append(matchFields, "matchField1")
		matchFields = append(matchFields, "matchField2")

		err = BulkAdd(input, matchFields)
	case "Col2":
		matchFields = append(matchFields, "matchField3")
		matchFields = append(matchFields, "matchField4")

		err = BulkAdd(input, matchFields)
	case "Col3":
		matchFields = append(matchFields, "matchField5")
		err = BulkAdd(input, matchFields)
	}
	return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	if (input.Collection == "Col1" || input.Collection == "Col2" || input.Collection == "Col3") && (input.Operation == "i" || input.Operation == "u" || input.Operation == "d") {
		return processJob(input)
	}
	return
}
```
