### ISSUE TITLE
Nested UUID fields stored in binary are not transferring correctly

### ISSUE THREAD

**Issue by concurrent-recursion** [rwynn/monstache#243]
When inserting a document into mongo, it is not correctly transferring over to elasticsearch with regards to UUIDs that are stored as binary (Type 4) data. 

Its correctly parsing any elements at the root level of the mongo document, but if the binary field is within an object, then its still parsing it as binary.

Given the following document in Mongo
{ 
    "_id" : UUID("8aa3b5f4-b086-4f7a-ac0b-14a814e593da"), 
    "createdDate" : ISODate("2019-06-18T19:28:33.381+0000"), 
    "createdByUserId" : UUID("00000000-0000-0000-0000-00016dedf9bb"), 
    "toRecipients" : [
        {
            "userId" : UUID("00000000-0000-0000-0000-00016dedf9bb")
        }
    ]
}

Results in the following document in elastic
{
        "_id" : "8aa3b5f4-b086-4f7a-ac0b-14a814e593da",
        "_source" : {
          "createdByUserId" : "00000000-0000-0000-0000-00016dedf9bb",
          "createdDate" : "2019-06-18T19:28:33.381Z",
          "toRecipients" : [
            {
              "userId" : {
                "Subtype" : 4,
                "Data" : "AAAAAAAAAAAAAAABbe35uw=="
              }
            }
          ]
        }
}

The expected results would be 
{
        "_id" : "8aa3b5f4-b086-4f7a-ac0b-14a814e593da",
        "_source" : {
          "createdByUserId" : "00000000-0000-0000-0000-00016dedf9bb",
          "createdDate" : "2019-06-18T19:28:33.381Z",
          "toRecipients" : [
            {
              "userId" : "00000000-0000-0000-0000-00016dedf9bb"
            }
          ]
        }
}

PS - Thanks for the quick fix on the last issue!

**Comment by rwynn** [comment]
Which version of monstache are you using?

**Comment by rwynn** [comment]
Thanks for reporting.  I think this should be fixed in latest `rel5` and `rel6` branches.  Let me know if you still see some issues.

**Comment by concurrent-recursion** [comment]
Thanks for the quick fix. 
Unfortunately I'm not familiar with Go so I'm currently using the docker image (6.0.7) so I won't be able to confirm its working until that's on dockerhub.

**Comment by rwynn** [comment]
@concurrent-recursion you should be good to go with 6.0.8 now.  Let me know how that goes.  Thanks.

**Comment by rwynn** [comment]
@concurrent-recursion let me know if you get a chance to test the latest version and whether or not I can close this issue.  Thanks!

**Comment by concurrent-recursion** [comment]
My issue is resolved. I've verified with the latest release. Thanks!
