### ISSUE TITLE
build.sh with local packages 

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#246]
Hi rwynn,

I'm trying to create the go plugin with the build.sh file. I have a locally defined package (let's call it localpackage). The file structure is like this

    ├──main.go
    ├──localpackage/
    |  ├──file1.go
    |  ├──file2.go

Normally, I would build this via `go mod init project` and `go build`, where localpackage is imported via `import "project/localpackage"`

How would I maintain this structure and have it work with build.sh? I have tried changing the Dockerfile to the following, but I get version conflicts when starting monstache (specifically: Unable to load mapper plugin ./tmp/plugin/plugin.so: plugin.Open("./tmp/plugin/plugin"): plugin was built with a different version of package github.com/olivere/elastic/uritemplates)

```
FROM rwynn/monstache-builder-cache:1.0.20 AS build-app

RUN mkdir /app

WORKDIR /app

COPY . .

RUN go mod download

ARG PLUGIN

WORKDIR /app/docker/plugin

RUN go mod init project

RUN go build -buildmode=plugin -o $PLUGIN.so
```

I'm guessing this is because the `go mod init project` command is overwriting the packages fetched by `go mod download` within build-app.

I have also tried copying the requirements in the go.mod file in the root of the monstache folder, but I still get version errors, such as "plugin was built with a different version of package errors"

**Comment by rwynn** [comment]
Hi @IchorPop, this seems to work ok for me for 6.0.8

```
diff --git a/docker/plugin/go.mod b/docker/plugin/go.mod
+module localmodule
+
+require (
+       github.com/olivere/elastic/v7 v7.0.0
+       github.com/rwynn/monstache v6.0.8
+       go.mongodb.org/mongo-driver v1.0.3
+)
+
+replace github.com/rwynn/monstache => /app

diff --git a/docker/plugin/localpackage/a.go b/docker/plugin/localpackage/a.go
+package localpackage
+
+func Hello() string {
+    return "Hello, "
+}

diff --git a/docker/plugin/localpackage/b.go b/docker/plugin/localpackage/b.go
+package localpackage
+
+func World() string {
+    return "World!"
+}

diff --git a/docker/plugin/plugin.go b/docker/plugin/plugin.go
+package main
+
+import (
+    "github.com/rwynn/monstache/monstachemap"
+    "localmodule/localpackage"
+)
+// a plugin to convert string document values to hello
+func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
+    doc := input.Document
+    for k, v := range doc {
+        switch v.(type) {
+        case string:
+            doc[k] = localpackage.Hello() + localpackage.World()
+        }
+    }
+    output = &monstachemap.MapperPluginOutput{Document: doc}
+    return
+}

```

Tested with

```
docker run --rm --net=host -v $(pwd)/docker-build:/tmp/plugin rwynn/monstache:6.0.8 -mapper-plugin-path /tmp/plugin/plugin.so
```

The key seems to be adding the `go.mod` and also adding the `replace` directive.  

Note, depending on which branch of monstache you are using you will need to target the corresponding version of monstache, eg. 6.0.8, 5.0.8, etc and the specific versions of the drivers in your go.mod.

**Comment by IchorPop** [comment]
I'm using version 4.17.2 to build the plugin (also using rwynn/monstache:4.17.2 in the docker run command). My go.mod file looks like this now

```
module project

require (
	github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8
	github.com/olivere/elastic v6.2.14
	github.com/rwynn/monstache v4.17.2
)

replace github.com/rwynn/monstache => /app
```

but I am still getting an error `Unable to load mapper plugin ./tmp/plugin/plugin.so: plugin.Open("./tmp/plugin/plugin"): plugin was built with a different version of package github.com/globalsign/mgo/internal/json`

**Comment by rwynn** [comment]
If using that version can you please try using the mgo and mgo replace from the go.mod here ...

https://github.com/rwynn/monstache/blob/v4.17.2/go.mod

**Comment by IchorPop** [comment]
Ah.. I didn't see the `replace github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8 => github.com/rwynn/mgo v0.0.0-20190318130802-4743670bc61d` at the end of the go.mod file. It working now! Thank you!

**Comment by rwynn** [comment]
No problem.  Glad you were able to get it working.

**Comment by IchorPop** [comment]
Hi @rwynn,

I'm currently on v6.2.5 and trying to upgrade to v6.4.1. I'm using the method you suggested above, with the extra line in `go.mod`

`replace github.com/rwynn/monstache => /app`

but when I run `build.sh` I'm getting the error

`/app/docker/plugin/go.mod:6: require github.com/rwynn/monstache: version "v6.4.1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6`

I tried with v6.3.2 and it seems that I get the same error message there as well.

**Comment by rwynn** [comment]
In recent go versions you may have to use the git commit hash with monstache.  Use the command `go get github.com/rwynn/monstache@de2ce024fb3e276ace0fdac10d34b4260db3bc3a` to update the go.mod file.  That is the commit hash for `v6.4.1`.

**Comment by rwynn** [comment]
You should also be able to do something like 

```
require (
	github.com/rwynn/monstache de2ce024fb3e
)
```

And then run `go mod tidy` to resolve it.

**Comment by IchorPop** [comment]
Thanks, that fixed the issue!
