### ISSUE TITLE
Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available

### ISSUE THREAD

**Issue by coppermine2019** [rwynn/monstache#250]
Hi,
Below is my elasticsearch https url. It works fine with curl but connection fails when using with monstache. The error message is **Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available**

elasticsearch-urls = ["https://myHttpsUrl:443/elasticsearch/"]

Please help.

**Comment by rwynn** [comment]
Monstache passes the URL given to this library. 

https://github.com/olivere/elastic

Maybe you can spot the problem there. I think it uses a HEAD request for the health check.

**Comment by coppermine2019** [comment]
Thanks for your reply.

A client uses a sniffing process to find all nodes of your cluster by default, automatically. you can disable it with the option elastic.SetSniff(false). 

How can set sniffing to false in monstache config file.

**Comment by rwynn** [comment]
Monstache always sets sniff to false with no option now to override. 

https://github.com/rwynn/monstache/blob/rel6/monstache.go#L468

So currently one needs to put all node url in elasticsearch-urls array.

**Comment by coppermine2019** [comment]
Is it possible to set Healthcheck to false.

elastic.SetHealthcheck(false);

Thanks.

**Comment by rwynn** [comment]
Yes, it is possible I know.  Your first comment was talking about Sniff not Healthcheck though.  They are separate client options.  

Monstache doesn't surface an option to set healthcheck to false, but you can simply checkout the code and add the line you referenced.  

Though healthcheck is just a HEAD request that looks for response code 200-299.  Does that work with curl for you on your ES proxy?

```
/vagrant/monstache$ curl -I localhost:9200
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 499
```

**Comment by coppermine2019** [comment]
curl -I localhost:9200
curl -I https://myHttpsUrl:443/elasticsearch/

Yes, both returned:

HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 501

Our haproxy routes elasticsearch requests (https://myHttpsUrl:443/elasticsearch/) to 9200 port.

I can't figure out why all curl calls work but I get "Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available"

Thanks.

**Comment by rwynn** [comment]
Any change if you put this in your config file?  Basically should turn off SSL cert validation on the connection.

```
elasticsearch-validate-pem-file = false
```

This would only apply if your ssl cert is not in root certificate pool.  But looks like you don't need the insecure flag on curl so shouldn't need this.

**Comment by rwynn** [comment]
That error comes from this part of the client:

https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1132

You could also try to increase the initial and subsequest health check timeouts.

```
elasticsearch-healthcheck-timeout-startup = 200
elasticsearch-healthcheck-timeout = 200
```

**Comment by coppermine2019** [comment]
Yes, tried with those three config parameters but got same error message.

elasticsearch-validate-pem-file = false
elasticsearch-healthcheck-timeout-startup = 200
elasticsearch-healthcheck-timeout = 200

Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available
Shutting down with exit status 1 after panic.

**Comment by rwynn** [comment]
I’m not sure what it could be. Maybe try the Golang client from olivere without Monstache involved and see if you can get that to work. Let me know if some change in Monstache is needed.

**Comment by coppermine2019** [comment]
If I do curl (with http)
curl -I http://myHttpsUrl/elasticsearch/
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://myHttpsUrl/elasticsearch/
Connection: close

health check timeout: no Elasticsearch node available

If I do curl (with http with port 443)
curl: (52) Empty reply from server
health check timeout: Head http://ws.mylearnerportal.com:443/elasticsearch: EOF: no Elasticsearch node available

I am guessing it it is using http instead of https. Is there a way to force to use https?

Thanks for your time.

**Comment by rwynn** [comment]
I think there is a SetScheme which Monstache does try to detect and use.

**Comment by coppermine2019** [comment]
At last I found the problem. 

slash at the end of my url https://myHttpsUrl/elasticsearch/. 

without slash (https://myHttpsUrl/elasticsearch) works fine.

https://github.com/olivere/elastic/commit/a80af35aa41856dc2c986204e2b64eab81ccac3a

Thanks.

**Comment by rwynn** [comment]
Glad you figured it out. I did not expect it to be that sensitive to an ending slash. I’ll add some caution to the docs about that.

**Comment by ahmadtanhaa** [comment]
Hi, @rwynn .
I have a similar problem while using Monstache. I did your proposed answers, however, I still encounter the following error:

**Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available**

I found that the problem is that I can not get Elastic to connect to an Elasticsearch node or cluster, however, I want to know can I fix it?!
In this way, I found [this link](https://github.com/olivere/elastic/wiki/Connection-Problems) which suggests some go codes.
My question is that where do I add those lines of code? To monstache.go file inside monstache directory?! I tried it and it didn't work.

**Comment by justintilson** [comment]
For me, fiddling with Elasticsearch permissions did the trick. In Kibana, go to: `/app/management/security/roles/`. Create/edit a role as needed.

I had to add `monitor` to the cluster privileges and `read`, `write`, `create_index`, and `monitor` for index permissions for the role that's associated with the user that Monstache is connecting with.

![elasticsearch-manage-users-5](https://github.com/rwynn/monstache/assets/1480031/cb70f57f-8dfd-442e-8b0f-a27ec484e39c)
