### ISSUE TITLE
ctrl + c not working: SIGINT and  SIGTSTP

### ISSUE THREAD

**Issue by pelletier197** [rwynn/monstache#253]
Basically, it doesn't seem possible to stop the application from running by doing a `CTRL + c` or suspend by doing s `CTRL + z`, so it's only possible to stop the process by killing it or by closing the terminal session. 

I tend to think that SIGINT and  SIGTSTP system callback are not implemented, but maybe that's just a problem on my machine.

**Comment by rwynn** [comment]
I’ve not had trouble as you describe. 

https://github.com/rwynn/monstache/blob/rel6/monstache.go#L2402

Can you put a debug statement and see what you find and let me know?

**Comment by rwynn** [comment]
Attaching a screen record of how it's working for me under linux.  
[Screencast 2019-07-10 20:08:20.zip](https://github.com/rwynn/monstache/files/3379840/Screencast.2019-07-10.20.08.20.zip)

**Comment by pelletier197** [comment]
I just checked and when I run it in local, I don't seem to get the problem. It's therefore probably a problem with my docker.

I'll close the issue, thank you for your fast reply !
