### ISSUE TITLE
Must the user have access to the admin database？

### ISSUE THREAD

**Issue by mowenlong** [rwynn/monstache#254]
The user can access the local database and business database, but not admin database. Can such users synchronize business databases? If so, why would the following errors occur?

INFO 2019/07/11 14:12:05 Started monstache version 5.0.9
INFO 2019/07/11 14:12:05 Successfully connected to MongoDB version 3.2.10
INFO 2019/07/11 14:12:05 Successfully connected to Elasticsearch version 6.8.1
INFO 2019/07/11 14:12:05 Listening for events
INFO 2019/07/11 14:12:05 Watching changes on the deployment
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin.
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin.
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin.
ERROR 2019/07/11 14:12:05 Error starting change stream. Will retry.: Invalid input namespace, admin

**Comment by rwynn** [comment]
MongoDB did not receive the change stream feature until version 3.6 and looks like you are before that. 

You will need to remove change-stream-namespaces and add

enable-oplog = true

Which enables older meteor style method of tailing the oplog collection directly.

**Comment by mowenlong** [comment]
I understand a little，Thank you

**Comment by mowenlong** [comment]
> MongoDB did not receive the change stream feature until version 3.6 and looks like you are before that.
> 
> You will need to remove change-stream-namespaces and add
> 
> enable-oplog = true
> 
> Which enables older meteor style method of tailing the oplog collection directly.

I understand a little，Thank you
