### ISSUE TITLE
Plugin issue with release 6?

### ISSUE THREAD

**Issue by Gamiot** [rwynn/monstache#255]
Hello,

I just started tested using Monstache I honestly think it is a fantastic piece of software. I stumbled upon an issue when creating a plugin with release 6. I tried to follow carefully the documentation, but Monstache end up with the following message :

"ERROR 2019/07/11 12:42:11 Unable to load mapper plugin /opt/plugin/plugin.so: plugin.Open("/opt/plugin/plugin"): plugin was built with a different version of package github.com/rwynn/monstache/monstachemap"

Keep in mind that it is my first experience with GoLang so they may be an obvious error that i do not see.

If anyone can help me out with this issue, this would be certainly appreciated!

**Reproduction steps**

1. From Windows 10, run monstache builder cache image (release 6)
```
docker run --rm -it -v C:\plugin\monstache:/opt/plugin rwynn/**monstache-builder-cache-rel6
```

2. Copy in the mounted volume the sample script (under the name plugin.go) provided in the documentation:
```
package main
import (
    "github.com/rwynn/monstache/monstachemap"
    "strings"
)
// a plugin to convert document values to uppercase
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
    doc := input.Document
    for k, v := range doc {
        switch v.(type) {
        case string:
            doc[k] = strings.ToUpper(v.(string))
        }
    }
    output = &monstachemap.MapperPluginOutput{Document: doc}
	return
}
```

3. Inside the container, clone Monstache Git repository in the /opt folder
```
/opt # git clone https://github.com/rwynn/monstache.git
Cloning into 'monstache'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 3293 (delta 64), reused 105 (delta 30), pack-reused 3153
Receiving objects: 100% (3293/3293), 842.42 KiB | 2.72 MiB/s, done.
Resolving deltas: 100% (1868/1868), done.
/opt # cd monstache
```

4. Checkout the release 6 branch and copy the plugin.go inside the Monstache root folder
```
/opt/monstache # git checkout rel6
Branch 'rel6' set up to track remote branch 'rel6' from 'origin'.
Switched to a new branch 'rel6'
/opt/monstache # cd ..
/opt # cd plugin
/opt/plugin # cp plugin.go ../monstache
```

5. Validate that the GO path is in a different location
```
/opt/monstache # env
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GOPATH=/go
GOLANG_VERSION=1.12.6
```

6.  Perform the Go installation in the Monstache root folder
```
/opt/monstache # go install
go: finding github.com/rwynn/gtm v0.0.0-20190709183103-9eb0bcfe66ed
go: downloading github.com/rwynn/gtm v0.0.0-20190709183103-9eb0bcfe66ed
go: extracting github.com/rwynn/gtm v0.0.0-20190709183103-9eb0bcfe66ed
```

7. Build the plugin and copy the plugin back to the mounted volume
```
/opt/monstache # go build -buildmode=plugin -o plugin.so plugin.go
cp plugin.so ../plugin
```
8. The mounted volume now contains both the plugin.go and the plugin,so files.  

9. The following docker-compose yml  was used to refer monstache release 6 with the plugin.

```
  dbsync:
   image: rwynn/monstache:rel6 
   entrypoint: monstache -mapper-plugin-path /opt/plugin/plugin.so -f /opt/config/config.toml
   volumes:
    - ../plugin/monstache:/opt/plugin
    - ./config/monstache:/opt/config
   networks:
      - esnet
```

10. The following Monstache configuration was used:
```
mongo-url = "mongodb://db:27017"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://elasticsearch:9200"]
```

11.  Run the container ended up with the following error
```
docker-compose up dbsync
Starting yml_dbsync_1_45f13a1d833c ... done
Attaching to yml_dbsync_1_45f13a1d833c
dbsync_1_45f13a1d833c | ERROR 2019/07/11 12:42:11 Unable to load mapper plugin /opt/plugin/plugin.so: plugin.Open("/opt/plugin/plugin"): plugin was built with a different version of package github.com/rwynn/monstache/monstachemap
yml_dbsync_1_45f13a1d833c exited with code 1
```

**Comment by rwynn** [comment]
Hi @Gamiot,

Thanks for trying monstache!

Go plugins are very particular about the loading binary and plugin shared lib being built from the same sources in the same directories even.  You may have run into a problem due to a new release that was made this morning and pushed to docker.  Anyway, this is a procedure I have had success with:

```sh
cd ~/build
git clone https://github.com/rwynn/monstache.git
cd monstache
# checkout a specific release of monstache to build against.  using latest here
git checkout v6.0.11
cd docker/plugin
# copy your plugin source code as plugin.go.  This file name can be changed in docker/plugin/.plugin file
cp ~/build/plugin.go .
# run build script that builds plugin in docker and outputs result plugin.so to docker-build folder
./build.sh
# test running against resulting plugin with same monstache version tag on docker hub as checkout
docker run --rm --net=host -v $(pwd)/docker-build:/tmp/plugin rwynn/monstache:6.0.11 -mapper-plugin-path /tmp/plugin/plugin.so
```

If this works and you want to move from a single plugin go file or add plugin dependencies from VCS then see this issue for guidance on how to do that.

https://github.com/rwynn/monstache/issues/246

**Comment by rwynn** [comment]
Forget to mention, since it seems you are doing this on windows you might try doing all the above steps in WSL, a linux VM, or maybe inside another docker container that lets you run the build.sh script.

**Comment by rwynn** [comment]
Another option would be to take the Dockerfile used to build each release that goes to Docker hub, and adapt it to also build your plugin and copy and bake the plugin.so into the resulting image like the binary.  

https://github.com/rwynn/monstache/blob/master/docker/release/Dockerfile

So add the build plugin command in stage 1.

```
RUN go build -buildmode=plugin -o $PLUGIN.so $PLUGIN.go
``` 

And copy the result like the binary in stage 2.  Then you have your own image with monstache+plugin.

**Comment by Gamiot** [comment]
Thanks you very much for the quick turn around! I was able to create and run the sample plugin using the procedure you provided. It seems that Golang is very (very) picky regarding version and naming. 

Is it a fair assumption that I could use **docker inspect** to retrieve the tag of the code used to build Monstache docker image? I would really like to use your official image from Docker Hub and need to ensure that i can retrieve the code reference easily.

```
docker pull rwynn/monstache:rel6
rel6: Pulling from rwynn/monstache
Digest: sha256:64f8fba2876067877f6f4b91c73b1881f51888a07d4936fbb0ed36049eadf5ee
Status: Downloaded newer image for rwynn/monstache:rel6

docker inspect rwynn/monstache:rel6
   "RepoTags": [
            "rwynn/monstache:6.0.11",
            "rwynn/monstache:rel6"
        ],
 "Labels": {
                "org.label-schema.build-date": "2019-07-11T13:17:57Z",
                "org.label-schema.schema-version": "6.0.11",
                "org.label-schema.vcs-ref": "3c38f7f",
                "org.label-schema.vcs-url": "https://github.com/rwynn/monstache"
            }
```
Is there a way to retrieve to appropriate version of the builder cache used as well? If not, i could suggest adding a label in the image to help retrieve the appropriate version for the cache builder.

I will continue investigate why the procedure i used was not working and close this issue afterward. I may found something that would help the developers like me that works on Windows to build the plugin.

**Comment by rwynn** [comment]
That’s a good suggestion about adding the builder tag. I think for now you can figure out which builder image was used by checking out the specific monstache release tag in git and then examining the Dockerbuild file under docker/release.

**Comment by rwynn** [comment]
Also, if you want to use the images released to docker hub, I think you could use the last procedure I mentioned to create the binary+plugin, but then copy just the plugin out of the docker image to the host.  I think it should still work when paired with rwynn/monstache on docker hub (haven't tried).

https://stackoverflow.com/questions/25292198/docker-how-can-i-copy-a-file-from-an-image-to-a-host

This make be a little cumbersome but maybe not if you scripted it all.

**Comment by rwynn** [comment]
I reviewed your original steps and have an idea that might work using those steps with a small change. 

If you notice in the following Dockerfile the build is done in /app

https://github.com/rwynn/monstache/blob/rel6/docker/release/Dockerfile

You clone Monstache to /opt in your steps. You might just try /app to match.  

Also just to be safe you might always checkout a release tag instead of a branch. And use the same docker release tag in your compose file.

**Comment by Gamiot** [comment]
Hello Rwynn,

I think you have nailed it! After trying different scenarios, I came to the conclusion as well that the /app path is required 

For the benefit of the others, please found below the updated procedure to build GoLang plugin on Windows 10. 

1. Retrieve the git source branch by inspecting the Docker image. 
```
docker inspect rwynn/monstache:rel6
"RepoTags": [
            "rwynn/monstache:6.0.11",
            "rwynn/monstache:rel6"
        ],
```
2. Retrieve for GitHub the builder-cache version
```
https://github.com/rwynn/monstache/blob/v6.0.11/docker/plugin/Dockerfile
FROM rwynn/monstache-builder-cache-rel6:1.0.1 AS build-app
```
3. Run the builder-cache image with a volume mounted containing your script (plugin.go)
```
docker run --rm -it -v C:\git\plugin\monstache:/opt/plugin rwynn/monstache-builder-cache-rel6:1.0.1
```

4. Checkout the code in the /app folder. 
```
 cd /
/ # git clone https://github.com/rwynn/monstache.git app
Cloning into 'app'...
/ # cd app
/app # git checkout v6.0.11
```

5. Copy the plugin.go in the /app/docker/plugin folder and run go mod download in /app and 
/app/docker/plugin location.
```
/app # cp /opt/plugin/plugin.go /app/docker/plugin
/app # go mod download
go: finding github.com/rwynn/gtm v0.0.0-20190709183103-9eb0bcfe66ed
/app # cd docker/plugin
/app/docker/plugin # go mod download
```

6.  Create the plugin.so and copy it in the mounted volume.
```
go build -buildmode=plugin -o plugin.so plugin.go
/app/docker/plugin # cp plugin.so /opt/plugin
```

7. Run the Monstache container (docker-compose yml is the same). The 
```
docker-compose up dbsync
Attaching to yml_dbsync_1_61b72e2f1ef0
dbsync_1_61b72e2f1ef0 | INFO 2019/07/15 14:14:20 Started monstache version 6.0.11
dbsync_1_61b72e2f1ef0 | INFO 2019/07/15 14:14:20 Successfully connected to MongoDB version 4.1.13
dbsync_1_61b72e2f1ef0 | INFO 2019/07/15 14:14:20 Successfully connected to Elasticsearch version 7.0.1
dbsync_1_61b72e2f1ef0 | INFO 2019/07/15 14:14:20 Listening for events
dbsync_1_61b72e2f1ef0 | INFO 2019/07/15 14:14:20 Watching changes on the deployment
```

Your plugin should work as intended.
