### ISSUE TITLE
changestream issue with mongo 3.6 and elasticsearch 6.2.2 using monstache:rel5

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#258]
Hi 

Any idea that why I will be getting following error ?

ERROR 2019/07/13 11:57:47 Error starting change stream. Will retry.: (Location40585) resume of change stream was not possible, as the resume token was not found. 

In my config resume = false.
Also randomly i see errors like elasticsearch node is dead or mongo times out though all are up.

**Comment by rwynn** [comment]
Please post a sanitized copy of your config file and the initial output from monstache when it starts up.

**Comment by richiarora** [comment]
hi following is the config file:
elasticsearch-healthcheck-timeout-startup=30
elasticsearch-healthcheck-timeout=10
verbose = true
stats = false
index-stats = false
resume-write-unsafe = false
exit-after-direct-reads = false
elasticsearch-retry = true
change-stream-namespaces = ["db.col1"]
[logs]
info = "info.out"
warn = "warn.out"
error = "error.out"
[[mapping]]
namespace = "db.col1"
index = "idx-db-dol1"
type = "_doc"

Currently, it is working fine since I had removed the container and started a new one.

If i get same error again i will share.

**Comment by rwynn** [comment]
One suggestion if using docker is to set the MONSTACHE_LOG_DIR env variable instead of putting log config in the file.  Then create a docker volume and map the log dir to that volume.

**Comment by rwynn** [comment]
@richiarora do you still see this issue with the latest release?

**Comment by richiarora** [comment]
@rwynn 
All good till now. Not facing counts issue.
