### ISSUE TITLE
NumberDecimal(Decimal128) support

### ISSUE THREAD

**Issue by nllahat** [rwynn/monstache#259]
Hi @rwynn and everyone (:

Is there anybody who tried to sync documents with NumberDecimal field type ?
I'm getting empty objects in ES and I don't know how to fix this issue.

Thanks!

**Comment by rwynn** [comment]
I think this is because the MongoDB go driver does not implement `MarshalJSON` for the `primitive.Decimal128` type.  

https://github.com/mongodb/mongo-go-driver/blob/master/bson/primitive/decimal.go

I am able to add a wrapper in monstache that seems to work though.  This needs to handle some special cases since some values are not valid in JSON.  

```
func (dec Decimal128) MarshalJSON() ([]byte, error) {
	encoded := dec.String()
    if encoded == "NaN" || strings.HasPrefix(encoded, "-Inf") || strings.HasPrefix(encoded, "Inf") {
        return []byte("null"), nil
    }
    return []byte(encoded), nil
}

```

**Comment by rwynn** [comment]
@nllahat this should be fixed now in the latest release.  Please reopen if you have problems.

**Comment by nllahat** [comment]
Hi @rwynn,

Thanks for the quick fix. I'm using the master version (4.17.7) so I added your fix to my cloned repository and build monstache from source and now I get this error:

`ERROR 2019/08/11 10:08:32 Bulk response item: {"_index":"some-index","_type":"_doc","_id":"5ad35a258429d322480545bc","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [balance.amount] of type [long] in document with id '5ad35a258429d322480545bc'","caused_by":{"reason":"Numeric value (123456789012345678012) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4ad8a2cd; line: 1, column: 408]","type":"json_parse_exception"}}}`

any idea ?

**Comment by nllahat** [comment]
Ok. my mistake. My mappings were wrong.
