### ISSUE TITLE
High CPU on Mongo

### ISSUE THREAD

**Issue by tranztec** [rwynn/monstache#260]
We have two monstache processes running against our production MongoDB.   One is running change stream against a collection with 18M documents and the other is running change stream against 6 collections with limited document counts.

The back fill of all collections was completed earlier in the week and we started the change stream monitoring on friday afternoon.   We've noticed much higher CPU % on the mongo server since that time.   We're having to run against the primary mongo node due to our previous cursor issue (trying to get our mongo provider to resolve that still), so this high CPU is not good for our overall performance.    Is there anything in the monstache configuration that might be causing this?

![2019-07-15_8-38-11](https://user-images.githubusercontent.com/389954/61217054-e5cdda80-a6dc-11e9-9cbe-aae232c32f5d.jpg)
![2019-07-15_8-42-44](https://user-images.githubusercontent.com/389954/61217067-ebc3bb80-a6dc-11e9-9f07-9138f05c90e6.jpg)

**Comment by rwynn** [comment]
I'm assuming you removed the direct reads you have previously set to do the back fill?

What does the following command show you?  

```
db.currentOp({appName:"monstache"});
```

If you removed the direct reads from before then that should show only change stream queries.  What the the `secs_running` on those?

**Comment by tranztec** [comment]
Had absolutely NOTHING to do with monstache.   It was a coincidence -- shutting down monstache completely did not reduce the CPU load.   We found the issue and resolved it.
