### ISSUE TITLE
Data incomplete synchronization

### ISSUE THREAD

**Issue by mowenlong** [rwynn/monstache#261]
Synchronize more than 10 million data
Es database has tens of thousands more data than mongodb database

Mongodb:
ReplSetHO: PRIMARY > db. paper. count ()
15017242
ES:
health status index            uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   papercheck.paper DoFu6AM-QIeI8kcc6d87uw   5   1   15072000            0      5.8gb          5.8gb

Config:
Namespace-regex ='^ papercheck. paper$'
Direct-read-namespaces = ["papercheck. paper"]
Reply = false
Index-as-update = true

**Comment by rwynn** [comment]
Delete the Elastic index and reindex. Keep monstache running with direct-read-namespace, resume on, replay off. It should keep in sync even with deletes in Mongodb.

**Comment by rwynn** [comment]
Also ensure that create / update / delete events are being synced. Previously you mentioned you had MongoDB version < 3.6. In this case you need special config and user must be able to access “local” database.  enable-oplog on.

**Comment by mowenlong** [comment]
> Also ensure that create / update / delete events are being synced. Previously you mentioned you had MongoDB version < 3.6. In this case you need special config and user must be able to access “local” database. enable-oplog on.

I use the  monstache version is 4.17.5, use enable-oplog on it will work?

**Comment by rwynn** [comment]
`enable-oplog` is only needed on monstache 5 or 6.  So you don't need it.  Just make sure your delete events are getting synced since you have more docs in Elastic than MongoDB.

**Comment by mowenlong** [comment]
> `enable-oplog` is only needed on monstache 5 or 6. So you don't need it. Just make sure your delete events are getting synced since you have more docs in Elastic than MongoDB.

when the data synces from es to MongoDB end the work,  although more docs in Elastic than MongoDB, but when i delete document in MongoDB, and the delete event will synced to Elastic .

**Comment by rwynn** [comment]
index-as-update is not good for data integrity as it does not send version number. If delete happens in MongoDb soon after update, it is possible delete command gets sent to Elastic before the update. This would result in less docs in MongoDB than Elastic. That is why index-as-update is not the default.  

With version number the update would be rejected by Elastic because it would be less than the version number of the delete.  This is the version conflict error. It is for data integrity.

**Comment by mowenlong** [comment]
I did not delete event, Actually I imported 10 million data into the MongoDB database(The content is the same)，not delete event,not update event.but after synced end, more docs in Elastic than MongoDB(About 40,000 docs),so What parameters should I set?

**Comment by rwynn** [comment]
If you can provide me some way to recreate it I will take a look. I’ve not seen more docs in Elastic than MongoDB unless delete is involved. I’m not sure how it could happen since _id field in MongoDB is reused in Elasticsearch.

**Comment by mowenlong** [comment]
hhh
Now synchronize production environments
Complete Synchronization！
Thank！
I don't know there's a problem with the data I created before.

**Comment by rwynn** [comment]
@mowenlong please reopen with a test case I can use to recreate this issue if you encounter it again.  Thanks.
