### ISSUE TITLE
tried to parse field

### ISSUE THREAD

**Issue by mowenlong** [rwynn/monstache#264]
ERROR 2019/07/22 09:52:37 Bulk response item: {"_index":"ksodcapiapp.job","_type":"_doc","_id":"5d3516cdb07eb8179e9830dd","status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [result.files.previewfiles] tried to parse field [null] as object, but found a concrete value"}}
ERROR 2019/07/22 09:52:40 Bulk response item: {"_index":"ksodcapiapp.job","_type":"_doc","_id":"5d3516cdb07eb8179e9830dd","status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [result.files.previewfiles] tried to parse field [null] as object, but found a concrete value"}}
ERROR 2019/07/22 09:52:40 Bulk response item: {"_index":"ksodcapiapp.job","_type":"_doc","_id":"5d3516cdb07eb8179e9830dd","status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [result.files.previewfiles] tried to parse field [null] as object, but found a concrete value"}}

Do I need a custom es index?
Or by monstache automatic Generation,but why this kind of mistake will happen?Thanks.

**Comment by rwynn** [comment]
This will happen independent of monstache. It just means that one time you indexed a field as an object and another time same field was not an object. MongoDB will let you do this. But, Elasticsearch doesn’t accept this difference. 

You might need to make all input data share the same data types.  One option is to mutate your docs in a Monstache script.

**Comment by mowenlong** [comment]
i see

**Comment by mowenlong** [comment]
A strange phenomenon has been discovered.
when i set direct-read-namespaces = ["translation.job"], and before appears `Direct reads completed` in screen.
When an error occurs:
`_ERROR 2019/07/25 10:10:52 Bulk response item: {"_index":"translation.job","_type":"_doc","_id":"5d390fa1c905431118754fda","status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [result.files] tried to parse field [files] as object, but found a concrete value"}}_`
and the document don't synchronize to es,In other words，This record cannot be queried in ES

But  after appears `Direct reads completed` in screen.When the same error occurs，this document will 
synchronize to es, and will set field is null.

When this error occurs, it will synchronize to es,although field is null. How to set it up?

**Comment by rwynn** [comment]
The completed message just indicates that all docs have been read into memory from MongoDB. The indexing is asynchronous and will occur after this message.

**Comment by mowenlong** [comment]
When this error occurs, can this document synchronize to es？This document can be queried in es. The conflicting fields are set to null.

**Comment by rwynn** [comment]
I think you can let the document succeed with some settings on your index. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html

Monstache does do anything in this regard. It simply sends the data in MongoDB or what you map said data to in a plugin.
