### ISSUE TITLE
 every time start monstache will copy all mongodb collection to es?

### ISSUE THREAD

**Issue by mowenlong** [rwynn/monstache#265]
monstache complete synchronization  50 million documents from mongodb to es.  It took several hours.
now i stop the monstache, and mongodb will continue to produce new documents.i start monstache again after a few minute .
Does this synchronize data on a previous basis?In other words，Will it still take several hours?

**Comment by mowenlong** [comment]
Because sometimes I need to close monstache,but mongodb too much data.
Every synchronization takes a lot of time after monstache restart.And it costs a lot of CPU and memory.
Can you just synchronize es without synchronization yet?
Once synchronized, you don't have to resynchronize

**Comment by rwynn** [comment]
If you ran Monstache with resume enabled the first time then you simply need to restart it after making one change: remove direct-read-namespaces. 

It should lookup the timestamp from previous run and start a new change stream using that timestamp.

**Comment by mowenlong** [comment]
but i set resume = false when run Monstache at first time ,can Is there any other way to set it up?

**Comment by rwynn** [comment]
If you find a timestamp from the oplog (local.oplog.rs) you can use -resume-from-timestamp with that value. 

It takes the timestamp as a 64 bit integer where high 32 bits are seconds since epoch.
