### ISSUE TITLE
Upgrading to 3.x results in broken ES client

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#27]
Hi @rwynn 

We attempted to upgrade to `3.0.6` and ended up with problems connecting to our three node ES cluster (5.2.2 with TLS using Search Guard SSL). The error output is:

```
root@tf-elasticsearch-20170619-0:~# monstache -f /usr/local/etc/monstache_config_preview.toml 
ERROR 2017/06/21 14:12:40 Unable to create elasticsearch client: no Elasticsearch node available
panic: Unable to create elasticsearch client: no Elasticsearch node available

goroutine 1 [running]:
log.(*Logger).Panicf(0xc42004eaf0, 0xd14431, 0x29, 0xc420529d40, 0x1, 0x1)
        /usr/local/go/src/log/log.go:215 +0xdb
main.main()
        /home/vagrant/go/src/github.com/rwynn/monstache/monstache.go:1384 +0x47c
```

I then tried the last `2.x` release which uses the old Go client, this worked perfectly, then stepped forward to the `3.0.0` release and was met with the same error output as above. So there is something relating to the new Elasticsearch client that doesn't like our setup, or config file perhaps.

Config:
```
mongo-url = "mongodb://XXXXXX:XXXXXX@10.128.0.7:27017,10.128.0.8:27017,10.128.0.9:27017/?authSource=admin&replicaSet=RS-Test-0"
mongo-pem-file = "/mongodb-test-rs.pem"
mongo-validate-pem-file = false
elasticsearch-url = "https://es0:9200"
elasticsearch-pem-file = "/etc/elasticsearch/root-ca/root-ca.pem"
cluster-name = "test-20170619"
replay = false
resume = true
resume-name = "test-20170619"
namespace-regex = "^testing.testdata$"
gtm-channel-size = 512
gzip = true
stats = true
elasticsearch-retry = true
dropped-databases = false
dropped-collections = false
verbose = true
```

The above config works fine with `2.14.0`, I assume it ignores any new options. Tried the ES URI as a string like above and also an array of strings with each node listed. Turned on/off gzip, stats etc. etc.

Ran out of ideas at the moment, I did hunt down this which seems similar to the error received: https://github.com/olivere/elastic/issues/312

**Comment by Crispy1975** [comment]
Also on investigating the ES logs we see the following:
```
[2017-06-21T13:55:39,970][WARN ][c.f.s.s.h.n.SearchGuardSSLNettyHttpServerTransport] [3rZ6PTp] Someone (/127.0.0.1:45334) speaks http plaintext instead of ssl, will close the channel
```
I think that shows that the issue is the new `Elastic` Go driver not communicating with an TLS enabled cluster.

**Comment by rwynn** [comment]
@Crispy1975, check the new client options in 3.0.  Mostly the same but elasticsearch url config is changed to accomodate golang driver change in monstache.

https://rwynn.github.io/monstache-site/options/#elasticsearch-urls

**Comment by Crispy1975** [comment]
No dice. I had already tried setting the URLs to an array, but did it again to be sure I hadn't made a mistake, this is what I have: 
```
elasticsearch-url = [ "https://es0:9200", "https://es1:9200", "https://es2:9200" ]
```
The hosts are in the `/etc/hosts` on the box `monstache` is running from and I've checked connectivity, can also `curl` ES no problem. So network is up and fine, but still getting the same error.

I also compiled a version with sniffing set the `true` and that also resulted in the error, this still looks related to the TLS transport, as watching the ES logs I see `monstache` making contact over the network, **but** as per the error below ES thinks it's communicating in plain text and not SSL.
```
[2017-06-22T09:02:41,193][WARN ][c.f.s.s.h.n.SearchGuardSSLNettyHttpServerTransport] [3rZ6PTp] Someone (/127.0.0.1:52316) speaks http plaintext instead of ssl, will close the channel
```
It says `127.0.0.1` as I am testing this actually **on** one of the ES nodes.

**Comment by rwynn** [comment]
Can you try adding the s to the end of elastic-url in config? So elastic-urls.

**Comment by Crispy1975** [comment]
```
ERROR 2017/06/22 14:07:07 elastic: http://10.128.3.1:9200 is dead
ERROR 2017/06/22 14:07:07 elastic: http://10.128.3.2:9200 is dead
ERROR 2017/06/22 14:07:07 elastic: http://10.128.3.3:9200 is dead
ERROR 2017/06/22 14:07:07 Unable to create elasticsearch client: no active connection found: no Elasticsearch node available
panic: Unable to create elasticsearch client: no active connection found: no Elasticsearch node available

goroutine 1 [running]:
log.(*Logger).Panicf(0xc420016c80, 0xd27181, 0x29, 0xc420529d40, 0x1, 0x1)
        /usr/local/go/src/log/log.go:215 +0xdb
main.main()
        /home/crispy/godev/src/github.com/rwynn/monstache/monstache.go:1423 +0x47c
```

**Comment by rwynn** [comment]
Looks like the driver does not auto detect the scheme. Can you do a local build of Monstache and set the scheme on the Client to https?
https://github.com/olivere/elastic/blob/release-branch.v5/client.go

**Comment by rwynn** [comment]
Also try reverting the sniff enable you changed

**Comment by Crispy1975** [comment]
@rwynn perfect, that build with the client set to `https` is working for us (also reverted the sniffing change). Will put the build through it's paces in our staging environments and see how things go under load there. :+1:

**Comment by rwynn** [comment]
@Crispy1975, just pushed a new release to fix the `https` scheme problem.  Please let me know if you find any issues with this release.

**Comment by Crispy1975** [comment]
@rwynn thanks, well test it first thing in the morning and feed back.

**Comment by rwynn** [comment]
@Crispy1975, is it OK if I close this issue?  Any improvements under load from 3.x?

**Comment by Crispy1975** [comment]
@rwynn yes I believe we are seeing improvements. We have also upgraded our infrastructure that MongoDB is running on which gives a boost but I think we are seeing better throughput from `monstache` also. All good. :tada:
