### ISSUE TITLE
Regex in direct read namespaces

### ISSUE THREAD

**Issue by chaitanyanettem** [rwynn/monstache#270]
Hi, we have dynamically created collections in each mongo database. 

I see that it is possible to have a regex when listening to oplog changes via `namespace-regex`. Is it possible to also get regex support in `direct-read-namespaces` for initially seeding an Elasticsearch index?

**Comment by rwynn** [comment]
Use direct-read-dynamic-exclude-regex and set direct-read-namespaces to [“”].

**Comment by chaitanyanettem** [comment]
this is good. thanks!
