### ISSUE TITLE
ReplicasetNoPrimary on Single node Replica

### ISSUE THREAD

**Issue by thilagaCloud** [rwynn/monstache#271]

**Comment by thilagaCloud** [comment]
Hi,
I have successfully installed monstache 6.0.12 and able to get the ChangeStreams(CS) into Elastic Search 7.2.0 from MongoDB 4.2.0-rc5 in  THREE NODEs Replicaset environment thru running **monstache.go** file. 
Now I am trying to create SINGLENODE Replicaset (I mean only one ubuntu node instead of 3 nodes). If i try to connect this newly created node , then it gives error as "current topology: Type: ReplicaSetNoPrimary".

Note:
1) I have converted Standalone node into Replicaset as instructed by https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/. 
2) Please find the attached rs.status() of **mongo** shell. It shows the single node is PRIMARY.
[rsStatus.txt](https://github.com/rwynn/monstache/files/3492199/rsStatus.txt)
3) My connectionString in the **monstache.go** file is 
const mongoURLDefault string = "mongodb://user:password@IPAddress:27017/?Replicaset=RepSet1&authSource=admin"
4) ES is running on http://localhost:9200.
5)Without monstache, I just made sure that Changestream thru **nodejs** in WATCH method. I am able to fetch CS there. Hence, there is no issue on Change Stream with this Single node replica. 

Please confirm me that monstache supports SINGLE NODE REPLICA, if so, what needs to be done. Thanks in Advance!

**Comment by rwynn** [comment]
It does support that. I use it all the time for testing. 

I just add a repl set name in Mongo config and then call rs.initiate() and then the console reports primary and I can begin using Monstache.

**Comment by rwynn** [comment]
Are the monstache and nodejs using same exact connection string and run from same host?

**Comment by thilagaCloud** [comment]
Thanks for the quick response Rwynn. Yes, i am using same exact connection string in both NODEJS as well as MONSTACHE and  both are running on the same host.

Anything to be changed in CONFIG side apart from connection string to support this?

**Comment by rwynn** [comment]
It should not require any special tricks. The following test is run via docker with every check in. And you can see that it only uses a one node replica set. 

https://github.com/rwynn/monstache/tree/rel6/docker/test

The config in this case is very simple in that it only requires the mongo connection string with user credentials.

**Comment by rwynn** [comment]
Check the members array in the `rs.status()` output and make sure when you connect that your connection string references same hostname and port from the `name` field in command output.  I noticed port in your uploaded rsStatus.txt was 29017. But your connection string uses IP and different port 27017.  

This is what my rs.status() output looks like.  

```
"members" : [
                {
                        "_id" : 0,
                        "name" : "127.0.0.1:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                       ....
                }
        ],

```

**Comment by thilagaCloud** [comment]
Sorry it was a typo mistake while raising the issue. Please find here the connection string which i copied from my monstache.go file.

**const mongoURLDefault string = "mongodb://xxxxx:Xxxxxx@ActualIP:29017/?Replicaset=RepSet1&authSource=admin"**

Is there anything related to the change in default port?

**Comment by rwynn** [comment]
Have you tried using the logical hostname instead of IP in the connection string?  

You also may want to see if you can replicate with a simple go program that uses the mongodb go driver version 1.0.4   See if you can open a change stream with it. It may be something you can report to MongoDB.

**Comment by rwynn** [comment]
Here is a simple go program you can use to test the driver independent of monstache:

test.go
```golang
package main

import (
	"context"
	"flag"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"log"
)

type ChangeDocNs struct {
	Database   string "db"
	Collection string "coll"
}
type ChangeDoc struct {
	DocKey            map[string]interface{} "documentKey"
	Id                interface{}            "_id"
	Operation         string                 "operationType"
	FullDoc           map[string]interface{} "fullDocument"
	Namespace         ChangeDocNs            "ns"
	Timestamp         primitive.Timestamp    "clusterTime"
	UpdateDescription map[string]interface{} "updateDescription"
}

func main() {
	changes := 0
	var mongoURL string
	flag.StringVar(&mongoURL, "url", "mongodb://localhost:27017", "MongoDB connection URL")
	flag.Parse()
	log.Printf("Connecting to MongoDB at %s", mongoURL)
	client, err := mongo.NewClient(options.Client().ApplyURI(mongoURL))
	if err != nil {
		log.Fatalln(err)
	}
	if err = client.Connect(context.Background()); err != nil {
		log.Fatalln(err)
	}
	defer client.Disconnect(context.Background())
	for {
		var pipe []interface{}
		opts := options.ChangeStream()
		opts.SetFullDocument(options.UpdateLookup)
		stream, err := client.Watch(context.Background(), pipe, opts)
		if err != nil {
			log.Fatalln(err)
		}
		log.Println("Waiting for changes")
		for stream.Next(context.Background()) {
			var changeDoc ChangeDoc
			if err = stream.Decode(&changeDoc); err != nil {
				log.Fatalln(err)
			}
			changes++
			log.Printf("%d changes received", changes)
		}
		stream.Close(context.Background())
	}
}
```

You can run via 

```
go run test.go -url "mongodb://xxxxx:Xxxxxx@host:29017"
```

If you get it to work then supply same URL string to monstache and try that.

**Comment by thilagaCloud** [comment]
Hi RWYNN,
When i tried installing monstache on the same server where mongodb installed, is working now. Please Close this ticket. Thanks for the coordination.

Regards,
ThilagaDas
