### ISSUE TITLE
Error while syncing full collection

### ISSUE THREAD

**Issue by sbnajardhane** [rwynn/monstache#277]
@rwynn 
Yesterday, there were lots of bulk updates (6-7 different bulk operations) on the same set of users(around 800k) in a short period of time. So the monstache plugin got stopped and started throwing an error
```ERROR 2019/09/10 17:19:52 Error tailing oplog entries: read tcp monstache-machine-ip:57321->mongo-primary-ip:27017: i/o timeout
ERROR 2019/09/10 17:20:10 Error tailing oplog entries: read tcp monstache-machine-ip:57796->mongo-primary-ip:27017: i/o timeout
ERROR 2019/09/10 17:20:22 Error tailing oplog entries: read tcp monstache-machine-ip:58227->mongo-primary-ip:27017: i/o timeout
ERROR 2019/09/10 17:20:34 Error tailing oplog entries: read tcp monstache-machine-ip:58755->mongo-primary-ip:27017: i/o timeout
```
So we have modified the mongo timeout setting **from**
```
# Oplog read operation timeout setting.
[mongo-dial-settings]
timeout=15
read-timeout=7
write-timeout=7

[mongo-session-settings]
socket-timeout=0
sync-timeout=7
```
To this 
```
# Oplog read operation timeout setting.
[mongo-dial-settings]
timeout=15
read-timeout=30
write-timeout=30

[mongo-session-settings]
socket-timeout=0
sync-timeout=30
```
 And it worked. 

Now, in order to restore the data from last sync timestamp, we have decided to go for full sync instead of reading from the oplog(as it might be so huge, 800k * 7 approximately)
But when we started to the plugin in full sync mode, it got restarted multiple times. Few chunks from info.log
```
INFO 2019/09/11 15:32:07 Pausing work for cluster HA
INFO 2019/09/11 15:32:09 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:32:09 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:32:17 Resuming work for cluster HA
INFO 2019/09/11 15:32:24 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:32:24 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:32:39 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:32:39 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:32:54 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:32:54 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:33:09 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:33:09 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:33:10 Pausing work for cluster HA
INFO 2019/09/11 15:33:11 Started monstache version 4.11.3
INFO 2019/09/11 15:33:11 Successfully connected to MongoDB version 3.2.22
INFO 2019/09/11 15:33:11 Successfully connected to Elasticsearch version 6.3.1
INFO 2019/09/11 15:33:11 Joined cluster HA
INFO 2019/09/11 15:33:11 Starting work for cluster HA
INFO 2019/09/11 15:33:11 Listening for events
INFO 2019/09/11 15:33:11 Sending systemd READY=1
INFO 2019/09/11 15:33:11 READY=1 successfully sent to systemd
INFO 2019/09/11 15:33:11 Sending systemd WATCHDOG=1
INFO 2019/09/11 15:33:11 WATCHDOG=1 successfully sent to systemd
INFO 2019/09/11 15:33:26 Sending systemd WATCHDOG=1
```
the plugin got started multiple times. After few updated, only the deleted doc count is getting updated in elasticsearch. So we have stopped the sync in between. Also noticed that plugin is getting paused and resume in between. Observed this few days ago as well.
So could please help us figure out why this might be happening.

Here is the config file for your reference:
```mongo-url = "mongo-primary-url:27017"
elasticsearch-urls = ["es-url"]
namespace-regex = 'db.user'
direct-read-namespaces = ['db.user']   # enabled this for during sync
exit-after-direct-reads = true                 # enabled this for during sync
gzip = true
index-as-update = false
fail-fast = false
elasticsearch-retry = true
prune-invalid-json = true
index-oplog-time = true
resume = true
cluster-name = "HA"
resume-name = "HA"

[logs]
info = "/mnt/monstache/logs/info.log"
warn = "/mnt/monstache/logs/warn.log"
error = "/mnt/monstache/logs/error.log"
trace = "/mnt/monstache/logs/trace.log"
stats = "/mnt/monstache/logs/stats.log"

[mongo-dial-settings]
timeout=15
read-timeout=7
write-timeout=7

[mongo-session-settings]
socket-timeout=0
sync-timeout=7

[[mapping]]
namespace = "db.user"
index = "user"
type = "_doc"
```

**Comment by rwynn** [comment]
Looks like you are using systemd to manage restarts of monstache if it stops? Do you have a section like below in your systemd config?  What is the WatchdogSec?  Systemd may be restarting it.

```
[Service]
Type=notify
ExecStart=/usr/local/bin/monstache -f /etc/monstache/config.toml
WatchdogSec=30s
Restart=always
```

You also have the cluster mode enabled.  That would be a reason for pausing/resuming logs.  Can you try without the following line

```
cluster-name = "HA"
``

**Comment by rwynn** [comment]
Also, if you have this set

```
exit-after-direct-reads = true  
```

Then I don't think you would want the process managed by systemd since monstache would exit itself and then get restarted by systemd and new direct reads started over again.

**Comment by sbnajardhane** [comment]
Yes

> Looks like you are using systemd to manage restarts of monstache if it stops? Do you have a section like below in your systemd config? What is the WatchdogSec? Systemd may be restarting it.
> 
> ```
> [Service]
> Type=notify
> ExecStart=/usr/local/bin/monstache -f /etc/monstache/config.toml
> WatchdogSec=30s
> Restart=always
> ```
> 
> You also have the cluster mode enabled. That would be a reason for pausing/resuming logs. Can you try without the following line
> 
> ```
> cluster-name = "HA"
> ```

Yes, the systemd has restared the plugin multiple time. By creating a separate systemd file it worked (y)

**Comment by sbnajardhane** [comment]
> You also have the cluster mode enabled. That would be a reason for pausing/resuming logs. Can you try without the following line
> 
> ```
> cluster-name = "HA"
> ```

Also, you have mentioned about the pausing/resuming log. So by removing `cluster-name' config, I won't be able to run the multiple processes to ensure High Availability mode. In case one of the process goes down another should start syncing the data, Right? Here my concern is that Pausing and resuming is normal when we have enabled the cluster mode. As from the code, I can see the line bulk.Stop(). Assuming it might be stopping some bulk operation. 
```
....
} else {
			infoLog.Printf("Pausing work for cluster %s", config.ClusterName)
			bulk.Stop()  // This line
			for range heartBeat.C {
				enabled, err = enableProcess(mongo, config)
				if enabled {
					infoLog.Printf("Resuming work for cluster %s", config.ClusterName)
					bulk.Start(context.Background())
					break
				}
			}
		}
....
```

**Comment by rwynn** [comment]
`bulk.Stop()` will cause a [flush](https://github.com/olivere/elastic/blob/v6.2.23/bulk_processor.go#L491) of all the buffered documents for each worker.  

Monstache shouldn't be quickly going back and forth between enabled and disabled in cluster mode though.  If that is the case something is wrong.   The active process should be extending the life of it lease by periodically updating the `monstache.cluster` collection with a new timestamp, thus preventing other processes from taking over.

**Comment by sbnajardhane** [comment]
Also, I have observed this behavior few days back. I haven't got any such log before. Now it looks like it is going back and forth every minute. monstache.cluster collection is getting updated every minute. Is it failing to write to the cluster collection after taking over from other processes?
```
INFO 2019/09/13 11:31:06 Pausing work for cluster HA
INFO 2019/09/13 11:32:06 Resuming work for cluster HA
INFO 2019/09/13 11:33:06 Pausing work for cluster HA
INFO 2019/09/13 11:34:06 Resuming work for cluster HA
INFO 2019/09/13 11:35:06 Pausing work for cluster HA
INFO 2019/09/13 11:36:06 Resuming work for cluster HA
INFO 2019/09/13 11:37:06 Pausing work for cluster HA
INFO 2019/09/13 11:38:06 Resuming work for cluster HA
INFO 2019/09/13 11:39:06 Pausing work for cluster HA
INFO 2019/09/13 11:40:06 Resuming work for cluster HA
INFO 2019/09/13 11:41:06 Pausing work for cluster HA
INFO 2019/09/13 11:42:06 Resuming work for cluster HA
INFO 2019/09/13 11:43:06 Pausing work for cluster HA
INFO 2019/09/13 11:44:06 Resuming work for cluster HA
INFO 2019/09/13 11:45:06 Pausing work for cluster HA
```

**Comment by rwynn** [comment]
You might want to debug the `ensureEnabled` [function](https://github.com/rwynn/monstache/blob/master/monstache.go#L1279).  This should be getting called and returning true for the active process.  
Conversely, the `enableProcess` [function](https://github.com/rwynn/monstache/blob/master/monstache.go#L1251) should be mostly returning false for the inactive processes.  It should only return true when the active process goes down.  

The problem may have been related to your previous issue with systemd, as monstache will delete its process information from `monstache.cluster` before it exits.  Only the processes that are long running should be part of a cluster.  The one shot runs of monstache should not have a cluster-name set on them.

**Comment by sbnajardhane** [comment]
Hi @rwynn 
I have successfully dumped all my data to monstache using by creating a separate config file for one-shot process with cluster-name disabled.
About the Pause/Resume log
I have tried debugging the ensureEnabled Function. As I have observed that just before the process pauses, the cluster entry is getting removed from the cluster collection. I am not sure why that entry is getting removed. When some other process start actively working for that cluster the entry is getting added again.
Added the values from the cluster collection. continuesly fetched the data from cluster collection. After some point the collection entry is getting removed and new is getting added.
```
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T16:59:57.554Z"), "pid" : 12369, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:07.527Z"), "pid" : 12369, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:07.527Z"), "pid" : 12369, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:07.527Z"), "pid" : 12369, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:07.527Z"), "pid" : 12369, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
db:PRIMARY> db.cluster.find()
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:16.716Z"), "pid" : 4450, "host" : "host-2" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:16.716Z"), "pid" : 4450, "host" : "host-2" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T17:00:26.749Z"), "pid" : 4450, "host" : "host-2" }
```
I have looked into the code. Method  `resetClusterState` (which is removing the cluster active process entry from the cluster collection) is getting called only once from the shutdown method. I am not able to figure out why the entry is getting removed.
I have tried on monstache 4.11.3 and 5.1 version. Still facing the same issue.

**Comment by rwynn** [comment]
@sbnajardhane the design is that the active process should be updating the `expireAt` field every 10s with the current time.  There is an index on `expireAt` which will delete the record from MongoDB if the time in `expireAt` is greater than 30s from the current time.

Do you think there is any difference between the time on the monstache machine and the MongoDB machine?  Is the active process not updating `expireAt` every 10 seconds?

**Comment by sbnajardhane** [comment]
Yes, the time on monstache and mongo machine are different. Mostly this might be causing an issue. will work around that. Thanks (y)
BTW The active process is successfully updating the `expireAt` every 10s.
```
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T18:04:46.756Z"), "pid" : 4450, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T18:04:56.757Z"), "pid" : 4450, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T18:04:56.757Z"), "pid" : 4450, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T18:05:06.731Z"), "pid" : 4450, "host" : "host-1" }
db:PRIMARY> db.cluster.find()
db:PRIMARY> db.cluster.find()
db:PRIMARY> db.cluster.find()
{ "_id" : "HA", "expireAt" : ISODate("2019-09-24T18:05:17.514Z"), "pid" : 12369, "host" : "host-2" }
```

**Comment by rwynn** [comment]
@sbnajardhane looking into MongoDB's $currentDate operator instead of sending a date from monstache.  This might help with clock skew.

**Comment by sbnajardhane** [comment]
@rwynn 
We were upgrading monstache from 4.11.3 to 5.1. As I have observed in **version 4.11.3**,  the worker continuously switching among fellow workers and keeps on syncing the data.
But on **version 5.1** all the workers go into the passive state after resuming/pausing for couple of times.
```
INFO 2019/09/26 10:05:20 Started monstache version 5.1.0
INFO 2019/09/26 10:05:20 Successfully connected to MongoDB version 3.2.22
INFO 2019/09/26 10:05:20 Successfully connected to Elasticsearch version 6.3.1
INFO 2019/09/26 10:05:20 Joined cluster HA_VPC
INFO 2019/09/26 10:05:20 Pausing work for cluster HA_VPC
INFO 2019/09/26 10:06:00 Resuming work for cluster HA_VPC
INFO 2019/09/26 10:06:00 Listening for events
INFO 2019/09/26 10:06:00 Resuming from timestamp {T:1569492538 I:1}
INFO 2019/09/26 10:07:00 Pausing work for cluster HA_VPC
INFO 2019/09/26 10:08:00 Resuming work for cluster HA_VPC
INFO 2019/09/26 10:09:00 Pausing work for cluster HA_VPC
```
After that this process didn't wake up again, similarly, other workers also become passive. And the entry for resume timestamp is also missing in the **db.monstache collection**. Entry against "HA_VPC" cluster should be present in the mongo collection. I am not sure why this is happening.
Everything seems to be working in version 4.11.3

**Comment by sbnajardhane** [comment]
@rwynn  About the system time out of sync issue. It seems that changing the system time on the mongo machine might cause an unpredictable issue.
The solution you have provided seems to be a good idea. But I am sure about modifying the code. Isn't it a good idea to have this enhancement into a plugin. i.e. Instead of passing a UTC now time to a mongo insert, It might be good to read it from the mongo machine itself. What are your thoughts around it.

> @sbnajardhane looking into MongoDB's $currentDate operator instead of sending a date from monstache. This might help with clock skew.

**Comment by rwynn** [comment]
@sbnajardhane  not sure I understand your question as $currentDate operator will update the document with MongoDB's time.  I am changing to that from sending time from monstache process.  Now only MongoDB server time is used.

**Comment by sbnajardhane** [comment]
> @rwynn
> Yesterday, there were lots of bulk updates (6-7 different bulk operations) on the same set of users(around 800k) in a short period of time. So the monstache plugin got stopped and started throwing an error
> 
> ```
> ERROR 2019/09/10 17:20:10 Error tailing oplog entries: read tcp monstache-machine-ip:57796->mongo-primary-ip:27017: i/o timeout
> ERROR 2019/09/10 17:20:22 Error tailing oplog entries: read tcp monstache-machine-ip:58227->mongo-primary-ip:27017: i/o timeout
> ERROR 2019/09/10 17:20:34 Error tailing oplog entries: read tcp monstache-machine-ip:58755->mongo-primary-ip:27017: i/o timeout
> ```
> 
> So we have modified the mongo timeout setting **from**
> 
> ```
> # Oplog read operation timeout setting.
> [mongo-dial-settings]
> timeout=15
> read-timeout=7
> write-timeout=7
> 
> [mongo-session-settings]
> socket-timeout=0
> sync-timeout=7
> ```
> 
> To this
> 
> ```
> # Oplog read operation timeout setting.
> [mongo-dial-settings]
> timeout=15
> read-timeout=30
> write-timeout=30
> 
> [mongo-session-settings]
> socket-timeout=0
> sync-timeout=30
> ```
> 
> And it worked.
> 
> Now, in order to restore the data from last sync timestamp, we have decided to go for full sync instead of reading from the oplog(as it might be so huge, 800k * 7 approximately)
> But when we started to the plugin in full sync mode, it got restarted multiple times. Few chunks from info.log
> 
> ```
> INFO 2019/09/11 15:32:07 Pausing work for cluster HA
> INFO 2019/09/11 15:32:09 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:32:09 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:32:17 Resuming work for cluster HA
> INFO 2019/09/11 15:32:24 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:32:24 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:32:39 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:32:39 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:32:54 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:32:54 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:33:09 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:33:09 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:33:10 Pausing work for cluster HA
> INFO 2019/09/11 15:33:11 Started monstache version 4.11.3
> INFO 2019/09/11 15:33:11 Successfully connected to MongoDB version 3.2.22
> INFO 2019/09/11 15:33:11 Successfully connected to Elasticsearch version 6.3.1
> INFO 2019/09/11 15:33:11 Joined cluster HA
> INFO 2019/09/11 15:33:11 Starting work for cluster HA
> INFO 2019/09/11 15:33:11 Listening for events
> INFO 2019/09/11 15:33:11 Sending systemd READY=1
> INFO 2019/09/11 15:33:11 READY=1 successfully sent to systemd
> INFO 2019/09/11 15:33:11 Sending systemd WATCHDOG=1
> INFO 2019/09/11 15:33:11 WATCHDOG=1 successfully sent to systemd
> INFO 2019/09/11 15:33:26 Sending systemd WATCHDOG=1
> ```
> 
> the plugin got started multiple times. After few updated, only the deleted doc count is getting updated in elasticsearch. So we have stopped the sync in between. Also noticed that plugin is getting paused and resume in between. Observed this few days ago as well.
> So could please help us figure out why this might be happening.
> 
> Here is the config file for your reference:
> 
> ```
> elasticsearch-urls = ["es-url"]
> namespace-regex = 'db.user'
> direct-read-namespaces = ['db.user']   # enabled this for during sync
> exit-after-direct-reads = true                 # enabled this for during sync
> gzip = true
> index-as-update = false
> fail-fast = false
> elasticsearch-retry = true
> prune-invalid-json = true
> index-oplog-time = true
> resume = true
> cluster-name = "HA"
> resume-name = "HA"
> 
> [logs]
> info = "/mnt/monstache/logs/info.log"
> warn = "/mnt/monstache/logs/warn.log"
> error = "/mnt/monstache/logs/error.log"
> trace = "/mnt/monstache/logs/trace.log"
> stats = "/mnt/monstache/logs/stats.log"
> 
> [mongo-dial-settings]
> timeout=15
> read-timeout=7
> write-timeout=7
> 
> [mongo-session-settings]
> socket-timeout=0
> sync-timeout=7
> 
> [[mapping]]
> namespace = "db.user"
> index = "user"
> type = "_doc"
> ```

This has been fixed. increased the time out values.
Also upgrading to version 5.2 resolved the issue of a few missing doc sync in bulk update.
