### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by asaf** [rwynn/monstache#28]
Hey,

It might be useful to integrate with systemd to increase reliability of monstache,

Could use github.com/coreos/go-systemd

It is require to send a `READY=1` event to systemd upon service instantiation (somewhere in main(), check this [link](https://vincent.bernat.im/en/blog/2017-systemd-golang))

It could be nice to integrate with the watchdog and send `WATCHDOG=1` if `daemon.SdWatchdogEnabled` returns interval > 0 such:

```golang
go func() {
    interval, err := daemon.SdWatchdogEnabled(false)
    if err != nil || interval == 0 {
        return
    }
    for {
        daemon.SdNotify(false, "WATCHDOG=1")
        time.Sleep(interval / 2)
    }
}()
```

Thanks.

**Comment by rwynn** [comment]
Thanks, I'll take a look at getting this in.  What would you like to see as the criteria for notifying the WATCHDOG?  Just always send it at half the returned interval?

**Comment by asaf** [comment]
@rwynn Awesome, well, I don't think it's necessary to add a param for this (Monstache has enough already:)) this is the recommended value, or /2 or /3 of the interval

**Comment by rwynn** [comment]
@asaf actually I wasn't suggesting adding new params.  I was wondering if any criteria should be checked before sending the WATCHDOG.  Otherwise, it will just send it regardless of whether or not any actual documents are being synced.  It will simply mean that the process is still alive.

**Comment by asaf** [comment]
This is the idea, to ensure that the process is alive :-)

**Comment by rwynn** [comment]
If you are happy with it as is then that's cool.  This is the part of the link that you sent me that had me thinking about additional checks:

> However, this doesn’t add much value: the goroutine is unrelated to the core business of the service. If for some reason, the HTTP part gets stuck, the goroutine will happily continue to send keep-alives to systemd

I was thinking maybe there was something related to the core business of Monstache that could be added.

**Comment by asaf** [comment]
@rwynn Maybe after pinging ES/Mongo but I assume this is more complicated.
