### ISSUE TITLE
Failed to find unique document for deletion using index pattern

### ISSUE THREAD

**Issue by coppermine2019** [rwynn/monstache#283]
Hi,

I am getting this message during deletion

ERROR  299 Elasticsearch-7.2.0-508c38a "[types removal] Specifying types in search requests is deprecated."
Failed to find unique document 5d81a012542dbd075e7944b5 for deletion using index pattern *

4e
{"_source":false,"query":{"term":{"_id":"5d81a012542dbd075e7944b5"}},"size":1}
0

**But when I did the search, it returns one document.**
GET /*/_search
{
  "_source":false,"query":{"term":{"_id":"5d81a012542dbd075e7944b5"}},"size":1
}

{
  "took" : 48,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "my_index_name",
        "_type" : "_doc",
        "_id" : "5d81a012542dbd075e7944b5",
        "_score" : 1.0
      }
    ]
  }
}

It calls this function:
func doDelete(config *configOptions, client *elastic.Client, mongo *mgo.Session, bulk *elastic.BulkProcessor, op *gtm.Op) {

if searchResult.Hits != nil && searchResult.Hits.TotalHits == 1 {
	hit := searchResult.Hits.Hits[0]
	req.Index(hit.Index)
	req.Type(hit.Type)
	if hit.Routing != "" {
		req.Routing(hit.Routing)
	}
	if hit.Parent != "" {
		req.Parent(hit.Parent)
	}
} else {
	errorLog.Printf("Failed to find unique document %s for deletion using index pattern %s", objectID, config.DeleteIndexPattern)
	return
}

seems like it is not entering this if block
if searchResult.Hits != nil && searchResult.Hits.TotalHits == 1 {

my config
delete-strategy = 0
routing-namespaces = [""]
delete-index-pattern = "*"

Please help.

Thanks for your time.

**Comment by rwynn** [comment]
Can you check that you're using monstache `v6`?  The source code for the latest release of that is in the `rel6` branch.

https://github.com/rwynn/monstache/tree/v6.1.1

The v6 monstache build is the only one that supports Elasticsearch 7+.  I say this only because the code you pasted looks like an older version.  

I looked at the v6 branch and there still might be an issue in monstache.  It shouldn't be setting the _type field in Elasticsearch 7+.  But that only occurs after the search result is returned, which it seems you're not even getting.

**Comment by coppermine2019** [comment]
monstache version number is 6.0.8

**Comment by rwynn** [comment]
@coppermine2019 that's pretty strange cause in 6.0.8 the type field is not set purposefully on the search request.

https://github.com/rwynn/monstache/blob/v6.0.8/monstache.go#L3399

It is set on the delete request added to the bulk service, and that should be removed, but that comes after the search has been performed.

https://github.com/rwynn/monstache/blob/v6.0.8/monstache.go#L3442

So, I'm not sure why you would be having the error message "Specifying types in search requests is deprecated."

It might be helpful if you ran a test with `verbose=true`. That will show a trace of all requests going to Elasticsearch and the Elastic client version I believe.

**Comment by rwynn** [comment]
I did a quick sanity test with monstache v6.1.1 and this is the trace I saw for 1 document deleted with your settings.

```
TRACE 2019/09/23 22:09:54 POST /%2A/_search HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.6 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

4e
{"_source":false,"query":{"term":{"_id":"5d8942af0ccbdf6b26c76fc7"}},"size":1}
0


TRACE 2019/09/23 22:09:55 HTTP/1.1 200 OK
Content-Length: 244
Content-Type: application/json; charset=UTF-8

{"took":491,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":
[{"_index":"test.test","_type":"_doc","_id":"5d8942af0ccbdf6b26c76fc7","_score":1.0}]}}
TRACE 2019/09/23 22:09:55 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.6 (linux-amd64)
Content-Length: 123
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_index":"test.test","_id":"5d8942af0ccbdf6b26c76fc7","version":6739991649608269825,"version_type":"external"}}
```

So in this case it was able to find the document via the search and then send it in a bulk as a delete request.

**Comment by coppermine2019** [comment]
This is what happening.

My elasticsearch url has a context path myelasticsearch as below.

elasticsearch-urls = ["https://mydomain.com/myelasticsearch/"]

during the search, code is appending the /myelasticsearch
hence the search is not returning any data.

TRACE 2019/09/23 18:06:21 POST /**myelasticsearch**/*/_search

#! Deprecation: [types removal] Specifying types in search requests is deprecated.
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [myelasticsearch]",
        "resource.type" : "index_or_alias",
        "resource.id" : "myelasticsearch",
        "index_uuid" : "_na_",
        "index" : "myelasticsearch"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [myelasticsearch]",
    "resource.type" : "index_or_alias",
    "resource.id" : "myelasticsearch",
    "index_uuid" : "_na_",
    "index" : "myelasticsearch"
  },
  "status" : 404
}

**Comment by rwynn** [comment]
Are you thinking that the context path is being used twice in the URL?  I'm not sure how that could happen, but monstache goes through the following [client](https://github.com/olivere/elastic/tree/v7.0.6).  I didn't see anything in there though that would do that.

**Comment by coppermine2019** [comment]
It was an issue with haproxy routing. It was adding an extra forward slash. Updated the haproxy routing config and now the deletes work fine. 
Thanks for your time and tips.
