### ISSUE TITLE
changeStream requiring root role

### ISSUE THREAD

**Issue by zvictor** [rwynn/monstache#286]
I am getting the error below when running monstache with any role other than `root`:
> ERROR 2019/09/27 16:51:56 Error starting change stream. Will retry: (Unauthorized) not authorized on admin to execute command { aggregate: 1, pipeline: [ { $changeStream: { allChangesForCluster: true, fullDocument: "updateLookup", startAtOperationTime: Timestamp(1569603089, 3) } } ], cursor: { batchSize: 512 }, lsid: { id: UUID("f6ec7d74-b503-4797-8ab3-08a85a014cd9") }, $clusterTime: { clusterTime: Timestamp(1569603111, 1), signature: { hash: BinData(0, 7F219299D90F18E761E367BF39ACDC2702CB06E6), keyId: 6741393900595838978 } }, $db: "admin", $readPreference: { mode: "primaryPreferred" } }

**tested on:**
- monstache:5.1.1
- mongo:4.0.6-xenial and mongo:4.0.12-xenial

I tried different combinations of permissions to the user monstache is using in the connection: 
```js
// root [WORKS]
db.createUser({
  ...
  roles: [
    { role: 'root', db: 'admin' },
  ],
});

// admin [FAILS]
db.createUser({
  ...
  roles: [
    { role: 'dbAdminAnyDatabase', db: 'admin' },
    { role: 'dbAdmin', db: 'local' }
  ],
});

// app-user [FAILS]
db.createUser({
  ...
  roles: [
    { role: 'readWrite', db: $MONGO_DB_NAME },
    { role: 'read', db: 'local' }
  ],
});
```

Isn't `{ role: 'read', db: 'local' }` supposed to be [enough](https://docs.mongodb.com/manual/reference/built-in-roles/#read)?

**Comment by rwynn** [comment]
Have you tried with the permissions listed here? Specifially, the last one to enable change streams on an entire deployment.  

https://docs.mongodb.com/manual/changeStreams/#access-control

Monstache 5 and 6 use the change streams API and no longer default to using the oplog collection in local directly.  This old behavior can be re enabled with `enable-oplog` but that's no recommended since the new API is better.

**Comment by zvictor** [comment]
the error disappeared once I properly defined `change-stream-namespaces` =)

I am migration from monstache 4 and I was making changes step by step; once I added `change-stream-namespaces` the error was gone

**Comment by zvictor** [comment]
I still see a single similar error after I start monstache, but this one doesn't seem to be causing any problem (the previous one was flooding the logs):

> ERROR 2019/09/27 18:30:10 (Unauthorized) not authorized on admin to execute command { replSetGetStatus: 1, lsid: { id: UUID("4a753b8c-6f41-4642-a0ff-0d693e78eecd") }, $clusterTime: { clusterTime: Timestamp(1569608997, 1), signature: { hash: BinData(0, EA600E8FE53F76CE954710E56E911532FC360393), keyId: 6741419279557591042 } }, $db: "admin" }
