### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by afnanali1992** [rwynn/monstache#289]
Hello, I downloaded the latest release by Monstache and when I tried to run the command of monstache -v after including the path of folder in my PATH Environment Variables, the following message was shown "cannot execute binary file".

So How could I solve this problem ?, And what is the reason of this issue?

**Comment by rwynn** [comment]
What OS are you running it on? There are separate folders for mac, windows, and linux.  Are you running the binary from the correct folder?

**Comment by afnanali1992** [comment]
My OS is Mac Mojave So, what the correct folder of mac ?

**Comment by rwynn** [comment]
darwin-amd64

**Comment by afnanali1992** [comment]
@rwynn Thanks a lot to your response, I ran it from linux-amd64 folder
