### ISSUE TITLE
Migration of existing MongoDB to ES

### ISSUE THREAD

**Issue by thilagaCloud** [rwynn/monstache#290]
Hi Rwynn,

I have installed mongodb few weeks back and i have set of documents. Now, i just installed Elastic search(ES) and Monstache. If i add, any records into MongoDb, it is synchronizing to ES. But I want all the existing Mongo Documents into ES. Does monstache support this initial migration?

Thanks
ThilagaDas

**Comment by thilagaCloud** [comment]
I got the answer from other old issue-solution. direct-read-namespace will help to do that. I tried, it is synchronizing for first namespace. The other one is giving error. Can you please check this?. Attached here the screenshot for your reference. Thanks!
<img width="960" alt="mongoSynch" src="https://user-images.githubusercontent.com/49547968/66114527-9d8fcb80-e5ec-11e9-9318-9da3c198b5a3.png">

**Comment by rwynn** [comment]
Check the _mapping for your index in Elasticsearch.  It seems like the field `data.description` should be mapped to `text` but it is currently mapped as a `long`. 

```bash
# replace test.test with the index monstache is writing to
curl "localhost:9200/test.test/_mapping?pretty"
```
If you had a number value for a description field in any of your MongoDB data, then it's possible this field got mapped to a long automatically by Elasticsearch when the first document was inserted.

**Comment by thilagaCloud** [comment]
Thanks rwynn. Removed the index and restarted monstache resolved this issue. This time it considers TEXT only not LONG.
