### ISSUE TITLE
resume-from-timestamp as an environment variable

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#292]
Hi rwynn,

Is there a way to set the 'resume-from-timestamp' as a command line argument or maybe an environment variable, instead of using the toml file?

**Comment by rwynn** [comment]
@IchorPop,

You should be able to pass on the command line like

```
go run monstache.go -resume-from-timestamp 1570476827
```

where the value is the T value (first value) in Timestamp `ts` from the oplog ...

```
rs1:PRIMARY> use local;
rs1:PRIMARY> db.oplog.rs.find({ns:"test.test"}).sort({$natural:-1}).skip(200).limit(1);
{ "ts" : Timestamp(1570476827, 76712),
```

**Comment by IchorPop** [comment]
Thanks @rwynn!
