### ISSUE TITLE
exit-after-direct-read trigger

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#294]
Hi @rwynn ,

More of a question than an issue: How does monstache trigger the exit for the exit-after-direct-read option when direct reading a collection? To my understanding, when it is direct reading a collection it will also sync any live changes. Does this mean that if inserts are frequently occurring for the mongo collection, then the exit will not trigger?

Thanks!

**Comment by rwynn** [comment]
You are correct that live changes are synced while reading directly.  However, the listeners for live changes do not factor into when the direct reads are "done".  For exiting after direct reads, monstache considers that "done" when all cursors opened directly against collections are exhausted.  And more specifically, went a wait group dedicated to direct reads, `DirectReadWg`, reaches 0. 

For each collection that must be directly read, monstache will first split the collection and setup a list of segments to read.  Initial segments might look like `_id` => min && `_id` < max, but the last segment will not have a max. So, for this last segment monstache will continue to call `getmore` until no results are returned.  It is possible that with continuous inserts this cursor will keep returning documents for each `getmore` call, and thus monstache never think the direct reads are done.  

Here, you can see how `DirectReadPaged` calls `DirectReadSegment` for each segment it produces.  `DirectReadPaged` is called for each collection in `direct-read-namespaces`.

https://github.com/rwynn/gtm/blob/master/gtm.go#L1335

**Comment by IchorPop** [comment]
Thanks @rwynn!

I'm having an issue where I'm trying to sync a mongo collection that is getting frequent and continuous inserts. It's hard to know when the direct read is finished so that I can use the resume-from-timestamp option to read missed messages (I've configured the go plugin such that duplicate messages are dealt with appropriately; this means I can safely start tailing the oplog slightly before the direct read was initiated via resume-from-timestamp.)

It would be nice if there was an option to direct read up to the point in time when the direct read was initiated (i.e. if the direct read was started at time x, then the direct read will only read documents that were already inserted at x and exit). If this timestamp is then returned back to the user, the user can use the resume-from-timestamp to pick up any missed messages.

**Comment by rwynn** [comment]
Hi @IchorPop, I think I can do something along those lines.  It would be a new boolean option `direct-read-bounded` that would default to false.  If you turn that on, it would always ensure min/max are set on the direct reads such that the cursor is immune to continuous updates to the collection.  If that sounds ok I can schedule for the next release.  What version of monstache do you use?  I am wondering if I need to backport this change to v3 and v4 or if I can just add to the newer v5 and v6?

**Comment by IchorPop** [comment]
Thanks, yes that would be very helpful. I'm using v6.

**Comment by rwynn** [comment]
@IchorPop please try monstache v6.2.3 with the `direct-read-bounded` option set to true.  This should ensure that the direct-reads do not continue forever with heavy inserts.

**Comment by IchorPop** [comment]
@rwynn I've upgraded to v6.2.3 and somehow the direct-read is not starting any more. I haven't changed anything except for the monstache version. I tried with a lower version (6.0.10) and the direct reads are working there.

**Comment by rwynn** [comment]
@IchorPop with the config you shared I do see an issue with the new `direct-read-bounded` option but not without it.  What output do you get?  For me I see lots of documents being sent due to the `verbose` setting.

**Comment by IchorPop** [comment]
@rwynn I get no output, only

```
Starting monstache7 ... done
Attaching to monstache7
```

This happens even without `direct-read-bounded`. However, when I switch back to v6.0.10, I get the normal output (a stream of documents being inserted to ES)

**Comment by rwynn** [comment]
Is this with the docker image?  What about running the release binary?

**Comment by IchorPop** [comment]
Yes, this is with the docker image (rwynn/monstache:6.2.3) -- I'll try with the release binary.

**Comment by rwynn** [comment]
@IchorPop I just pushed a new release with a fix for `direct-read-bounded`.  I was getting error message "Document is nil".  

 I think the issue you were seeing is probably something else though.  I was seeing normal output without that setting applied.  I tried running the docker image directly and it was ok for me, but didn't try in docker-compose.   

I wonder if somehow the docker image was corrupted, if that is even possible?

**Comment by IchorPop** [comment]
Hmm, just tried with "rwynn/monstache:6.2.4", same error. After switching to "rwynn/monstache:6.0.10" I get the normal output.

I tested with "rwynn/monstache:6.2.2" and I also get the expected output (i.e. only 6.2.3 and upwards causes the error)

**Comment by rwynn** [comment]
I'm not able to replicate the non-starting issue.  I tried again with the binary from https://github.com/rwynn/monstache/releases/download/v6.2.4/monstache-964c477.zip.  And also, by running the docker image like...

```
docker run --rm --net=host rwynn/monstache:6.2.4 --verbose
INFO 2019/10/25 14:26:03 Started monstache version 6.2.4
INFO 2019/10/25 14:26:03 MongoDB go driver v1.1.2
INFO 2019/10/25 14:26:03 Elasticsearch go driver 7.0.6
INFO 2019/10/25 14:26:03 Successfully connected to MongoDB version 4.0.13
INFO 2019/10/25 14:26:03 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/10/25 14:26:03 Listening for events
INFO 2019/10/25 14:26:03 Sending systemd READY=1
INFO 2019/10/25 14:26:03 Watching changes on the deployment
WARN 2019/10/25 14:26:03 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
```

There were some changes related to signal handling in 6.2.3.  For example if the monstache process is sent a SIGINT, SIGTERM, or SIGKILL before it enters its event loop, then it will exit immediately with a 1 exit status code.

**Comment by IchorPop** [comment]
I haven't been able to get it working with the binary yet, mainly because I keep getting version conflict errors. It's much easier to use build.sh and then use the docker image since my plugin code is not a single file but with locally defined packages.

When you did those tests, did you also supply a plugin.so file?

**Comment by rwynn** [comment]
I do think it's related to having a plugin.  I seem something similiar when adding the -mapper-plugin-path.

**Comment by IchorPop** [comment]
Should have tried it earlier -- without the plugin.so file, I can run the 6.2.4 docker image fine as well (see below). So it should be related to supplying a plugin file.

```
INFO 2019/10/25 15:21:22 Started monstache version 6.2.4
INFO 2019/10/25 15:21:22 MongoDB go driver v1.1.2
INFO 2019/10/25 15:21:22 Elasticsearch go driver 7.0.6
INFO 2019/10/25 15:21:22 Successfully connected to MongoDB version 4.0.13
INFO 2019/10/25 15:21:22 Successfully connected to Elasticsearch version 7.1.1
INFO 2019/10/25 15:21:22 Sending systemd READY=1
INFO 2019/10/25 15:21:22 Starting http server at :8080
INFO 2019/10/25 15:21:22 Listening for events
INFO 2019/10/25 15:21:27 Stopping all workers
```

**Comment by rwynn** [comment]
But I was able to load a plugin that I build outside of docker.  So still not sure what is going on.  

Seems like the hang happens with (1) golang plugin + (2) docker.

**Comment by rwynn** [comment]
@IchorPop I think I found a fix for this.  It's a strange issue (deadlock?) between the use of `plugin.Open` and `signal.Notify` happening concurrently in 2 separate go routines.  When I move the plugin loading first it seems to work.  

Can you try pulling the latest from `rel6` and then running monstache/docker/release/build.sh to generate your own local monstache:6.2.4 image.  Then try with that local image and let me know if it works as before.

**Comment by IchorPop** [comment]
@rwynn Yes, it's working now with the local 6.2.4 image!

**Comment by rwynn** [comment]
@IchorPop thanks for testing, hopefully this should be good to go now in 6.2.5.

**Comment by IchorPop** [comment]
Tried the `direct-read-bounded` option on 6.2.5, working as expected. Closing this issue, thanks again!

**Comment by IchorPop** [comment]
Hi rwynn,

Seems like I was wrong above. I'm doing some direct-reads with the `direct-read-bounded` flag and it doesn't seem to prevent monstache from chasing new inserts. I'm testing on a very small collection and it seems to wait for new inserts instead of indicating that the direct-read has been completed. I tried inserting a new document in the collection and it recognizes it, even though `direct-read-bounded` is set to true.

I'm using the 6.2.5 docker image with a golang plugin. TOML file is as below:

```
verbose = true
enable-http-server = true
mongo-url = "..."
elasticsearch-urls = ["http://es7:9600"]
elasticsearch-max-seconds = 10
enable-oplog = true
direct-read-no-timeout = true
direct-read-split-max = -1
direct-read-bounded = true
namespace-regex = '^collection\.test$'
direct-read-namespaces = ["collection.test"]
```

**Comment by IchorPop** [comment]
For what it's worth, this seems to happen regardless of using `enable-oplog` or `change-stream-namespaces`

**Comment by rwynn** [comment]
Hi @IchorPop,

If I understand what you are trying to achieve, you need to simply sync the direct reads of a collection and then stop monstache?

If that's the case then you might need to add 

```toml
# this is the only way to get monstache to stop responding to events and exit
exit-after-direct-reads = true
# monstache will always sync change events unless you add this
disable-change-events = true
```

Monstache treats change stream events (inserts, updates, deletes) separately from direct reads.  There is no way to turn change events off mid process.  Monstache will always keep processing the stream of changes (even after direct reads complete).  You can only signal to monstache that you want to stop all processing all events with `exit-after-direct-reads`.

**Comment by IchorPop** [comment]
Ah, I'm mistaken -- `direct-read-bounded` is working, it gives a message that direct reads is completed (it was hidden from my console log, instead monstache logs it to the info logs, which I forgot to check). What I didn't expect was that monstache would still listen to new inserts with the `direct-read-bounded` flag set to true.

Your suggestion seems to work, but now I'm wondering the difference between those two flags and the `direct-read-bounded` flag?

**Comment by IchorPop** [comment]
With those two options that you suggested, i.e. now my toml file looks like this:

```
verbose = true
enable-http-server = true
mongo-url = "..."
elasticsearch-urls = ["http://es7:9600"]
elasticsearch-max-seconds = 10
direct-read-no-timeout = true
direct-read-split-max = -1
direct-read-bounded = true
exit-after-direct-reads = true
disable-change-events = true
change-stream-namespaces=["collection.test"]
direct-read-namespaces = ["collection.test"]
```

the "Direct reads completed" message appears if I direct read small collections (~100 documents), but does not appear when reading larger collections (>1m documents)

**Comment by rwynn** [comment]
I would suggest trying with `verbose=false` since that will dump your entire collection to the logs.  It may be slowing things down.  I wouldn't recommend that setting to be on in normal operation.
