### ISSUE TITLE
Elasticsearch monstache high cpu

### ISSUE THREAD

**Issue by mahesh3590** [rwynn/monstache#295]
Hi rwynn,

It's more of a question than an issue.
I am using monstache to sync mongo-db data to elasticsearch. My assumption is monstache uses bulk api to index the data to elasticsearch.
My Elastisearch cluster has single node, 4-core, 26GB RAM ubuntu machine with default configuration of 5 primary shards and 1 replica for the index. Kibana shows indexing rate of 1500docs/sec.
When monstache is indexing the data, node runs at 100% CPU on each core. 
1. Is this behaviour normal? 
2. If I want to reduce CPU consumption what should I do?

I am happy to provide any other information if required. Any help would be much appreciated!!

Thanks,
Magesh

**Comment by rwynn** [comment]
Hi @mahesh3590, 

I think what you're seeing if relatively normal for a single node Elasticsearch cluster with a client like monstache that is doing alot of bulk indexing (yes, it does use bulk).  

https://discuss.elastic.co/t/high-cpu-on-bulk-requests/39969

It would be helpful to know more about your monstache configuration with respect to the use of direct-reads and how often data is being changed in MongoDB.  Monstache, by default, reads from all collections in direct-reads concurrently in multiple go routines and pushes data to Elasticsearch in another 4 (by default) go routines that buffer up to 8bm (by default) of data before bulking.  

Here are some settings you can play with to see if you get results you are looking for:

```
# defaults to 8MB of data in each bulk
elasticsearch-max-bytes = 2000000

# defaults to 4 go routines bulking to Elasticsearch
elasticsearch-max-conns = 1

# since we are slowing down reads using gtm-settings
direct-read-no-timeout = true

# only sync one collection at a time for direct reads instead of all at the same time
direct-read-concur = 1

[gtm-settings]
# defaults to 512, this will slow down reads from MongoDB
channel-size = 1
```

Some things you can try on the Elasticsearch side (shown [here](https://github.com/rwynn/monstache-showcase/blob/master/elasticsearch/config/template.json)) are 

- Increase the refresh_interval from default 1s to e.g. 30s for your indexes
- Set the number of replicas to 0 while indexing and then change to 1 after indexing is complete

**Comment by mahesh3590** [comment]
Hi @rwynn ,

Thanks for the response. That helped !
I am able to bring down the CPU usage.

I also want real time sync. If I update any document in mongo db it should reflect in Elasticsearch (. I have been playing around with monstache config params but with no luck. I tried using change streams but it throws an error.
"ERROR 2019/10/19 10:16:17 Error starting change stream. Will retry.: BSON field '$changeStream.startAtOperationTime' is an unknown field."

Can you help me out on this?

I am using monstache 6.2.2 and mongo 3.6.

Here is my config file:

mongo-url = "mongodb://MONGO-IPADDRESS:27017/"
elasticsearch-url = "http://localhost:9200"
direct-read-namespaces = ["myDB.charm","myDB.video"]
change-stream-namespaces = [ "myDB.video"]

enable-oplog = true
verbose = true
elasticsearch-max-conns = 1
elasticsearch-max-bytes = 10000
direct-read-no-timeout = true
direct-read-concur = 1
channel-size = 1
#stats=false

replay = true
resume = true
resume-name = "default"

index-as-update=true
index-oplog-time=true


[logs]
info = "logs/info.log"
warn = "logs/warn.log"
error = "logs/error.log"
trace = "logs/trace.log"
[[mapping]]
namespace = "myDB.charm"
index = "myDB"
type = "charm"
[[mapping]]
namespace = "myDB.video"
index = "myDB"
type = "video"

Thanks,
Magesh

**Comment by mahesh3590** [comment]
Thank you for the response.
It worked for me!
