### ISSUE TITLE
writing pipeline plugin in golang

### ISSUE THREAD

**Issue by liyerliyer** [rwynn/monstache#296]
English isn't my first language, so please excuse any mistakes.
I want to remove a field from documents and also add another filed to documents. based on [monstache  documentation](https://rwynn.github.io/monstache-site/advanced/#golang) I realized I have to use pipeline. 
I wrote plugins in javascript and it works but i don't know how I write it in golang. 
My question is: what is stages and which value i have to assign to it.
 is there any sample code? 
```
func Pipeline(ns string, changeStream bool) (stages []interface, err error){
    stages = ???
}
```

**Comment by rwynn** [comment]
Hi @liyerliyer,

You may be able to use a plugin like [this example](https://github.com/rwynn/monstache-showcase/blob/master/plugin/plugin.go) to accomplish your task.  This does not use a pipeline but rather simply converts the document to be indexed in golang code.

The pipeline stages that you mentioned are documented [here](https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/).  You may not heed to use this though.  There are some restrictions on the types of stages that you can use for [change streams](https://docs.mongodb.com/manual/changeStreams/#modify-change-stream-output).

**Comment by liyerliyer** [comment]
@rwynn 
Thank you for your prompt reply.

> You may be able to use a plugin like this example to accomplish your task. This does not use a pipeline but rather simply converts the document to be indexed in golang code.

I saw that example but the problem is that my documents have many fields and I should send few of them to Elastic Search. 
So I think it's not beneficial to retrieve all fields into monstache. I believe that  it is better to use aggregation pipeline and just retrieve  necessary fileds.

> The pipeline stages that you mentioned are documented here. You may not heed to use this though. There are some restrictions on the types of stages that you can use for change streams.

I read  those links and i wrote apprigation pipeline in javascript and it works fine. I just want to Write it in golang. 
so there is not any sample code?

**Comment by liyerliyer** [comment]
@rwynn 
thanks for your reply.
I compiled this code with build.sh script and I get this error:
```
./plugin.go:4:64: syntax error: unexpected comma, expecting {
The command '/bin/sh -c go build -buildmode=plugin -o $PLUGIN.so $PLUGIN.go' returned a non-zero code: 2
```

**Comment by rwynn** [comment]
@liyerliyer I've update the example go plugin code above.

**Comment by liyerliyer** [comment]
same error! 
`  command-line-arguments
./plugin.go:4:64: syntax error: unexpected comma, expecting {
The command '/bin/sh -c go build -buildmode=plugin -o $PLUGIN.so $PLUGIN.go' returned a non-zero code: 2
`

**Comment by rwynn** [comment]
@liyerliyer I don't think my code edit was saved the first time.  Please try again, it should be different now.

**Comment by liyerliyer** [comment]
thanks a lot for your help. it is works now.
