### ISSUE TITLE
Is there a way to push multiple mongodb collections to single elasticsearch index

### ISSUE THREAD

**Issue by vasupal1996** [rwynn/monstache#298]
I'm looking for a way to track changes from multiple collections. For example

**MongoDB:**
> User:
`name` - str
`article_ids` - list of objectids

> Article
`title` - str
`description` - str
`user` - objectid

**Elasticsearch**
> UserArticle:
`name` - str
`articles` - nested
      `>title`
      `>description`

1. Now, whenever any change in the above two collections occurs. I want to know from which collection update is coming from and push those changes to the UserArticle index accordingly.

2. Also if there is a way to update only the specific fields. For example, there is a change in Article collection, then just update articles in UserArticle of that matching user?

**Comment by IchorPop** [comment]
You'll need to write a plugin for this. One solution is to use the `Process` function within your golang plugin. Something like the following:

```
// Process - plugin function for monstache
func Process(input *monstachemap.ProcessPluginInput) (err error) {
	ctx := context.Background()
	if (input.Document["type"] == "user") {
		_, err := upsertUser(ctx, input.ElasticClient, input.Document["objectId"], input.Document)
		if err != nil {
			//handle error
		}
	}
	if (input.Document["type"] == "article") {
		_, err := upsertUser(ctx, input.ElasticClient, input.Document["objectId"], input.Document)
		if err != nil {
			//handle error
		}
	}
	return
}

// Checks if the user document exists, if not, then create a document for the user with the corresponding article
func upsertArticle(ctx context.Context, client *elastic.Client, objectId string, article interface{}) (*elastic.UpdateResponse, error) {
	script := elastic.NewScriptStored("upsertArticle-script").Params(map[string]interface{}{"article": article})
	result, err := client.Update().
		Index("yourindex").
		Type("_doc").
		Id(objectId).
		Script(script).
		Upsert(map[string]interface{}{
			"articles": []interface{}{article},
		}).
		Do(ctx)

	if err != nil || result == nil {
		return nil, err
	}
	return result, nil
}


// Upserts user documents
func upsertUser(ctx context.Context, client *elastic.Client, objectId string, doc map[string]interface{}) (*elastic.UpdateResponse, error) {
	result, err := client.Update().
		Index("yourindex").
		Type("_doc").
		Id(objectId).
		Doc(doc).
		DocAsUpsert(true).
		Do(ctx)

	if err != nil || result == nil {
		return nil, err
	}
	return result, nil
}
```

`upsertArticle-script` is a stored scripted as below:

```
if (ctx._source.containsKey("articles")) {
	if (!ctx._source["articles"].contains(params[\"article\"])) {
		ctx._source["articles"].add(params[\"article\"]);
	}
} else {
	ctx._source["articles"] = [params[\"article\"]];
}
```

**Comment by vasupal1996** [comment]
Thanks, but can you explain what `ctx := context.Background()` and  can I access `context` (Do i need to import it from somewhere?)

**Comment by IchorPop** [comment]
Yes you'll need to import the package `context`. I've edited the example above to be more complete. Also, the `go.mod` file should be:

```
module project

require (
	github.com/olivere/elastic/v7 v7.0.6
	github.com/rwynn/monstache v6.2.5
	go.mongodb.org/mongo-driver v1.1.2
)
```

The `upsertArticle-script` is needed to append articles to your nested array within each user document in Elastic.

As for context: https://golang.org/pkg/context/. It is recommended to use either `context.TODO()` or `context.Background()` when unsure and then refine later.
