### ISSUE TITLE
How to check for liveness on a k8s pod

### ISSUE THREAD

**Issue by cmosgh** [rwynn/monstache#30]
I find monstache to work amazingly fast and scaling it in a kubernetes cluster seems easy but what I can't find documented is how to check if monstache is still running to kill/respawn a pod for it.

Did I miss that in the documentation at https://rwynn.github.io/monstache-site ?

**Comment by rwynn** [comment]
Hi, thanks for using monstache.  I'm not too familiar with kubernetes yet, but I recently added support for systemd to monstache.  After you set this up you should be able to use the following command to see if monstache is alive (returns 0 if running, non-zero otherwise)

`systemctl --quiet is-active monstache.service`

Setting up systemd is documented at https://rwynn.github.io/monstache-site/system-d/.  

The `is-active` command info is at https://www.freedesktop.org/software/systemd/man/systemctl.html

Please let me know if that works or if something additional is needed.  I'll add the final solution to the docs.

**Comment by cmosgh** [comment]
So the idea in [kubernetes](https://kubernetes.io/) that you'll create a Docker image and place your running service inside. In order to make sure your service is running kubernetes checks at specified intervals if the service is still up and if not stops and then restarts a new pod with the service.

One way to do this is make your service respond to a simple http call with 500OK on a specified path on a specific port which kubernetes will ping at requested intervals. 
With this running HA services is pretty easy since if a service stops responding it will be restarted automatically.

**Comment by rwynn** [comment]
Thanks, that makes sense.  I should have something to commit for this shortly.  I'll use this as a template: https://github.com/kubernetes/kubernetes/blob/master/test/images/liveness/server.go

**Comment by rwynn** [comment]
Just added a commit for this. Please let me know how it goes.

**Comment by cmosgh** [comment]
I forked it and patched a much simpler non configurable version for my needs
Will also try this commit

Also I've created a Dockerfile for a basic containerization. Not pushed yet tho. Still cluster tests are in progress.

**Comment by rwynn** [comment]
@cmosgh, how's this working out for you?  Thanks.

**Comment by cmosgh** [comment]
Sorry about the late reply, we had some serious issues with the cluster. Still didn't get the time to run this version.
Will get back as soon as possible

**Comment by rwynn** [comment]
No problem. Just let me know if it’s still an issue when you get to it.

**Comment by cmosgh** [comment]
Hi there Ryan, 
Eventually reached the point of wanting to change the version to one of yours.
The problem is that with the latest src I can't build. I keep getting
`./monstache.go:575:10: unknown field 'Session' in struct literal of type monstachemap.MapperPluginInput
./monstache.go:598:13: output.Parent undefined (type *monstachemap.MapperPluginOutput has no field or method Parent)
./monstache.go:599:28: output.Parent undefined (type *monstachemap.MapperPluginOutput has no field or method Parent)
./monstache.go:601:13: output.Version undefined (type *monstachemap.MapperPluginOutput has no field or method Version)
./monstache.go:602:29: output.Version undefined (type *monstachemap.MapperPluginOutput has no field or method Version)
./monstache.go:604:13: output.VersionType undefined (type *monstachemap.MapperPluginOutput has no field or method VersionType)
./monstache.go:605:33: output.VersionType undefined (type *monstachemap.MapperPluginOutput has no field or method VersionType)
./monstache.go:607:13: output.TTL undefined (type *monstachemap.MapperPluginOutput has no field or method TTL)
./monstache.go:608:25: output.TTL undefined (type *monstachemap.MapperPluginOutput has no field or method TTL)
./monstache.go:610:13: output.Pipeline undefined (type *monstachemap.MapperPluginOutput has no field or method Pipeline)
./monstache.go:610:13: too many errors`

And if I want to use the built version from [Releases](https://github.com/rwynn/monstache/releases) (linux-amd64 folder) in my docker container, I keep getting the message `standard_init_linux.go:178: exec user process caused "no such file or directory"`

Could it be is not a standalone app you are putting there? Maybe it needs some golang libs?
