### ISSUE TITLE
Rotating logs

### ISSUE THREAD

**Issue by chandra2037** [rwynn/monstache#301]
Deploying Monstache as a Kubernetes Pod. Configured MONSTACHE_LOG_DIR as /app/logs/, also enabled verbose=true
I am seeing log files (error.log, warn.log, info.log, trace.log) in /app/logs directory. The plan is to index these logs into Elasticsearch using Filebeat, so that developers have access to logs for troubleshooting any indexing issues.

Question:
Can I configure log files to be rotated or deleted after a certain time, like say after every 24 hours? So that logs won't fillup the Kubernetes node ephemeral storage.

Thank you for any help.

**Comment by rwynn** [comment]
@chandra2037 in latest release you have more control over log rotation. See [log-rotate](https://rwynn.github.io/monstache-site/config/#log-rotate) for properties you can set.

```toml
# at end of file
[log-rotate]
max-size = 8
max-backups = 1
max-age = 1
```

I would take care in setting `verbose` to true for production.  That will log a trace of the entire bulk request.  Errors are always logged so you may not need to log the entire payload.  That mainly exists for debugging.

**Comment by chandra2037** [comment]
Thank you @rwynn for providing the quick fix. This is very helpful.
