### ISSUE TITLE
resuming synchronization after monstache restart

### ISSUE THREAD

**Issue by onur-gokce** [rwynn/monstache#304]
Hello Ryan,

First of all thank you so much for this useful tool!
 
I am having problems in configuring monstache (version 6.1.0) correctly for resuming the synchronization after monstache is restarted. Currently when I restart monstache, it scans the mongodb (version 4.2.1) from start instead of scanning only for the changes. I created a database on the mongodb server for monstache and a user that has write access to this database. Nothing has been written to this database so far. 

I paste below my monstache configuration file. Please also see my comments on the configuration file. Any help is highly appreciated!

```
enable-http-server = true
http-server-addr = ":9090"
pprof = true

logs = { info = "/data/monstache6.1.0/logs/info.txt", warn = "/data/monstache6.1.0/logs/warn.txt", error = "/data/monstache6.1.0/logs/error.txt", trace = "/data/monstache6.1.0/logs/trace.txt", stats = "/data/monstache6.1.0/logs/stats.txt" }
mapper-plugin-path = "/data/monstache6.1.0/plugin/englishOnly.so"

mongo-url = "mongodb://monstache:password@server:27017/db.collection?authSource=monstache"


# I have a clustered MongoDB running. I am not sure if
# the following setting needs to be set or not. Currently
# it is not set and monstanche can sychronize Mongodb
# and elasticsearch without problems
#mongo-config-url = "mongodb://server:27019"

elasticsearch-urls = ["http://server:9200"]
elasticsearch-user = "monstache"
elasticsearch-password = "password"
elasticsearch-retry = true

# As I understood when using change-stream-namespaces the following setting is not required.
#namespace-regex = '^db/.collection$'

direct-read-namespaces = ["db.collection"]
change-stream-namespaces = ["db.collection"]
gzip = true
stats = true
elasticsearch-max-conns = 4 
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
verbose = false
exit-after-direct-reads = false
```

**Comment by rwynn** [comment]
@onur-gokce your configuration looks ok to me.  

You are correct that you **do not** need `mongo-config-url` or `namespace-regex` when using `change-stream-namespaces`.  

When you specify `direct-read-namespaces` monstache will always do a full sync of any collections/views that you specify.  So, after you complete the initial sync you can comment out this setting.  Or you can have 2 config files, one for initial sync and another for realtime sync.  

Initial sync
```toml
direct-read-namespaces = [ "db.collection"]
exit-after-direct-reads = true
resume = true
```

Realtime
```toml
change-stream-namespaces = ["db.collection"]
resume = true
```
You should be seeing a timestamp produced in collection `monstache.monstache` with this configuration.  

```
rs1:PRIMARY> use monstache;
switched to db monstache
rs1:PRIMARY> db.monstache.find()
{ "_id" : "default", "ts" : Timestamp(1573052132, 6) }
```

After the initial sync is done you only need to restart with the realtime config.

**Comment by onur-gokce** [comment]
Hello @rwynn,
Thanks a lot for your prompt reply and the information.
Monstache now works as I expected after following your suggestions.

**Comment by mix4242** [comment]
Hi @rwynn.

I appreciate this is an old & resolved issue, but in the example you give for the initial sync config above, you include `resume = true`. Does that mean that restarts of monstache running that initial sync config will carry on indexing from the last indexed document, not start the entire direct-reads from scratch?
