### ISSUE TITLE
Unauthorized on monstache to execute command

### ISSUE THREAD

**Issue by blackholegalaxy** [rwynn/monstache#306]
Using latest version of monstache, on a fresh DB, we encounter many and many errors in logs:

```
ERROR 2019/11/08 19:52:59 (Unauthorized) not authorized on monstache to execute command
 { update: "monstache", lsid: { id: UUID("700759db-793a-4a70-83a2-fbc10139fde6") }, txnNumber: 48, 
$clusterTime: { clusterTime: Timestamp(1573260778, 1), signature: { hash: BinData(0, 
CF24798CFC881BBF7FB1AA4B780E9B3F0351501D), keyId: 6757027603028115457 } }, 
$db: "monstache" }
```

Is there any manipulation to do on database before hooking monstache to it? Do we need to add a user or a monstache db? Can't see any monstache db anywhere.

**Comment by rwynn** [comment]
@blackholegalaxy check out the first note under https://rwynn.github.io/monstache-site/start/#usage.

It sounds like MongoDB has auth enabled.  In which case the user you connect with will need certain priviledges.   

If you enable `resume` or `cluster-name` then the user in the connection string needs write and create index access to the MongoDB database named `monstache` (you can override the name of the db with `config-database-name`).   

You can use a command like this ... https://docs.mongodb.com/manual/reference/command/grantRolesToUser/#example

So for example...

```javascript
db.runCommand( { grantRolesToUser: "monstacheUser",
                 roles: [
                    { role: "readWrite", db: "monstache"}
                 ],
                 writeConcern: { w: "majority" , wtimeout: 2000 }
             } )
```

**Comment by blackholegalaxy** [comment]
Missed this part of the doc :D It worked thanks :)
