### ISSUE TITLE
Sync 2 collections to 1 index

### ISSUE THREAD

**Issue by mjacquin** [rwynn/monstache#307]
Hello rwynn.

I'm trying to sync 2 collections to 1 index and I encounter some problems.
At first I was using scripts to transform the document by doing a find on the other collection but this run very poorly at 20 index/s...
Then I saw the `relate` option so I created a mongo view with a lookup on the other collection and configured monstache so that the view is used instead when a modification occur on any of the 2 collections.
```
[[mapping]]
namespace = "db.tracks_view"
index = "db.tracks"

[[relate]]
namespace = "db.tracks"
with-namespace = "db.tracks_view"
keep-src = false

[[relate]]
namespace = "db.tracks_maia"
with-namespace = "db.tracks_view"
keep-src = false
```

This is kinda working but I have other problems now.
- During mass update I have the `Relate queue is full` error and update are skipped which means ES and mongo are no longer synced :(
- I can't `direct-read` on `tracks_view` because the collections have about 1 million items and the direct read never start. (I guess you are doing a sort which is not working on a view with a lookup)

Any idea on how I should do this ?

**Comment by rwynn** [comment]
Hi @mjacquin, for the relate queue full message, you can increase the size of the buffer to help remove this error.

```toml
# defaults to 1000 only
relate-buffer = 5000000
```
When a mass update occurs this triggers lots of lookups when `relate` is turned on since monstache needs to redirect to the view to retrieve the source document for Elasticsearch.  I wanted to make this bounded so that is the reason why the buffer was created.  

For the second item, you should be able to use a view in `direct-read-namespaces`.  I just tested this again on a view with 4 million documents and it appears to still be working for me using monstache `v6.3.1` against MongoDB `v4.0.13`.   Do you get any error messages?  What versions of monstache and MongoDB are you running with?

It took about 10 minutes for me to sync the `test.testView` using the following setup...

```
rs1:PRIMARY> db.test.count()
4000000
rs1:PRIMARY> db.createView("testView", "test", [{$match: {c32: {$gt: 0}}}]);
{
        "ok" : 1,
        "operationTime" : Timestamp(1573658946, 1),
        "$clusterTime" : {
                "clusterTime" : Timestamp(1573658946, 1),
                "signature" : {
                        "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                        "keyId" : NumberLong(0)
                }
        }
}
rs1:PRIMARY> db.testView.count()
4000000
```

```toml
direct-read-namespaces = [ "test.testView" ]
exit-after-direct-reads = true

[[mapping]]
namespace = "test.testView"
index = "myindex"
```

```
time go run monstache.go -f ~/config.toml 
INFO 2019/11/13 15:12:49 Started monstache version 6.3.2
INFO 2019/11/13 15:12:49 MongoDB go driver v1.1.3
INFO 2019/11/13 15:12:49 Elasticsearch go driver 7.0.9
INFO 2019/11/13 15:12:49 Successfully connected to MongoDB version 4.0.13
INFO 2019/11/13 15:12:49 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/11/13 15:12:49 Listening for events
INFO 2019/11/13 15:12:49 Watching changes on the deployment
INFO 2019/11/13 15:22:37 Direct reads completed
INFO 2019/11/13 15:22:37 Stopping all workers
INFO 2019/11/13 15:22:37 Shutting down

real    9m55.070s
user    13m35.148s
sys     0m26.176s
```

```
curl localhost:9200/myindex/_count?pretty
{
  "count" : 4000000,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  }
}

```

**Comment by mjacquin** [comment]
Thanks for the quick reply @rwynn 

I will try the `relate-buffer`

For the view mine has a `$lookup` in the aggregation pipeline
```javascript
db.tracks.aggregate([
    {
        "$lookup": {
            "from": "tracks_maia",
            "localField": "_id",
            "foreignField": "_id",
            "as": "maia"
        }
    },
    {
        "$unwind": {
            "path": "$maia",
            "preserveNullAndEmptyArrays": true
        }
    },
    {
        "$project": {
            "maia._id": 0,
            "maia.tenant": 0,
            "maia.raw": 0,
            "maia.updated_at": 0
        }
    }
]).saveAsView("tracks_view");
```

When I start the direct read on this view I can see the operation in mongo hanging for minutes...
I looked at your project `gtm` and I see that you set a sort on the query
If you sort on a view a `$sort` stage will be added at the end of the aggregation pipeline and I assume that what mongo is trying to do is looking up every single document with the `$lookup` stage and then sorting it.

This query never end
```javascript
db.tracks_view.find({})
    .sort({ _id: -1 })
```

```javascript
db.tracks_view.find({})
    .sort({ _id: -1 })
    .explain()
```
```javascript
{
	"stages" : [
		{
			"$cursor" : {
				"query" : {
					
				},
				"queryPlanner" : {
					"plannerVersion" : 1,
					"namespace" : "db.tracks",
					"indexFilterSet" : false,
					"parsedQuery" : {
						
					},
					"queryHash" : "8B3D4AB8",
					"planCacheKey" : "8B3D4AB8",
					"winningPlan" : {
						"stage" : "COLLSCAN",
						"direction" : "forward"
					},
					"rejectedPlans" : [ ]
				}
			}
		},
		{
			"$lookup" : {
				"from" : "tracks_maia",
				"as" : "maia",
				"localField" : "_id",
				"foreignField" : "_id",
				"unwinding" : {
					"preserveNullAndEmptyArrays" : true
				}
			}
		},
		{
			"$project" : {
				"maia" : {
					"_id" : false,
					"raw" : false,
					"tenant" : false,
					"updated_at" : false
				}
			}
		},
		{
			"$sort" : {
				"sortKey" : {
					"_id" : -1
				}
			}
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1573661475, 1),
		"signature" : {
			"hash" : BinData(0,"qkJ4FIbBRF5tW/9zE4gWcZG7X/Q="),
			"keyId" : 6743883010237530114
		}
	},
	"operationTime" : Timestamp(1573661472, 1)
}
```

**Comment by rwynn** [comment]
@mjacquin gtm does a sort but only in the initial phase to break the collection/view into segments for reading concurrently....
https://github.com/rwynn/gtm/blob/master/gtm.go#L1426

You can turn off the collection/view segmenting by setting

```
direct-read-split-max = -1
```

Then you will be left with gtm simply reading the entire view with one cursor without a sort in...
https://github.com/rwynn/gtm/blob/master/gtm.go#L1070

**Comment by mjacquin** [comment]
@rwynn I set `direct-read-split-max = -1` and the direct read start after about 5min now.

The 5min seems to be due to a `count` operation on the collection (view)
I dunno if this is a mandatory operation or if it can be avoided but at least it's working after the 5min :)

Thanks for the help.
Amazing work !

**Comment by rwynn** [comment]
I'll see what I can do about optioning out that `count` operation.  It's used in conjunction with the avg document size to try to estimate the best batch size to use.  However, it looks like this operation is expensive.  I wonder how the `count` operation performs against the collection vs the view.  I would guess the former would be much faster.  I guess MongoDB is not able to optimize this for views due to possible $match stages?

BTW, I really wish there was a way to differentiate a view from a collection in the driver.  I cannot seem to find a way ask MongoDB to answer that.

**Comment by mjacquin** [comment]
Yes this operation is very expensive on my view (killing my db :p)
On a regular collection there is no impact.

This is a messy way to do it but if you do `db.collection.getIndexes()` on a view, you will get an error :
```json
{
	"message" : "Namespace db.tracks_view is a view, not a collection",
	"operationTime" : "Timestamp(1573666166, 1)",
	"ok" : 0,
	"code" : 166,
	"codeName" : "CommandNotSupportedOnView",
	"$clusterTime" : {
		"clusterTime" : "Timestamp(1573666166, 1)",
		"signature" : {
			"hash" : "BlHGGgFFhVWjap6SZ4i8AtJaPHM=",
			"keyId" : "6743883010237530114"
		}
	},
	"name" : "MongoError"
}
```
Maybe you can check if it's a view like that ?

**Comment by rwynn** [comment]
Actually, I think `db.getCollectionInfos` will give me the type (collection vs view).  I think I can try to use that to optimize this.

**Comment by rwynn** [comment]
@mjacquin I think I am now able to detect the view and just go directly into read cursor mode. 

https://github.com/rwynn/gtm/blob/v2.0.4/gtm.go#L1415

If you are able to pull the latest commit in monstache `rel6` or `rel5` and give me any feedback on whether or not this improves the situation for you?

I was going to push a new release soon and hope to get this fix verified before that.  If a local build is not convenient for you to test I'll just cut the release based on my testing.

**Comment by mjacquin** [comment]
@rwynn Wow nice! This is working perfectly now :)

Thanks for the amazing work 👍

When will you release this as a docker image ?

**Comment by rwynn** [comment]
@mjacquin, I just released a new docker image.  Thanks for working through this issue;  let me know if you see any problems.

**Comment by mjacquin** [comment]
@rwynn Thanks a lot :)
