### ISSUE TITLE
server selection error: server selection timeout

### ISSUE THREAD

**Issue by johncarmack1984** [rwynn/monstache#309]
`$ monstache`:

```
ERROR 2019/11/15 03:35:16 Unable to connect to MongoDB using URL mongodb://localhost:27017: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
Addr: <hostname>:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27017[-360]) connection is closed
Addr: <hostname>:27018, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27018[-361]) connection is closed
Addr: <hostname>:27019, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27019[-362]) connection is closed
```

`rs.status()`:

```
{
	"set" : "rs0",
	"date" : ISODate("2019-11-15T11:34:24.146Z"),
	"myState" : 1,
	"term" : NumberLong(6),
	"syncingTo" : "",
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 2,
	"writeMajorityCount" : 2,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1573817656, 1),
			"t" : NumberLong(6)
		},
		"lastCommittedWallTime" : ISODate("2019-11-15T11:34:16.581Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1573817656, 1),
			"t" : NumberLong(6)
		},
		"readConcernMajorityWallTime" : ISODate("2019-11-15T11:34:16.581Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1573817656, 1),
			"t" : NumberLong(6)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1573817656, 1),
			"t" : NumberLong(6)
		},
		"lastAppliedWallTime" : ISODate("2019-11-15T11:34:16.581Z"),
		"lastDurableWallTime" : ISODate("2019-11-15T11:34:16.581Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1573817636, 1),
	"lastStableCheckpointTimestamp" : Timestamp(1573817636, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "priorityTakeover",
		"lastElectionDate" : ISODate("2019-11-15T11:33:36.195Z"),
		"termAtElection" : NumberLong(6),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(1573817606, 1),
			"t" : NumberLong(5)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1573817606, 1),
			"t" : NumberLong(5)
		},
		"numVotesNeeded" : 2,
		"priorityAtElection" : 1,
		"electionTimeoutMillis" : NumberLong(10000),
		"priorPrimaryMemberId" : 2,
		"numCatchUpOps" : NumberLong(1375993858),
		"newTermStartDate" : ISODate("2019-11-15T11:33:36.575Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2019-11-15T11:33:37.722Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "<hostname>:27017",
			"ip" : "127.0.0.1",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 79,
			"optime" : {
				"ts" : Timestamp(1573817656, 1),
				"t" : NumberLong(6)
			},
			"optimeDate" : ISODate("2019-11-15T11:34:16Z"),
			"syncingTo" : "",
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1573817616, 1),
			"electionDate" : ISODate("2019-11-15T11:33:36Z"),
			"configVersion" : 2,
			"self" : true,
			"lastHeartbeatMessage" : ""
		},
		{
			"_id" : 1,
			"name" : "<hostname>:27018",
			"ip" : "127.0.0.1",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 62,
			"optime" : {
				"ts" : Timestamp(1573817656, 1),
				"t" : NumberLong(6)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1573817656, 1),
				"t" : NumberLong(6)
			},
			"optimeDate" : ISODate("2019-11-15T11:34:16Z"),
			"optimeDurableDate" : ISODate("2019-11-15T11:34:16Z"),
			"lastHeartbeat" : ISODate("2019-11-15T11:34:22.253Z"),
			"lastHeartbeatRecv" : ISODate("2019-11-15T11:34:23.758Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "",
			"syncingTo" : "<hostname>:27017",
			"syncSourceHost" : "<hostname>:27017",
			"syncSourceId" : 0,
			"infoMessage" : "",
			"configVersion" : 2
		},
		{
			"_id" : 2,
			"name" : "<hostname>:27019",
			"ip" : "127.0.0.1",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 68,
			"optime" : {
				"ts" : Timestamp(1573817656, 1),
				"t" : NumberLong(6)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1573817656, 1),
				"t" : NumberLong(6)
			},
			"optimeDate" : ISODate("2019-11-15T11:34:16Z"),
			"optimeDurableDate" : ISODate("2019-11-15T11:34:16Z"),
			"lastHeartbeat" : ISODate("2019-11-15T11:34:22.253Z"),
			"lastHeartbeatRecv" : ISODate("2019-11-15T11:34:22.392Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "",
			"syncingTo" : "<hostname>:27018",
			"syncSourceHost" : "<hostname>:27018",
			"syncSourceId" : 1,
			"infoMessage" : "",
			"configVersion" : 2
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1573817656, 1),
		"signature" : {
			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
			"keyId" : NumberLong(0)
		}
	},
	"operationTime" : Timestamp(1573817656, 1)
}
```

**Comment by rwynn** [comment]
@johncarmack1984 check out this issue from yesterday https://github.com/rwynn/monstache/issues/308

**Comment by rwynn** [comment]
Have you tried connecting with the hostname set to the value of <hostname> in your `rs.status()` output instead of using localhost?

Adding `direct=true` may fix it but I've not needed to use that.

**Comment by johncarmack1984** [comment]
With hostname set to `rs.status()` output:

```
ERROR 2019/11/15 04:43:38 Unable to connect to MongoDB using URL mongodb://<hostname>:27017/: server selection error: server selection timeout
current topology: Type: Unknown
Servers:
Addr: <hostname>:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27017[-121]) connection is closed
```

Where would I add `direct=true`? At the end of the hostname, like `mongo-url = "mongodb://<hostname>l:27017/?direct=true"` or somewhere else?

**Comment by johncarmack1984** [comment]
Output with it at the end of URL like above:

```
ERROR 2019/11/15 04:46:29 Unable to connect to MongoDB using URL mongodb://<hostname>:27017/?direct=true: server selection error: server selection timeout
current topology: Type: Unknown
Servers:
Addr: <hostname>:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27017[-121]) connection is closed
```

**Comment by johncarmack1984** [comment]
Looking through that thread, and the StackOverflow answer, I tried:

`mongo-url = "mongodb://<hostname>:27017/?connect=direct"`

with result:

```
ERROR 2019/11/15 05:47:26 Unable to connect to MongoDB using URL mongodb://<hostname>:27017/?connect=direct: server selection error: server selection timeout
current topology: Type: Single
Servers:
Addr: <hostname>:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(<hostname>:27017[-121]) connection is closed
```

**Comment by johncarmack1984** [comment]
Also I'm not running in Docker, just on OS X, not sure if that's useful info or not.

**Comment by rwynn** [comment]
Not sure if it would be helpful but you might check out the monstache test setup:
https://github.com/rwynn/monstache/tree/v6.3.2/docker/test

That seems to be able to [connect](https://travis-ci.org/rwynn/monstache/builds/612210536) but not sure if you setup is different.

**Comment by rwynn** [comment]
@johncarmack1984 docker is not required so you **should** be ok.  This issue is a bit old but might be helpful:

https://jira.mongodb.org/browse/GODRIVER-674

I guess I would look into https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#bind-ip-compatibility and make sure the hostnames in `rs.status()` are bound by mongod and that you can resolve all of them from the host.  

Also, maybe check the mongodb logs for any clues.

**Comment by johncarmack1984** [comment]
Okay... I think rather than incorporate Docker into the stack at this point in time, I'll pursue an alternate method of syncing Mongo and elasticsearch. Thanks for your time :)

**Comment by johncarmack1984** [comment]
Yep, I'm binding mongod to the hostname, I'm using the [mongodb docs recommended commands for building a replica set for testing.](https://docs.mongodb.com/manual/tutorial/deploy-replica-set-for-testing/). here's the commands I'm using for each of the mongod instances, maybe there's something I'm missing in here:

`mongod --replSet rs0 --port 27017 --bind_ip localhost,<hostname> --dbpath /usr/local/var/mongodb/rs0-0  --oplogSize 128`

`mongod --replSet rs0 --port 27018 --bind_ip localhost,<hostname> --dbpath /usr/local/var/mongodb/rs0-1  --oplogSize 128`

`mongod --replSet rs0 --port 27019 --bind_ip localhost,<hostname> --dbpath /usr/local/var/mongodb/rs0-2 --oplogSize 128`

The replica set is working, updates to the primary are automatically sent to the secondaries, so that's good. :) Just can't quite get golang to find it.

**Comment by johncarmack1984** [comment]
Mongod log from the primary (27017):

```2019-11-15T08:22:25.002-0800 I  NETWORK  [listener] connection accepted from 127.0.0.1:54685 #23 (15 connections now open)
2019-11-15T08:22:25.002-0800 I  NETWORK  [conn23] received client metadata from 127.0.0.1:54685 conn23: { driver: { name: "mongo-go-driver", version: "v1.1.2" }, os: { type: "darwin", architecture: "amd64" }, platform: "go1.12.6" }
2019-11-15T08:22:25.002-0800 I  NETWORK  [conn23] end connection 127.0.0.1:54685 (14 connections now open)```

**Comment by johncarmack1984** [comment]
Found a way to make it work using another method, this issue remains unresolved within monstache but because I am no longer using monstache I'll go ahead and close the issue. thanks for your help, I appreciated having a few things to try :)

**Comment by rwynn** [comment]
@johncarmack1984 glad you found a solution to even though it wasn't monstache unfortunately.  If you had some spare time I would appreciate if you tried the latest monstache v6.3.2.  It uses golang 1.13.4 and mongodb go driver v1.1.3.  Not sure if that would make any difference, but would be good to know.

**Comment by rwynn** [comment]
@johncarmack1984 I was curious so I tried this on macOS High Sierra after downloading latest monstache and MongoDB community edition 4.2.1.

Made only the following changes...

```
mongod --replSet rs0 --port 27017 --bind_ip localhost --dbpath ~/data/rs0-0 --oplogSize 128

mongod --replSet rs0 --port 27018 --bind_ip localhost --dbpath ~/data//rs0-1 --oplogSize 128

mongod --replSet rs0 --port 27019 --bind_ip localhost --dbpath ~/data/rs0-2 --oplogSize 128
```
Then ran `rs.initiate()` in the mongo shell.

And monstache v6.3.2 started right up without any connection errors (no extra config). 

```
./monstache
```

Maybe I'll try adding the hostname to try to replicate it.

**Comment by johncarmack1984** [comment]
Hmmm. there may be something unique to my setup that is preventing them from seeing each other, I tried those mongod commands & I'm still getting the same errors. Server selection error, server selection timeout. ¯\_(ツ)_/¯

**Comment by adit-yaa** [comment]
I have run into the same problem, the code was working fine earlier I did not change anything in it but all of a sudden this error starts showing up

**Comment by adit-yaa** [comment]
okay so I found the solution to this issue lol it was just that I hadn't whitelisted the IP that I was using.

**Comment by Sakura-by** [comment]
> okay so I found the solution to this issue lol it was just that I hadn't whitelisted the IP that I was using.

Hi, I meet the same problem just as this. Can you describe how you solve it little more detailed, please? That would be helpful for me. Thanks!😀

**Comment by Sakura-by** [comment]
> > okay so I found the solution to this issue lol it was just that I hadn't whitelisted the IP that I was using.
> 
> Hi, I meet the same problem just as this. Can you describe how you solve it little more detailed, please? That would be helpful for me. Thanks!😀

Oh, I hava solve it by add param 'connect=direct'. Sorry to bother you!

**Comment by hjander** [comment]
I faced exactly the same error message when trying to connect to AWS DocumentDB but could not resolve it with adding  'connect=direct'. Instead it turned out i had forgotten to add the certificates to the connectionstring. The following worked for me:
mongodb://.......docdb.amazonaws.com:27017/test?tlsCAFile=/app/rds-ca-2019-root.pem
