### ISSUE TITLE
Support parent-child relationships

### ISSUE THREAD

**Issue by bmin** [rwynn/monstache#31]
I was playing with this tool, work just fine. Was looking for a way to make parent-child relationships. Do you have any plan to provide support for parent-child relationships?

**Comment by rwynn** [comment]
Thanks, I will take a look at making this happen.

**Comment by rwynn** [comment]
I've added initial support for this but not added to the docs yet.  For now you would need to build yourself and use javascript or a golang plugin to accomplish parent-child.
If you follow the example at https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child.html then a javascript snippet to for parent-child would look something like this:

```

[[script]]
namespace = "test.company"
routing = true
script = """
module.exports = function(doc) {
	doc._meta_monstache = { type: doc.type };
	if (doc.type === "employee") {
		doc._meta_monstache.parent = doc.parent;
	}
	delete doc.parent;
	delete doc.type;
	return doc;
}
"""
```

Your mongodb docs would need to have a `type`attribute and optionally a `parent` attribute for the children.  
You don't need the `type` attribute but just some way to distinguish between the two and override the ES type accordingly.

**Comment by rwynn** [comment]
Btw snippet above will use index test.company instead of simply company. You can override the index in monstache or add your mapping’s to test.company index instead of company.

**Comment by bmin** [comment]
Thank you for replying prompt action; I made bit of a hack to serve my purpose; but certainly I will follow your propose way to achieve this. I will grab and test it; and will let you know :)

**Comment by bmin** [comment]
@rwynn : Thank you, I have tested it today, worked as expected. Closing the issue.

**Comment by kimus** [comment]
How can this be done with multiple collections?

I was trying something like this and nothing happens:

```
[[script]]
namespace = "some.User"
script = """
module.exports = function(doc) {
  doc._meta_monstache = { routing: doc._id };
  return _.omit(doc, "password", "verificationToken");
}
"""

[[script]]
namespace = "some.Profile"
routing = true
script = """
module.exports = function(doc) {
  var meta = { type: 'profile' };
  var id = doc.userId;
  if (id) {
    meta.parent = id;
    meta.routing = id;
  }
  doc._meta_monstache = meta;
  return _.omit(doc, "userId");
}
"""
```
