### ISSUE TITLE
Can I use Monstache with ingest node?

### ISSUE THREAD

**Issue by kychanbp** [rwynn/monstache#310]
Can I do enrichment through ingest node before indexing into Elasticsearch? Similar to Logstash?

**Comment by rwynn** [comment]
@kychanbp you can use monstache middleware in golang or javascript to set the `pipeline` option in bulk index requests.  

Read the docs on [middleware](https://rwynn.github.io/monstache-site/advanced/#middleware) and look for how to set the `pipeline` option. 

Alternatively, you can use an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-templates.html) to setup the [index.default_pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html#dynamic-index-settings) and then you need not specify the pipeline through monstache.

**Comment by kychanbp** [comment]
@rwynn Thanks! I will go for the alternative option!

**Comment by SHwan93** [comment]
@kychanbp is it work?

**Comment by rwynn** [comment]
@SHwan93 @kychanbp since this question was asked `pipeline` became a simple attribute on a `mapping` configuration.  This makes it possible to solve the problem without a go/javascript plugin.

https://rwynn.github.io/monstache-site/config/#pipeline

```toml
[[mapping]]
namespace = "db.col"
pipeline = "mypipeline"
```

**Comment by SHwan93** [comment]
@rwynn 
you mean no need to edit plugin.go and  to insert index.default_pipeline in template?

Just add pipline in toml file?
right?

**Comment by SHwan93** [comment]
it isn't work

`
mongo-url = "mongodb://xxxxxxx"
elasticsearch-urls = ["http://elasticsearch:9200"]
direct-read-namespaces = ["social-monitor-dev.MonitoringData"]
change-stream-namespaces = ["social-monitor-dev.MonitoringData"]
gzip = false
stats = true
index-stats = false
index-files = false
elasticsearch-max-conns = 4 
dropped-collections = false
dropped-databases = false
resume = true
resume-write-unsafe = false
resume-name = "ian"
resume-strategy = 0
file-highlighting = false
exit-after-direct-reads = false
mapper-plugin-path = "/monstache/plugin.so"
enable-oplog=true
elasticsearch-healthcheck-timeout-startup=10
elasticsearch-retry=true

[logs]
info = "/dev/stdout"
warn = "/dev/stdout"
error = "/dev/stderr"

[[mapping]]
namespace="social-monitor-dev.MonitoringData"
index="data"
pipeline="monitoringdata-monthly-index"
`

monstache insert data in wrong index. 
but, if I send the request directly it works fine.
`
curl -X PUT -H "Content-Type: application/json; charset=utf-8" -d '{
  "uploadedAt" : "2021-06-01T12:02:01.789Z"
}' http://localhost:9200/monitoringdata/_doc/1?pipeline=mydata-monthly-index
`

**Comment by rwynn** [comment]
@SHwan93 yes, if all you need is to assign an ingest pipeline you can now do this directly in the toml config without needing a plugin.
https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html

**Comment by SHwan93** [comment]
@rwynn  Thanks a lot
