### ISSUE TITLE
no Elasticsearch node available

### ISSUE THREAD

**Issue by ry13er** [rwynn/monstache#314]
I have been trying to get the contianerized version of monstache up and running on my local machine and have been struggling for a few days now with not being able to connect elastic search.  The following is the command I am running and the error I keep getting.

docker run -it --net=host -v C:/Dockerdata/monstache:/config rwynn/monstache:latest -f /config/config.toml
INFO 2019/12/10 19:45:25 Started monstache version 6.4.1
INFO 2019/12/10 19:45:25 MongoDB go driver v1.1.3
INFO 2019/12/10 19:45:25 Elasticsearch go driver 7.0.9
INFO 2019/12/10 19:45:25 Successfully connected to MongoDB version 4.0.13
ERROR 2019/12/10 19:45:40 Unable to create Elasticsearch client: health check timeout: Head http://localhost:9200: dial tcp [::1]:9200: connect: connection refused: no Elasticsearch node available

my config is set as follows
mongo-url = "mongodb://dk_customer*************************"
elasticsearch-urls = [ "http://localhost:9200" ]
verbose = true
enable-http-server = true
direct-read-namespaces = ["dk_customer_graph_sandbox.testcustchanges"]
change-stream-namespaces = ["dk_customer_graph_sandbox.testcustchanges"]

This works just fine running the .exe locally

I would appreciate any help I can get.  thanks in advance.

**Comment by rwynn** [comment]
@ry13er I've not used Docker for Windows, only for Linux.  But, this [stackoverflow link](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) seems to have some tips to get it working.  

It seems that maybe `--net=host` only works on linux hosts.

**Comment by ry13er** [comment]
thanks for pointing me in the right direction.  
using elasticsearch-urls = [ "http://host.docker.internal.9200" ] worked.
