### ISSUE TITLE
Mapping for direct read

### ISSUE THREAD

**Issue by leandono** [rwynn/monstache#315]
Hi,
Is there any way to map and manipulate values of a document when a direct read is running? I read all the documentation and I saw that:

- The Map function allows add custom properties to the doc to be saved in Elastic, but only is called for changes
- The Pipeline function is called for direct read and changes, and I know that I can use a combination of`$addFields` and `$project` to add properties, but in my case, I need also manipulate the value to insert (like remove characters by length and replace).

Thanks

**Comment by rwynn** [comment]
Hi @leandono, the `Map` function should be run for direct reads.  The direct reads are sent as inserts.  Are you not seeing the data being sent for direct reads?

Another way to do it is on the Elasticsearch side by setting up your indexes with a default pipeline.  There is [alot you can do](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-conditional-complex.html) in an Elasticsearch pipeline and it may be a good alternative to a monstache plugin.

**Comment by leandono** [comment]
Maybe could be that for direct reads using MongoDB views the Map function is not used?

**Comment by rwynn** [comment]
I'm pretty sure it should be used for those, too.  The map function is called before indexing [here](https://github.com/rwynn/monstache/blob/v6.4.1/monstache.go#L934) and I think everything goes through that via the [indexC](https://github.com/rwynn/monstache/blob/v6.4.1/monstache.go#L4489) channel.

**Comment by leandono** [comment]
Sorry for the delay, but you are right! Maybe was a confusion testing different approaches, thanks
