### ISSUE TITLE
Golang process function version conflicts

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#318]
Hi @rwynn,

I'm using a golang plugin that simply uses the Elastic client within the `Process` function to index/update documents (only input.ElasticClient.Update(), not update_by_query, so only one Elastic document is affected), i.e. something like this:

```
// Skips all documents and lets Process() deal with the documents
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	output = &monstachemap.MapperPluginOutput{Document: input.Document, Skip: true}
	return
}

// Process - plugin function for monstache
func Process(input *monstachemap.ProcessPluginInput) (err error) {

	ctx := context.Background()
	docs := someTransformation(ctx, input.Document, input.MongoClient, input.ElasticClient)

	for _, doc := range docs {
		handleDocs(input, doc)
	}
	return
}
```

and here is my toml file:

```
verbose = false
elasticsearch-max-conns = 2
elasticsearch-max-seconds = 10
direct-read-no-timeout = true
elasticsearch-max-bytes = 2500000000
enable-http-server = false
exit-after-direct-reads = false
resume = true
direct-read-bounded = true
direct-read-split-max = 1
disable-change-events = false
```

Under very heavy inserts into Mongo, I'm getting the occasional 409 version conflict. I've noticed that these 409 conflicts happen with the updates to the more heavy documents in Elastic which have many nested documents. I'm wondering if this because of `elasticsearch-max-conns = 2`, does this mean that there are effectively 2 workers processing docs (via the `Process` function) and thus causing inserts/updates to be out of order?

**Comment by rwynn** [comment]
Hi @IchorPop monstache starts many concurrent go routines.  `elasticsearch-max-conns` determines the number of go routines that actually send bulk requests to Elasticsearch.  For each conn there is a corresponding buffer and that buffer will be flushed periodically according to other settings such as max-seconds, max-bytes, and max-docs.  Additionally, there is a setting `post-processors`.  This defaults to 10 and is the number of go routines that will concurrently be executing your `Process` function.  

So, basically, you have to assume that events will be processed out of order and use a document [version](https://www.elastic.co/blog/elasticsearch-versioning-support) to ensure that old data gets rejected in the event it is sent after new data. 

Monstache does this by default by using the [MongoDB event timestamp as the version number](https://github.com/rwynn/monstache/blob/rel6/monstache.go#L1127).  If events happen to document D at T1 and T2, but the document at T2 is sent to Elasticsearch first, then when T1 data is sent it will be rejected by Elasticsearch with a 409 version conflict.  This is actually what you want - reject old data.  I don't consider it a real error and monstache [no longer logs 409 as an error](https://github.com/rwynn/monstache/blob/rel6/monstache.go#L457).  

I am not sure by your post, but the `ProcessPluginInput` passed into the function gives access to a `ElasticBulkProcessor` field.  You can use this to queue documents for indexing [the same way](https://github.com/rwynn/monstache/blob/rel6/monstache.go#L2775) monstache does.

**Comment by IchorPop** [comment]
Thank you for the explanation!
