### ISSUE TITLE
Plugin package error: built with a different version of package github.com/globalsign/mgo/internal/json

### ISSUE THREAD

**Issue by ialisyed** [rwynn/monstache#322]
Hi, 
I am getting this error:
**plugin was built with a different version of package github.com/globalsign/mgo/internal/json
INFO 2019/12/27 17:28:59 Shutting down with exit status 1 after panic.**

**monstache version** 3.26.2
**go version** go1.13.4 linux/amd64

I am building the plugin from the tag 3.26.2 as stated in documentation but still I am getting this issue. What's the problem here?

**Comment by rwynn** [comment]
Hi @ialisyed,

This seems to work OK for me...

```sh
$ git status
HEAD detached at v3.26.2
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        plugin.go

nothing added to commit but untracked files present (use "git add" to track)
```

```sh
$ cat plugin.go
package main

import (
        "gopkg.in/rwynn/monstache.v3/monstachemap"  // matches monstache.go import
        "strings"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
        doc := input.Document
        for k, v := range doc {
                switch v.(type) {
                case string:
                        doc[k] = strings.ToUpper(v.(string))
                }
        }
        output = &monstachemap.MapperPluginOutput{Document: doc}
        return
}
```

```sh
$ go install
$ go build -buildmode=plugin -o plugin.so plugin.go
$ which monstache.v3
/home/vagrant/go/bin/monstache.v3
$ monstache.v3 --mapper-plugin-path plugin.so
INFO 2019/12/27 19:11:02 Started monstache version 3.26.2
INFO 2019/12/27 19:11:02 Successfully connected to MongoDB version 4.0.13
INFO 2019/12/27 19:11:02 Successfully connected to Elasticsearch version 7.0.0
INFO 2019/12/27 19:11:02 Listening for events
```

**Comment by ialisyed** [comment]
Hi @rwynn Thanks for looking into it,
Which go version are you using with it?
I am doing everything in `/root`. I tried all day with different versions of go and monstache and I was keep getting error of different version, either of package "errors" or for "internal/json" or for the the one I mentioned

**Comment by rwynn** [comment]
go version go1.13.4 linux/amd64

Are you also building the binary using `go install`.  That should help pair up the binary and the plugin.

**Comment by rwynn** [comment]
For what it's worth I get the same error you do when I try to use the monstache binary from github downloads.  I think that is just because the plugin loading is very picky.  It helps if you build the monstache binary using `go install` inside the same checkout of `v3.26.2`.

**Comment by ialisyed** [comment]
Yes :/
`go mod download`
`go install`
`go build -buildmode=plugin -o plugin.so plugin.go`
`monstache --mapper-plugin-path plugin.so`

**Comment by rwynn** [comment]
Try running `monstache.v3` or rename the binary in `/root/go/bin/monstache.v3` to monstache.

**Comment by rwynn** [comment]
What versions of MongoDB and Elasticsearch are you using?  Are you using monstache v3 because of an older version of Elasticsearch?

**Comment by ialisyed** [comment]
I followed these steps to download and setup monstache. Has it got something to do with it?
```
sudo mkdir monstache
cd monstache
sudo wget https://github.com/rwynn/monstache/releases/download/v4.15.0/monstache-eee3f26.zip
sudo unzip monstache-eee3f26.zip
export PATH=“<monstache Installation Path>:$PATH”
          Ex export PATH=/opt/monstache/build/linux-amd64:$PATH
monstache -v
> 4.15.0
```

**Comment by ialisyed** [comment]
yes, I have elastic search 2.4. 
When I run only `monstache` it works fine. But it gives error with plugin.

**Comment by rwynn** [comment]
Yes, I find that if you are going to be using plugins, it's better to build the binary instead of downloading it.   So the step where you run `go install` is going to install a binary at `/root/go/bin/monstache.v3`.  Use that binary instead of the one you downloaded.  You can rename it to `monstache` after you run `go install` or simply use `monstache.v3`.

**Comment by ialisyed** [comment]
Okay. Thanks a lot @rwynn! I will look into it once I get back to work.

**Comment by rwynn** [comment]
@ialisyed no problem let me know how that goes.

**Comment by ialisyed** [comment]
It worked. Thanks A lot! 
One more thing,
I am opening sql connection to fetch some data in map function of plugin but it is making too many connections as per data. Is it possible to make connection only one type and then query as per records?
