### ISSUE TITLE
[[relate]] not working

### ISSUE THREAD

**Issue by gate3** [rwynn/monstache#323]
Hi, 

This is an absolutely awesome project, I intend to learn Go just so I can contribute. Thank you

I have two collections related by an objectId. They are well synced with elastic search and when I make changes the changes do reflect without any issues. I also decided to populate the data the id represents using [[script]]

```
[[script]]
namespace = "naijacowry.products"
script = """
module.exports = function(product) {
   product.category = findOne({_id: product.category}, {database: "test", collection: "categories"});
   product.merchant = findOne({_id: product.merchant}, {database: "test", collection: "merchants"});
   return product;
}
"""
```
I also used [[relate]] to sync updates. 
```
[[relate]]
namespace = "test.categories"  # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "test.products"
src-field = "_id"
match-field = "category._id"
```
The [[script]] works well but where the problem occurs is when I make changes to a record in mongodb. The [[relate doesn't seem to work, as the linked value doesn't seem to change. I have followed the documentation and the [[relate]] seems correct. Below is the nature of the data

```
{
  name: "Some product",
  category._id: "xxx",
  category.name: "some category name"
}
```
Any help will be appreciated.

**Comment by rwynn** [comment]
It might be related to having a dot in the key name of your document.  

https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name

The relate may be trying and failing to match a document that looks like this...

```javascript
{
  name: "Some product",
  category {
     _id: "xxx",
     name: "some category name"
  }
}
```

**Comment by gate3** [comment]
Hi @rwynn, I don't see any other way to work with it. Do you have any suggestions

**Comment by rwynn** [comment]
@gate3 , haven't tried this but maybe configure as ...

```toml
[[relate]]
namespace = "test.categories"  # when a thing changes look it up in the assoicated view by _id and index that
with-namespace = "test.products"
src-field = "_id"
match-field = "category\uff0e_id"
```

**Comment by gate3** [comment]
Genius, absolutely genius. Will try it and get back thanks a bunch

**Comment by gate3** [comment]
I bow to your genius, sir. It works now, although I still need to observe if it was due to me restarting monstache or not. But at least now it works, Thank you so so much.
