### ISSUE TITLE
Monstache plugin sql connection to fetch data

### ISSUE THREAD

**Issue by ialisyed** [rwynn/monstache#324]
Hi,
I am opening sql connection to fetch some data in map function of plugin but it is making too many connections as per data. Is it possible to make connection only one type and then query as per records?
**and Is it possible to cache some data from sql by saving it inside a variable in plugin and keep using that data? and how is it possible??**

I am getting this error after sometimes:
` connect: cannot assign requested address`

Here is my code inside map function

       
        db, err := sql.Open("mysql", "usr:pwd@@tcp(ip:port)/db")
	if err != nil {
        panic(err.Error())
	}
	err = db.QueryRow("QUERY")
           err != nil && err != sql.ErrNoRows{
		panic(err.Error()) // proper error handling instead of panic in your app
	}
	// defer the close till after the main function has finished
	db.Close()
```

**Comment by rwynn** [comment]
Hi @ialisyed,

I haven't tried this but you should be able to use a go `init` [function](https://golang.org/doc/effective_go.html#init) in your plugin to get a reference to a `db` once and set some [connection pool options](http://go-database-sql.org/connection-pool.html) on it.

```golang
var db *sql.DB
func init() {
        var err error
	db, err = sql.Open("mysql",
		"user:password@tcp(127.0.0.1:3306)/hello")
	if err != nil {
		log.Fatal(err)
	}
       // set connection pool options
      // e.g. http://go-database-sql.org/connection-pool.html
}
// Map implements the callback from monstache
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
    err = db.QueryRow("QUERY")
    // do not call or defer db.Close() here
    // see last 2 paragraphs at http://go-database-sql.org/accessing.html about reusing db
   
   // do stuff
   return
}
```

**Comment by ialisyed** [comment]
It worked! Thanks a lot!
