### ISSUE TITLE
Data synced but mongodb updates not reflecting in ES.

### ISSUE THREAD

**Issue by ialisyed** [rwynn/monstache#325]
Hi, I have successfully synced all data from mongodb to elasticSearch by enabling the flag `direct-read-namespaces = ["db.products"]` . I have also set `index-as-update = true` but when I update any document in mongodb. It does not reflect in elastic search.
Below is my monstache config.
I am using monstache rel3 with elasticsearch 2 and mongodb 3.

```
elasticsearch-max-conns = 10
replay = true
resume = true
resume-name = "default"
namespace-regex = "db.^"
direct-read-namespaces = ["db.products"]
index-as-update = true
verbose = true

[[mapping]]
namespace = "db.products"
index = "product_catalog"
type = "product"
```

**Comment by rwynn** [comment]
Try removing the `namespace-filter` or set it to something like

```
namespace-regex = '^db\.'
```

**Comment by ialisyed** [comment]
Changing the regex worked. Can you please explain me how it effected updates reflection?
