### ISSUE TITLE
Minor documentation update - "bulk" thread renamed to "write" in ES7

### ISSUE THREAD

**Issue by benlavalley** [rwynn/monstache#326]
The Monstache setup documentation mentions updating the elasticsearch config:

thread_pool:
   bulk:
     queue_size: 200

ES7 introduced a breaking change and this should now be "write" and not "bulk"

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#write-thread-pool-fallback

After checking the default settings, this now appears to be set at 200 by default:

curl "localhost:9200/_cluster/settings?include_defaults=true"

"write":{"queue_size":"200","size":"16"}

**Comment by rwynn** [comment]
Thanks Ben, I've removed these instructions as it looks like the default is now 200 for this queue.
