### ISSUE TITLE
Config file contains undecoded keys: ["mapping.type"]

### ISSUE THREAD

**Issue by ialisyed** [rwynn/monstache#329]
I am getting this error when I am using monstache rel6
this is my config. I am not even using type

```
elasticsearch-max-conns = 10
replay = false
resume = true
resume-name = "default"
namespace-regex = '^db\.products$'
direct-read-namespaces = ["db.products"]
index-as-update = true
verbose = true
exit-after-direct-reads = false

[[mapping]]
namespace = "db.products"
index = "index_name"
```

**Comment by ialisyed** [comment]
Had to delete the pod and restart it again

**Comment by dachuylinux** [comment]
i have same error. I'm using mongo 4.2 and Elasticsearch 7.6.2 and run Monstache version 6.5.3 My file toml config:
mongo-url = "mongodb://localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]
direct-read-namespaces = ["horae.hmacs"]
change-stream-namespaces = ["horae.hmacs"]

#namespace-regex = '^mydb\.mycollection$'
gzip = true
stats = true
index-stats = true
elasticsearch-max-conns = 4 
dropped-collections = true
dropped-databases = true
resume = true
resume-write-unsafe = false
resume-name = "default"
resume-strategy = 1
verbose = true
file-highlighting = true
exit-after-direct-reads = false

[[mapping]]
namespace = "horae.hmacs"
index = "horae"
**# type = "hmacs"** 
If i uncomment line **type = "hmacs"**, i will receive same the problem.

**Comment by rwynn** [comment]
@dachuylinux recent versions of Elasticsearch [no longer support mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html). This is why monstache also does not support mapping types in the latest version.
