### ISSUE TITLE
elastic "No processor type exists with name [attachment]"

### ISSUE THREAD

**Issue by remotejob** [rwynn/monstache#33]
My first tentative was unsuccessful probably lack Ingest attachment plugin ?

I tested on 6.1 and as well on 5.6.5

 curl localhost:9200/_cat/plugins?v

name    component         version

```
I_KmNJ8 ingest-geoip      6.1.0

I_KmNJ8 ingest-user-agent 6.1.0

I_KmNJ8 x-pack            6.1.0

```

```
INFO 2017/12/15 05:15:31 Successfully connected to elasticsearch version 6.1.0
TRACE 2017/12/15 05:15:31 PUT /_ingest/pipeline/attachment HTTP/1.1
Host: localhost:9200
User-Agent: elastic/5.0.58 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Encoding: gzip
Content-Type: application/json
Vary: Accept-Encoding
Accept-Encoding: gzip

68
��A
Ы���)J�*LbP�������NM    �e>@x~+X�hv�a�yt��.�鑠�W�|��-4������{���Ά��Y
0


TRACE 2017/12/15 05:15:31 HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Processor_type: attachment

{"error":{"root_cause":[{"type":"parse_exception","reason":"No processor type exists with name [attachment]","header":{"processor_type":"attachment"}}],"type":"parse_exception","reason":"No processor type exists with name [attachment]","header":{"processor_type":"attachment"}},"status":400}
panic: elastic: Error 400 (Bad Request): No processor type exists with name [attachment] [type=parse_exception]

goroutine 1 [running]:
main.main()
        /exwindoz/home/juno/gowork/src/github.com/rwynn/monstache/monstache.go:2160 +0x270a

```

```
gzip = true
stats = true
index-stats = true
mongo-url = "mongodb://localhost:27017"
#mongo-pem-file = "/path/to/mongoCert.pem"
#mongo-validate-pem-file = false
elasticsearch-urls = ["http://localhost:9200"]
#elasticsearch-user = ""
#elasticsearch-password = ""
elasticsearch-max-conns = 10
#elasticsearch-pem-file = "/path/to/elasticCert.pem"
elastic-validate-pem-file = false
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
namespace-regex = '^mydb\.(mycollection|\$cmd)$'
namespace-exclude-regex = '^mydb\.(ignorecollection|\$cmd)$'
gtm-channel-size = 200
index-files = true
file-highlighting = true
file-namespaces = ["users.fs.files"]
verbose = true
cluster-name = 'docker-cluster'
direct-read-namespaces = ["db.collection", "test.test"]
exit-after-direct-reads = false


```

**Comment by rwynn** [comment]
Have you followed these instructions yet? 

https://rwynn.github.io/monstache-site/gridfs/
https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html

`sudo bin/elasticsearch-plugin install ingest-attachment`

Did the plugin install successfully?

**Comment by rwynn** [comment]
You're most likely gonna want to comment these out.
```
namespace-regex = '^mydb\.(mycollection|\$cmd)$'
namespace-exclude-regex = '^mydb\.(ignorecollection|\$cmd)$'
```

**Comment by rwynn** [comment]
Also, just to be clear, monstache only requires the ingest-attachment plugin when file content indexing is enabled in the config.

If you change the following to false monstache will not attempt requests requiring ingest-attachment.
```
index-files = false
```
Depending on your needs you may need that to be true and to have installed the ingest-attachment plugin on all ES nodes.

**Comment by jihadadulrazaqjasim** [comment]
Hello @rwynn,
I am using php client and installed elasticsearch on my mac m1 computer,
I installed ingest-attachment,

when i attempt to ingest attachment using 

`     $response = $client->ingest()->putPipeline([

                        'id' => 'my_pipeline_id',

                        'body' => [

                            'description' => 'my attachment ingest processor',

                            'processors' => [

                                [
                                    'attachment' => [
                                        'field' => 'my_field'
                ]
            ]
        ]
    ]
]);`

i face same issue as @remotejob mention, it says 'No processor type exists with name [attachment]'

**Comment by rwynn** [comment]
I think the pipeline ID literally need to be `attachment`. 

```curl
PUT _ingest/pipeline/attachment
{
  "description" : "Extract file information",
  "processors" : [
    {
      "attachment" : {
        "field" : "file",
        "indexed_chars" : -1
      }
    }
  ]
}
```
So you may need to change `my_pipeline_id` -> `attachment`
