### ISSUE TITLE
Unable to connect to Elasticsearch on AWS

### ISSUE THREAD

**Issue by iperiago** [rwynn/monstache#337]
Hi, I'm desperately trying to use Monstache with an Elasticsearch hosted service. 

While it can connect to a local Elasticsearch server, it fails everytime if the service is hosted. 

My latest try involved AWS as I saw this guide :

https://rwynn.github.io/monstache-site/advanced/#aws-signature-version-4
https://medium.com/@ahuijsen/setting-up-permissions-for-elasticsearch-service-in-aws-2fef7cc02b4c

Which I followed to the letter. 

I have my credentials, region and a working endpoint (with :443 termination) in my .toml file, and I still keep having this error : 

`Unable to create Elasticsearch client: health check timeout: Head http://127.0.0.1:9200: dial tcp 127.0.0.1:9200: connect: connection refused: no Elasticsearch node available`

Any help is greatly appreciated, thanks a lot in advance

**Comment by rwynn** [comment]
How are you setting the config `elasticsearch-urls`?  I would not expect the host port of `127.0.0.1:9200` to be the correct value for a hosted service.  

I would expect you might need something like 

```toml
elasticsearch-urls = ["https://<endpoint_from_aws_overview_screen>:443"]
```

**Comment by iperiago** [comment]
I just found out that for some reason monstache was grabbing the wrong .toml config file ! it now works sorry for the unnecessary issue
