### ISSUE TITLE
MongoDB View Replication

### ISSUE THREAD

**Issue by lgrossi** [rwynn/monstache#343]
Hi,

I'm trying to do advanced replication on mongodb view using monstache based on this documentation: https://rwynn.github.io/monstache-site/advanced/#mongodb-view-replication and I'm struggling to get it working.

So, the flow I have is basically:
- A collection 'book'
- A collection 'person'
- A view 'book-view' that performs three lookups into person: author, illustrator, reviewer.

The view lookup is defined like:
```
  {
    "$lookup": {
      "from": "person",
      "localField": "author",
      "foreignField": "id",
      "as": "authorDoc"
    }
  },
  {
    "$lookup": {
      "from": "person",
      "localField": "illustrator",
      "foreignField": "id",
      "as": "illustratorDoc"
    }
  },
  {
    "$lookup": {
      "from": "person",
      "localField": "reviewer",
      "foreignField": "id",
      "as": "reviewerDoc"
    }
  },
```

Right now the .toml file looks like that:
```
[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "author"
keep-src = false

[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "illustrator"
keep-src = false

[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "reviewer"
keep-src = false
```

Based on the documentation it looks all right, so:
- every update on the person collection should trigger replication update in the book documents if book.author/illustrator/review == person.id.

However, its not working. Am I missing anything?

**Comment by rwynn** [comment]
Hi is `db.book` something that would be in your `change-stream-namespaces`?  You would need to be listening to events on it.  Also, I didn't notice any mention of `book-view` in your config.  If you want to sync the contents of the view and not simply docs in `db.persion` then you would need a `relate` targeting the view.

**Comment by lgrossi** [comment]
Sorry, I have the view configurations as well, I just didn't include it because the normal book update replication works fine. What doesn't work is replication trigger on book when person is update.

The mapping configs:
```
[[mapping]]
namespace = "db.book"
index = "book"
type = "book"

[[mapping]]
namespace = "db.book-view"
index = "book"
type = "book"

[[relate]]
namespace = "db.book"
with-namespace = "db.book-view"
keep-src = false

[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "author"
keep-src = false

[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "illustrator"
keep-src = false

[[relate]]
namespace = "db.person"
with-namespace = "db.book"
src-field = "id"
match-field = "reviewer"
keep-src = false
```

**Comment by rwynn** [comment]
Ok, since you are using the oplog can you ensure that you don't have any filter on the `db.book` namespace, e.g. if you are using a regex that it would match `db.book`.  

Also, it seems you have an `id` field in `db.book` in addition to `_id`?  And that `id` field not `_id` is referenced by `db.person`?  

Maybe it would help to grab a copy of the monstache source and add a few debug statements in some places? 

When monstache should be detecting the change in person
https://github.com/rwynn/monstache/blob/master/monstache.go#L4324

When monstache should be looking up the document in book
https://github.com/rwynn/monstache/blob/master/monstache.go#L996

**Comment by lgrossi** [comment]
Hey, thank you for your replies.
No, I don't use filters at all in any namespace.
Yes, id is the reference property for person, indeed.

I actually already run a copy of monstache source with some customs, I'll try some debugging then, thank you for pointing me out where. Will add here if I have any other update.

Any other thoughts about what else could it be?

**Comment by rwynn** [comment]
The only other thing I can think of would be that it is related to you have 3 relationships.  Multiple relates is something that the code is expecting but just something to look out for.  

I don't see any problems in the configuration.

**Comment by lgrossi** [comment]
Didnt work as well.. I appreciate, will try to debug it next week! Thank you

**Comment by lgrossi** [comment]
@rwynn it ends up that we were actually using regx filters very specific to book collection in mongo. Once I enhanced it to include books it start working. Thank you!

**Comment by rwynn** [comment]
@lgrossi glad to hear you got it working!
