### ISSUE TITLE
Only part of mongo records are synced

### ISSUE THREAD

**Issue by sunnyque** [rwynn/monstache#344]
I have mongodb collection with 60 millions records and only 9 mil of them are indexed in elasticsearch (docs.count) after running monstache.

Mongo 4.2.2, Elasticsearch 7.5.2, monstache 6, config is:

```
mongo-url = "mongodb://localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]

direct-read-namespaces = ["db.posts"]
change-stream-namespaces = ["db.posts"]

gzip = false
stats = true
index-stats = true
elasticsearch-max-conns = 4
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
resume-strategy = 1
index-files = false
file-highlighting = true
verbose = false
cluster-name = 'rs0'

[[mapping]]
namespace = "db.posts"
index = "posts"
```

Already checked known issues and didn't find the answer, what could go wrong? no errors in monstache logs (last info record is 'Pausing work for cluster rs0') and monstache still running

also curious: is it possible to sync only specific fields of the mongodb collection, I know about [[pipeline]] but it seems only for change detection, not sync itself.

**Comment by sunnyque** [comment]
upd: changed settings to

```
mongo-url = "mongodb://localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]
direct-read-namespaces = ["db.posts"]
change-stream-namespaces = ["db.posts"]
gzip = false
elasticsearch-max-conns = 4
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-name = "default"
verbose = false
cluster-name = 'rs0'
```
removed existing indexes and run sync again.
now is 29 mil records is indexed. well, half is definitely better that 1/6, still wonder where is the rest

**Comment by rwynn** [comment]
You might want to try removing the `cluster-name` option as that is enabling the clustering mode that is producing the message "Pausing work for cluster..".   Usually that setting is only used with multiple monstache processes to provide redundancy.  That mode works through a collection named `monstache.cluster`.  

I'm not sure what the problem could be if there are no errors.  If you enable `stats` again, what do you see when the count stops increasing?  Don't enable `index-stats` just `stats` so it only prints to the console.   Any errors in the Elasticsearch logs?   

For syncing specific fields see [middleware](https://rwynn.github.io/monstache-site/advanced/#middleware) in go or javascript.  Example [go plugin](https://github.com/rwynn/monstache-showcase/blob/master/plugin/plugin.go).  

Another way to omit fields is to do it on the Elasticsearch side by setting up a default pipeline for your indexes and dropping or transforming fields in that pipeline.  You can setup the default pipeline using an index template.  

https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by sunnyque** [comment]
rwynn, thank you for answer. will try out your hints incl. plugin implementation in go and share results as I get them

**Comment by sunnyque** [comment]
Plugin implementation was really simple and intuitive, just needed to build monstache binary as well. 
BTW: it is possible build monstache in Windows by using Windows Subsystem for Linux

Removed cluster-name and run again from scratch, at this time seems every record is indexed and successfully filtered by plugin

Closing issue. Thanks again Ryan
