### ISSUE TITLE
noisy failures of `findOne`

### ISSUE THREAD

**Issue by zvictor** [rwynn/monstache#346]
hello @rwynn ! Once again, thank you so much for the great and hard work you have made on this project. Your dedication is really fascinating 🏆

---

Today's issue is rather a cosmetic one. I am used to run `exists = findOne(...)` type of queries to **know if I already have a certain document in my database**, and then take action based on that.

For monstache, though, not finding the document (which is often the expected scenario) seems to be a big deal. My logs are full of these lines:
```haskell
Error in function findOne: mongo: no documents in result
```

Is there a way to silent `findOne` if no doc is found?

**Comment by rwynn** [comment]
hey @zvictor that seems like a reasonable request, I'll silence that in the next release.

I think you might be able to work around with a `find` and `limit` for now.  

```
exists = _size( find( {...} , { limit: 1 } ) ) === 1;
```

**Comment by zvictor** [comment]
awesome! I will be waiting for the next release. Thanks!
