### ISSUE TITLE
[[relate]] not working when `match-field` contain arrays

### ISSUE THREAD

**Issue by pakerfeldt** [rwynn/monstache#347]
I'm trying to use [[relate]] to make sure that changes to joined collections will trigger updates to the other collection.

Config looks like this:
```
[[relate]]
namespace = "players"
with-namespace = "teams"
src-field = "_id"
match-field = "players.value.id"
keep-src = true
```
The thing is that both `players` and `value` fields are arrays. Even though `teams.find({"players.value.id" : "someId"})` works perfectly in Mongo, I don't seem to get any hits in Monstache. For the sake of it, I changed the structure to exclude arrays but still having nested fields and this worked just fine with Monstache. So I'm drawing the conclusion that it can't seem to handle arrays in the `match-field`. I was looking through the source code and in particular `buildSelector` but couldn't seem find anything wrong, but I'm also not familiar with `mgo` either. Perhaps you can shed some light? Thanks!

**Comment by rwynn** [comment]
Hi @pakerfeldt, when monstache sees a `match-field` like `players.value.id` it will construct a query like `teams.find( { players: { value: { id: <value> } } } )`.  I think I need to give an option for the query to look like `teams.find({"players.value.id" : <value> })`.  

I actually just made a commit with this option on the relate, `dot-notation`. And you would set that to true.  Don't have a release for this yet, though.

**Comment by pakerfeldt** [comment]
Thank you! Will try it out on Monday. We can build it locally in the meantime, that's fine.

**Comment by pakerfeldt** [comment]
Seems to be working, thanks!

One thing we realised was that it's impossible to specify multiple `relates` with the same `namespace`. In our case we have one collection used in many views. And so we tried to have two `relate` specifying the same `namespace` (source collection) but different `with-namespace` (the views). Only the first one specified was in effect though.

We solved this by chaining this such that there's one `relate` for `col->view1` and then another for `view1->view2`. Seems to be doing the trick but also feels a bit hacky. If you have any suggestions on this I would be glad to take them.

**Comment by rwynn** [comment]
Hi @pakerfeldt, it should be possible to relate one collection directly to multiple collections/views.  I tried to replicate the issue on my end but it seemed to work ok....

I created collections `test.a`, `test.b` and `test.c`.  

I also created views `test.b_view` and `test.c_view` as follows:

```
db.createView("b_view", "b", [ {$lookup: {from: "a", localField: "_id", foreignField: "_id", as: "a"}}] )
db.createView("c_view", "c", [ {$lookup: {from: "a", localField: "_id", foreignField: "_id", as: "a"}}] )
```

To start the data looks like...

```
rs1:PRIMARY> db.a.find()
{ "_id" : 1, "name" : "a" }
rs1:PRIMARY> db.b.find()
{ "_id" : 1, "name" : "b" }
rs1:PRIMARY> db.c.find()
{ "_id" : 1, "name" : "c" }
rs1:PRIMARY> db.b_view.find()
{ "_id" : 1, "name" : "b", "a" : [ { "_id" : 1, "name" : "a" } ] }
rs1:PRIMARY> db.c_view.find()
{ "_id" : 1, "name" : "c", "a" : [ { "_id" : 1, "name" : "a" } ] }

```

I then ran monstache 6.5.1 with this config...

```toml
verbose = true

[[relate]]
namespace = "test.a"
with-namespace = "test.b_view"

[[relate]]
namespace = "test.a"
with-namespace = "test.c_view"

```

Finally, with monstache running I made the final update

```
rs1:PRIMARY> db.a.update({_id: 1}, {$set: {updated: new Date()}});
```

And I was able to get the following output from monstache (with 2 docs sent for the update)

```
TRACE 2020/02/25 00:57:06 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.10 (linux-amd64)
Content-Length: 178
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.b_view","_id":"1","version":6797181853589218272,"version_type":"external"}}
{"a":[{"_id":1,"name":"a","updated":"2020-02-25T00:57:06.006Z"}],"name":"b"}

TRACE 2020/02/25 00:57:06 HTTP/1.1 200 OK
Content-Length: 238
Content-Type: application/json; charset=UTF-8

{"took":389,"errors":false,"items":[{"index":{"_index":"test.b_view","_type":"_doc","_id":"1","_version":6797181853589218272,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2020/02/25 00:57:06 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/7.0.10 (linux-amd64)
Content-Length: 178
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.c_view","_id":"1","version":6797181853590112021,"version_type":"external"}}
{"a":[{"_id":1,"name":"a","updated":"2020-02-25T00:57:06.006Z"}],"name":"c"}

TRACE 2020/02/25 00:57:06 HTTP/1.1 200 OK
Content-Length: 238
Content-Type: application/json; charset=UTF-8

{"took":220,"errors":false,"items":[{"index":{"_index":"test.c_view","_type":"_doc","_id":"1","_version":6797181853590112021,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```

Are you able to reproduce the issue with this basic example?  Is there possibly something about your use case that is different?
