### ISSUE TITLE
bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Action/metadata line [1] contains an unknown parameter [_version] [type=illegal_argument_exception]

### ISSUE THREAD

**Issue by sakthiskv** [rwynn/monstache#350]
monstache is not able to sync data from mongodb to elastic search with error: elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request).

error :
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_version]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_version]"},"status":400}
ERROR 2020/03/09 16:25:23 elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Action/metadata line [1] contains an unknown parameter [_version] [type=illegal_argument_exception]

recently i updated  ELASTICSEARCH VERSION 7.6. that time only i am  getting above error. so please help me

**Comment by rwynn** [comment]
For that version of Elasticsearch you should use monstache v6.5.1.  See this [link](https://rwynn.github.io/monstache-site/advanced/#versions) for details.

**Comment by sakthiskv** [comment]
yeah its working fine. thank you  @rwynn
