### ISSUE TITLE
[BUG] Error establishing the oplog cursor

### ISSUE THREAD

**Issue by constantx** [rwynn/monstache#353]
**Describe the bug**

I'm running monstache with docker, and when using `enable-oplog = true`, got this error:

```
ERROR 2020/03/17 08:03:52 Error establishing the oplog cursor: (Unauthorized) not authorized on local to execute command { find: "oplog.rs", awaitData: true, filter: { ts: { $gt: Timestamp 0|0 }, op: { $in: [ "c", "i", "u", "d" ] }, fromMigrate: { $exists: false } }, sort: { $natural: 1 }, tailable: true }
```

Monstache configuration:

```toml
enable-oplog = true
namespace-regex = '^mydb\.orders$'
```

**Software information (please complete the following information):**
 - Operating System:
 - Monstache Version: monstache:6.5.2
 - MongoDB Version: v3.4.16
 - Elasticsearch Version: 7.5.1
 - Docker Version: 19.03.8, build afacb8b

**Comment by devansvd** [comment]
User not able to access `local` mongodb collection. give permission or test without authentication first.
