### ISSUE TITLE
Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available

### ISSUE THREAD

**Issue by fnadav** [rwynn/monstache#354]
Hi,

I have an EC2 and Elasticsearch in the same VPC.
I can call on the elasticsearch https url just fine with curl from the EC2 instance,
but i fail to connect with monstache. for the following url i get:
```
elasticsearch-urls = ["https://...eu-central-1.es.amazonaws.com:443"]
```
```
Unable to create Elasticsearch client: 
health check timeout: no Elasticsearch node available
```
i've been going through the board and found [this very similar issue](https://github.com/rwynn/monstache/issues/250).
however in my case i dont have a '/' in my url.

would appreciate the help :]
ps, if i wanted to insert `elastic.SetHealthcheck(false);` in the code, where would i put it?

#### MORE INFO:
connection to docdb was no problem. elasticsearch failed.
i tried this with monstache 4.19.4, 6.5.2 and elastic 6 and 7 - always same result.

```
# curl -I https://...eu-central-1.es.amazonaws.com:443
HTTP/2 200 
date: Tue, 17 Mar 2020 13:24:44 GMT
content-type: application/json; charset=UTF-8
content-length: 514
access-control-allow-origin: *
```

also, i called 
```
curl -XGET https://...eu-central-1.es.amazonaws.com:443/_nodes/https | jq .
```
and got:
```
{
  "_nodes": {
    "total": 0,
    "successful": 0,
    "failed": 0
  },
  "cluster_name": ".:.",
  "nodes": {}
}
```
i dont actually know what the check does, but maybe its relevant.
elasticsearch definitely works tho, i have data there i can read.

**Comment by rwynn** [comment]
Check https://rwynn.github.io/monstache-site/advanced/#aws-signature-version-4 just in case.

If you want to disable the health check you can do so by changing the code here -> https://github.com/rwynn/monstache/blob/rel6/monstache.go#L585.

**Comment by fnadav** [comment]
HI rwynn,

Thank you for the prompt reply. i tried providing the credentials (although why would i need them if i can call on it without providing them in curl?).

this time i get:
```
ERROR 2020/03/17 17:14:16 Unable to create Elasticsearch client: health check timeout: Head "https://vpc-documentdb-elastic-test-6-jdef63vkzy5gerp6eia26xceli.eu-central-1.es.amazonaws.com:443": SharedCredsLoad: failed to get profile: no Elasticsearch node available
```
which i guess is an improvement?
i couldnt find anything useful bout this new message on the internet. i suspect its because i use ephemeral keys. will update when i try with real credentials.

cheers!

**Comment by rwynn** [comment]
Check that if you have 

```toml
[aws-connect]
profile = "myprofile"
```

Then in `~/.aws/credentials` you have a matching section with `[myprofile]`.  

For example..

```ini
[myprofile]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

**Comment by rwynn** [comment]
I'm not sure why you would need request signing if you are running monstache from same host as curl and curl is already working without request signing.  

Monstache just uses the elastic go library.  You might try a simple example like https://github.com/olivere/elastic/blob/release-branch.v7/recipes/connect/connect.go to see what the problem might be.

**Comment by fnadav** [comment]
> Check that if you have
> 
> ```toml
> [aws-connect]
> profile = "myprofile"
> ```

after adding the above i got the previous message (from before using credentials):

````
ERROR 2020/03/19 16:34:28 Unable to create Elasticsearch client:
health check timeout: no Elasticsearch node available
```

**Comment by fnadav** [comment]
> I'm not sure why you would need request signing if you are running monstache from same host as curl and curl is already working without request signing.
> 
> Monstache just uses the elastic go library. You might try a simple example like https://github.com/olivere/elastic/blob/release-branch.v7/recipes/connect/connect.go to see what the problem might be.

will try and update, thx!

**Comment by rwynn** [comment]
@peavers try specifying the URL env var as

```
MONSTACHE_ES_URLS=http://elastic:9200"
```

It's documented at https://rwynn.github.io/monstache-site/config/#elasticsearch-urls but I think granted it's a little confusing.  The only time you specify with `[]` is in the toml file.

If that doesn't work check out and compare with https://github.com/rwynn/monstache-showcase since I know that works.

**Comment by yunivrsl** [comment]
Ryan,

I'm having the exact same issue here.  I've tried all that were suggested, adding "- MONSTACHE_ES_URLS=http://elasticsearch:9200" where "elasticsearch" is the service in the docker-compose.yml
but, nothing worked.  I've used the service name, container name, and even localshost.

Attached is my docker-compose.yml file.  I'd appreciate if you can provide any ideas to the fix.

thank you

[docker-compose.txt](https://github.com/rwynn/monstache/files/5021489/docker-compose.txt)

**Comment by yunivrsl** [comment]
Ryan,

disregard my message:  i've gotten to work by adding the two settings:
elasticsearch-healthcheck-timeout-startup = 200
elasticsearch-healthcheck-timeout = 200
