### ISSUE TITLE
Question related with https://github.com/rwynn/monstache/issues/249

### ISSUE THREAD

**Issue by sgonv** [rwynn/monstache#356]
MongoDB server version: 4.0.13
Monstache version: v6.5.2
Elasticsearch version: 7.5.0

I have a collection that has 2 Billion documents in it.

And I ran 3 monstache daemons with below configuration,
```
cluster-name = "blahblah"

# MongoDB config
mongo-url = "blahblah"

# Elasticsearch config
elasticsearch-urls = ["blahblah"]
elasticsearch-user = "blahblah"
elasticsearch-password = "blahblah"

direct-read-namespaces = ["blahblah"]
change-stream-namespaces = ["blahblah"]

enable-http-server = true
mapper-plugin-path = "blahblah_plugin.so"
```
I got these errors.
```
ERROR 2020/03/18 16:53:21 Error performing direct read of collection blahblah: (CursorNotFound) cursor id 62275785311 not found
ERROR 2020/03/18 16:53:21 Error performing direct read of collection blahblah: (CursorNotFound) cursor id 60438150598 not found
ERROR 2020/03/18 16:53:21 Error performing direct read of collection blahblah: (CursorNotFound) cursor id 61407159196 not found
...
```

After read https://github.com/rwynn/monstache/issues/249,
I added `direct-read-split-max = 200` option, but same error occurred.

When I ran following command on my MongoDB server,
```
db.adminCommand({getParameter: 1, cursorTimeoutMillis: 1})
```
I got
```
"cursorTimeoutMillis" : NumberLong(600000),
...
```

What can I do to solve this error?

**Comment by rwynn** [comment]
Hi @sgonv ,

Can you try with the following settings?

```toml
direct-read-concur = 1
direct-read-no-timeout = true
direct-read-split-max = -1
```

You can read about those settings [here](https://rwynn.github.io/monstache-site/config/#direct-read-no-timeout)

The last one might not be needed.  It turns off collection splitting and reads the whole collection with 1 cursor.  If this works you may be able to remove that setting.  The default is 9 splits which would read your collection with 10 cursors over different ranges of the collection.

**Comment by sgonv** [comment]
Thanks for fast response.

I added those settings. After that, the number of document is increased more than before setting.
But all 3 workers' last logs are
```
INFO 2020/03/19 15:47:52 Pausing work for cluster blahblah
```
and it seems that they doesn't work any more. (ES document count is not increasing any more)

Here is the full log from the start.
```
INFO 2020/03/19 14:46:26 Started monstache version 6.5.2
INFO 2020/03/19 14:46:26 Go version go1.14
INFO 2020/03/19 14:46:26 MongoDB go driver v1.3.1
INFO 2020/03/19 14:46:26 Elasticsearch go driver 7.0.12
INFO 2020/03/19 14:46:26 Successfully connected to MongoDB version 4.0.13
INFO 2020/03/19 14:46:26 Successfully connected to Elasticsearch version 7.5.0
INFO 2020/03/19 14:46:26 Joined cluster blahblah
INFO 2020/03/19 14:46:26 Starting work for cluster blahblah
INFO 2020/03/19 14:46:26 Listening for events
INFO 2020/03/19 14:46:26 Watching changes on collection blahblah.blahblah
INFO 2020/03/19 14:46:26 Resuming from timestamp {T:1584519826 I:207}
INFO 2020/03/19 15:25:53 Pausing work for cluster blahblah
INFO 2020/03/19 15:33:53 Resuming work for cluster blahblah
INFO 2020/03/19 15:47:52 Pausing work for cluster blahblah
```

**Comment by rwynn** [comment]
@sgonv I should have mentioned this before.  I recommend doing the initial sync with a single monstache process and cluster mode disabled (by removing `cluster-name` from your config).

The reason for this is that cluster mode is for providing fail over.  But in this case it seems to be detecting a slow process as a failed process and switching to another one.  The problem is that direct reads are not resume able, so that may be why you are not seeing a complete sync.  

So to summarize, I suggest you use two configs.  One to perform the initial sync and then one to keep things in sync afterward.  

```toml
# config for initial sync

# keep track of timestamps and resume streams from them
resume = true

# perform the initial sync and then exit
exit-after-direct-reads = true

# settings for reading a large collection
direct-read-concur = 1
direct-read-no-timeout = true
direct-read-split-max = -1

# MongoDB config
mongo-url = "blahblah"

# Elasticsearch config
elasticsearch-urls = ["blahblah"]
elasticsearch-user = "blahblah"
elasticsearch-password = "blahblah"

direct-read-namespaces = ["blahblah"]
change-stream-namespaces = ["blahblah"]

enable-http-server = true
mapper-plugin-path = "blahblah_plugin.so"

```


And then once that completes restart with this config...

```toml
# keep track of timestamps and resume streams from them
resume = true

# MongoDB config
mongo-url = "blahblah"

# Elasticsearch config
elasticsearch-urls = ["blahblah"]
elasticsearch-user = "blahblah"
elasticsearch-password = "blahblah"

change-stream-namespaces = ["blahblah"]

enable-http-server = true
mapper-plugin-path = "blahblah_plugin.so"

```

**Comment by sgonv** [comment]
I could finish my direct read with config that you've suggested.

But monstache finished with exit code 1 and I don't know why.

I expected that monstache finished with exit code 0. Is it right?

One thing I suspect is this log `ERROR 2020/03/24 19:00:00 replSetGetStatus is not supported through mongos`.

My another MongoDB for test is consisted as a shared cluster. So I added `mongo-config-url` option, but same error message appeared.

Here is full log for my test.
```
INFO 2020/03/24 18:59:53 Started monstache version 6.5.2
INFO 2020/03/24 18:59:53 Go version go1.14
INFO 2020/03/24 18:59:53 MongoDB go driver v1.3.1
INFO 2020/03/24 18:59:53 Elasticsearch go driver 7.0.12
INFO 2020/03/24 18:59:53 Successfully connected to MongoDB version 4.0.1
INFO 2020/03/24 18:59:53 Successfully connected to Elasticsearch version 7.5.0
INFO 2020/03/24 18:59:53 Listening for events
INFO 2020/03/24 18:59:53 Watching changes on the deployment
INFO 2020/03/24 18:59:53 Resuming from timestamp {T:0 I:0}
INFO 2020/03/24 19:00:00 Direct reads completed
ERROR 2020/03/24 19:00:00 replSetGetStatus is not supported through mongos
INFO 2020/03/24 19:00:00 Stopping all workers
INFO 2020/03/24 19:00:00 Shutting down
```

**Comment by rwynn** [comment]
Yes, it should exit with `0` if there are no errors.  

Unfortunately, the call to `replSetGetStatus` is not going to work through mongos.  monstache uses the call to `replSetGetStatus` to record the timestamp of when the direct reads finish. It uses this timestamp is subsequent runs to resume change streams from that time. 
 
The `mongo-config-url` option is only to support sharded setups on versions of MongoDB before 3.6.  So you shouldn't set that in your case.

**Comment by rwynn** [comment]
I will think about how to suppress that call in a future release if going through mongos.

**Comment by sgonv** [comment]
I tried without `mongo-config-url` option, but same error occurred.
Then can't I use direct read functionality?

**Comment by rwynn** [comment]
The error just means that it is not able to record a timestamp for resuming.  It does not mean that the sync did not occur.  Do you see all the documents in Elasticsearch?

**Comment by rwynn** [comment]
Just added https://github.com/rwynn/monstache/commit/33f5a2edd3418262d2968955f8a32210c9182478 to `rel6` branch.  

This commit hopefully should fix that error for you.  You would need to run `make all` in the `rel6` branch to build it.

**Comment by sgonv** [comment]
Thanks for the fix. It worked.

And I have some questions.

1. If I want to increase the speed of direct read, can I use workers configuration?
https://rwynn.github.io/monstache-site/advanced/#workers

2. After direct finished, there will be a short term between the completion of direct read and the start of reading for change stream. Is monstache aware of where to start reading change stream?
Can I be sure that there is no loss because of the term between the direct read process and the change stream read process?

**Comment by rwynn** [comment]
> 1. If I want to increase the speed of direct read, can I use workers configuration?
>    https://rwynn.github.io/monstache-site/advanced/#workers

You can try workers.  However, in my experience a monstache process without workers can often overload Elasticsearch and you don't need more.  If you increase `elasticsearch-max-conns` from the default of 4 to 8 or 12 then you should see much more load generated on Elasticsearch.  Sometimes more than Elasticsearch can handle.  Generally, reads out of MongoDB will be very fast and indexing to Elasticsearch much slower in comparison.  The final bulk index phase is what slows the pipeline down.  You can even see this yourself in an experiment by just printing the read data from MongoDB and not indexing it.  In this case monstache will finish very quickly.  

Change the source code in https://github.com/rwynn/monstache/blob/v6.5.2/monstache.go#L4609 to
```golang
// if err = ic.routeOp(op); err != nil {
  // ic.processErr(err)
// }
infoLog.Println(op)
```
So I would say increase the `elasticsearch-max-conns` value to 8 and see what happens.  

Also read and apply the advice at https://rwynn.github.io/monstache-site/config/#direct-read-namespaces with regards to `refresh_interval` and `number_of_replicas` in Elasticsearch to optimize the throughput. 

> 2. After direct finished, there will be a short term between the completion of direct read and the start of reading for change stream. Is monstache aware of where to start reading change stream?
>    Can I be sure that there is no loss because of the term between the direct read process and the change stream read process?

The change streams are actually started at the same time as the direct reads.  So there is no delay between the two.  This is documented in a warning block under https://rwynn.github.io/monstache-site/config/#direct-read-namespaces.

**Comment by sgonv** [comment]
> @sgonv I should have mentioned this before. I recommend doing the initial sync with a single monstache process and cluster mode disabled (by removing `cluster-name` from your config).
> 
> The reason for this is that cluster mode is for providing fail over. But in this case it seems to be detecting a slow process as a failed process and switching to another one. The problem is that direct reads are not resume able, so that may be why you are not seeing a complete sync.
> 
> So to summarize, I suggest you use two configs. One to perform the initial sync and then one to keep things in sync afterward.
> 
> ```toml
> # config for initial sync
> 
> # keep track of timestamps and resume streams from them
> resume = true
> 
> # perform the initial sync and then exit
> exit-after-direct-reads = true
> 
> # settings for reading a large collection
> direct-read-concur = 1
> direct-read-no-timeout = true
> direct-read-split-max = -1
> 
> # MongoDB config
> mongo-url = "blahblah"
> 
> # Elasticsearch config
> elasticsearch-urls = ["blahblah"]
> elasticsearch-user = "blahblah"
> elasticsearch-password = "blahblah"
> 
> direct-read-namespaces = ["blahblah"]
> change-stream-namespaces = ["blahblah"]
> 
> enable-http-server = true
> mapper-plugin-path = "blahblah_plugin.so"
> ```
> 
> And then once that completes restart with this config...
> 
> ```toml
> # keep track of timestamps and resume streams from them
> resume = true
> 
> # MongoDB config
> mongo-url = "blahblah"
> 
> # Elasticsearch config
> elasticsearch-urls = ["blahblah"]
> elasticsearch-user = "blahblah"
> elasticsearch-password = "blahblah"
> 
> change-stream-namespaces = ["blahblah"]
> 
> enable-http-server = true
> mapper-plugin-path = "blahblah_plugin.so"
> ```
Even though direct read and reading change stream occur simultaneously, after the process with first config is terminated, there will be short term before starting the process with second config. How can I switch (direct read + reading change stream) to (only reading change stream) without the loss of reading?

**Comment by rwynn** [comment]
> Even though direct read and reading change stream occur simultaneously, after the process with first config is terminated, there will be short term before starting the process with second config. How can I switch (direct read + reading change stream) to (only reading change stream) without the loss of reading?

The reason you would not lose data when you switch is that the first process will save a timestamp in `monstache.monstache` collection.  The 2nd process will read this timestamp and resume the change stream from that point in time using https://docs.mongodb.com/manual/changeStreams/#start-time.

**Comment by sgonv** [comment]
Thanks for your immediate help! I think I can launch monstache successfully. 👍
