### ISSUE TITLE
[BUG] Monstache does not create timestamp collection when resume is set to true

### ISSUE THREAD

**Issue by dino-brzika** [rwynn/monstache#362]
**Describe the bug**
I am trying to setup monstache to resume using timestamps but on run it does not create collection inside my db to save timestamps. After direct reads are completed,  there is a error: 
ERROR 2020/03/27 20:31:27 (Unauthorized) not authorized on admin to execute command { replSetGetStatus: 1, lsid: { id: UUID("some uuid") }, $db: "admin" }

This authorization error is happening only if resume and direct-read-namespace are used together. Otherwise it is not reported.
I have readWrite access only to my database since it is provided as a service.
Initial direct read works. Sometimes sync on change triggers in the span of minutes after change, sometimes it does not sync after 45 minutes. If resume is not set i observed that it always triggers under 15 minutes. With verbose logging on, i can see direct reads, but nothing happens if follow up change on collection is performed. When resume and config-database are commented out, verbose shows that monstache detects changes almost immediately (sync happens later).
Could this issue interfere with sync in some way?
Do i really need access to admin database?
Not sure if this is bug or just a environment or monstache setup issue and would appreciate if you could provide some feedback.

**To Reproduce**

Monstache configuration:

```toml
# describe config here
config-database-name = "mongotest"
resume = true
direct-read-namespaces = ["mongotest.testc"]
change-stream-namespaces = ["mongotest.testc"]
gzip = true
dropped-collections = true
dropped-databases = true
delete-index-pattern = "mongotest.testc*"
```

Run monstache with configuration above.
**Expected behavior**
Collection monstache is created inside mongotest database and visible from mongo shell.
Changes are detected in reasonable time.
Timestamp is used to resume syncing since last checkpoint.

**Software information (please complete the following information):**
 - Operating System: Windows 10
 - Monstache Version: 6.5.2
 - MongoDB Version: 4.0.2
 - Elasticsearch Version: 7.3.1
 - Docker Version:  19.03.8

**Additional context**
I am testing using Docker from Windows 10 machine. Mongo is located on remote machine as
is Elasticsearch.  Also i am unable to set logging to files. Whatever i try it does not work. Maybe it is related to this problem.

**Screenshots**
```
INFO 2020/03/31 16:43:34 Started monstache version 6.5.2
INFO 2020/03/31 16:43:34 Go version go1.14
INFO 2020/03/31 16:43:34 MongoDB go driver v1.3.1
INFO 2020/03/31 16:43:34 Elasticsearch go driver 7.0.12
INFO 2020/03/31 16:43:34 Successfully connected to MongoDB version 4.0.2
INFO 2020/03/31 16:43:35 Successfully connected to Elasticsearch version 7.3.1
INFO 2020/03/31 16:43:35 Listening for events
INFO 2020/03/31 16:43:35 Watching changes on collection mongotest.testc
INFO 2020/03/31 16:43:35 Resuming from timestamp {T:0 I:0}
INFO 2020/03/31 16:43:35 Direct reads completed
ERROR 2020/03/31 16:43:35 (Unauthorized) not authorized on admin to execute command { replSetGetStatus: 1, lsid: { id: UUID("some uuid") }, $db: "admin" }
```
Best regards,
Dino

**Comment by rwynn** [comment]
I think for the first issue you need to give the user, that you connect to MongoDB with, the following privilege -> https://docs.mongodb.com/manual/reference/privilege-actions/#replSetGetStatus.

**Comment by rwynn** [comment]
The best way to do this is probably by giving the user this built-in role -> https://docs.mongodb.com/manual/reference/built-in-roles/#clusterMonitor

**Comment by dino-brzika** [comment]
Hi,

Thanks for quick reply. I requested that role this morning.
Not sure how much this config makes sense as direct read will sync everything so timestamp is irrelevant. I will probably split this into two configs per your recommendations on another issue or go with direct read and normal sync if role could not be granted.
I would like this issue to stay open until i confirm that given role solved a problem or role could not be granted.

Best regards,
Dino
