### ISSUE TITLE
Watching changes on specific fields on view collection to elasticsearch

### ISSUE THREAD

**Issue by zoadyik** [rwynn/monstache#363]
Hello, how to watching on specific fields with view

I have a view "db.user_views" in this view has aggregate create array field source from  "department" on db.company

change-stream-namespaces = ["db.user", "db.company" ]

[[mapping]]
namespace = "db.user_views"
index = "usersIndex"
type = "user"

[[relate]]
namespace = "db.user"
with-namespace = "db.user_views"
src-field = "username"
match-field = "username"
keep-src = false

[[relate]]
namespace = "db.company"
with-namespace = "db.user_views""
src-field = "username"
match-field = "username"
keep-src = false

for example when db.company insert new record and match username I want to watching changes on "department" fields only

I tried pipeline below but not working

[[pipeline]]
namespace = "db.company"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $match: {
          $or: [
            { "updateDescription": {$exists: false} },
            { "updateDescription.updatedFields.department": {$exists: true}}
          ]
        }
      }
    ];
  } else {
    return [];
  }
}
"""

**Comment by rwynn** [comment]
Is it true that all three of `db.user`, `db.company`, and `db.user_views` has a top-level field called `username`?  

Your second relate says that when `db.company` changes use the `username` field of the company and match that to the `username` field in `db.user_views` view.  Is that correct?

**Comment by zoadyik** [comment]
Thanks for quick reply. @rwynn 
I did not set `verbose =` true. I thought it not working but actually it works!
