### ISSUE TITLE
Error performing direct read of collection (CursorNotFound) with sharding and multiple DNS entries

### ISSUE THREAD

**Issue by soluscale** [rwynn/monstache#368]
I kept experiencing the CursorNotFound error after anywhere from a few seconds to a few minutes on every collection configured for direct reads on a sharded cluster with two shards and a primary/secondary replica on each shard.  I had the configured settings for direct reads:

direct-read-split-max = -1
direct-read-concur = 1
direct-read-bounded = true
direct-read-no-timeout = true

I believe I figured out the issue, I have multiple mongos servers and my DNS was configured as an A record with all 3 mongos server IPs.  Normally this allows you to just use the DNS entry and you'll randomly get one of the 3 DNS servers based on however an application uses multiple DNS servers.

In this case what I believe was happening is that at some point the app was reevaluating its connections and establishing another connection to another mongos from one of the 3 and it couldn't use its reference to the cursor it had open since cursors are tied to specific mongos instances.  To fix the issue (so far it's been running successfully) was to not use the DNS entry and instead hard-code an IP of one of my individual mongos instances into the config file.

If you concur this would've caused an issue within the program, I suggest you implement some kind of internal stickiness to a specific mongos IP for reusing the cursor.  I don't know what happens when that mongos becomes unavailable and you have to switch, I guess you'd have to restart the direct read from the beginning again for whatever collection(s) were in progress.

Apologies for not tracking this down in the code but I hope the explanation is sufficient, please let me know if you have any questions.

**Comment by rwynn** [comment]
I think maybe this issue could be raised against the mongodb go [driver](https://github.com/mongodb/mongo-go-driver)?.   You might get a better response from the MongoDB team on if it's a bug or how monstache should be handling it.  

Monstache doesn't really handle the low level details of the connections.  However, I can think about adding an option to restart the direct read on all errors or certain errors.

The MongoDB driver was recently updated to version `1.3.2`.  Not sure if that helps this situation, but I usually upgrade monstache shortly after they release new drivers.

**Comment by rwynn** [comment]
Found more on this issue [here](https://dba.stackexchange.com/questions/130321/can-mongodb-be-configured-to-sit-behind-a-load-balancer#130703) and [here](http://craiggwilson.com/2013/10/21/load-balanced-mongos/).  

Seems like it might be best to keep using a direct connection to a single mongos for long-lived queries (full collection read) that require multiple getMore commands over a period of time.

**Comment by soluscale** [comment]
Yes, that's exactly why we don't run a load balancer in front of our mongos cluster.  Honestly it was no problem at all addressing the issue once I realized what was going on.  I wanted to at a minimum inform others that may run into this and additionally bring it to your attention in case there was something simple you could put in place to make it stickier during the bulk load in this situation.  I'm going to mark this closed and this will at least be documented for anyone else that encounters this.  Thank you!

**Comment by rwynn** [comment]
@soluscale thanks :+1:  for bringing it to my attention!  I've definitely had some questions over time about the dreaded "cursor not found" error.  Understanding this will help debug those in the future.
