### ISSUE TITLE
Weird index using time machine and index mapping

### ISSUE THREAD

**Issue by neurovul** [rwynn/monstache#372]
Hello,

I am facing a weird issue when I am using time machine and index mapping.

Here is a part of my config.toml:

    time-machine-namespaces = ["db.table"]

    time-machine-index-prefix = "history"

    [[mapping]]
    namespace = "db.table"
    index = "db.test-1.table"
 
It will create the following indexes on ElasticSearch: db.test-1.table and **history.db.test-4.table...**

If I change the mapping and use 

```
[[mapping]]
    namespace = "db.table"
    index = "db.test-2.table"
```

It will create : db.test-1.table and **history.db.test-16.table...**

If I change the mapping and use 

```
[[mapping]]
    namespace = "db.table"
    index = "db.test-3.table"
```

It will create : db.test-1.table and **history.db.test-10.table...**

I think it is related to current date because I tried these examples today at 10:XX (04 16 2020 10:XX).
Then I tried at 11:XX (04 16 2020 11:XX) and it gave **history.db.test-4.table...**, **history.db.test-16.table...**, **history.db.test-11.table...**

I am using docker image rwynn/monstache:6.5.2

Best regards

**Comment by rwynn** [comment]
@neurovul thanks for the report.  I think I know what is going on.  Monstache is apply the date format to your index name when it should only be appending the date.  That is why you are seeing numbers being replaced with parts of the current date.  I will add a fix for this.

**Comment by neurovul** [comment]
Hello

Sorry for really late answer. It is working well then I'm closing this issue. Thanks a lot for your responsiveness.

BR
