### ISSUE TITLE
Can Sync with Elasticsearch in real time  ?

### ISSUE THREAD

**Issue by latestk-develop** [rwynn/monstache#373]
Hello. I'm using monstache 6.1.0 / mongodb 4.0.10 / elasticsearch 7.4.2

my monstache setting is
```
elasticsearch-urls = ["http://192.168.88.30:9201", "http://192.168.88.30:9202", "http://192.168.88.30:9203"]
namespace-regex = 'user.item'

gzip = true

elasticsearch-max-conns = 4
elasticsearch-max-docs = 1
elasticsearch-max-seconds = 1
elasticsearch-retry = true

dropped-collections = false
dropped-databases = false

delete-strategy = 2

mapper-plugin-path = "/home/plugin.so"
routing-namespaces = ["item-*"]

enable-http-server = true
```

my elasticsearch index setting is
`refresh_interval = "1s"`

I want to sync in real time, 
but delay 3 ~ 10 seconds to update.

Which setting is wrong in monstache? or is it impossible ?

**Comment by rwynn** [comment]
Your config looks fine for minimizing latency.  What happens in the plugin?  You might want to try without the plugin for comparison.  Also, use `verbose=true` and see how much time between when you change in MongoDB and when monstache sends the request to index.  Monstache will log each request in this case.

**Comment by latestk-develop** [comment]
Thank you for reply.
My plugin is just change a few mongoDB document fields. and i think that process is not too hard.
Because sometimes monstache sync very quickly with elasticsearch (almost 1~2s) but sometimes sync really slow up to 10s(or over).

**Comment by rwynn** [comment]
@latestk-develop you might want to try making the following changes to your config...

```toml
# watch changes on only 1 collection instead of the default of all user collections
change-stream-namespaces = [ 'user.item' ]

# you no longer need a namespace filter since you are only watching the 1 collection you need
# namespace-regex = 'user.item'
```

This will reduce the number of changes that monstache receives.

**Comment by latestk-develop** [comment]
Thanks
After following your comments, sync noticeably reduced !!
