### ISSUE TITLE
[BUG] Validation Failed: 1: when loading high number of documents to AWS ElasticSearch Service

### ISSUE THREAD

**Issue by rpong** [rwynn/monstache#377]
We are trying to sync a mongoDB collection with 500K documents with a total size of 90mb. but we are getting a bunch of the following:

```
ERROR 2020/05/13 16:18:23 Bulk response item: {"_index":"onepropertee.tracking","_type":"_doc","_id":"BmsthZ2PjRBnWpjf2","status":400,"error":{"type":"illegal_argument_exception","reason":"Validation Failed: 1: this action would add [10] total shards, but this cluster currently has [2402]/[2000] maximum shards open;"}}
```
All other collections are syncing just fine.

We are using AWS ElasticSearch service with 2 nodes.

Here's our relevant Monstache Configuration:
```
gzip = true
stats = true
index-stats = true
elasticsearch-max-conns = 4
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
index-files = false
file-highlighting = true
verbose = true
cluster-name = 'ilove-onepropertee'
exit-after-direct-reads = false
```

Environment:
Monstache Version: 6.4.1
MongoDB Version: 4.2.6
ElasticSearch Version: AWS ES Service (ElasticSearch 7.1)

My Hunch is that there is a setting that we can tweak down to prevent the sync process from adding shards to the ElasticSearch endpoint, but can't seem to find the setting.

**Comment by rwynn** [comment]
Hi @rpong I'm not aware of a way that monstache can fix this issue (control sharding).  You may need to follow the suggestions [here](https://discuss.elastic.co/t/number-of-shards-open-issue-7-0-1/180785) to fix on the  Elasticsearch side.

**Comment by rpong** [comment]
got it, it seems the bulk operation is what is triggering the shard addition, perhaps because of the number of documents we are trying to sync. anyway, we'll figure out something and update here once we get this resolved.

awesome software btw, we've been using this for the past couple of years. keep at it! thank you.

**Comment by rwynn** [comment]
> awesome software btw, we've been using this for the past couple of years. keep at it! thank you.

Thanks I really appreciate it!  If you do find a monstache change that would help fix this just let me know.
