### ISSUE TITLE
synchronize data from MongoDb to ElasticSearch

### ISSUE THREAD

**Issue by hassen2017** [rwynn/monstache#38]
Hi,
I m new in ES and i want  synchronize data from MongoDb to ElasticSearch
I have followed the steps in https://rwynn.github.io/monstache-site/start/ 
this is my config.toml : 

``
gzip = true
stats = true
index-stats = true
mongo-url = "mongodb://localhost/testdb11"

elasticsearch-urls = ["http://localhost:9200"]

elasticsearch-max-conns = 10

dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
namespace-regex = '^testdb11\.(commentaires|\$cmd)$'
namespace-exclude-regex = '^testdb11\.(commentaires|\$cmd)$'
gtm-channel-size = 200
index-files = true
file-highlighting = true
file-namespaces = ["commentaires.contenu"]
verbose = true

direct-read-namespaces = ["testdb11.commentaires", "test.test"]
exit-after-direct-reads = false
``

This is the result that i m seeing in elasticsearch.bat cmd : 

[2018-01-26T13:38:31,960][INFO ][o.e.n.Node               ] [nEk71vY] started
[2018-01-26T13:38:32,676][INFO ][o.e.g.GatewayService     ] [nEk71vY] recovered [8] indices into cluster_state
[2018-01-26T13:38:40,556][INFO ][o.e.c.r.a.AllocationService] [nEk71vY] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[books][1]] ...]).
[2018-01-26T13:40:46,897][INFO ][o.e.c.m.MetaDataCreateIndexService] [nEk71vY] [testdb11.commentaires] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2018-01-26T13:40:48,999][INFO ][o.e.c.m.MetaDataMappingService] [nEk71vY] [testdb11.commentaires/-G_AYL89S-SUSQmBKrn0Gw] create_mapping [commentaires]

I m not sure if this result is fine !!? and where can i find the indexed data if this is fine

**Comment by rwynn** [comment]
@hassen2017 thanks for trying monstache.  

First, you will want to make sure that your settings for `namespace-regex` and `namespace-exclude-regex` do not match.  The former is what your want to include in sync and the latter is what you want to exclude from sync.  In the case above you are excluding documents from the `testdb11.commentaires` collection which I'm pretty sure is not what you want.  I should make that more clear in the docs.  You do not need to configure either of those filters if you just want to sync all changes.  

Next, you start monstache with the `-verbose` flag you should see activity in your console anytime you make changes to MongoDB that match your filtering (if any).  This activity will be the bulk indexing API requests to Elasticsearch.  Note the responses to these requests and make sure that they are successful.  

Finally, to view your data in Elasticsearch you can use something like curl or install Kibana to visualize your indexes.  See [mapping](https://rwynn.github.io/monstache-site/advanced/#index-mapping) for information on how monstache determines the index and type of documents.

For your config you can try a curl request like below to view the data in Elasticsearch.

```
curl -XGET 'localhost:9200/testdb11.commentaires/_search?pretty'
```

**Comment by hassen2017** [comment]
@rwynn thanks for your response  that's helped to understand the concepts 

I have cloned and installed  git://github.com/mobz/elasticsearch-head.git and I succeeded to see my data into the  Cluster Overview

**Comment by hassen2017** [comment]
Hello @rwynn
I used Kibana to visualise the data indexed to elasticsearch & I was runnig Monstache with this cmd in Ubentu 16.4 : ./bin/monstache -f config.toml  --verbose 
But i cannot visualise the data in realTime when i make changes to MongoDB 
Please what can I doing for that  ?

**Comment by rwynn** [comment]
@hassen2017 

Please read the info at https://www.elastic.co/guide/en/kibana/current/discover.html

You will want to make sure you have configured a valid index pattern in Kibana for the data you want to view.  For example if you wanted to view the Mongo data from the database `test` and the collection `users` you would set the index pattern in Kibana to `test.users`.  When you type the index pattern, Kibana should let you create it when it detects matching indexex in Elasticsearch.  Also, setup the index pattern to be time based.  You can choose use the _timestamp field, or tell monstache to add a date field by using the following configuration settings -> https://rwynn.github.io/monstache-site/config/#index-oplog-time.  Set `index-oplog-time` to true and you will get a date field added by monstache that you can use when creating the index-pattern.  Finally, make sure you have auto-refresh turned on in Kibana and that you are not filtering the data with a search term.
