### ISSUE TITLE
Unable to connect to mongodb via SSL x509 authentication

### ISSUE THREAD

**Issue by yunivrsl** [rwynn/monstache#380]
**Describe the bug**
i have monstache v. 6.5.2 and attempting to run against mongodb via ssl and x509 authencation, however, I do not see the server options to provide in the URL.
I tried ssl, sslCA, sslKey, ssl Cert, along with authMechism, but, not working.

**To Reproduce**

Monstache configuration:

```toml
# describe config here
mongo-url = mongodb://<CN=.......> @<db1>:27107, <db2>:27107,<db3>:27107/mydb?replicaSet=<myRS>&ssl=true&authMechanism=MONGODB-X509&sslCert=<path to cer>&sslKey=<path to key>&sslCA=<path to CA>
```

Configure mongodb to enable ssl

**Expected behavior**

**Software information (please complete the following information):**
 - Operating System: RHEL
 - Monstache Version: 6.5.2
 - MongoDB Version: 4.0.10
 - Elasticsearch Version: 7.1
 - Docker Version: na

**Additional context**

**Screenshots**

**Comment by rwynn** [comment]
Hi @yunivrsl can you check your parameter names against the names within the case statements here -> https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/connstring/connstring.go

**Comment by yunivrsl** [comment]
Hi, i tried the set of sslcertificatefile, sslprivatekeyfile, and sslcafile.. now i'm getting connection refused error.  better than before.  not sure, from the link you sent what these cases are expecting and what the difference is between these SSL ..file cases and what i need to provide

**Comment by rwynn** [comment]
Can you try something like this with the path to your corresponding file?
```
mongodb://<server:port>?ssl=true&sslclientcertificatekeyfile=/mongodb-charts/volumes/db-certs/client.pem&authMechanism=MONGODB-X509
```
from https://docs.mongodb.com/charts/current/administration/configure-ssl-data-sources/#add-a-new-tls-ssl-enabled-data-source

**Comment by yunivrsl** [comment]
i have tried:
mongodb://<db1-server:port>?ssl=true&sslclientcertificatekeyfile=/mongodb-charts/volumes/db-certs/client.pem&authMechanism=MONGODB-X509
==> connection refused

i have tried:
mongodb://<db1-server:port>?ssl=true&sslclientcertificatekeyfile=/mongodb-charts/volumes/db-certs/client.pem&sslclientcertificatefile=/mongodb-charts/volumes/db-certs/client.cer&sslcertificateauthorityfile=/mongodb-charts/volumes/db-certs/ca,crt&authMechanism=MONGODB-X509
==> failed to find CERTIFICATE  (not sure what this is b/c all the paths are correct)

My application, i'm connecting using a config file for mongoose connection with mongodb with the following attributes:

`
"mongo:"  {
    "servers": [
         {
             "host": "db1-server",
             "port": "<port>"
         },
     ]
     "db": "<db-name>".
     "user": "CN=......",
     "ssl": {
            "cert": "path to cert"
            "key": "path to key"
            "ca": "path to ca"
      }
      "connectionOption": {
             "replicaSet": <setname>
      }
`

**Comment by yunivrsl** [comment]
Just realized the connection refused message, monstache is trying to connect to mongodb://localhost... "localhost"?  it's not reading the mongo-url that i've specified.

**Comment by yunivrsl** [comment]
using:
mongodb://db1-server:port?ssl=true&sslcertificatefile=/mongodb-charts/volumes/db-certs/client.pem&sslprivatekeyfile=/mongodb-charts/volumes/db-certs/client.cer&sslcafile=/mongodb-charts/volumes/db-certs/ca,crt&authMechanism=MONGODB-X509

does reach the database b/c tailing the database log, "connection accepted .... " then "end connection.."  but, monstache returns with:
"x509: certificate signed by unknown authority"

however, this is a legit certs, key, and ca file.

**Comment by yunivrsl** [comment]
GOTIT!!!!

needed to use "tlscerfiticatefile", "tlsprivatekeyfile", and "tlscafile" combination

**Comment by rwynn** [comment]
@yunivrsl Glad to hear you figured it out!  Sorry I couldn't be of more help on this one.  I think if I have some time I will create a request for better documentation on the go driver side around this.

**Comment by selvackp** [comment]
tls is working as expected 

We are configuring Percona Backup for MongoDB
