### ISSUE TITLE
plugin was built with a different version of package internal/cpu[BUG]

### ISSUE THREAD

**Issue by chenyiping111** [rwynn/monstache#382]
when i use versions 4.19.6 or 4.19.5, "plugin was built with a different version of package internal/cpu",  I build mg plugin in tar.gz files , 4.19.3 works great

**Comment by chenyiping111** [comment]
I updated go version from 1.12 to 1.14, how can i resolve the problem?

**Comment by rwynn** [comment]
I would suggestion cloning the git repository, checking out the tag of the version you want to use, and then building both the `monstache` binary and your plugin.  To build monstache you can simply run `go install`.  To build the plugin run something like `go build -buildmode=plugin -o myplugin.so myplugin.go`.  Then use the monstache binary you built together with the plugin you built. If you build both the binary and the plugin they will definitely work together.

**Comment by chenyiping111** [comment]
my fault, I need "go install"

**Comment by chenyiping111** [comment]
My steps：
 unnzip monstache-d771a35.zip
export ...
monstache -v
//4.19.6
tar -zxf monstache-4.19.6.tar.gz
cd monstache-4.19.6
go install
go build -buildmode=plugin -o pub_plugin.so pub_plugin.go
monstache -mapper-plugin-path pub_plugin.so -cluster-name pub5 -worker w1 -f pub5.toml

there is still err:
Unable to load mapper plugin pub_plugin.so: plugin.Open("pub_plugin"): plugin was built with a different version of package internal/cpu
INFO 2020/06/08 01:43:46 Shutting down with exit status 1 after panic.

I can't understand, I used to do it like above, but it won’t work now

**Comment by chenyiping111** [comment]
> I would suggestion cloning the git repository, checking out the tag of the version you want to use, and then building both the `monstache` binary and your plugin. To build monstache you can simply run `go install`. To build the plugin run something like `go build -buildmode=plugin -o myplugin.so myplugin.go`. Then use the monstache binary you built together with the plugin you built. If you build both the binary and the plugin they will definitely work together.

My steps：
unnzip monstache-d771a35.zip
export ...
monstache -v
//4.19.6
tar -zxf monstache-4.19.6.tar.gz
cd monstache-4.19.6
go install
go build -buildmode=plugin -o pub_plugin.so pub_plugin.go
monstache -mapper-plugin-path pub_plugin.so -cluster-name pub5 -worker w1 -f pub5.toml

there is still err:
Unable to load mapper plugin pub_plugin.so: plugin.Open("pub_plugin"): plugin was built with a different version of package internal/cpu
INFO 2020/06/08 01:43:46 Shutting down with exit status 1 after panic.

I can't understand, I used to do it like above, but it won’t work now
