### ISSUE TITLE
Mongo $unset not propagated to ES

### ISSUE THREAD

**Issue by exentrich** [rwynn/monstache#383]
I have simple to describe problem: When I `$unset` some field in document in Mongodb, this change not applied to Elasticsearch.

Here my Go plugin:
```go
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	doc := input.Document

	delete(doc, "__v") //mongoose specific

	output = &monstachemap.MapperPluginOutput{
		Document: doc,
		Routing: getUserId(doc),
	}

	return
}
```

Maybe you have an idea how to send `unset` operations through Go plugin?

**Comment by rwynn** [comment]
Is it possible you have `index-as-update=true`?  The default is not to update but to do a full replace of the document in Elasticsearch.  It may be that Elasticsearch doesn't realize you want the field removed because of this.

If that isn't it try with `verbose=true` and see what's getting sent in response to the `$unset` event.

**Comment by exentrich** [comment]
Oh, sorry forgot to mention, yes I have `index-as-update=true`.
In this case I have any chance to sync unsets?

**Comment by rwynn** [comment]
You might be able to look at the `UpdateDescription` field in the input and if you notice an `$unset` then explicitly add a `nil` value for the field inside the doc that you map to.  This should indicate to Elasticsearch that the field should be removed.

**Comment by exentrich** [comment]
Thanks!

**Comment by chenyiping111** [comment]
> You might be able to look at the `UpdateDescription` field in the input and if you notice an `$unset` then explicitly add a `nil` value for the field inside the doc that you map to. This should indicate to Elasticsearch that the field should be removed.

how can I process the `$unset` in golang plugin?
