### ISSUE TITLE
Feature request: client certificate authentication on ElasticSearch

### ISSUE THREAD

**Issue by gbaulieu** [rwynn/monstache#384]
Hello and thanks for your great work!

To my knowledge, the only supported authentication method of monstache to ElasticSearch is basic auth. Is it foreseen to also add support for a client certificate authentication? Some ELS clusters can only be accessed that way...

Best regards

**Comment by gbaulieu** [comment]
I compiled the rel6 branch on an ubuntu 18.04 with go1.14.4. Tested with MONSTACHE_ES_PKI_CERT and MONSTACHE_ES_PKI_KEY environment variables:
`Successfully connected to Elasticsearch version 7.5.1`. Seems to be working fine!
Thanks a lot! Not even 2 days between feature request and commit, wow! :-)

**Comment by rwynn** [comment]
@gbaulieu glad to hear it worked out.  Will try to get out a new release soon.  Thanks!
