### ISSUE TITLE
Specify _id range while doing full sync

### ISSUE THREAD

**Issue by sameerkattel** [rwynn/monstache#395]
Is there a way to specify _id range while doing full sync ?
I have a timestamp based standard increasing UUID.

`db.getCollection('test.collection').find({ _id:{$gte:UUID("08d81de8-606f-a6e9-8af6-984fac000001"), $lte:UUID("08d81de8-6073-1176-8af6-984fac000003")}})`

**Comment by rwynn** [comment]
Use a [go plugin](https://rwynn.github.io/monstache-site/advanced/#golang) and implement a `Pipeline` function.   Return a [pipeline](https://docs.mongodb.com/manual/core/aggregation-pipeline/) such that one of the stages does a match on the UUIDs that you need.  You can read the UUIDs from environment variables in the go plugin.
