### ISSUE TITLE
Merge collections into one index ?

### ISSUE THREAD

**Issue by MoroccanGeek** [rwynn/monstache#397]
Hello, i have in my mongo database several collections, and indexing them is working fine with monstache, but i was just wondering is it possible to get the data and inserted in one global index ? Because for the moment each collection has its index.
Thank you

**Comment by rwynn** [comment]
You can use [mapping](https://rwynn.github.io/monstache-site/config/#mapping).  Watch out for duplicate _ids across collections.  

Alternatively, Elasticsearch allows you to [search multiple indexes](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html).

**Comment by MoroccanGeek** [comment]
Thank you
