### ISSUE TITLE
elasticsearch 6.x support

### ISSUE THREAD

**Issue by mattful** [rwynn/monstache#40]
Any plans to support Elasticsearch 6.x?

**Comment by rwynn** [comment]
Hi, please see this issue.  https://github.com/rwynn/monstache/issues/32.  Is there something about Elasticsearch 6.X that is not already supported?

**Comment by mattful** [comment]
Sorry... missed that. It answers my questions. Thank you.

**Comment by rwynn** [comment]
No problem.  Since it's been asked a couple of times now I'm wondering what might be prompting this question.  Is it just the lack of it being stated explicitly in the docs?  Thanks.

**Comment by mattful** [comment]
Yep. I was looking around for any confirmation in in the docs. The mongo
connector was broken by ES 6 with the change to single mapping type. Also
noticed that the code was still importing v5 of the olivere/elastic
library. But you addressed both those concerns over in the other issue.
