### ISSUE TITLE
How to watch a field whose type is array or map?

### ISSUE THREAD

**Issue by KuoKongQingYun** [rwynn/monstache#400]
I read the page,
[https://rwynn.github.io/monstache-site/advanced/#watching-changes-on-specific-fields-only](https://rwynn.github.io/monstache-site/advanced/#watching-changes-on-specific-fields-only)
but it seems like work only when the type of the field is basic such as string,number and so on.
If I insert an item into a field whose type is array or map,it doesn't work.
could you help me and write an example?

**Comment by rwynn** [comment]
Testing with 2 MongoDB shells open

First shell

```javascript
cursor = db.getSiblingDB("test").watch()
while (!cursor.isExhausted()){
   if (cursor.hasNext()){
      printjson(cursor.next());
   }
}
```

Second shell
```javascript
db.test.insert({foo: {bar: [1]}});
db.test.update({}, {$addToSet: {"foo.bar": 2}});
```

Update statement results in
```json
"updateDescription" : {
                "updatedFields" : {
                        "foo.bar" : [
                                1,
                                2
                        ]
                },
                "removedFields" : [ ]
        }

```

Does that help?

**Comment by KuoKongQingYun** [comment]
@rwynn 
I found another way to do this yesterday,
Thank you very much all the same.
