### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#403]
Hi 

As per documentation 
Aggregation Pipelines
You can alter or filter direct reads and change streams by using a pipeline definition. Note, when building a pipeline for a change stream the root of the document will be the change event and the associated document will be under a field named fullDocument.

So is it that it will only work with direct-read-namespaces ?

Thing is that I had 2 config files(addConfig.toml,config.toml)  
addConfig is executed once for initial load doing direct reads from collection and pipeline works as per expectation

In another config file, I am just listening on changeStreams and using same pipeline config that I had used for addConfig

But new data that I am adding to collection is not being passed to elasticsearch

If I remove the pipeline from config.toml then it works fine.

addConfig.toml looks like: 
>elasticsearch-max-bytes = 6291456
elasticsearch-healthcheck-timeout-startup = 30
elasticsearch-healthcheck-timeout = 10
elasticsearch-retry = true
verbose = true
stats = false
index-stats = false
resume-write-unsafe = false
fail-fast = true
direct-read-split-max = 1
direct-read-concur = 1
disable-change-events = true
exit-after-direct-reads = true
direct-read-namespaces = [ "db1.col1" ]
[[mapping]]
namespace = "db1.col1"
index = "index-db1.col1"
type = "_doc"
[[pipeline]]
namespace = "db1.col1"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      { $project: {"fullDocument.field1": 1} }
    ];
  } else {
    return [
      { $project: { "field1": 1 } }
    ];
  }
}
"""

config.toml looks like 
>elasticsearch-max-bytes = 6291456
elasticsearch-healthcheck-timeout-startup = 30
elasticsearch-healthcheck-timeout = 10
elasticsearch-retry = true
verbose = true
stats = false
index-stats = false
resume-write-unsafe = false
fail-fast = true
direct-read-split-max = 1
direct-read-concur = 1
exit-after-direct-reads = false
change-stream-namespaces = [ "db1.col1" ]
[[mapping]]
namespace = "db1.col1"
index = "index-db1.col1"
type = "_doc"
[[pipeline]]
namespace = "db1.col1"
script = """
module.exports = function(ns, changeStream) {
if (changeStream) {
    return [
      { $project: {"fullDocument.field1": 1} }
    ];
 } else {
    return [
      { $project: { "field1": 1 } }
    ];
   }
 }
 """

using rel5 of monstache

**Comment by rwynn** [comment]
With change streams monstache requires that you keep the original change stream event intact and only mess with the `fullDocument` field.  I think the `$project` is too destructive.  You might try to use [$set](https://docs.mongodb.com/manual/reference/operator/aggregation/set/) or [$unset](https://docs.mongodb.com/manual/reference/operator/aggregation/unset/) to apply changes only to the `fullDocument`.

**Comment by richiarora** [comment]
Thanks for quick reply. I actually wanted to send limited fields only to elasticsearch.
So as you see i was using $project: {"fullDocument.field1": 1}
but still wasnt able to see trace logs of document being moved with just field 1

so if i only want to send say field1 what should have been done in pipeline ?

**Comment by rwynn** [comment]
I'm not sure.  I would experiment with $unset and $set to get the results you want.

**Comment by rwynn** [comment]
You can experiment using javascript without monstache involved.  Pass the pipeline to watch and follow the instructions at https://docs.mongodb.com/manual/reference/method/db.watch/#example.

**Comment by richiarora** [comment]
sure let me try same

**Comment by richiarora** [comment]
currently using 3.6 hence that watch() function is not available.

**Comment by rwynn** [comment]
It seems that using `$set` or `$unset` in a change stream pipeline requires MongoDB 4.2.  So if only on 3.6 you might try a `$project` but specify the fields from the `fullDocument` to omit. 

```javascript
{ $project: { "fullDocument.field1": 0, "fullDocument.field2": 0  } }
```

**Comment by richiarora** [comment]
Got it yup same does happen I can omit but cannot include.

Closing it as its mongo dependent.
