### ISSUE TITLE
Full sync resumability

### ISSUE THREAD

**Issue by sameerkattel** [rwynn/monstache#404]
Few questions regarding full sync resumability:
1. How does monstache know if full sync has completed if there is no token stored yet?
2. How does monstache resume full sync if stopped while doing full sync but has a resume token saved?

**Comment by rwynn** [comment]
Direct read namespaces result in a full read of the entire collection unless the user configures a pipeline, e.g. by implementing the `Pipeline` function in a go plugin.  If a pipeline is implemented the user can optionally return a match stage that limits the amount of records processed.  

The resume token that monstache saves when `resume` is enabled is only used to automatically resume the change stream via the API options `SetStartAtOperationTime` or `SetResumeAfter`.

**Comment by sameerkattel** [comment]
Thanks @rwynn So every time, when monstache  is restarted with full sync on then it always do full sync irrespective of what sync state( token or time) is saved in db, correct?

**Comment by rwynn** [comment]
> Thanks @rwynn So every time, when monstache is restarted with full sync on then it always do full sync irrespective of what sync state( token or time) is saved in db, correct?

Yes, unless you provide a pipeline configuration, in which case the logic for resuming would be up to the user to decide when constructing the pipeline stages.

**Comment by sameerkattel** [comment]
Is it possible to  have an option to save full sync state saved once completed so that full sync is skipped start on a restart? Will help to keep only one monstache process that can target both full sycn and real time sync?

**Comment by rwynn** [comment]
In the next release there will be a `direct-read-stateful` boolean option.  You can try it out now from the latest in `rel6` and `rel5` branches.  This just saves the full sync state in a collection named `monstache.directreads`.  @sameerkattel
