### ISSUE TITLE
Got abnormal timestamp when it is assigned to meta version as a variable.

### ISSUE THREAD

**Issue by swaddy** [rwynn/monstache#405]
Hi Rynn,

I always got abnormal timestamp like "6847724285683826688" when it is set to meta version as a variable.

The variable gmtUnixMilli should be 1585290095046, while the result is 6847724285683826688 when assigned to version in meta. The value is weird and I don't know where it is from.
```
    doc.projectName = doc.extension.projectName;
    doc.gmtUnixNano = doc.gmtModified.UnixNano();
    var gmtUnixMilli = doc.gmtModified.UnixNano()/1000000;
    doc.content = doc.extension.content;
    var meta = { type: "_doc", index:doc.scenes+"_entry", version:gmtUnixMilli, versionType:"external" };
    doc._meta_monstache = meta;
    return _.pick(doc, "_meta_monstache", "projectName", "content", "gmtModified", "gmtUnixNano");

----es request log:
{"index":{"_index":"reinforce_entry","_id":"5e7d9b6f3fc1f20006d2e966","_type":"_doc","version":6847724285683826688,"version_type":"external"}}
{"gmtModified":"2020-03-27T06:21:35.046Z","gmtUnixNano":1585290095046000000}
```

When I assign the value 1591855056624 to version in meta directly, it works well.

Can you please let me know how to make the variable assignment work well.

 ```
 doc.gmtUnixNano = doc.gmtModified.UnixNano();
    var gmtUnixMilli = doc.gmtModified.UnixNano()/1000000;
    doc.content = doc.extension.content;
    var meta = { type: "_doc", index:doc.scenes+"_entry", version:1591855056624, versionType:"external" };
    doc._meta_monstache = meta;
    return _.pick(doc, "_meta_monstache", "projectName", "content", "gmtModified", "gmtUnixNano");
----es request log:
{"index":{"_index":"reinforce_entry","_id":"5e7d9c6d3fc1f20006d2e96d","_type":"_doc","version":1591855056624,"version_type":"external"}}
{"gmtModified":"2020-03-27T06:25:49.579Z","gmtUnixNano":1585290349579000000}
```

**Comment by rwynn** [comment]
Does this work?

```javascript
var gmtUnixMilli = Math.trunc(doc.gmtModified.UnixNano()/1000000);
```

I believe there is an error getting swallowed when it tries to turn `version` into an integer.

**Comment by swaddy** [comment]
Unfortunately，using Math.trunc i got the error : ['trunc' is not a function].

Math.trunc is used to truncate the decimal part of number while I don't think doc.gmtModified.UnixNano()/1000000 will get an decimal, I think it is the issue that the result type range exceed `version ` which is predefined as JS integer can hold,  other field like `gmtUnixNano ` works well.

I also tried `var gmtUnixMilli = doc.gmtUnixNano.toString().slice(0, -6);`, it still have the weird value.

**Comment by swaddy** [comment]
Finally, I got the right way

`parseInt(doc.gmtUnixNano.toString().slice(0, -6), 0).valueOf();`
