### ISSUE TITLE
syslog/graylog

### ISSUE THREAD

**Issue by timansky** [rwynn/monstache#41]
it will be nice to have ability to send logs to remote server with different verbose level 

PS
while launched with verbose=true, indexing speed is very slow

**Comment by rwynn** [comment]
I thought about having the ability to send the logs to Elasticsearch just like there is an option to send stats to Elasticsearch.  I might implement that at some point.  

The verbose option is mainly there so that you can debug/verify the trace log of bulk requests to Elasticsearch.  It might be a lot of data depending on the size of your documents.  I would not enable this option in production.  

I haven't noticed verbose slowing things down dramatically.  Are you logging to files or just to Stdout?

**Comment by timansky** [comment]
i think gelf mo reliable/universal protocol

yeah verbose is slow when stdout, my use case is docker container
it sends logs to stdout and then docker redirects it to graylog(gelf protocol)

**Comment by rwynn** [comment]
It logs errors no matter what.  I only logs the entire request/response trace when verbose is on.  You probably should turn verbose off in your container and just use gelf for errors.

**Comment by rwynn** [comment]
@timansky just added release 3.6.1 to help out a little bit hopefully.  You can force test of this error logging by inserting documents with incompatible types.  

`
db.test.insert({foo: 1});
db.test.insert({foo: "abc"});
`
With this enabled you should be able to safely turn off verbose and still get enough info to determine what went wrong.

**Comment by timansky** [comment]
thanks, will test.

PS
meanwhile i've asked for direct graylog(gelf) functionality because of mine method doesn't parse multiline messages

**Comment by rwynn** [comment]
Are you asking for logging in monstache to be done via something like https://github.com/Graylog2/go-gelf with new config option to specify graylog server monstache must connect to?  Sorry I did not understand your request.

**Comment by timansky** [comment]
yeap, this will be perfect

**Comment by rwynn** [comment]
@timansky can you please build using `go get -u github.com/rwynn/monstache` and then run monstache with flag `-graylog-addr localhost:12201` or whatever your server is set to and let me know how that goes?

**Comment by rwynn** [comment]
scratch that, you can just try 3.6.4 now instead of building from source.

**Comment by rwynn** [comment]
@timansky I added the option to set -graylog-addr.  Let me know if this is OK.  Thanks. Graylog can categorized the message by the prefix right?  I'm assuming it works like Logstash.
