### ISSUE TITLE
High sync delay between MongoDB and ES

### ISSUE THREAD

**Issue by jeasonchan** [rwynn/monstache#413]
Hey rwynn:
       Thx for such a nice tool and monstache works very nice between Replica Sets/Shard Cluster  and ES in change stream mode  with no data loss. 
        However, the sync takes much longer than begin as time flows. For example, at first day, I inserted 500 docs and monstache took only 2s  to sync the docs to ES and few days later I inserted the same 500 docs again but this time monstache took 9s to sync. Then I treid with 3 workers to balance the workload but that made no sense.
     
PS: all hosts are next to each other in space and network.

       Is there any possible reason or solution?
      
       Here are my  my toml without worker params:
`
mongo-url = "mongodb://10.40.65.100:31000"

mongo-config-url="mongodb://10.40.65.100:32000,10.40.65.101:32000,10.40.65.102:32000"

elasticsearch-urls = ["http://localhost:9200"]

elasticsearch-max-seconds = 10
elasticsearch-max-conns = 12

change-stream-namespaces = ["sharding_db_test.jeason_test3"]

verbose = true

direct-read-namespaces = ["harding_db_test.jeason_test3"]

gzip = true

exit-after-direct-reads = false

cluster-name = "cluster-name"

resume = true

resume-name = "resume-name"

[[script]]
namespace = "sharding_db_test.jeason_test"
routing = true
script = """
module.exports = function(doc) {
    doc._meta_monstache = { routing: doc.work_space_id };
    return doc;
}
"""
`

**Comment by jeasonchan** [comment]
I will turn off verbose and try again after got ur reply under other issue :

I would suggest turning verbose to false, the default. Verbose is reserved for debugging monstache. It logs a full trace of every request.

**Comment by rwynn** [comment]
Hi @jeasonchan as far as your settings...
```toml
elasticsearch-max-seconds = 10
elasticsearch-max-conns = 12
```

You may want to lower both of those.  With max seconds at 10, monstache will flush every 10 seconds.  If some docs are added to MongoDB shortly after a flush, they won't be flushed till 10 seconds later.  

Also, the `elasticsearch-max-docs` and `elasticsearch-max-bytes` settings apply per connection.  So if you are distributing events across 12 connections instead of the default of 4 you will flush to Elasticsearch less (each connection mantains its own buffer of bytes to send).  

Another way to look at it, you could keep the 12 connections but lower the `elasticsearch-max-bytes` to 1mb instead of the default of 8mb.

**Comment by jeasonchan** [comment]
Hi @rwynn ，followed your adivce and read the monstache-site/config again, I added the params to make the sync be real-time int the condition where all docs are very small and are inserted one by one per second: 

elasticsearch-max-seconds = 1
elasticsearch-max-conns = 1
elasticsearch-max-bytes = 1

Finally, the sync dely is very steady and is about 9s-10s. And I doubt that maybe the change stream of shard cluster contributes to the dealy So I started a chang-stream-watch server and doc-insert server to test the change steram delay. After comparing the change stream arrival time and insert time,  I ensured the change stream delay is blamed for sync delay.

Finally, I got the offical explain: https://docs.mongodb.com/manual/administration/change-streams-production-recommendations/#sharded-clusters

Thx for your adive and mybe I shoud shift to Replica Sets to avoid change stream delay of sharded-clusters.

**Comment by jeasonchan** [comment]
Hi @rwynn I got an idea, for sharded-clusters we can start a monstache for each shard not for mongos, so even though I want sync data between sharded-clusters  and ES, I still set the mongo-url param as the shard mongo-connect-string. And the monstache DB in each shard just works right for resume function.

After testing, sync delay is reduced to 2s , comparted to directly geting change stream from mongo router.

That works, nice!!!!
