### ISSUE TITLE
Very large plugin size for Go

### ISSUE THREAD

**Issue by g14a** [rwynn/monstache#419]
Hello! 
    I built a Go plugin for monstache which embeds references into the source document. It works perfectly. But my plugin source is just one function but when I build it with `go build -buildmode=plugin -o plugin.so plugin.go` the shared object is a whopping 22MB!

Is there something I can do to reduce the size, or did I miss any step during the build? @rwynn 

Thank you in advance!

**Comment by rwynn** [comment]
Hi @g14a you can reduce the resulting size a little by using `go build -buildmode=plugin -ldflags="-s -w" -o plugin.so plugin.go`.  But not really a huge difference.

**Comment by g14a** [comment]
Yeah I did that and it just reduced it from 22MB to 17MB.
