### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by benan789** [rwynn/monstache#42]
Getting this since patching to 3.6.2

```
panic: close of closed channel

goroutine 144 [running]:
main.shutdown.func2(0xc420c94600, 0xc420c94660)
        /home/ec2-user/go/src/github.com/rwynn/monstache/monstache.go:2133 +0x131
created by main.shutdown
        /home/ec2-user/go/src/github.com/rwynn/monstache/monstache.go:2128 +0x13f
```

**Comment by rwynn** [comment]
Thanks for the report. Do you always get this or just sometimes?

**Comment by rwynn** [comment]
Please give 3.6.3 a try this should be fixed now. Thanks.

**Comment by benan789** [comment]
No longer getting the panic but in errors log getting this

```
INFO 2018/02/14 03:41:21 Successfully connected to MongoDB version 3.4.10
INFO 2018/02/14 03:41:21 Successfully connected to Elasticsearch version 5.6.7
INFO 2018/02/14 03:41:21 Joined cluster apollo
INFO 2018/02/14 03:41:21 Starting work for cluster apollo
INFO 2018/02/14 03:41:21 Entering event loop
INFO 2018/02/14 03:41:21 Shutting down
```

It worked fine before 3.6.2

**Comment by rwynn** [comment]
Really sorry about this.  Please try 3.6.4 which adds back a check to only quit after direct reads are finished in you explicitly set `exit-after-direct-reads` to true.

**Comment by benan789** [comment]
Haha np, that fixed it. Amazing package btw, can't believe I didn't come across it sooner.

**Comment by rwynn** [comment]
Thanks!  I am trying to get the word out but hopefully it will grow organically because I don't have time for marketing.
