### ISSUE TITLE
when use documentdb lastCommittedOpTime not found

### ISSUE THREAD

**Issue by zhengdai** [rwynn/monstache#422]
when i use monstache to sync data from documentdb, the error logs is lastCommittedOpTime not found, how can I sync documentdb by monstache

**Comment by rwynn** [comment]
Have you tried the recommendations at https://rwynn.github.io/monstache-site/advanced/#amazon-documentdb-with-mongodb-compatibility?

**Comment by zhengdai** [comment]
> Have you tried the recommendations at https://rwynn.github.io/monstache-site/advanced/#amazon-documentdb-with-mongodb-compatibility?

thank you
