### ISSUE TITLE
Find montache process

### ISSUE THREAD

**Issue by fayas-mdosl** [rwynn/monstache#424]
I ran my monstache in the background and now I want to stop and change to a new collection! in my configuration file!
please tell me how to find the running monstache process!
I tried ps aux |grep monstache

one more thing, how do I sync my entire database instead of a specific collection.

I am new to monstache and the document is not clear enough though!

**Comment by fayas-mdosl** [comment]
I can not find the process but if create systemd service I can be able to start and stop monstache.
but logs do not work. only work if start with systemd services.

I stop all the services and try manually running monstache -f config.toml (it does not log)

**Comment by rwynn** [comment]
Is it possible your regular use doesn't have permission to write to the location of those logs?  Can you write the logs to your user's home directory?

**Comment by fayas-mdosl** [comment]
@rwynn Yes mate. it worked
