### ISSUE TITLE
Does monstache support the routing key in Elasticsearch?

### ISSUE THREAD

**Issue by zhengdai** [rwynn/monstache#435]
I want to know if the monstache supported the routing key in Elasticsearch when insert?

**Comment by rwynn** [comment]
Yes it supports it in both the javascript and golang plugins.  There are a few examples in the [documentation](https://rwynn.github.io/monstache-site/advanced/#indexing-metadata).  Also, [here](https://rwynn.github.io/monstache-site/advanced/#joins).  Hopefully,that is what you meant.

**Comment by zhengdai** [comment]
> Yes it supports it in both the javascript and golang plugins. There are a few examples in the [documentation](https://rwynn.github.io/monstache-site/advanced/#indexing-metadata). Also, [here](https://rwynn.github.io/monstache-site/advanced/#joins). Hopefully,that is what you meant.

thank you very much
