### ISSUE TITLE
whats preffered way to  run .toml file in background 

### ISSUE THREAD

**Issue by milansuthars** [rwynn/monstache#438]
i have created systemd /lib/systemd/system/monstache.service file , it runs but works only once when the service restarts after that any updates from mongo does not reflect in an Index , running direct command works perfectly but service file unable to push updates, i have referred this 
https://rwynn.github.io/monstache-site/advanced/#systemd
here is my service file content 

[Unit]
Description=monstache sync service

[Service]
User=root
Group=root
#Type=forking
Type=notify
#Type=simple
#Type=oneshot
ExecStart=/usr/local/bin/build/linux-amd64/monstache  -f /usr/local/bin/build/linux-amd64/mongo-elastic.toml &
WatchdogSec=30s
Restart=always
#RestartSec=0

#[Install]
WantedBy=multi-user.target

**Comment by sbnajardhane** [comment]
I am also running monstache using systemctl command as a service. I haven't faced any issues for 1 year.
In your config, I guess **"&"** is not needed in the exec command. It's already running as a service. We don't have to put **"&"** at the end of the command to put in the background.
let's try out without **"&"** if you still face the issue. Please paste your monstache toml config as well.

**Comment by milansuthars** [comment]
thanks for reply @sbnajardhane this is my .toml config  and if you could share you config then it can be great 
my  config updates when i run it manually  but using systemctl its not so i though its related to systemd config  file 

`mongo-url ="mongodb://localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]
direct-read-namespaces = ["ntcarfte.ntc.cdr"]
#direct-read-namespaces = ["ntcarfte.ntc.cdr","ntcarfte.ntc.callpath_utilizationreport_data"]
gzip = true
stats = true
index-stats = true


elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000 

dropped-collections = false
dropped-databases = false

resume = true
resume-write-unsafe = true
resume-name = "default"
index-files = false
file-highlighting = false
verbose = true
exit-after-direct-reads = false

index-oplog-time=true

index-as-update = true

[logs]
info = "/var/log/monstache/info.log"
warn = "/var/log/monstache/warn.log"
error = "/var/log/monstache/error.log"
trace = "/var/log/monstache/trace.log"
debug = "/var/log/monstache/debug.log"
[mongo-dial-settings]

timeout=15

read-timeout=30

write-timeout=30

[mongo-session-settings]
socket-timeout=0
sync-timeout=7

[[mapping]]
namespace = "ntcarfte.ntc.cdr"
index = "cdr_data"
#type = "child_info"

[[mapping]]
#namespace = "ntcarfte.ntc.callpath_utilizationreport_data"
#index = "callpath_data"
#type = "parent_info"
`


above is my current config and below is example i have used
this is a reference i have used for .toml config  because it wasn't working 
https://medium.com/@nehajirafe/mongodb-to-elasticsearch-sync-using-monstache-cfe1177594b6

`mongo-url =”mongodb://localhost:27017"
elasticsearch-url =”http://localhost:9200"
elasticsearch-max-conns = 10
replay = true
resume = true
resume-name = “default”
namespace-regex =’common.^’
direct-read-namespaces = [“common.parent_info”,”common.child_info”]
index-as-update = true
verbose = true
[logs]
info = “/var/logs/monstache/info.log”
warn = “/var/logs/monstache/warn.log”
error = “/var/logs/monstache/error.log”
trace = “/var/logs/monstache/trace.log”
[[mapping]]
namespace = “common.child_info”
index = “dataintelindex_child”
type = “child_info”
[[mapping]]
namespace = “common.parent_info”
index = “dataintelindex_parent”
type = “parent_info”
`

**Comment by sbnajardhane** [comment]
@milansuthars 
The `direct-read-namespaces` is for the initial dump. It directly read from your database instead of tailing the oplog collection. For real-time sync, you need to watch all events happening on your selected DB collections ([more details here](https://rwynn.github.io/monstache-site/config/#direct-read-namespaces)).  In order to listen to changes from the selected collection, you need to set the `namespace-regex` config.
This is the sample config I have added 
```
# monstache plugin will only listen for the insert, update, delete event on these collections.
namespace-regex = 'db.user|db.transaction'
# Index document into EC user index
[[mapping]]
namespace = "db.user"
index = "user"
type = "_doc"

[[mapping]]
namespace = "db.transaction"
index = "transaction"
type = "_doc"
```

**Comment by milansuthars** [comment]
thanks @sbnajardhane  but still its same i have removed & and i dont see any error log , here is my config updated can you please give some more hints if its about .service file .
its standalone server having mongo ES and monstache on same server ,im novice to systemd my mind sufggest me on that whats your opinion please share.



> mongo-url ="mongodb://localhost:27017"
elasticsearch-url ="http://localhost:9200"
elasticsearch-max-conns = 10
replay = true
resume = true
resume-name = "default"
namespace-regex = 'ntcarfte.ntc.cdr'
direct-read-namespaces = ["ntcarfte.ntc.cdr"]
index-as-update = true
verbose = true
[logs]
info = "/var/log/monstache/info.log"
warn = "/var/log/monstache/warn.log"
error = "/var/log/monstache/error.log"
trace = "/var/log/monstache/trace.log"
[[mapping]]
namespace = "ntcarfte.ntc.cdr"
index = "cdr_data"
type = "_doc"

**Comment by sbnajardhane** [comment]
Here there might be two problems.
Either your system service file is misconfigured or the toml file. I suggest you to run monstache with the direct commands `/usr/local/bin/build/linux-amd64/monstache -f /usr/local/bin/build/linux-amd64/mongo-elastic.toml` and verify if everything is working fine. I can't see any problem with the system ctl file. Below I have provided some directions to debug the issue
**1. Configuring the .toml file**
I have maintained two .toml configs, [I have got this suggestion from the](https://github.com/rwynn/monstache/issues/277) @rwynn and its a cleaner approach I can think of.
First config to dump all the data to ES. Once everything gets sync the plugin will automatically exists then you can resume the syncing with another config which will resume working from some previous timestamp
**For Initial Dump**
```
# This option will take a mongo db dump for the memtioned collection
# and push them to the elasticsearch mapped index
direct-read-namespaces = ['db.user']
# Enable this option to get notified after the dump process gets over.
exit-after-direct-reads = true
# Disable the change events (reading from oplog) during the direct reads.
disable-change-events = true
```
**For ongoing updates**
```
# monstache plugin will only listen for the insert, update, delete event on these collections.
namespace-regex = 'db.user|db.transaction'
# Index document into EC user index
[[mapping]]
namespace = "db.user"
index = "user"
type = "_doc"

[[mapping]]
namespace = "db.transaction"
index = "transaction"
type = "_doc"
```

**Comment by rwynn** [comment]
To expand on what @sbnajardhane wrote, in recent versions of monstache there is a new `direct-read-stateful` boolean option.  This was added so you can maintain one config file / service and have the state of the initial sync recorded when completed.  This just means that when you restart the service the full sync will not by repeated as long as it had finished at least once. 

```toml
direct-read-stateful = true
```
This can be used as an alternative to the 2-service approach.

**Comment by sbnajardhane** [comment]
@rwynn 
This is a great enhancement.
