### ISSUE TITLE
Unable to connect to MongoDB using URL mongodb://REDACTED@localhost:27017: server selection error: server selection timeout, current topology ....  current topology: { Type: ReplicaSetNoPrimary,

### ISSUE THREAD

**Issue by byteab** [rwynn/monstache#444]
adding `connect=direct` to mongodb connection string fixed the issue fixed the issue.
it should be documented in some where. that for single node replica we should add this option

**Comment by EhsanSarshar** [comment]
@rwynn plz help me to solve it

**Comment by EhsanSarshar** [comment]
/?connect=direct"

**Comment by pcinnusamy** [comment]
@EhsanSarshar 

I am also facing an issue while connecting Document DB, Can you please share the sample connection string ?

**Comment by rishavmehra** [comment]
@pcinnusamy have you found the solution? if yes, please share the string
