### ISSUE TITLE
Quick question: Can we import from another .js file in a Javacript script?

### ISSUE THREAD

**Issue by aguyinmontreal** [rwynn/monstache#45]
Can we import from another .js file in a Javacript script?

If yes, how to? And where does a relative path should start from (the .exe file OR the TOML file)?

**Comment by rwynn** [comment]
No you cannot do that yet.

**Comment by aguyinmontreal** [comment]
No problem! I'll just copy paste my code into the config.toml file.

**Comment by rwynn** [comment]
@aguyinmontreal in the latest version you can reference a file path to a script.  You still cannot import scripts from within the script itself though.  You would need to use a build tool to bundle everything together.  https://rwynn.github.io/monstache-site/config/#script
