### ISSUE TITLE
Bulk index request fails, not all documents are indexed

### ISSUE THREAD

**Issue by petersaalbrink** [rwynn/monstache#450]
Hi,

I'm facing an issue where not all documents from a MongoDB collection are indexed (only ~5%). In the logs, I'm seeing a message like this repeatedly:

```
Nov  9 21:27:44 37-97-169-90 monstache[4034]: ERROR 2020/11/09 21:27:44 Bulk index request with execution ID 187 has 1 line failure/warning(s)
```

I've tried to figure out what this failure/warning is, but unsuccessfully.

The collection is created through a `mongorestore` command, from a dump that was created on another instance. On this other instance, there was no issue with syncing of documents. 

A restart of Monstache does not trigger a complete indexing operation. Changing one of the documents in MongoDB does, however, but I want the index to be created immediately after the restore.

Elasticsearch version 6.3.1
MongoDB version 3.6.3
Monstache version 4.8.0

Could you please help me identify the issue?

**Comment by rwynn** [comment]
Hi @petersaalbrink ,

Do you have `direct-read-namespaces` specified somewhere in your monstache configuration?  Docs [here](https://rwynn.github.io/monstache-site/config/#direct-read-namespaces).  That setting should allow you to do a full sync of the given MongoDB namespaces any time monstache is restarted.  

Also, if possible, you may want to consider upgrading monstache to `v5.7.1`.  The instructions for using that version with pre-4.0 versions of monstache is in the blue note [here](https://rwynn.github.io/monstache-site/advanced/#versions).

You also may want to try setting `verbose=true` in your monstache configuration to troubleshoot errors.

**Comment by petersaalbrink** [comment]
Hi @rwynn, thank you for your fast response! 

I was somewhat familiar with the `direct-read-namespaces` setting, but apparently I've never read the documentation for it; it looks like it probably is the solution in this case. 

Thanks for pointing it out! I will try it and let you know the result.

**Comment by petersaalbrink** [comment]
It worked, of course! Thanks again. Closing this issue.
