### ISSUE TITLE
Configure without replicaset - to listen for creates, updates & delete ?

### ISSUE THREAD

**Issue by devansvd** [rwynn/monstache#451]
Trying to configure monstache without replicasets to listen for creates, updates, and delete, As per the docs I have turned on `enable-oplog = true` to emulate changes events and `resume-strategy = 0` Also tested with resume-strategy = 1. 

**Issue :** Couldn't** get this working for listen on create, updates, and delete.

A sample config for with and without replica would be great to the docs.
```
verbose = true
mongo-url = "mongodb://192.168.2.169:27018"
elasticsearch-urls = ["http://192.168.2.169:9200"]
elasticsearch-user = "elastic"
elasticsearch-password = "elastic"
elasticsearch-max-conns = 10
enable-oplog = true
resume = true
resume-strategy = 0
config-database-name = "monstache"
mongo-oplog-database-name = "monstache_oplog"
direct-read-namespaces = ["np.details"]
```
logs from monstache verbose

```
INFO 2020/11/11 07:12:45 Started monstache version 6.7.1
INFO 2020/11/11 07:12:45 Go version go1.14
INFO 2020/11/11 07:12:45 MongoDB go driver v1.4.3
INFO 2020/11/11 07:12:45 Elasticsearch go driver 7.0.21
INFO 2020/11/11 07:12:45 Successfully connected to MongoDB version 3.0.15
INFO 2020/11/11 07:12:45 Successfully connected to Elasticsearch version 7.9.3
INFO 2020/11/11 07:12:45 Listening for events
INFO 2020/11/11 07:12:45 Sending systemd READY=1
WARN 2020/11/11 07:12:45 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2020/11/11 07:12:45 Direct reads completed
ERROR 2020/11/11 07:12:45 key "operationTime" was not found
```

**Comment by rwynn** [comment]
Hi @devansvd you have the right idea to set `enable-oplog=true` given that you have a pre-v3.6 version of MongoDB (so no change streams available).  

When you enable that mode monstache will attempt to read from the [MongoDB 3.0 oplog](https://docs.mongodb.com/v3.0/reference/local-database/#local.oplog.rs) directly to read insert/delete/update events and emulate a change stream. 

You customized the `mongo-oplog-database-name` option which defaults to the `local` database.  That may be why you got the error that you did around `operationTime`.   You normally should not need to customize `mongo-oplog-database-name`. 

Another thing to consider is that you need to enable the oplog.  It is not created by default.  To create it you need to be a member of a replica set, even if you are just using a replica set of 1 node.  To do that you can follow these MongoDB 3.0 [instructions](https://docs.mongodb.com/v3.0/tutorial/convert-standalone-to-replica-set/#procedure) and stop at 1 node.  

So in total I would suggest removing these 3 lines...
```toml
resume-strategy = 0
config-database-name = "monstache"
mongo-oplog-database-name = "monstache_oplog"
```
and making sure that `rs.status()` command looks OK from the MongoDB shell after following the instructions.

**Comment by devansvd** [comment]
@rwynn mongodb version less than 3.6 or greater than 3.6 - either case we need to enable replica sets to make this works right ? - without sets its not possible ?

**Comment by rwynn** [comment]
@devansvd yes you need an `oplog` for monstache to tail in this case.  That is only way it can detect changes.

**Comment by devansvd** [comment]
@rwynn thanks for clarifying. Great work indeed. I have tried quite a few solutions like 

- Logstash with jdbc connection faced BJSON parsing exception almost not possible to use it
- logstash with logstash-input-mongodb plugin messing up nested json objects and arrays impossible to utilize.
 
As a end user I feel monstache is the best solution out there & solved the problem well especially for change events.  Thanks for making this.
