### ISSUE TITLE
Update golang version to fix fatal error: mlock failed

### ISSUE THREAD

**Issue by 3fd** [rwynn/monstache#456]
I'm running into the https://github.com/golang/go/issues/37436 issue when starting monstache on an ubuntu 20.04 host

Can you please update the golang version to >= 1.14.1?

I have verified that upgrading to 1.14.1 fixes the issue

**Comment by rwynn** [comment]
Hi @3fd thanks for your help identifying the issue.  Can you try with monstache `6.7.2`?

**Comment by 3fd** [comment]
The issue is fixed in the new version. Thank you
