### ISSUE TITLE
docker run: error parsing uri: scheme must be "mongodb" or "mongodb+srv"

### ISSUE THREAD

**Issue by justintilson** [rwynn/monstache#457]
I'm trying to get monstache running with docker and am currently blocked by:

Unable to connect to MongoDB using URL "`mongodb://mongo:27017`": error parsing uri: scheme must be "mongodb" or "mongodb+srv"

As far as I can tell, the mongo URL, including correct scheme is being loaded in from my .env file.

My (stripped down) run command:

`docker run --env-file .env rwynn/monstache:6.7.1`

Abbreviated contents of my .env file:

`MONSTACHE_MONGO_URL="mongodb://mongo:27017"`

The hostname of mongo is `mongo`

Is this PEBKAC or a real issue?

**Comment by rwynn** [comment]
Hi @justintilson that's weird.  I'm not seeing the same behavior outside of docker...

```
$ export MONSTACHE_MONGO_URL="mongodb://mongo:27017"
$ monstache -print-config | grep mongo
  "MongoURL": "mongodb://mongo:27017",
$ monstache -verbose
ERROR 2020/11/25 09:13:28 Unable to connect to MongoDB using URL mongodb://mongo:27017: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongo:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongo: Temporary failure in name resolution }, ] }
exit status 1
$ monstache -v
6.7.1
```

But when I run with docker I get some weirdness.

```
$ cat .env
MONSTACHE_MONGO_URL="mongodb://mongo:27017"

$ docker run --env-file .env rwynn/monstache:6.7.1 -print-config | grep mongo
  "MongoURL": "\"mongodb://mongo:27017\"",

```

If I remove the quotes around  the value it seems to work.

```
$ cat .env
MONSTACHE_MONGO_URL=mongodb://mongo:27017
```

**Comment by justintilson** [comment]
My tired eyes missed the quotes. I must have copied from bash and forgot to clean up. Thank-you!
