### ISSUE TITLE
Build plugin and run monstache with one multi-stage build Dockerfile

### ISSUE THREAD

**Issue by casparkirsch** [rwynn/monstache#458]
**Desired behavior**
I’m working on a Dockerfile that is 1. building a monstache plugin and 2. runs monstache with that plugin. I tried to mirror the steps for building a plugin from [this repo](https://github.com/rwynn/monstache/blob/rel6/docker/plugin/Dockerfile) along with instructions from the [documentation](https://rwynn.github.io/monstache-site/advanced/#golang).

**Problem**
Monstache always fails to run with the error `Unable to load mapper plugin /usr/src/search-sync/plugin.so: plugin.Open("/usr/src/search-sync/plugin"): plugin was built with a different version of package github.com/rwynn/monstache/monstachemap`.

**My Dockerfile**
```
FROM rwynn/monstache-builder-cache-rel6:1.0.5 AS builder

WORKDIR /usr/src/search-sync-plugin

RUN git clone --depth 1 --branch v6.7.1 https://github.com/rwynn/monstache.git .
RUN go mod download

WORKDIR /usr/src/search-sync-plugin/docker/plugin

COPY plugin/plugin.go .

RUN go mod download
RUN go build -buildmode=plugin -o build/plugin.so plugin.go

FROM rwynn/monstache:6.7.1

WORKDIR /usr/src/search-sync

COPY --from=builder /usr/src/search-sync-plugin/docker/plugin/build/plugin.so /usr/src/search-sync/plugin.so
COPY monstache.toml /etc/monstache/monstache.toml
COPY start.sh .

ENTRYPOINT []
CMD ["sh", "start.sh"]
```

**Question**
I’m new to Go and its dependency management (coming from a Node.js background). Do you have a hint for me what might be going wrong with my approach or to solve that version mismatch?

**Comment by rwynn** [comment]
Hi @kernfruit,

Can you try the following, given a folder with contents...

```
Dockerfile  plugin.go
```

And Dockerfile as...

```Dockerfile
####################################################################################################
# Step 1: Build the app and plugin
####################################################################################################

FROM rwynn/monstache-builder-cache-rel6:1.0.6 AS build-app

RUN mkdir /app

WORKDIR /app

RUN git clone --depth 1 --branch v6.7.1 https://github.com/rwynn/monstache.git .

COPY ./plugin.go .

RUN make release

RUN go build -buildmode=plugin -o build/plugin.so plugin.go

####################################################################################################
# Step 2: Copy output build file to an alpine image
####################################################################################################

FROM rwynn/monstache-alpine:3.12.1 AS final

ENTRYPOINT ["/bin/monstache"]

COPY --from=build-app /app/build/linux-amd64/monstache /bin/monstache
COPY --from=build-app /app/build/plugin.so /bin/plugin.so

```

Run 

```bash
docker build -t monstache .
```

Which should allow you to run the container with the plugin like ...

```bash
docker run --rm --net=host monstache:latest -mapper-plugin-path /bin/plugin.so
```

The key will this approach is that both the monstache binary and plugin are built with the same `go.mod` from the same directory.

**Comment by casparkirsch** [comment]
Hi @rwynn!

This worked, thank you very much!
