### ISSUE TITLE
Plugin build error - build with different version of internal/unsafeheader

### ISSUE THREAD

**Issue by adiliqbl** [rwynn/monstache#460]
Hi. First of all, thanks to this amazing library. It has made it quite easy for syncing Mongo with Elasticsearch.

**Environment**:
linus: Ubuntu 18.04.4 LTS
go version: go1.15.5 linux/amd64  
monstache: v6.7.1

I am having difficulty building a plugin for adding suggestions to Elasticsearch. After building the plugin using commands below, I'm getting this error, I am unable to fix it after spending hours on it:

> Unable to load mapper plugin /path/to/suggester_plugin.so: plugin.Open("/path/to/suggester_plugin"): plugin was built with a different version of package internal/unsafeheader.

```shell script
git clone https://github.com/rwynn/monstache.git
cd monstache
git fetch --all --tags --prune
git checkout tags/v6.7.1
go install
go build -buildmode=plugin -o suggester_plugin.so suggester_plugin.go
```

This is the plugin code:
```go
package main

import (
	"log"
	"os"
	"github.com/rwynn/monstache/monstachemap"
)

func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	output = &monstachemap.MapperPluginOutput{Skip: true}
	return
}

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	mapping := `{
		"properties" : {
			"Event" : { "type" : "string" },
			"suggest" : { 
				"type" : "completion",
				"analyzer" : "simple",
				"search_analyzer" : "simple",
				"payloads" : true
			}
		}
	}`

	input.ElasticClient.PutMapping().Index("mydb.collection").BodyString(mapping)
	return
}
```

**Comment by adiliqbl** [comment]
I was able to get it working by building monstache from the source code instead of using the downloaded file. I might've missed that from the documentations. Closing this ticket now!

**Comment by rwynn** [comment]
Hi @adiliqbl 

Thanks and glad you figured it out!  Native go plugins are a little tough.  I've found that building the monstache binary and plugin shared object file together from the source code like you did is the best way to ensure successful pairing.  I need to make the documentation clearer around this and that the resulting binary of the `go install` step should be used.    

If you go the plugin route it's easiest to disregard the monstache release binaries and build the binary from source.
