### ISSUE TITLE
[[relate]] not working when match-field type is string

### ISSUE THREAD

**Issue by minhuyen** [rwynn/monstache#464]
- users collection:

{
    "_id" : ObjectId("5fbcba4e0317afbe69aefe1f"),
    "name" : "Tesst meo the nao"
}

 - course collection:

{
    "_id" : ObjectId("5fbcbf926f800bc0282dc1c1"),
    "status" : "active",
    "countDone" : 1,
    "userId" : "5fbcba4e0317afbe69aefe1f",
    "note" : "Note test potato cake orange orange potato beer beer cake"
}

config:

[[relate]]
namespace = "user.users"
with-namespace =  "course.course_users"
src-field = "_id"
match-field = "userId"
keep-src = true
dot-notation = true

When I update users collections it can not trigger sync course collection.
Can we have the option to convert the value field to string?

Thanks

**Comment by rwynn** [comment]
Hi @minhuyen as you found right now type conversion is not supported in relate.  If you are comfortable with go you can write a plugin that listens for changes to the users collection in a `Process` function, finds the corresponding course, and queues it to be indexed.

I will think about how to possibly add the type conversion feature in the future.   

You may find it easier to add the conversion for now to the [selector](https://github.com/rwynn/monstache/blob/rel6/monstache.go#L1114) in the `processRelate` function.

**Comment by minhuyen** [comment]
Hi @rwynn!
Thanks for your answer. 

I'm not comfortable with go but I will try it.

Have a nice day!
