### ISSUE TITLE
Not removing deleted items in Elasticsearch on direct read

### ISSUE THREAD

**Issue by adiliqbl** [rwynn/monstache#466]
Hi. I've setup monstache processes multiple ways - first one is full sync (using `direct-read-namespace/exit-after-direct-read`) as cronjob and second listening to specific collection (using `change-stream-namespaces`). Everyone thing is working except that full sync isn't deleting the items that were indexed in ES previously but now deleted in mongodb. I have searched through the documentation and issues, but couldn't find anything similar. I'm sure there's something wrong with the config that I can't figure out.

**Environment**
go version: go1.15.5 linux/amd64
monstache: v6.7.1

I'm using this command for executing:  
```
monstache -f "monstache-config.toml" -mapper-plugin-path "monstache_plugin.so" -direct-read-namespace db.products -exit-after-direct-reads
```

**Config File**
```shell script
change-stream-namespaces = ["db.products"]
routing-namespaces = ["", "db.products"]
delete-index-pattern = "product"

elasticsearch-max-conns = 10
elasticsearch-retry = true
dropped-collections = true
dropped-databases = true
config-database-name = "elasticsearch-monstache"
gzip = true
stats = true
resume = true
resume-name = "default"
resume-write-unsafe = false
index-as-update = true
enable-http-server = true
http-server-addr = ":9090"
verbose = false

[logs]
info = "/etc/monstache/info.log"
warn = "/etc/monstache/warn.log"
error = "/etc/monstache/error.log"
trace = "/etc/monstache/trace.log"

[[mapping]]
namespace = "db.products"
index = "product"

[[filter]]
namespace = "db.products"
script = """
module.exports = function(doc, ns, updateDesc) {
    return doc.active >= 1;
}
"""

[[script]]
namespace = "db.products"
script = """
var counter = 1;
module.exports = function(doc) {
   doc.image = doc.images && doc.images.length > 0 ? doc.images[0] : null;
   delete doc.images;
   return doc;
}
"""
```

**monstache_plugin.go**
```golang
package main

import (
	"log"
	"os"
	"github.com/rwynn/monstache/monstachemap"
)

func Process(input *monstachemap.ProcessPluginInput) (err error) {
	var infoLog = log.New(os.Stdout, "INFO ", log.Flags())
	infoLog.Printf("Suggester process started")

	carMapping := `{
		"properties" : {
			"Event" : { "type" : "string" },
			"suggest" : {
				"type" : "completion",
				"analyzer" : "simple",
				"search_analyzer" : "simple",
				"payloads" : true
			}
		}
	}`

	input.ElasticClient.PutMapping().Index("db.products").BodyString(carMapping)
	return
}
```

Here's the output from `info.log` file. Though monstache is printing changeStream error from time to time (I deleted the logs for testing, will comment here once I see the error again).
```
INFO 2020/12/08 08:36:55 Started monstache version 6.7.1
INFO 2020/12/08 08:36:55 Go version go1.15.5
INFO 2020/12/08 08:36:55 MongoDB go driver v1.4.3
INFO 2020/12/08 08:36:55 Elasticsearch go driver 7.0.21
INFO 2020/12/08 08:36:56 Successfully connected to MongoDB version 4.4.1
INFO 2020/12/08 08:36:56 Successfully connected to Elasticsearch version 7.10.0
INFO 2020/12/08 08:36:56 Listening for events
INFO 2020/12/08 08:36:56 Watching changes on collection db.products
INFO 2020/12/08 08:36:57 Direct reads completed
INFO 2020/12/08 08:36:57 Resuming from timestamp {T:1607397619 I:2}
INFO 2020/12/08 08:36:58 Stopping all workers
INFO 2020/12/08 08:36:58 Shutting down
```

**Comment by rwynn** [comment]
hi @adiliqbl , I noticed in your `mapping` you have the index set to `product` but in the `delete-index-pattern` you have monstaches searching only the index `products` with an s.  I think maybe you want to change to the following

```toml
delete-index-pattern = "product"
```

If you have monstache indexing into other indices in Elasticsearch then you would enumerate all of those separated by comma, e.g.

```toml
delete-index-pattern = "product,user,invoice"
```

**Comment by adiliqbl** [comment]
Hi @rwynn, thanks for replying. Actually I misspelled `delete-index-pattern` while pasting here, my apologies for that. Do you think there's anything else that might be causing the issue?

**Comment by rwynn** [comment]
Can you try setting `verbose=true` then running monstache and capturing the output when a delete occurs in collection `db.products` in MongoDB?  It should be sending a request to Elasticsearch shortly after.  Need to see what is in that request.

**Comment by adiliqbl** [comment]
Here's the `trace.log` from change stream on item deletion.
```
TRACE 2020/12/08 23:13:50 POST /product/_search HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (linux-amd64)
Transfer-Encoding: chunked
Accept: application/json
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==
Content-Type: application/json
Accept-Encoding: gzip

4e
{"_source":false,"query":{"term":{"_id":"5fcce635aa488e019864eabc"}},"size":1}
0


TRACE 2020/12/08 23:13:50 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"product","_type":"_doc","_id":"5fcce635aa488e019864eabc","_score":1.0}]}}
TRACE 2020/12/08 23:13:50 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (linux-amd64)
Content-Length: 65
Accept: application/json
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_index":"product","_id":"5fcce635aa488e019864eabc"}}

TRACE 2020/12/08 23:13:50 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":11,"errors":false,"items":[{"delete":{"_index":"product","_type":"_doc","_id":"5fcce635aa488e019864eabc","_version":2,"result":"deleted","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":72,"_primary_term":1,"status":200}}]}
```

**Comment by rwynn** [comment]
That actually looks OK to me.  I don't see any errors in that log.  Does that _id look correct to you?  Did the document get deleted?

**Comment by adiliqbl** [comment]
Yes. Everything works normally in change stream mode. But if the change stream mode isn't running and some data gets deleted from mongodb, then monstache isn't deleting those entries from elasticsearch when using direct-read, but it updates/inserts items correctly.

**Comment by rwynn** [comment]
Hi @adiliqbl change streams are required for detecting the delete events.  Direct reads are simply reading what is currently in the collection which does not include any history of what was once there.

**Comment by adiliqbl** [comment]
Okay, so from what I understand, monstache doesn't delete items from ES that are missing in Mongodb? How would you suggest to handle this scenario? Because I'm using ES for product queries and if monstache crashes and data is deleted from back-end in the mean while, the deleted items will still show up in ES search.

Thank you for your replies, really appreciate.

**Comment by rwynn** [comment]
Hi @adiliqbl the `resume` setting when enabled keeps track of the last processed event timestamp.   If monstache crashes, the next time run it resumes the change stream from the last event timestamp it received.  This should pick up events that were missed by monstache but captured by MongoDB (including deletes).

**Comment by adiliqbl** [comment]
Right, I was under the impression that direct reads dumps entire data and deletes old ES indices. 

Closing the ticket. Thank you so much for clearing this for me. :)
