### ISSUE TITLE
[[relate]] not working

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#468]
I have two collections Modify and Product. Each Modify item is relate to several Product.
I'm using version 5.7.2. When I change the Modify item, only one item from Product is updated. If i downgrade to version 5.7.1 then it works properly, all related Product is updated. I see it in verbose mode. What could be the problem?

I use the same conf file in both cases
```
relate-buffer = 5000
prune-invalid-json = true

change-stream-namespaces = [
    "db.Modify",
    "db.Product"
]
...
[[relate]]
namespace = "db.Modify"
with-namespace = "db.Product"
src-field = "_id"
match-field = "modifyId"
keep-src = false
```

**Comment by rwynn** [comment]
Hi, thanks for reporting.  I think it should be fixed in https://github.com/rwynn/monstache/commit/595c6bf72cab80fb082b7ef0cc9e717b6647020e

**Comment by rwynn** [comment]
@ail-13 pushed a new release with a fix for this.  Thanks.

**Comment by ail-13** [comment]
Thanks for your great work!
