### ISSUE TITLE
[[relate]] error

### ISSUE THREAD

**Issue by ail-13** [rwynn/monstache#469]
Hi, I update to 5.7.3 to fix my [problem](https://github.com/rwynn/monstache/issues/468), but now I have infinity errors when I try to change Modify item:

...
ERROR 2020/10/12 18:32:34 elastic: bulk processor "monstache" failed: elastic: Error 400 (Bad Request): Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;21: type is missing; [type=action_request_validation_exception]
ERROR 2020/10/12 18:32:34 elastic: bulk processor "monstache" was unable to perform work: elastic: Error 400 (Bad Request): Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;21: type is missing; [type=action_request_validation_exception]
...

![image](https://user-images.githubusercontent.com/45662718/102486215-bcf00880-4079-11eb-9e1b-777d643220bb.png)

**Comment by rwynn** [comment]
Hi @ail-13, trying to figure out what the problem might be. 

Is it possible you downloaded or are using monstache `v6` instead of `v5`?  

Can you verify that the output of `monstache -v` is giving you 5.7.3? 

I checked both the `v5.7.3` download and docker image and both seem to be sending `_type` information.

```
./build/linux-amd64/monstache -verbose
INFO 2020/12/17 08:43:26 Started monstache version 5.7.3
INFO 2020/12/17 08:43:26 Go version go1.15.5
INFO 2020/12/17 08:43:26 MongoDB go driver v1.4.4
INFO 2020/12/17 08:43:26 Elasticsearch go driver 6.2.35
INFO 2020/12/17 08:43:26 Successfully connected to MongoDB version 4.2.11
INFO 2020/12/17 08:43:26 Successfully connected to Elasticsearch version 7.10.1
INFO 2020/12/17 08:43:26 Sending systemd READY=1
WARN 2020/12/17 08:43:26 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2020/12/17 08:43:26 Listening for events
INFO 2020/12/17 08:43:26 Watching changes on the deployment
TRACE 2020/12/17 08:43:40 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.2.35 (linux-amd64)
Content-Length: 147
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5fdb608b937b75f8377f34f2","_type":"_doc","version":6907220603619508226,"version_type":"external"}}
{"foo":1}

```

**Comment by ail-13** [comment]
Sorry, that is my mistake. I used wrong version. I downloaded 6.7.3 instead 5.7.3. Now I use 5.7.3 and it work properly. Thanks for your help!
