### ISSUE TITLE
Failed request line #0 details: {"_index":"ttt.No2","_type":"_doc","_id":"5a9bff2d4e3d6cf0131b07af","status":400,"error":{"type":"invalid_index_name_exception","reason":"Invalid index name [ttt.No2], must be lowercase","index":"ttt.No2"}}

### ISSUE THREAD

**Issue by snoopy83101** [rwynn/monstache#47]
Failed request line #0 details: {"_index":"ttt.No2","_type":"_doc","_id":"5a9bff2d4e3d6cf0131b07af","status":400,"error":{"type":"invalid_index_name_exception","reason":"Invalid index name [ttt.No2], must be lowercase","index":"ttt.No2"}}

Is there any way to do it?

Mongodb allows the capitalization, it already exists

**Comment by rwynn** [comment]
See index mapping at https://rwynn.github.io/monstache-site/advanced/  so that you can change index name to lowercase.

**Comment by rwynn** [comment]
added a fix to master and rel3 branches to do this automatically.  will be in next release. For now you can use a custom index mapping.

**Comment by rwynn** [comment]
this should be fixed now in the latest release.  thanks.

**Comment by snoopy83101** [comment]
Thank you very much for your kind help, although my English machine is fine   O__O "…

**Comment by kgrvamsi** [comment]
@rwynn do you mean that if the collection name is like Employee then mapping should be like 

```
[[mapping]]
namespace = "test.employee"
index = "test"
type = "employee"
```

**Comment by rwynn** [comment]
If the collection name is `Employee` then the mapping should be
```
[[mapping]]
namespace = "test.Employee"
index = "test"
type = "employee"
```

Monstache will only lowercase you index names since ES does not allow otherwise.  MongoDB namespace is whatever you have in MongoDB.

**Comment by kgrvamsi** [comment]
@rwynn your library rocks and it helped me alot (was using mongo-connector before) and can i use this in production and here are my settings that i want to use.(please advice if these values makes sense)

```
gzip = true

stats = true

index-stats = true

mongo-url = "mongodb://root:jerry@192.168.0.47:27017/connectortest"

elasticsearch-urls = ["http://192.168.0.46:9200"]

elasticsearch-user = "elastic"

elasticsearch-password = "elasticpassword"

elasticsearch-max-conns = 10

dropped-collections = true

dropped-databases = true

replay = false

resume = true

resume-write-unsafe = false

resume-name = "default"

verbose = true

direct-read-namespaces = ["connectortest.syncthis","connectortest.vamsi"]

 

[[mapping]]

namespace = "connectortest.syncthis"

index = "connectortest"

type = "syncthis"

 

[[mapping]]

namespace = "connectortest.vamsi"

index = "connectortest"

type = "vamsi"
```

**Comment by rwynn** [comment]
@kgrvamsi thanks and those settings look fine.  Just read the comments on this issue to understand the implications of syncing 2 collections to the same index.  https://github.com/rwynn/monstache/issues/49

**Comment by kgrvamsi** [comment]
@rwynn if i create different indexes for the same table what would be the settings i need to use?
( ```namespace-regex = '^mydb\.(mycollection|\$cmd)$' ``` )

I'm not sure if on the pattern of collection that i may end up as there are 50 collections with different names.

**Comment by rwynn** [comment]
If by that you mean you want to index anything in `mydb` then you could use

```
namespace-regex = '^mydb\.'
```

That will include database and collection drops resulting in a delete index.  If you don't want that you can turn those off globally

```
dropped-databases = false
dropped-collections = false
```

You can test expressions here https://golang.org/pkg/regexp/.  If the namespace matches then the operation will be not be ignored.

**Comment by kgrvamsi** [comment]
if i'm trying to sync the data for the first time then i can use drop-database and dropped-collections to true right?will that impact if i restart the monstache by deleting the old indexes created in ES?

**Comment by rwynn** [comment]
When those are true it just means that if you issue a drop db/collection in Mongodb that will be synced to ES which means index deletes sent.

If they are false monstache ignores that type of operation. It would then only delete individual docs when you delete those in MongoDB. 

It’s probably safest to set those both to false and manually delete indexes in ES if you want to.
