### ISSUE TITLE
how to use namespace-regex in change-stream-namespaces pattern

### ISSUE THREAD

**Issue by jctang1016** [rwynn/monstache#471]
Hi, we have dynamically created collections in mongo database.

I see that it is possible to have a regex when listening to oplog changes via namespace-regex. 
I want to sync colletions like "model_coll_inst_*"
how can i use this?
change-stream-namespaces = [""] 
namespace-regex = '^cmdb-paas-v2-test\.model_inst_coll_$'

**Comment by jctang1016** [comment]
mongo version: 3.6
es: 7.0+

config.toml-->:
    mongo-url = "mongodb://user:pwd@x.x.x.x:27017"
    elasticsearch-urls = ["http://x.x.x.x:9200"]
    change-stream-namespaces = [ "" ]
    namespace-regex = '^mydb\.model_inst_coll_$'
    elasticsearch-user = "user"
    elasticsearch-password = "pwd"
    elasticsearch-max-conns = 4
    dropped-collections = true
    dropped-databases = true
    resume = true
    resume-name = "mydb"
    resume-strategy = 1
    verbose = true

ERROR 2020/12/22 16:54:52 Error starting change stream. Will retry: (Location40415) BSON field '$changeStream.allChangesForCluster' is an unknown field.

**Comment by rwynn** [comment]
Hi @jctang1016 , to open change streams against `the deployment` or `a database` you would need MongoDB server 4.0.  With 3.6 you can only open change streams against specific collections by full name.  

If you need to use MongoDB 3.6 and need to listen to all change events then you can use a configuration like

```toml
# enable the legacy mode to directly tail the oplog collections
enable-oplog = true
# turn off change streams
change-stream-namespaces = []
```

This requires that you give the user that monstache connects with the ability to read from the oplog.
