### ISSUE TITLE
Custom settings for Elasticsearch Indices ?

### ISSUE THREAD

**Issue by duypv98** [rwynn/monstache#472]
I am using `monstache` version 6.7.3 with MongoDB 4.4 and Elasticsearch 7.10.1. It works well, thank you.
But I need to change some settings of the elasticsearch indices (I want to custom index's analyzer) before sync and I can't find any instructions.

Could you help me on this ? Thanks !

**Comment by rwynn** [comment]
Hi @duypv98 I've intentionally kept monstache out of the domain of index settings configuration.  I usually suggest using [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) prior to running monstache as you can see in [this example](https://github.com/rwynn/monstache-showcase/blob/master/elasticsearch/configure.sh). 

If you've already created indexes using monstache you can delete them, create index templates wtih `index_patterns` matching the names of those indexes, and re-run monstache using `direct-read-namespaces` to do a full sync.

**Comment by duypv98** [comment]
@rwynn Thank you so much!
