### ISSUE TITLE
Data is not syncing

### ISSUE THREAD

**Issue by somaniketan74** [rwynn/monstache#474]
Hi, I am new to monstache, i want to just sync all collection in my database to elastic search. For some reason it's not working. I tried insert / update / delete. No operation reflecting in index.

Monstache version: 6.7.3
Mongodb: 4.2
Elasticsearch: 7.10

I am running monstache using following command
`./monstache -f config.toml -verbose`

config.toml

```
mongo-url = "mongodb://XXXX:XXXXX@test-shard-00-00.2wf2l.mongodb.net:27017,test-shard-00-01.2wf2l.mongodb.net:27017,test-shard-00-02.2wf2l.mongodb.net:27017/monstache?ssl=true&replicaSet=atlas-gl2qi0-shard-0&authSource=admin&retryWrites=true"
elasticsearch-urls = ["http://localhost:9200"]

change-stream-namespaces = ["monstache"]

[logs]
error = "./logs/error.log" 
info = "./logs/info.log"
warn = "./logs/warn.log"
trace = "./logs/trace.log"

```
info.log

> INFO 2021/01/10 16:39:19 Started monstache version 6.7.3
INFO 2021/01/10 16:39:19 Go version go1.15.5
INFO 2021/01/10 16:39:19 MongoDB go driver v1.4.4
INFO 2021/01/10 16:39:19 Elasticsearch go driver 7.0.22
INFO 2021/01/10 16:39:19 Successfully connected to MongoDB version 4.2.11
INFO 2021/01/10 16:39:19 Successfully connected to Elasticsearch version 7.10.1
INFO 2021/01/10 16:39:19 Sending systemd READY=1
INFO 2021/01/10 16:39:19 Listening for events
INFO 2021/01/10 16:39:19 Watching changes on database monstache

warn.log

> WARN 2021/01/10 16:39:19 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)

User privilege
`db.runCommand(    {      usersInfo:  { user: "ketan", db: "monstache" },      showPrivileges: true    } )`

> {
	"users" : [
		{
			"_id" : "admin.ketan",
			"user" : "ketan",
			"db" : "admin",
			"roles" : [
				{
					"role" : "testRole",
					"db" : "admin"
				}
			],
			"inheritedRoles" : [
				{
					"role" : "testRole",
					"db" : "admin"
				},
				{
					"role" : "dbAdmin",
					"db" : "monstache"
				},
				{
					"role" : "read",
					"db" : "monstache"
				},
				{
					"role" : "readWrite",
					"db" : "monstache"
				}
			],
			"inheritedPrivileges" : [
				{
					"resource" : {
						"db" : "monstache",
						"collection" : ""
					},
					"actions" : [
						"bypassDocumentValidation",
						"collMod",
						"collStats",
						"compact",
						"convertToCapped",
						"createCollection",
						"createIndex",
						"dbStats",
						"dropCollection",
						"dropDatabase",
						"dropIndex",
						"enableProfiler",
						"listCollections",
						"listIndexes",
						"planCacheIndexFilter",
						"planCacheRead",
						"planCacheWrite",
						"reIndex",
						"renameCollectionSameDB",
						"storageDetails",
						"validate"
					]
				},
				{
					"resource" : {
						"db" : "monstache",
						"collection" : "system.profile"
					},
					"actions" : [
						"changeStream",
						"collStats",
						"convertToCapped",
						"createCollection",
						"dbHash",
						"dbStats",
						"dropCollection",
						"find",
						"killCursors",
						"listCollections",
						"listIndexes",
						"planCacheRead"
					]
				},
				{
					"resource" : {
						"db" : "monstache",
						"collection" : ""
					},
					"actions" : [
						"changeStream",
						"collStats",
						"dbHash",
						"dbStats",
						"find",
						"killCursors",
						"listCollections",
						"listIndexes",
						"planCacheRead"
					]
				},
				{
					"resource" : {
						"db" : "monstache",
						"collection" : "system.js"
					},
					"actions" : [
						"changeStream",
						"collStats",
						"dbHash",
						"dbStats",
						"find",
						"killCursors",
						"listCollections",
						"listIndexes",
						"planCacheRead"
					]
				},
				{
					"resource" : {
						"db" : "monstache",
						"collection" : ""
					},
					"actions" : [
						"changeStream",
						"collStats",
						"convertToCapped",
						"createCollection",
						"createIndex",
						"dbHash",
						"dbStats",
						"dropCollection",
						"dropIndex",
						"emptycapped",
						"find",
						"insert",
						"killCursors",
						"listCollections",
						"listIndexes",
						"planCacheRead",
						"remove",
						"renameCollectionSameDB",
						"update"
					]
				},
				{
					"resource" : {
						"db" : "monstache",
						"collection" : "system.js"
					},
					"actions" : [
						"changeStream",
						"collStats",
						"convertToCapped",
						"createCollection",
						"createIndex",
						"dbHash",
						"dbStats",
						"dropCollection",
						"dropIndex",
						"emptycapped",
						"find",
						"insert",
						"killCursors",
						"listCollections",
						"listIndexes",
						"planCacheRead",
						"remove",
						"renameCollectionSameDB",
						"update"
					]
				}
			]
		}
	],
	"ok" : 1
}

Am i missing anything for configuration?

**Comment by somaniketan74** [comment]
@rwynn Please help me here.

**Comment by rwynn** [comment]
@somaniketan74 `monstache` is the name of the [config database](https://rwynn.github.io/monstache-site/config/#config-database-name) the monstache uses by default for it own runtime metadata.  The assumption is that this is reserved for monstache and not something related to your application that you want to sync. 

If you want to use that as the database name for the data that gets synced then you need to change the config db to something else.  

```toml
config-database-name = "anything"
```

**Comment by antonimmo** [comment]
@rwynn  Does it mean you cannot listen to changes (using `change-stream-namespaces`) to the same database set as `config-database-name`?

**Comment by rwynn** [comment]
@antonimmo yes, events from whatever db that is set to are filtered... https://github.com/rwynn/monstache/blob/43c082989edafd957b5b8c4a4182da45a0cc5090/monstache.go#L1348

**Comment by somaniketan74** [comment]
Thank @rwynn for suggestion. I was using "monstache" as database. that was the issue. After changing database name it start listening all events.

**Comment by antonimmo** [comment]
Same here. Also, it would be nice that Monstache detects you're trying to stream from `config-database-name` and warn you it will be filtered out, or state it somewhere in the documentation.
