### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by lihaiswu** [rwynn/monstache#475]
I'm using rwynn/monstache:6.7.3 and seeing following error when running with command "GODEBUG=x509ignoreCN=0 monstache -f /monstache.config.toml"

ERROR 2021/01/13 06:47:46 Unable to connect to MongoDB using URL mongodb://REDACTED@host1:27017, host2:27017, host3:27017/admin?replicaSet=test-0&SSL=true&SSLCaFile=/etc/ssl/certs/cat-cert-mongo.crt: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: host1: 27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : x509: certificate signed by unknown authority }, { Addr: host2: 27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : x509: certificate signed by unknown authority }, { Addr: host3: 27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : x509: certificate signed by unknown authority }, ] }

From the log, we can see the state is connected, but throw error: "x509: certificate signed by unknown authority". The same cert file works for other applications. Any idea on how to make it work? Thanks.

**Comment by rwynn** [comment]
Hi @lihaiswu can you check the driver docs [here](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Connect).  If you can configure your connection string to work with the official go driver then it should also work for monstache.

**Comment by lihaiswu** [comment]
Thanks @rwynn . We can make it work using following mongo-url:

`mongo-url = "mongodb://REDACTED@host1:27017, host2:27017, host3:27017/database-name?replicaSet=test-0&SSL=false&tlscafile=/etc/ssl/certs/cat-cert-mongo.crt&authMechanism=SCRAM-SHA-256"`


INFO 2021/01/13 07:58:45 Started monstache version 6.7.3
INFO 2021/01/13 07:58:45 Go version go1.15.5
INFO 2021/01/13 07:58:45 MongoDB go driver v1.4.4
INFO 2021/01/13 07:58:45 Elasticsearch go driver 7.0.22
INFO 2021/01/13 07:58:45 Successfully connected to MongoDB version 4.2.6
