### ISSUE TITLE
Elastic "no such index" 

### ISSUE THREAD

**Issue by mlodic** [rwynn/monstache#476]
Hi everyone and congratulations on this great project!

Regarding this closed issue #263, I am facing the same problem. I get a lot of these error messages:
```
elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]
```

The point is:
* I tripled check the configuration: all the indexes that monstache should sync already exist
* I tried with `verbose=true` and trace logs but they do not show 404 HTTP requests...I only see 200 status code there
* All the sync seems to work correctly, I got the same number of documents both in Elastic and MongoDB. However this error keeps appearing multiple times in a row (~4 times) with non-repetitive intervals times (usually at least 1 time an hour).

How can I find which is the index that is not created? Is it possible that is something related to inner workings of Monstache? Is it possible to increase the logs to see what is the main cause? Do you have any suggestion?

Thank you in advance

**Comment by rwynn** [comment]
Hi @mlodic, I wasn't able to figure out what might be producing this message.  But I added a commit to attempt to print more details from the `elastic.Error`.  By default the `Error` method only prints a [subset](https://github.com/olivere/elastic/blob/21064b90616b5e9a45df8c406b222d46cad5b14b/errors.go#L103) of the information. 

Would you be able to build monstache from latest `rel5` or `rel6` branch and let me know if this additional logging reveals anything about the index that is not being found?

**Comment by mlodic** [comment]
Thank you! I have just implemented the rel5! I'll tell you as soon as I get some results

**Comment by mlodic** [comment]
It does solve the problem

```
elastic: Error 404 (Not Found): no such index [type=index_not_found_exception]: [details={"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"redacted","index":"redacted","root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"redacted","index":"redacted"}]}]
```

**Comment by mlodic** [comment]
Thank you, I will keep using this build until the new release.
