### ISSUE TITLE
question: Mongodb document got deleted after it's created for a while 

### ISSUE THREAD

**Issue by lihaiswu** [rwynn/monstache#478]
I created a document in test-staging.Foo, then the document was synced to Elasticsearch successfully. However, this document got deleted after a few minutes. I didn't perform any operations on the collection after that. Just monitor the monstache log, not sure what might delete this document in db:

==== 1. Start monstache ====
INFO 2021/01/13 19:06:52 Started monstache version 6.7.3
INFO 2021/01/13 19:06:52 Go version go1.15.5
INFO 2021/01/13 19:06:52 MongoDB go driver v1.4.4
INFO 2021/01/13 19:06:52 Elasticsearch go driver 7.0.22
INFO 2021/01/13 19:06:53 Successfully connected to MongoDB version 4.2.6
INFO 2021/01/13 19:06:53 Successfully connected to Elasticsearch version 7.10.0
INFO 2021/01/13 19:06:53 Sending systemd READY=1
WARN 2021/01/13 19:06:53 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2021/01/13 19:06:53 Starting http server at :8080
INFO 2021/01/13 19:06:53 Joined cluster monstache-cluster
INFO 2021/01/13 19:06:54 Starting work for cluster monstache-cluster
INFO 2021/01/13 19:06:54 Listening for events
INFO 2021/01/13 19:06:54 Watching changes on collection test-staging.Foo
INFO 2021/01/13 19:06:55 Resuming from timestamp {T:1610593336 I:3}

==== 2. Create document in the collection ====
TRACE 2021/01/13 19:08:13 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (darwin-amd64)
Content-Length: 172
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test-staging.foo","_id":"5fffb59c13b4cab80c157924","version":6917447234283896833,"version_type":"external"}}
{"city":"test_city","name":"test_name"}

TRACE 2021/01/13 19:08:13 HTTP/1.1 200 OK
Content-Length: 275
Content-Type: application/json; charset=UTF-8

{"took":5,"errors":false,"items":[{"index":{"_index":"test-staging.foo","_type":"_doc","_id":"5fffb59c13b4cab80c157924","_version":6917447234283896833,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":44,"_primary_term":1,"status":201}}]}

==== 3. After a few minutes, received unknown record: {"__v":0,"id":396,"name":"foo"} and above document got deleted ====
TRACE 2021/01/13 19:10:48 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (darwin-amd64)
Content-Length: 171
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test-staging.foo","_id":"5fffb63669ec0e0116e334e1","version":6917447895708860417,"version_type":"external"}}
{"__v":0,"id":396,"name":"foo"}

TRACE 2021/01/13 19:10:48 HTTP/1.1 200 OK
Content-Length: 275
Content-Type: application/json; charset=UTF-8

{"took":5,"errors":false,"items":[{"index":{"_index":"test-staging.foo","_type":"_doc","_id":"5fffb63669ec0e0116e334e1","_version":6917447895708860417,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":45,"_primary_term":1,"status":201}}]}
TRACE 2021/01/13 19:10:48 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (darwin-amd64)
Content-Length: 140
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_index":"test-staging.foo","_id":"5fffb59c13b4cab80c157924","version":6917447895708860418,"version_type":"external"}}

TRACE 2021/01/13 19:10:48 HTTP/1.1 200 OK
Content-Length: 276
Content-Type: application/json; charset=UTF-8

{"took":3,"errors":false,"items":[{"delete":{"_index":"test-staging.foo","_type":"_doc","_id":"5fffb59c13b4cab80c157924","_version":6917447895708860418,"result":"deleted","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":46,"_primary_term":1,"status":200}}]}
TRACE 2021/01/13 19:10:48 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/7.0.22 (darwin-amd64)
Content-Length: 140
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"delete":{"_index":"test-staging.foo","_id":"5fffb63669ec0e0116e334e1","version":6917447895708860419,"version_type":"external"}}

TRACE 2021/01/13 19:10:48 HTTP/1.1 200 OK
Content-Length: 276
Content-Type: application/json; charset=UTF-8

{"took":3,"errors":false,"items":[{"delete":{"_index":"test-staging.foo","_type":"_doc","_id":"5fffb63669ec0e0116e334e1","_version":6917447895708860419,"result":"deleted","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":47,"_primary_term":1,"status":200}}]}

=====
=====
Looks like the new index  {"__v":0,"id":396,"name":"foo"} triggered to delete the original document. I have no idea where was ' {"__v":0,"id":396,"name":"foo"} ' from? And how it triggered the delete operation to original document. @rwynn - Could you please help to analyze the log and point me the possible cause? Thanks a lot.

**Comment by lihaiswu** [comment]
Following is the configuration:

mongo-url = "mongodb://test-monstache:xxxxxx@localhost:27017"

elasticsearch-urls = ["http://localhost:9200"]
elasticsearch-max-seconds = 5
elasticsearch-max-conns = 6

change-stream-namespaces = ["test-staging.Foo"]

config-database-name = "monstache-staging"

dropped-collections = true
dropped-databases = true

resume = true
resume-strategy = 0

verbose = true

cluster-name = 'monstache-cluster'

enable-http-server = true

**Comment by rwynn** [comment]
Hi @lihaiswu is it possible there is another client interacting with the database?  The inclusion of field `__v` may indicate that the Mongoose ORM is being used.

**Comment by lihaiswu** [comment]
@rwynn  actually, the collection `foo` is a dummy collection I created for testing. I think there's only one client interacting with this collection. Even there's another client, I wonder why the new document `{"__v":0,"id":396,"name":"foo"}` can cause another document to be deleted.

I see a warning in ES has a warning doesn't support "__v" field names beginning with '__'. Is it possible one bad document which has "__v" field sync to ES and cause to remove all other good documents? I think it's painful if that's the case. It's really weird to me.

**Comment by lihaiswu** [comment]
@rwynn anyway, thanks for your help. I'm going to close it and continue to investigate from my side.

**Comment by rwynn** [comment]
@lihaiswu monstache would not delete a document in response to another being updated.  It only attempts to delete in Elasticsearch for an initiating delete event in MongoDB coming from the change stream.  

If another client has the access to delete documents or drop collections then you may see those events propagate to the index.  Do you see this same behavior in a local environment?

**Comment by lihaiswu** [comment]
> @lihaiswu monstache would not delete a document in response to another being updated. It only attempts to delete in Elasticsearch for an initiating delete event in MongoDB coming from the change stream.
> 
> If another client has the access to delete documents or drop collections then you may see those events propagate to the index. Do you see this same behavior in a local environment?

Really appreciate it @rwynn . I think my team has been using that 'Foo' collection in the system tests, and maybe it's cleanup by the system test. I'll create another collection to try it.
