### ISSUE TITLE
Regex case sensitive

### ISSUE THREAD

**Issue by DanBrk** [rwynn/monstache#479]
Hi,

To have case insensitive regex we usually add '/i' at the end of the expression.
Please give an example how to do it in Monstache config ?

Regards.

**Comment by rwynn** [comment]
hi @DanBrk,

Is this what you mean?

```toml
namespace-regex = '(?i)^tESt\.TesT$'
```
See https://play.golang.org/p/WgpNhwWWuW and more generally the Flags section at https://github.com/google/re2/wiki/Syntax.

**Comment by DanBrk** [comment]
Thanks a lot. That is exactly what I meant.
