### ISSUE TITLE
Different mappings are wrong

### ISSUE THREAD

**Issue by snoopy83101** [rwynn/monstache#48]
{
   no:[1,2,3]
}
or
{
   no:1
}
or
{
   no:{
      no1:1
      no2:2
   }
}

The above situation is often seen in mongodb ！
And it has already existed

Then  some Error in ES 6 , I think it wants to make my data type exactly the same， How do I deal with it?

**Comment by snoopy83101** [comment]
Now I have to land the ES version to 5.x

**Comment by rwynn** [comment]
Perhaps the best solution to that would be to use JavaScript to coerce the no field into a number array type.   So, you would need to detect case #2 or #3 and use code to transform to form #1.  Delete the index and rerun monstache to reindex the data with same type. 

Or if you don’t need to search this field you could simply set up a mapping in ES such that the no field is not indexed.

**Comment by rwynn** [comment]
Example to disable a field if you choose to not transform in JavaScript. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html

**Comment by snoopy83101** [comment]
thx！
If I keep all，The best way should be。。。。。？
no.length>2
no=2
no.no1=1
Suppose all want to query

Is not only using the low version 5.x？

**Comment by snoopy83101** [comment]
I do not quite understand why it（es 6） does not have a better solution, only to delete the index

**Comment by rwynn** [comment]
To my knowledge there's no difference between ES 5 and 6 with regards to this.  When using dynamic mapping the first document indexed determines the field types and subsequent documents must conform to that type.

Once the index is created, you cannot change the type mapping of existing fields in ES 5 or 6, only reindex the into another index or delete the index and recreate.   Are you saying you can successfully index a field with multiple data types in ES 5?

The javascript I was thinking of would be something like

```
module.exports = function(doc) {
    if (doc.no) {
      if (!Array.isArray(doc.no)) {
         // only if ordering of values not important
         doc.no = _.values(doc.no);
      }
    }
    return doc;
}
```

**Comment by snoopy83101** [comment]
I think I should understand. Thank you very much!
