### ISSUE TITLE
Unable to load Multiple External JS scripts - version 6.7.3

### ISSUE THREAD

**Issue by philbannon** [rwynn/monstache#480]
Hi there,

New to monstache and can I say thank you for building such an awesome tool!

I have a mongoDB which has multiple collections. What I'm trying to do and it doesn't seem possible is have multiple external scripts which will pick certain fields from different collections and sync only those fields to ElasticSearch

For example I would like to have two external scripts:

First one: 
`[[script]]
script = """
module.exports = function(doc, ns) {
    // the doc namespace e.g. test.test is passed as the 2nd arg
    return _.pick(doc, "skillName", "skillDescription");
}
"""`

Second one:
`[[script]]
script = """
module.exports = function(doc, ns) {
    // the doc namespace e.g. test.test is passed as the 2nd arg
    return _.pick(doc, "name", "displayName", "city");
}
"""`

And finally in my config.toml:

[[script]]
namespace = "devly.users"
path = "./scripts/devly-users.js"
routing = true

[[script]]
namespace = "devly.skills"
path = "./scripts/devly-skills.js"
routing = true

If I then try to run monstache I get this error:

ERROR 2021/02/03 20:19:09 (anonymous): Line 2:1 Unexpected token ILLEGAL (and 4 more errors)

Sorry If I'm doing something really stupid. 

thanks

**Comment by rwynn** [comment]
Hi @philbannon thanks for trying monstache!  Are the contents of the external files simply the javascript? e.g.

```javascript
module.exports = function(doc, ns) { 
    // the doc namespace e.g. test.test is passed as the 2nd arg
    return _.pick(doc, "skillName", "skillDescription");
}
```
If not then reducing to just that might fix it.

**Comment by philbannon** [comment]
Hi @rwynn thanks for the response, so i eh was doing something VERY stupid, I left the [[script]] tag in the external js files :-/

Thanks for the help btw!!
