### ISSUE TITLE
<<< Monstache full sync is not being Matched Existing MongoConnector sync - Staging release>>>

### ISSUE THREAD

**Issue by pcinnusamy** [rwynn/monstache#495]
@rwynn ,
We have recently migrated from MongoConnector (sync service ) to Monstache and done the fullsync from MongoDB to ES during  testing phase
Existing flow : MongoDB --> MongoCOnnector --> ES --> Kibana  ( BAU)
New flow      : MongoDB --> Monstache --> ES --> Kibana
Problem statement :
When we checked new index that the document count and deleted document count is higher than  BAU index, but store size of the new index  is higher than the BAU index. I got confused whether any indices are out of sync or had a data loss while sync the data .
Since I am new to this tech stack, need to yours expertise to understand the gap why there is a huge difference on doc count . Thanks 

![image](https://user-images.githubusercontent.com/78079694/113035560-ec102d00-91c5-11eb-89ae-9b3eb0f22088.png)

**Comment by rwynn** [comment]
Does the docs count for the monstache index match the docs count in the MongoDB collection?

**Comment by pcinnusamy** [comment]
We couldn't figure it out Since MongoDB collections having nested docs and it's not showing as actual count of the documents. When it comes to Monstache , it's having both documents along with Expunged document. PFA screen.

![Uploading ES_Count_Issue.JPG…]()

**Comment by pcinnusamy** [comment]
![ES_Count_Issue](https://user-images.githubusercontent.com/78079694/113082489-26e98380-920d-11eb-85d8-d3c3f8354ee4.JPG)

**Comment by pcinnusamy** [comment]
@rwynn ,

Sorry to the rush you, Currently we are unable to move forward due to this blocker. Kindly check and share your views on it.

**Comment by rwynn** [comment]
hi @pcinnusamy,

If the doc counts do not match what you are expecting I would suggest looking into the monstache error logs.  It will be reporting an errors in encounters from bulk index requests there.

You might also enable `stats=true` and `index-stats=true` which reports error counts.

**Comment by pcinnusamy** [comment]
Thanks for your expertise advise  @rwynn ,

I can see many
[Index Optimization R&D_test_results.docx](https://github.com/rwynn/monstache/files/6247770/Index.Optimization.R.D_test_results.docx)
 records were in failed state, Please confirm whether below configs needs to be enabled order to capture the error or failure.

verbose = true Verbose = true
[logs]
info = "/path/monstache/logs/info.log"
warn = "/path/monstache/logs/warn.log"
error = "/path/monstache/logs/error.log"
trace = "/path/monstache/logs/trace.log"


Note : I have disabled the verbose to increase the performance since  logs a full trace of every request.

**Comment by pcinnusamy** [comment]
@rwynn ,
When I am checking Monstache.stats.<<date>> file, Many docs were failed.
Also I didn't enable verbose as I have initiated full sync and it will trace the each request. Now I have enabled  verbose=true and logged the error with log file. 

verbose = true Verbose = true
[logs]
info = "/path/monstache/logs/info.log"
warn = "/path/monstache/logs/warn.log"
error = "/path/monstache/logs/error.log"
trace = "/path/monstache/logs/trace.log"

**Comment by pcinnusamy** [comment]
Hi @rwynn ,

I got the below  errors from Monstache, also I can see here these two items related to docs and services are running fine.

Warn log :

1. WARN 2021/04/05 12:06:37 For performance reasons it is recommended to use elasticsearch-max-bytes instead of elasticsearch-max-docs since doc size may vary
>>> Here I want to copy the 11 M data and what is avg value that we can keep ?

2. WARN 2021/04/05 12:06:37 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
>>> What should I do for this issue ?


Error Log : 
1. ERROR 2021/04/05 12:10:17 Bulk response item: {"_index":"staging-ll1-loanapp monstache","_type":"_doc","_id": "59595797e4b0e7a797a302c1","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [info.scores.tuDti1.scoreValue] of type [double] in document with id '59595797e4b0e7a797a302c1'","caused_by":{"reason":"[double] supports only finite values, but got [Infinity]","type":"illegal_argument_exception"}}}

2. ERROR 2021/04/05 12:10:12 json: unsupported value: NaN

3.  json: error calling MarshalJSON for type monstachemap.Time: Time.MarshalJSON: year outside of range [0,9999]

4. ERROR 2021/04/05 13:54:29 json: unsupported value: -Inf

Please suggest what needs to be done on this @rwynn

**Comment by rwynn** [comment]
One easy to implement solution is to set

```toml
prune-invalid-json = true
```

These values are ok in MongoDB but not ok sending to Elasticsearch.

**Comment by pcinnusamy** [comment]
Great @rwynn , I can see all the above errors got cleared now. _/\_

But end of the end of the error log file getting below message, Can you please help me to clear this error.
ERROR 2021/04/06 20:01:39 elastic: bulk processor "monstache" failed but may retry: elastic: uncommitted bulk response items

**Comment by rwynn** [comment]
When monstache gets the following response status codes on bulk line items you will see that message and it will retry them. 
`408, 429, 503, 507`

The most common of those is probably `429` or `TOO_MANY_REQUESTS`.

**Comment by pcinnusamy** [comment]
Noted with many thanks @rwynn .

I can see many docs were captured with below warning message from WARN.logs and those docs are  not synced with ES after added this **prune-invalid-json = true** config. 

WARN 2021/04/06 17:55:57 Dropping key filed1: invalid float64 value: NaN for document _id: 548883d2e4b00482d13bd087

Is there any way to skip this validation and make it sync with ES ? As we have raised all those problematic documents with upstream team and we have to sync time being.

**Comment by pcinnusamy** [comment]
Hi @rwynn 
Upon further execution, we get the below error messages.

1. ERROR 2021/04/07 09:40:38 Bulk response item: {"_index":"staging-monstache","_type":"_doc","_id":"5a9a1b01e4b0f1dcaf85c670","status":400,"error":{"type":"illegal_argument_exception","reason":"Limit of total fields [8000] in index [staging-Monstache] has been exceeded"}}

Samy >>> Actually document not having much fields and with in the range, even though we are getting this error. Also this document has been successfully synced thru Mongoconnector. Not sure why monstache throwing error even it's with in the range.

ES : 
{
  "staging-monstache" : {
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "8000"
          },
          "ignore_malformed" : "true"
        },
        "refresh_interval" : "30s",
        "number_of_shards" : "8",
        
`
 2. ERROR 2021/04/07 07:38:33 Bulk response item: {"_index":"staging-lion1-underwriting-monstache","_type":"_doc","_id":"58707e30e4b08f2477450041","status":400,"error":{"type":"illegal_argument_exception","reason":"mapper [underwritingDataClarity.clearBankBehavior.fisChexAdvisor.amountClosures.threeYearsAgo.amountDbl] cannot be changed from type [long] to [float]"}}

`

@rwynn  Kindly advise what needs to be done on this issue.

**Comment by rwynn** [comment]
Hi @pcinnusamy , monstache just sends the data from MongoDB, giving you the option to transform the documents / filter the fields sent via plugins or scripts.  The configuration of Elasticsearch with regards to the indexing is out of the scope of what Monstache is doing.  You may need to consult the Elasticsearch vendor for help with configuring indexes / index templates for your use case.

**Comment by pcinnusamy** [comment]
Noted with many thanks @rwynn .
