### ISSUE TITLE
Is possible to pass read and write DB host name in Monstache

### ISSUE THREAD

**Issue by pcinnusamy** [rwynn/monstache#499]
Hi @rwynn ,

understand if using python to connect mongodb, we can put multiple mongodb hostnames in the url and usually we will be using read ( replica ) and write ( primary )thru mongodb url. Can i put read and write into one line, then it will smart enough to know which hostname can write, then another one is read only. 
Why we are asking this question is , as we need to specify readPreference primary for write, secondary for read, so we thought it is better to separate everything while passing thru URL and  write will write into Primary node, read will be secondary.

To enabled resume, monstache will write the current timestamp to docdb then our mongourl has to be flexible enough to let monstache know when write use db-1, if read use db-2. Please find the example.

Example of MongoURI :
ex: 

mongodb://<username>:<password>@<master1>:<port>,<replica1>:<port>,<replica2>:<port>/<db>?replicaSet=<replicaSet_name>&readPreference=<readPreference_option>

Example Python format:
"mongodb://{username}:{password}@{master}:{port},{replica1}:{port},{replica2}:{port}/{db}?replicaSet={replicaSet_name}&readPreference={readPreference_option}".format(**MONGO_CREDS)

MONGO_CREDS = {
    'username': mongo_username,
    "password": mongo_password,
    "master": "host_a.com",
    "replica1": "host_b.com",
    "replica2": "host_c.com",
    "db": "admin",
    "replicaSet_name": "rs3mongorep",
    "readPreference_option": "secondaryPreferred",
    "port": 27017
}.

Kindly check and share your suggestion @rwynn

**Comment by rwynn** [comment]
Hi @pcinnusamy  I think possible limitation with DocumentDB is that change streams must be opened against the primary and not a replica.
https://docs.aws.amazon.com/documentdb/latest/developerguide/change_streams.html#change_streams-limitations
So, not sure is it possible to read only from a replica with change streams enabled in monstache.

You probably could have a separate instance of monstache that performs only the direct reads, and that can probably be configured to connect with `readPreference=secondary`.  For this specific instance you would need to also disable change streams with `disable-change-events=true` in the monstache config.

The docs for the connection string are here:
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by pcinnusamy** [comment]
Thanks for your valuable information @rwynn .

If we connect monstache thru separate instance for direct reads, how do we resume service when we enable the change stream from another instance, since the instance which we are creating for direct read will write the  resume name ="default"  under primary documentDB right . Please correct me if am wrong.

**Comment by pcinnusamy** [comment]
Thanks for your valuable information @rwynn .

Since documentdb is not supporting the change streams for replica, how to read the incremental data ? 
Is only possible option is that need to sync the data from  primary  time being ?

**Comment by rwynn** [comment]
Yes, I think limitation in DocumentDB is that you can only do real time (change stream) sync from primary.  You could do periodic batch (called direct read in monstache) on secondary though.

This is just my reading of the documentation.  I have not actually used DocumentDB. Consult with the vendor for confirmation one way or the other.

**Comment by pcinnusamy** [comment]
Thank you for your tremendous  support on our delivery @rwynn. 

Could you please review this JIRA and provide your [suggestion.](https://github.com/rwynn/monstache/issues/497)
As I am  unable to understand the cluster mode concept, please shed more on it to get clear picture. Thanks

**Comment by pcinnusamy** [comment]
I am closing the ticket ,since there is a possible limitation on documentdb and nothing to do with Monstache service.
