### ISSUE TITLE
mongstache synchronization time format problem

### ISSUE THREAD

**Issue by Mankvis** [rwynn/monstache#501]
As in the title, the time format in mongodb is "ISODate("2020-07-24T00:00:00.000Z")". It seems that the data cannot be modified to ISODate("2020-07-24 00:00:00")" after finding the information. Is there a way to specify the format when saving es synchronously?

**Comment by rwynn** [comment]
Hi @Mankvis ,

Monstache currently writes a MongoDB ISODate using the format defined [here](https://github.com/rwynn/monstache/blob/e9c8b730d0f67a51d4c2998d267357f6f726d7ce/monstachemap/encoding.go#L13).  So, e.g. it sends `2021-04-12T22:14:33.613Z` to Elasticsearch.  

Unfortunately, the only way to customize this would be to use a plugin and convert the date to a string programmatically in the format you want.

**Comment by Mankvis** [comment]
> Hi @Mankvis ,
> 
> Monstache currently writes a MongoDB ISODate using the format defined [here](https://github.com/rwynn/monstache/blob/e9c8b730d0f67a51d4c2998d267357f6f726d7ce/monstachemap/encoding.go#L13). So, e.g. it sends `2021-04-12T22:14:33.613Z` to Elasticsearch.
> 
> Unfortunately, the only way to customize this would be to use a plugin and convert the date to a string programmatically in the format you want.

Oh, well, thank you very much.
