### ISSUE TITLE
What does "Failed" in the STATS metric indicate?

### ISSUE THREAD

**Issue by ScubaDrew** [rwynn/monstache#517]
eg:

`STATS 2021/05/25 16:08:43 {"Flushed":1670292,"Committed":9078219,"Indexed":67254957,"Created":0,"Updated":0,"Deleted":0,"Succeeded":58567314,"Failed":8687643,"Workers":[{"Queued":0,"LastDuration":17000000},{"Queued":0,"LastDuration":15000000},{"Queued":0,"LastDuration":12000000},{"Queued":0,"LastDuration":18000000},{"Queued":0,"LastDuration":14000000},{"Queued":0,"LastDuration":34000000}]}`

My "Failed" count goes up a lot. I don't have any error messages that make me think anything is wrong. Sync seems to be working. 

Thanks!

**Comment by rwynn** [comment]
Hi @ScubaDrew `Failed` is incremented for any line items in the response with status not between 200 and 299.

https://github.com/olivere/elastic/blob/b80de84b2610432a3cc16f4a73ccfe31f03c02de/bulk.go#L440

It might be a transient error.  But you may need to check the elasticsearch logs for details.  Monstache does not log some errors such as `409` (version conflict).  That simply means that the document has already been previously processed.  Monstache uses the timestamp of the change event as the version number.

https://github.com/rwynn/monstache/blob/e9c8b730d0f67a51d4c2998d267357f6f726d7ce/monstache.go#L538

**Comment by ScubaDrew** [comment]
Thanks @rwynn ! 

Looks like for status != 409 I should get an error message ?

**Comment by rwynn** [comment]
Yes anything outside of `200-299` and `409` should be getting logged.
