### ISSUE TITLE
how to sync data to kafka?

### ISSUE THREAD

**Issue by josh7** [rwynn/monstache#527]
This project is great! We sycn mongo to es with it. Now we need sycn mongo to other data components! Can monstache support sync data to kafka?

**Comment by rwynn** [comment]
Hi @josh7 , thanks!  Monstache is specifically for MongoDB and Elasticsearch only.  But I do have another project related to Kafka.

https://github.com/rwynn/route81

And I think there are other official [Kafka connectors](https://www.mongodb.com/kafka-connector) provided by MongoDB.  

Hope that helps!
