### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by hpinhal** [rwynn/monstache#528]
Greetings!

Is there a plan to support ARM CPUs?

**Comment by ImNM** [comment]
It works on m1 arm 64 :)

With warn message 
test env
---
docker desktop kubernetes
skaffold
Helm chart elsaticsearch cluster
Mongo db atlas
---
Prod env

Eks

**Comment by ms0510k** [comment]
how can start monstach?
my cpu arm64
only amd64, windows format in download folder

**Comment by ImNM** [comment]
> how can start monstach? my cpu arm64 only amd64, windows format in download folder

@ms0510k 
just excute docker img
it works on arm64

**Comment by suroot-chalt** [comment]
> @ms0510k just excute docker img it works on arm64

I tried docker image on arm64 but get this error:
  exec /bin/monstache: exec format error
Can you share your config?

**Comment by porn** [comment]
You can run monstache on ARM64:
- download & extract source code
- install some `go` (e.g. `golang-go` on Ubuntu distro, just successfully tested on version: 1.18.1)
- go to the directory with extracted source code
- run `go install` -> this creates `~/go/bin/monstache` binary that can be used :heavy_check_mark:
