### ISSUE TITLE
Worker not coming up in HA cluster

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#53]
in toml file i have following : 
cluster-name = "HA"
workers = [ "es1" , "es2" , "es3" ]

I start with 3 workers and it works fine but if i abruptly kill 1 server say es2 and then try to bring es2 up again then i get following in error log: 
ERROR 2018/03/19 18:39:59 not found 

I get following in info log: 
INFO 2018/03/19 18:36:42 Shutting down
 INFO 2018/03/19 18:38:16 Successfully connected to MongoDB version 3.6.3
 INFO 2018/03/19 18:38:16 Successfully connected to Elasticsearch version 6.2.2
 INFO 2018/03/19 18:38:16 Joined cluster HA
 INFO 2018/03/19 18:38:16 Starting work for cluster HA
 INFO 2018/03/19 18:38:16 Entering event loop
 INFO 2018/03/19 18:38:16 Sending systemd READY=1
 INFO 2018/03/19 18:38:16 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
 INFO 2018/03/19 18:38:56 Pausing work for cluster HA

Any pointer you may provide as to why es2 worker is not coming up?

**Comment by rwynn** [comment]
The reason a worker would start paused is if there is already a document in the `monstache.cluster` collection with an _id == $cluster-name.$worker-name.  That just means that presumably another process is already working on behalf of this worker in the cluster.  

If another process is not really working on his behalf, the document in `monstache.cluster` should time out in 30s and be auto-removed from the collection by MongoDB.  At that point the worker that was paused should then be able to insert into that collection and become the active worker.  Then the process should log "Resuming work for cluster HA".

The whole HA thing works by putting ttl indexes on the `monstache.cluster` collection:
https://github.com/rwynn/monstache/blob/master/monstache.go#L772

Each process tries to insert into that collection and backs off "pauses" if it cannot, and "resumes" if it can.

**Comment by rwynn** [comment]
You should see something like this when you set a `cluster-name`.

```
use monstache;
switched to db monstache
> db.cluster.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "monstache.cluster"
        },
        {
                "v" : 2,
                "key" : {
                        "expireAt" : 1
                },
                "name" : "expireAt_1",
                "ns" : "monstache.cluster",
                "background" : true,
                "expireAfterSeconds" : 30
        }
]
db.cluster.find()
{ "_id" : "HA:es1", "host" : "vagrant", "expireAt" : ISODate("2018-03-19T13:46:58.540Z"), "pid" : 2846 }
{ "_id" : "HA:es2", "expireAt" : ISODate("2018-03-19T13:46:57.036Z"), "pid" : 2863, "host" : "vagrant" }
{ "_id" : "HA:es3", "expireAt" : ISODate("2018-03-19T13:46:49.873Z"), "pid" : 2880, "host" : "vagrant" }
```

**Comment by richiarora** [comment]
Ah ok now i understand, so basically my idea of using cluster was that say 3 processes are running and now i need to update config file to add new mapping so i will update mapping and stop 1 process eg. es2 and start it again so that it can work as per updated config and since this process was started just now its created time will be newer than previous 2 processes and this will take precedence.

What i now understand is that i will have to stop all process and restart so that new changes are reflected. Kindoff what i was doing earlier in normal mode.

Also let me know if i could be of assistance to improve logging currently its not too much descriptive atleast in ERROR logs.

**Comment by rwynn** [comment]
When you want to change the `cluster-name` or the array of `workers` then you need to stop all processes and bring them back up again with the new config.  It doesn't work to change these settings on the fly. 

But if you are not changing the settings, just stopping and restarting an existing worker, then that should work.

**Comment by richiarora** [comment]
well my usecase is to add new mapping / collection to be synced to elasticsearch hence that will require restart.
Another case that i observed was that if i start 3 worker processes at same time then all 3 exit at same time though in logs i see pause logs. In cluster collection i see 3 documents for each worked with same expireAt time. 
So i am left with no worker.
If i try to start again a worker thread say es1 it also exits after 30s. I was hoping that atleast it should be running. I do see expireAt time is updated by 10sec. Any idea again what could be wrong here? Else will have to use single process that could meet my requirements

**Comment by rwynn** [comment]
The monstache process should not exit once it has connected to MongoDB and ES under any circumstances unless you have `fail-fast` set to true or you kill it / ctrl-c it.  If it is exiting and not visible under ps then something is wrong.  

Can you explain to me why you would not to restart the process when a new collection is added to MongoDB?  Monstache tails the oplog and sends any updates for any collection that is not explicitly filtered by the user in the config.  By default it syncs everything.  So I don't understand why a restart is needed?

**Comment by rwynn** [comment]
It would also stop if you have exit-after-direct-reads = true. That’s not the default.

**Comment by richiarora** [comment]
hi thanks for prompt reply, yes in my settings i have fail-fast set to true.
I had set same to true as i wanted to know if there was any issue in collection document parsing eg. mapping float to int etc. since mongo is schemaless some documents had a particular field as long and some had same field as float. But elasticsearch needs schema. I guess when we create mapping in elasticsearch it uses first few documents.
I will check with this option set to false and share the output.

Regarding question : Why restart is needed though oplog is being tailed? 
Answer :
My scenario is very specific currently i have collectionA,collectionB,collectionC in my database.
Now i am implementing elasticsearch only for collectionA and in future I might need it to be implemented for collectionB.Since collectionB is already existing and i would like to sync complete data of all existing documents i have in collectionB for same i would do following changes in the config.toml

1. Add mapping for new collection
2. update namespace regex to include new collection
3. update direct-read-namespaces [remove collectionA since it is already synced and we listen to oplog now for further updates, add  collectionB since we want to completely sync all the documents of collectionB
4. stop monstache process and restart same

**Comment by rwynn** [comment]
I don't think you need to set `cluster-name` or `workers` at all in your use case.

Day 1
```toml
namespace-regex = '^mydb\.(c1|\$cmd)$'
direct-read-namespaces = ["mydb.c1"]
resume = true
```
Then you decide you also want to sync mydb.c2.  You would create a new config as below.

Day 2
```toml
namespace-regex = '^mydb\.(c1|c2|\$cmd)$'
direct-read-namespaces = ["mydb.c2"]
resume = true
```
Start the new process and then quit the process started on Day 1.  It doesn't matter if they are both running at the same time for a short period.  

You can also run single shots like

```
monstache -direct-read-namespace mydb.c1 -direct-read-namespace mydb.c2 -exit-after-direct-reads
```
to catch up as needed.

**Comment by richiarora** [comment]
yup thats what i was doing, just wanted to test HA concept if that could provide me no downtime while i update the configuration and add new mapping.

**Comment by rwynn** [comment]
yeah, the `cluster-name` is supposed to give you redundancy, so that if you have a couple of servers you can ensure that as long as one is running you are good.  but `workers` is a different concept.  Workers split the load between multiple processes.  They do this by doing a sort of round-robin where if you have 3 workers, each will push 1/3 of the changes to MongoDB to Elasticsearch. 

The problem with workers is that you cannot currently just add a new worker on the fly.  Because the hashing needs to know all the worker name in order to decide if it needs to process or ignore the current change.  So that feature is limited currently in that you need to stick with the number workers you choose at the beginning unless you stop all processes and restart.  

But the HA concept should be OK if you stick with just supplying `cluster-name` and not `workers`.  You can have as many processes with the same `cluster-name` and only 1 should be actually syncing changes from the oplog at a time.  When 1 is stopped another from the set should pick up.  At least that's how it's supposed to work.

**Comment by richiarora** [comment]
Ok I understand. 1 more thing sometimes i just get error log saying "ERROR 2018/03/19 18:39:59 not found" using only cluster-name now and no workers. How to debug such cases.

**Comment by rwynn** [comment]
I tried setting mgo.SetLog and mgo.SetDebug but that didn’t seem helpful. 

Maybe by tailing the MongoDB log file itself?  I don’t see those not found error so not sure. 

Do you use custom JavaScript?  Find methods in those scripts?

**Comment by richiarora** [comment]
well when i run monstache outside docker it works fine and syncs all 100000 records.
When i run inside docker then it just syncs 20000 entries.

Dockerfile : 
FROM golang:1.8.1
ENV MONGO_URL="mongodb://localhost:27017"
ENV ES_URL="http://localhost:9200"
RUN go get -u github.com/rwynn/monstache
COPY config.toml .
CMD ./bin/monstache -verbose -mongo-url "$MONGO_URL" -elasticsearch-url "$ES_URL" -f config.toml

config.toml is 
stats = true
index-stats = true
elasticsearch-max-conns = 10
dropped-collections = true
dropped-databases = true
namespace-regex = '^(collection1|\$cmd)'
resume = true
resume-write-unsafe = false
cluster-name = "testcluster"
direct-read-namespaces = ["collection1"]
exit-after-direct-reads = false
fail-fast=true
[logs]
info = "info.out"
error = "error.out"
[[mapping]]
namespace = "collection1"
index = "index1"
type = "_doc"

**Comment by richiarora** [comment]
Well i found issue in docker i was using flags -it while running the container. I replaced same with -d and all worked fine.
-it are for interactive shell

**Comment by rwynn** [comment]
Docker images are also provided with the entry point set to be the Monstache executable. You may already be aware of these. 

https://rwynn.github.io/monstache-site/advanced/

**Comment by richiarora** [comment]
Closing the issue now.
