### ISSUE TITLE
Is it possible to use a variable within a toml file?

### ISSUE THREAD

**Issue by lineaheshsh** [rwynn/monstache#532]
hello lewin
I am a junior developer in Korea.

I am currently trying to link mongo and elasticsearch using monstache.

What I'm currently curious about is change-stream-namespaces

Can I use "%{index_nm}_%{+YYYYMMdd}" variable and date form like logstash?

This part is very important to me.

This is because the MongoDB collection will be created daily in the form aaa_20210702.

**Comment by rwynn** [comment]
hi @lineaheshsh 

if you configure as
```toml
change-stream-namespaces = [ "" ]
```
then monstache will watch for changes on all databases and collections, even newly created.

If you configure as 
```toml
change-stream-namespaces = [ "a", "b" ]
```

then monstache will watch all collections in either the `a` or `b` database only.  

does that help?

**Comment by rwynn** [comment]
if you need more control beyond the above you can also configure https://rwynn.github.io/monstache-site/config/#namespace-regex

**Comment by lineaheshsh** [comment]
Thanks for your reply.

But it's not what I wanted.

What I want is the same content as the following issue number.
https://github.com/rwynn/monstache/issues/533

I want to create a specific collection as an index in date format.
