### ISSUE TITLE
How to Create Index name with format date

### ISSUE THREAD

**Issue by meta4sec** [rwynn/monstache#533]
Hello

I want to ask how create index name using format date

Example:
mongodata.YYYY.MM
mongodata.YYYY.MM.dd
mongodata.2021.02
mongodata.2021.02.01

I try index name with format mongodata-%{+YYYY.MM.dd} its not work.

Thanks

**Comment by rwynn** [comment]
Hi @meta4sec,

Currently this isn't possible to do with configuration only.  You would need to use a javascript or go plugin to generate the index name.

Another thing to consider is [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html) which gives you a fixed index alias and Elasticsearch manages the backing indexes (e.g. time based) based on your configuration.

**Comment by meta4sec** [comment]
Ok thanks confirm
