### ISSUE TITLE
not authorized on admin to execute command

### ISSUE THREAD

**Issue by lineaheshsh** [rwynn/monstache#534]
hello lewin

There is an issue during testing, so I'm leaving a new inquiry

Currently the behavior I want is:

1. When monstache is started, all data is read and indexed in elasticsearch.
2. Real-time changes are not accepted.

My settings are below.

mongo-url = "mongodb://{user}:{password}@{ip}:{port}/{database}?authSource=admin"
elasticsearch-urls = [{elastic-url}]
elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000
direct-read-namespaces = ["ticket_replica.ticket_place_20210705", "ticket_replica.ticket_man_20210705", "ticket_replica.ticket_casting_20210705", "ticket_replica.ticket_video_20210705", "ticket_replica.ticket_auto_20210705"]
dropped-collections = false
dropped-databases = false

gzip = true
stats = true
index-stats = true
resume = true
resume-name = "ticket_replica"
resume-strategy = 0
index-as-update = true
verbose = true

[[mapping]]
namespace = "ticket_replica.ticket_place_20210705"
index = "mon_ticket_place_20210705"

[[mapping]]
namespace = "ticket_replica.ticket_man_20210705"
index = "mon_ticket_man_20210705"

[[mapping]]
namespace = "ticket_replica.ticket_casting_20210705"
index = "mon_ticket_casting_20210705"

[[mapping]]
namespace = "ticket_replica.ticket_video_20210705"
index = "mon_ticket_video_20210705"

[[mapping]]
namespace = "ticket_replica.ticket_auto_20210705"
index = "mon_ticket_auto_20210705"

[logs]
info = "./logs/info.log"
trace = "./logs/trace.log"
error = "./logs/error.log"
warn = "./logs/warn.log"

Sensitive information is indicated in the form of {}.
As I expected, it reads the entire data and indexes it in elasticsearch, but the error.log is throwing the below error.

ERROR 2021/07/06 13:43:59 (Unauthorized) not authorized on admin to execute command { serverStatus: 1, lsid: { id: UUID("56fcaa36-23d3-449d-a0e6-0738f76ad067") }, $db: "admin", $readPreference: { mode: "primary" } }

This error is being stamped indefinitely.

This error seems to be trying to access the admin db.

Can't I stop this error?

**Comment by lineaheshsh** [comment]
It has been confirmed that if the namespace-regex and change-stream-namespaces options are specified as follows, the error occurs only once.

namespace-regex = '^ticket_replica\.'
change-stream-namespaces = ["ticket_replica.ticket_place_20210705", "ticket_replica.ticket_man_20210705", "ticket_replica.ticket_casting_20210705", "ticket_replica.ticket_video_20210705", "ticket_replica.ticket_auto_20210705"]
direct-read-namespaces = ["ticket_replica.ticket_place_20210705", "ticket_replica.ticket_man_20210705", "ticket_replica.ticket_casting_20210705", "ticket_replica.ticket_video_20210705", "ticket_replica.ticket_auto_20210705"]

Why does change-stream-namespace access admin db?

**Comment by rwynn** [comment]
Hi @lineaheshsh,

if you need only a full sync and no change streams and no resume, I think you can configure as such and it will not use the `servertStatus` admin command for the purpose of getting the current timestamp to save for future runs:

```tom
disable-change-events = true
direct-read-namespaces = ["x.y", "a.b" ]
resume = false
exit-after-direct-reads = true
```

I think in the future I may introduce a `disable-admin-commands` boolean since this is a common question.

**Comment by lineaheshsh** [comment]
Very satisfied with the results.

I appreciate your effort.
