### ISSUE TITLE
The write index may be explicitly disabled using is_write_index=false

### ISSUE THREAD

**Issue by reterius** [rwynn/monstache#549]
I got this error in monstache error.log file:

elastic: bulk processor "monstache" was unable to perform work: elastic: Error 400 (Bad Request): no write index is defined for alias [content-scan-ui-db]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index [type=illegal_argument_exception]

I have an elastic search index template like that :

`{
  "index_patterns": [
    "content-scan-ui-db-*"
  ],
  "settings": {
    "index": {
      "lifecycle": {
        "name": "content-scan-ui-db-policy",
        "rollover_alias": "content-scan-ui-db"
      },
      "highlight": {
        "max_analyzed_offset": "600000000"
      },
      "refresh_interval": "1800s",
      "number_of_shards": "10",
      "sort": {
        "field": "created_date",
        "order": "desc"
      },
      "analysis": {
        "filter": {
          "autocomplete_filter": {
            "type": "edge_ngram",
            "min_gram": "1",
            "max_gram": "20"
          }
        },
        "analyzer": {
          "autocomplete": {
            "filter": [
              "lowercase",
              "autocomplete_filter"
            ],
            "type": "custom",
            "tokenizer": "standard"
          }
        }
      },
      "number_of_replicas": "1"
    }
  },
  "aliases": {
    "content-scan-ui-db": {}
  },
  "mappings": {
    "properties": {
      "register_detection_report_register_state": {
        "type": "keyword"
      },
      "parent_ids": {
        "type": "keyword"
      },
      "type": {
        "type": "keyword"
      },
      "scraping_progress_status": {
        "type": "keyword"
      },
      "scraping_period": {
        "type": "keyword"
      },
      "bookmarks": {
        "type": "keyword"
      },
      "html_content": {
        "type": "text"
      },
      "search_crawling_last_request_start_date_time": {
        "type": "date"
      },
      "scraping_last_request_status_code": {
        "type": "keyword"
      },
      "auth_detection_report_auth_state": {
        "type": "keyword"
      },
      "template_is_template": {
        "type": "boolean"
      },
      "sorting_id": {
        "type": "keyword"
      },
      "keyword": {
        "type": "keyword"
      },
      "scraping_type": {
        "type": "keyword"
      },
      "search_cms_info_cms_id": {
        "type": "keyword"
      },
      "address": {
        "type": "text"
      },
      "crawling_period": {
        "type": "keyword"
      },
      "company_id": {
        "type": "keyword"
      },
      "scraping_scraped": {
        "type": "keyword"
      },
      "crawling_status": {
        "type": "keyword"
      },
      "crawling_progress_status": {
        "type": "keyword"
      },
      "template_address_id": {
        "type": "keyword"
      },
      "scraping_status": {
        "type": "keyword"
      },
      "search_scraping_last_request_start_date_time": {
        "type": "date"
      },
      "crawling_type": {
        "type": "keyword"
      },
      "user_id": {
        "type": "keyword"
      },
      "crawling_last_request_status_code": {
        "type": "keyword"
      },
      "crawling_crawled": {
        "type": "keyword"
      },
      "view_user_ids": {
        "type": "keyword"
      },
      "created_date": {
        "type": "date"
      }
    }
  }
}`

And i have a script file for monstache:
`module.exports = function(doc, ns) {
    console.log("BASLADI")

    var datetime_start = new Date();
    console.log(datetime_start);

    console.log(doc._id)

    var index_seperate_name = doc.company_id
    var index_name = "content-scan-ui-db-" + index_seperate_name ;

    console.log("index name: ", index_name) ;

    doc._meta_monstache = { index: index_name, type: "_doc", routing: doc._id };

    var row = {}

    row['search_cms_info_cms_id'] = null ;
    row['search_crawling_last_request_start_date_time'] = null ;
    row['search_scraping_last_request_start_date_time'] = null ;

    row['template_address_id'] = null ;
    row['template_is_template'] = null ;

    if("scraping" in doc){

        if("scraped" in doc.scraping){

            doc['scraping_scraped'] = doc.scraping.scraped

        }

        if("status" in doc.scraping){

            doc['scraping_status'] = doc.scraping.status

        }

        if("type" in doc.scraping){

            doc['scraping_type'] = doc.scraping.type

        }

        if("period" in doc.scraping){

            doc['scraping_period'] = doc.scraping.period

        }

        if("progress_status" in doc.scraping){
            doc['scraping_progress_status'] = doc.scraping.progress_status

            if(doc.scraping.progress_status != "not_scraped"){
                doc['scraping_scraped'] = "success"
            }

        }

        if("last_request" in doc.scraping){

            if("status_code" in doc.scraping.last_request){
                doc['scraping_last_request_status_code'] = doc.scraping.last_request.status_code

            }

            if("start_date_time" in doc.scraping.last_request){
                row['search_scraping_last_request_start_date_time'] = doc.scraping.last_request.start_date_time;
            }

        }

    }

    if("crawling" in doc){

        if("crawled" in doc.crawling){
            doc['crawling_crawled'] = doc.crawling.crawled
        }

        if("type" in doc.crawling){

            doc['crawling_type'] = doc.crawling.type

        }

        if("status" in doc.crawling){
            doc['crawling_status'] = doc.crawling.status
        }

        if("period" in doc.crawling){
            doc['crawling_period'] = doc.crawling.period

        }

        if("progress_status" in doc.crawling){
            doc['crawling_progress_status'] = doc.crawling.progress_status
        }

        if("last_request" in doc.crawling){

            if("status_code" in doc.crawling.last_request){
                doc['crawling_last_request_status_code'] = doc.crawling.last_request.status_code
            }

            if("start_date_time" in doc.crawling.last_request){
                row['search_crawling_last_request_start_date_time'] = doc.crawling.last_request.start_date_time;

            }

        }

    }

    if("cms_info" in doc){
        if("cms_id" in doc.cms_info){
            doc['search_cms_info_cms_id'] = doc.cms_info.cms_id

        }
        delete doc.cms_info;
    }

    if("auth_detection_report" in doc){
        if("auth_state" in doc.auth_detection_report){
            doc['auth_detection_report_auth_state'] = doc.auth_detection_report.auth_state
        }

        delete doc.auth_detection_report;
    }

    if("register_detection_report" in doc){
        if("register_state" in doc.register_detection_report){
            doc['register_detection_report_register_state'] = doc.register_detection_report.register_state
        }

        delete doc.register_detection_report;
    }

    if("template" in doc){
        if("address_id" in doc.template){

            row['template_address_id'] = doc.template.address_id

        }

        if("is_template" in doc.template){

            row['template_is_template'] = doc.template.is_template

        }

        delete doc.template;

    }

    doc['search_cms_info_cms_id'] = row['search_cms_info_cms_id'] ;
    doc['search_crawling_last_request_start_date_time'] = row['search_crawling_last_request_start_date_time'] ;
    doc['search_scraping_last_request_start_date_time'] = row['search_scraping_last_request_start_date_time'] ;

    doc['template_address_id'] = row['template_address_id'] ;
    doc['template_is_template'] = row['template_is_template'] ;

    doc['sorting_id'] = doc._id

    if("crawl_meta_data" in doc){
        delete doc.crawl_meta_data;
    }

    if("crawling" in doc){
        delete doc.crawling;
    }

    if("scraping" in doc){
        delete doc.scraping;
    }

    if("create_type" in doc){
        delete doc.create_type;
    }

    if("title" in doc){
        delete doc.title;
    }

    if("transfer_to_child" in doc){
        delete doc.transfer_to_child;
    }

    if("user_id" in doc){
        delete doc.user_id;
    }

    if("description" in doc){
        delete doc.description;
    }

    if("hashed_value" in doc){
        delete doc.hashed_value;
    }

    if("max_fail_req_count" in doc){
        delete doc.max_fail_req_count;
    }

    if("priority" in doc){
        delete doc.priority;
    }

    if("waiting_time" in doc){
        delete doc.waiting_time;
    }

    if ("html_text" in doc){

        doc['html_content'] =  doc['html_text']

    }else if("html_content" in doc){

        if(doc['html_content'] != null){

            doc['html_content'] = doc['html_content'].replace(/<script[^>]*>.*?<\/script>/gi, '');
            doc['html_content'] = doc['html_content'].replace(/<\/?[^>]+(>|$)/g, '');
            doc['html_content'] = doc['html_content'].replace(/  +/g, ' ');

        }

    }

    if("html_text" in doc){
        delete doc.html_text;
    }

    console.log("BITTI")

    var datetime_finish = new Date();
    console.log(datetime_finish);

    return doc ;
}`

and my config file like that:
`mongo-url ="mongodb://****:**************@****************:27017"
config-database-name = "monstache_ui_db"
elasticsearch-urls =["http://**********-**********-sharded:9200"]
elasticsearch-user = ""
elasticsearch-password = ""
elasticsearch-max-conns = 10
replay = false
resume = true
resume-name = "default"
direct-read-namespaces = ["content-scan.addresses"]
index-as-update = false
verbose = true
change-stream-namespaces = ["content-scan.addresses"]
exit-after-direct-reads = false
gzip = false

[logs]
info = "/var/logs/monstache/info.log"
warn = "/var/logs/monstache/warn.log"
error = "/var/logs/monstache/error.log"
trace = "/var/logs/monstache/trace.log"

[[mapping]]
namespace = "content-scan.addresses"
index = "content-scan-ui-db"

[[script]]
namespace = "content-scan.addresses"
path = "script2.js"`

And this is my index lifecycle policies:
`{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "365d",
            "max_size": "9000gb"
          },
          "set_priority": {
            "priority": 100
          }
        }
      }
    }
  }
}`

I dont know how can i solve this problem, please help me.

**Comment by reterius** [comment]
Please help me

**Comment by rwynn** [comment]
@reterius
you should be able to get more information about your index alias `content-scan-ui-db` using https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-alias.html.

monstache must be configured to send data to an index alias that points to only a single write enabled index.  For reading outside of monstache the index alias may point to multiple indices.  But that is not allowed when writing.

**Comment by reterius** [comment]
Hi @rwynn, thanks for your answer.

I got some detail of my alias via following endpoint: http://localhost:9200/_alias/content-scan-ui-db

Response:

{
    "content-scan-ui-db-6110ef56f31be100c47494dd": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-60d2fe8a1cbd4b00bf75d5f0": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-6091bcdc3ed68cbfad875bdb": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-60b0cc7a8c89cd00bcf3e22b": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-60b0ccda8c89cd00bcf3e39b": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-6110ee4bf31be100c47492cb": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-60b9fbb1e611ec00bc4f9566": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-60b0cc248c89cd00bcf3e0c7": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    },
    "content-scan-ui-db-61082b961f9c8900c408d128": {
        "aliases": {
            "content-scan-ui-db": {}
        }
    }
}

We have so many company so that we creating dynamicly all index when monstache insert collection from mongodb to elasticsearch in script. Forexample content-scan-ui-db-6110ef56f31be100c47494dd "6110ef56f31be100c47494dd" that id is company id. We have separated all indexes for each company as dynamicly.

**Comment by rwynn** [comment]
I think you may need to create another index alias that only point to 1 real index at a time.  The index the alias points to can change over time but it must only point to 1 index in order for MongoDB to be able to write to it.  Does that make sense?  Configure monstache to write to this new alias that only points to one index at a time.

**Comment by reterius** [comment]
I solved this isue while remove the alias from index template. No need alias for this case on our structure.
