### ISSUE TITLE
Debugging and log verbosity

### ISSUE THREAD

**Issue by abbudao** [rwynn/monstache#554]
Hey @rwynn, first, I would like to thank you for this great project; it's really incredible.
I want to comment about an issue I've encountered when syncing a huge collection (90M). Monstache was not syncing all items to it; sometimes it stopped at 10%, sometimes it halted at the half, and we took a while to figure out why because, in the default log verbosity, nothing seemed wrong.

As you might imagine, when syncing a big collection all kind of spurious data appears. In our case, after turning on verbose mode, we've found a small number of documents that had an id a little longer than what elastic search allows (512 bytes). That was halting the whole sync, and it was logged at trace level.

Can something be done to log this not only at verbose but also on default verbosity? Or maybe we can ignore invalid items and report that they couldn't be sync? 

A sample of the error log:
``` 
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] is too long, must be no longer than 512 bytes but was: 519;2: id [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] is too long, must be no longer than 512 bytes but was: 524;3: id [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] is too long, must be no longer than 512 bytes but was: 518;4: 
```
After removing the document with these ids, Monstache worked just fine, so I'm reporting this more as a way of contributing.

**Comment by rwynn** [comment]
Thanks @abbudao this is something that monstache should handle.  It seems like that limit on _d has been in for a while. I will look into a fix for this.

**Comment by patrickserrano** [comment]
@rwynn on the topic of logging verbosity, is there any chance we could get something that's more detailed than the default logging but didn't include full traces like we get with `verbose = true`? It'd be extremely useful :)

**Comment by rwynn** [comment]
My intention was to log any error returned by Elasticsearch without needed to turn verbose on.

I thought that was being done at https://github.com/rwynn/monstache/blob/439b2e5d340adb0aa4191e3029ef05bd40c53a51/monstache.go#L532.

I will need to look into how this error is escaping that logging.  

@patrickserrano is there something specific that you're interested in seeing logged?

**Comment by abbudao** [comment]
@rwynn I appreciate you taking your time to solve this issue. Thank you.
May I ask for a release containing it?  I'm interested in this fix and the Mongo/Elastic drivers bump that you committed.

**Comment by rwynn** [comment]
@abbudao sorry for the wait on the fix for this one.  I have no been able to dedicate enough time lately.
