### ISSUE TITLE
Two monstache instances reading from a single Mongo document

### ISSUE THREAD

**Issue by philbannon** [rwynn/monstache#564]
Hey Ryan,

Hope you're keeping well mate. Sorry if this has been asked before (I searched but didn't find anything).

So here's my scenario:
I currently have a single monstache instance watching my Users collection. When there is an insert etc, I pick certain fields and send them to ES. Now I'm only sending certain fields as its a publicly facing ES instance and I don't want / need to expose all the data in the collection.

Now, let's say I wanted to have a separate ES Index (privately accessible), in a separate ES instance which takes all the data from the User Collection.

Is it possible to have another monstache instance running, which watches the same collection and pumps all that data to the other ES instance? 

Thanks for the help!!
Phil

**Comment by rwynn** [comment]
Hey Phil,
Yes, I think it is possible.  If you set different values for [config-database-name](https://rwynn.github.io/monstache-site/config/#config-database-name) then monstache will store the change stream state separately.

**Comment by philbannon** [comment]
Excellent! Thanks for the fast response @rwynn I'll give it ago.

I was thinking that once a change stream was consumed by one Monstache they event would be "gone" and not picked up by the second monstache! 

Can't thank you enough @rwynn

**Comment by philbannon** [comment]
@rwynn that worked perfectly thanks mate. Out of curiosity, what is the use case for setting multiple ES URL's in the config property elasticsearch-urls

**Comment by rwynn** [comment]
@philbannon I'm not exactly sure, but I the client monstache uses https://github.com/olivere/elastic accepts multiple [node](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html) URLs within the same Elasticsearch cluster.  It might be a good question to ask over there.  My guess would be that even when a node is down in the cluster the cluster may still be able to take traffic to the remaining healthy nodes.

**Comment by philbannon** [comment]
Thanks @rwynn ah yeah ok your right that's correct based off the standard ES configs. 

I thought perhaps it was something specific to Monstache! 

Thanks for the info mate, have a great week🤘
