### ISSUE TITLE
elastic: <url> is dead when trying to copy to aws

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#57]
Hi 

I am now trying to copy collection to amazon based ES.
However seldom i see following in the error logs: 
ERROR 2018/03/29 11:03:21 elastic: < url of elasticsearch > is dead.

Though I am able to access the elasticsearch from browser and records are also copied but not all.

Because of this error some records are not pushed.
However when i try to copy collection to local docker container running elasticsearch it works fine.

My configuration : 
elasticsearch-max-conns = 10
elasticsearch-client-timeout = 120 
resume-write-unsafe = false
cluster-name = "test-cluster"
direct-read-namespaces = ["mydb.mycollection"]
exit-after-direct-reads = true
fail-fast = true
elasticsearch-max-docs = 500 
elasticsearch-retry = true
[logs]
info = "info.out"
error = "error.out"
[[mapping]]
namespace = "mydb.mycollection"
index = "index-mydb.mycollection"
type = "_doc"

**Comment by rwynn** [comment]
Any reason why you are using fail-fast?  That will bail before attempting reconnects.

**Comment by richiarora** [comment]
hi thanks for quick reply.

Say i am pushing one document where status type is int and another document where status type is float so i wanted to stop pushing further documents. First I will rectify and then start pushing again.

So to summarize I wanted to use fail fast in case there is some ambiguity in field types in docs

**Comment by rwynn** [comment]
There error message you mentioned would be emitted during a health check if the Elasticsearch server failed to respond to a HEAD request. This could be caused by the server being down or just overloaded.

I would run the sync again and monitor ES.

**Comment by richiarora** [comment]
ah ok, also one more observation was that i was getting monitoring-es index locally but not on aws hosted elasticsearch so it could be how elasticsearch is configured on aws

**Comment by rwynn** [comment]
Did you happen to figure out what was going on?

**Comment by richiarora** [comment]
hi @rwynn sorry for delayed reply so our team has updated aws node recently I still need to test bulk load.

**Comment by rwynn** [comment]
Here is a link to the code that is producing the message your mentioned.

https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L1001

You will notice that it does a HEAD request to the base URLs your configure in `elasticsearch-urls` in monstache.  This seems to default to timeout after 1 second. 

I do think the elastic client will recover when the health check fails.  It just marks a connection as dead until it can respond to a HEAD request within 1 second.

**Comment by richiarora** [comment]
closing it for now as never observed recently
