### ISSUE TITLE
Trying to override _id

### ISSUE THREAD

**Issue by enterpinamullah** [rwynn/monstache#574]
```
[[script]]
script = """
module.exports = function(doc, ns, changeDesc) {
    var col = ns.split('.')[1],
        myId = col + '_' + doc['_id'];
    doc._meta_monstache = { id: myId };
    return doc;
}
"""
```
upon running this code on monstache from rel6 branch, I am getting this result
_id: col\_[object Object] instead of a string

**Comment by rwynn** [comment]
What is the [type](https://docs.mongodb.com/manual/reference/bson-types/) of the `_id` value in this mongodb document?  

Is it `ObjectId` or something else?

**Comment by enterpinamullah** [comment]
Yes it is ObjectId.

**Comment by enterpinamullah** [comment]
If i pass _id to a new field in the doc as is, than the objectId would
display correctly but if I concat a string with it, it shows [object
Object] for _id

**Comment by enterpinamullah** [comment]
> What is the [type](https://docs.mongodb.com/manual/reference/bson-types/) of the `_id` value in this mongodb document?  
> 
> Is it `ObjectId` or something else?

_id is UUID in mongodb but in monstache I checked with typeof and it shows as object for doc['_id']

**Comment by enterpinamullah** [comment]
In monstache.go how do I add UUID case?

```func opIDToString(op *gtm.Op) string {
	var opIDStr string
	switch id := op.Id.(type) {
	case primitive.ObjectID:
		opIDStr = id.Hex()
	case primitive.Binary:
		opIDStr = monstachemap.EncodeBinData(monstachemap.Binary{id})
	case float64:
		intID := int(id)
		if id == float64(intID) {
			opIDStr = fmt.Sprintf("%v", intID)
		} else {
			opIDStr = fmt.Sprintf("%v", op.Id)
		}
	case uuid.UUID:
		opIDStr = id.String()
	case float32:
		intID := int(id)
		if id == float32(intID) {
			opIDStr = fmt.Sprintf("%v", intID)
		} else {
			opIDStr = fmt.Sprintf("%v", op.Id)
		}
	default:
		opIDStr = fmt.Sprintf("%v", op.Id)
	}
	return opIDStr
}
```

**Comment by enterpinamullah** [comment]
Ryan, if you could add support for _id type UUID that would be great!

**Comment by rwynn** [comment]
@enterpinamullah I think a UUID is mapped to the bson binary type (subtype \x03 or \x04).

So I believe the object you are seeing in javascript is the respresentation of this go struct:
https://github.com/mongodb/mongo-go-driver/blob/ad5fd8acf73ba41776144e742b8283d04115e71b/bson/primitive/primitive.go#L19

You might try to see if you can access properties `Subtype` and `Data` and see if you can use them in some way to achieve your objective.  

Haven't tried this but maybe ...

```toml
[[script]]
script = """
module.exports = function(doc, ns, changeDesc) {
   console.log(typeof(doc['_id']['Data']));
    
   var myId = col + '_' + doc['_id']['Data'].join('');
   ....
    
}
```
"""

**Comment by enterpinamullah** [comment]
I will try this today and yes I can access those properties and the data property do have the data but its not in hex or uuid format also the subtype is \x04

**Comment by enterpinamullah** [comment]
I tried the code 
```
doc['_id']['Data'].join('');
```
and I get this -> observation_panels-14430149123177114781111342752642242176137
what I want is in uuid format like so: a81bf292-e275-43ce-893e-681840227b6c

**Comment by rwynn** [comment]
I think the best way to handle this is to provide some new functions to the javascript runtime:

* stringFromBinData
* binDataFromString
* stringFromObjectId
* objectIdFromString

Monstache already has the go code to handle UUID ( I had forgotten about it )
https://github.com/rwynn/monstache/blob/d1f65da734ce358b678091161f80fa987ef31c23/monstachemap/encoding.go#L61

So if you just use Monstache without any conversion step it does the expected thing with UUID.

Just need to provide access to that functionality from the javascript runtime.

**Comment by rwynn** [comment]
If you would be interested in submitting a PR ( I do not have a lot of time right now ) you basically have to insert some code here to attach a go function to the vm:

https://github.com/rwynn/monstache/blob/rel6/monstache.go#L1847

https://github.com/robertkrimen/otto

**Comment by rwynn** [comment]
I don't think actually `binDataFromString` is needed (it would be difficult to account for all the cases).  Maybe just `uuidFromString`.

**Comment by enterpinamullah** [comment]
SIR, let me know about the changes that are required to be done to
monstache so that it would allow me to concat a str with uuid. I will do
that tomorrow.

**Comment by rwynn** [comment]
Here's an example

```golang
func jsStringFromBinData(call otto.FunctionCall) otto.Value {
	exported, err := call.Argument(0).Export()
	if err != nil {
		errorLog.Printf("error exporting argument in stringFromBinData: %s", err)
		return otto.NullValue()
	}
	binData, ok := exported.(primitive.Binary)
	if !ok {
		errorLog.Printf("error converting argument to stringFromBinData to primitive.Binary: %s", err)
		return otto.NullValue()
	}
	s, _ := otto.ToValue(monstachemap.EncodeBinData(monstachemap.Binary{binData}))
	return s
}

env.VM.Set("stringFromBinData", jsStringFromBinData)

```

Might need to be added in a couple places.

**Comment by enterpinamullah** [comment]
Thanks, I'll check it out and let you know tomorrow🤗

**Comment by enterpinamullah** [comment]
Fixed it, do you want me to submit a pull request?
