### ISSUE TITLE
direct-read-dynamic-include-regex doesn't work

### ISSUE THREAD

**Issue by jamessecward** [rwynn/monstache#577]
I saw this new feature and trying to put it on my development environment

the use case is sometimes I need to re-sync from mongodb to elasticsearch due to changing mapping

the full config is below
```
mongo-url = "mongodb://mongodb:27017"

elasticsearch-urls = ["http://elasticsearch:9200"]

elasticsearch-healthcheck-timeout-startup = 300

elasticsearch-healthcheck-timeout = 300

elasticsearch-max-conns = 10

elasticsearch-max-seconds = 1

elasticsearch-max-docs = 1

direct-read-dynamic-include-regex = '^log\.(admin|client))(.+)$'

namespace-regex = '^log\.(admin|client)(.+)$'

enable-http-server = true
```

but it work if I use direct-read-namespaces

```
direct-read-namespaces = ['log.admins']
```

**Comment by rwynn** [comment]
Hi @jamessecward 

you need to set this to trigger / enable dynamic direct reads
```toml
direct-read-namespaces = [ "" ]
```

**Comment by jamessecward** [comment]
thx, it works
should add this to document

**Comment by rwynn** [comment]
I think I put it in first `note` here
https://rwynn.github.io/monstache-site/config/#direct-read-namespaces

but maybe not really that clear or discoverable.
