### ISSUE TITLE
failed: json: unsupported value: +Inf

### ISSUE THREAD

**Issue by a-magdy** [rwynn/monstache#59]
Hi @rwynn,

__Problem__: Monstache keeps logging this error forever and stops the whole execution of documents (in other words crashes):

<img width="835" alt="skaermbillede 2018-04-23 kl 13 29 48" src="https://user-images.githubusercontent.com/14139855/39125929-ff4680e4-4700-11e8-91f0-d7d81b68108b.png">

__Cause__: I have a `Double` field with the value `Infinity` -special value not a string-  in my MongoDB database

__Quick Solution__: update this value to `0` instead of `Infinity`

__But__: what if this happened again, I think it would be better if the tool would be able to bypass such cases and continue the execution

__More Info__:

- I've used `mongo-connector` for quite some time, and when it was time to upgrade to `ES6`, I noticed that mongo-connector hasn't been maintained for a while, and I could get it to work, but I wanted to use the best tool as long as I was refactoring stuff.

- Tried `appbaseio/abc` `compose/transporter` and your tool, and after some trials and comparisons I settled on `monstache` as the best tool to use.

- While testing them, I got the same error in all 3 tools, which I was _not_ getting in `mongo-connector`, I noticed that all 3 are written in `go`, and they probably all use the `go` `json` parser, which has [an issue](https://github.com/golang/go/issues/3480) with this error and it is marked as both `FrozenDueToAge` & `Unfortunate`, so I guess it won't be fixed

- I don't mind that there is a certain requirement in the library that doesn't allow certain values, but blocking the whole document from being sent to `Elasticsearch`, and completely block monstache from processing other documents, while logging the same error endlessly doesn't look like the best approach.

- `mongo-connector` on the other hand, only rejects the field with the `Infinity` value, sends the rest of the document, and continues with the execution, the log for the same problem I get from `mongo-connector` (only 1 line):

<img width="941" alt="skaermbillede 2018-04-23 kl 14 41 23" src="https://user-images.githubusercontent.com/14139855/39127144-730aee7c-4704-11e8-8ee6-ad05a103af32.png">

- In my config I've got `"continueOnError": true` in `mongo-connector` config & `fail-fast = false` in `monstache` config -not sure if this info helps, but I thought it might be relevant-.

__Another Trial__: I tried to fix the problem by updating `Elasticsearch` schema for the doc that has this problem:
- I updated this field's mapping property [`ignore-malformed`](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/ignore-malformed.html) to `true`

- And the whole doc setting: `"index.mapping.ignore_malformed": true` as an [index-level default](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/ignore-malformed.html#ignore-malformed-setting) but still didn't work (I thought that maybe `monstache` is logging an error from `Elasticsearch`, but apparently this error in thrown before it reaches `Elasticsearch`

__Proposal__: I think a good solution is to wrap the code that encodes/handles json sent from mongodb, and allow a configurable action of either:
- [default] `drop only the corrupted field` 
- `drop only the current doc`
- `stopping the whole execution and maybe exiting with failure -to signal corrupted data-`
Also maybe logging which document exactly has a problem in it, as it took me a whole to figure out the actual problem

Thanks :)

**Comment by rwynn** [comment]
@a-magdy thanks for reporting this.  

The reason you're seeing it over and over again is that monstache defaults to a 1s auto flush.  You can change that, but it wouldn't fix the issue because the go elastic client does not reset bulk actions until a request completes.

https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L268

So when you get a case that a line item will not even be serialized to make that request, then you can never get out of this loop.  If it was able to at least form the request it would flush the pending actions in the line referenced above.  

I also don't believe there is any API in the go elastic client to reset (method is private) the queue without sending it to Elasticsearch. I could detect this situation but not really do much about it besides completely stopping the bulk processor and re-creating the processor.  It would be nice to have an api to reset it for these scenarios.

It would not be too difficult to add code to Monstache to alter the document before sending to the elastic go client.  Not really sure though which level is best to solve this at though.  That may be a little heavy since every document would need to pass though this function.

**Comment by rwynn** [comment]
I think one fix might be as simple as calling reset before returning when the body of the request cannot be formed since that request will never be fixed:

https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L202

**Comment by a-magdy** [comment]
@rwynn Thanks for the quick and thorough reply as always :)

Oh, I don't fully understand what happens in the flush to elasticsearch, and why resetting will fix the problem -as in, won't the client library try to parse the same document and send it again-

I think I have to do a little bit of digging into the library :) if I get it I'll create a PR, otherwise, I'll open an issue in the repo and ask for help there, thanks for pin pointing the line that needs to be updated :) that saves a lot of time :) 

And about the performance overhead, I agree with you that validating every document will be a performance overhead, I think it could be a pluggable thing if one wants to (to solve a problem like this) but having it there by default is not the best option definitely

Thanks again for your help, things are more clear now :)

**Comment by a-magdy** [comment]
@rwynn Dude, seriously I am astonished by the level of support you give to this library, someone should give you a medal 🏅 

I tested the the latest version `4.5.0` and I am already using the new config: `prune-invalid-json` 🎉 

I think it might be useful in the future, if something was logged in these 2 lines: https://github.com/rwynn/monstache/commit/8eba13c4ba41c8d816b57b4688eee2d074f89243#diff-5cbfca03ad4227882d2c7ad42f281f54R537 & https://github.com/rwynn/monstache/commit/8eba13c4ba41c8d816b57b4688eee2d074f89243#diff-5cbfca03ad4227882d2c7ad42f281f54R540, either as a warning or an error, maybe with the index/_id of the doc, or the path of this field, it will help debug problems with the data itself

Thank you so much :)

**Comment by rwynn** [comment]
@a-magdy thanks, I'll add a note to self to add something to the logs about this.  Just pushed yet another release.  Sorry for all the churn but I think I'm finally pretty happy with the performance on very large collections. Let me know if you see any issues in this regard.

**Comment by a-magdy** [comment]
@rwynn Thank you :) really appreciate your effort :)
