### ISSUE TITLE
Indexer stats says failed: 1098 but no errors in the logs

### ISSUE THREAD

**Issue by lakshmikanthadn** [rwynn/monstache#595]
The indexer statistics printed in the standard out says there are some failures. But there are NO errors in the log.
How do I know which doc failed and why?.

Here is one such stat.
```
STATS 2022/01/05 16:51:57 {"Flushed":5761,"Committed":13104,"Indexed":6299518,"Created":0,"Updated":0,"Deleted":0,"Succeeded":6298420,"Failed":1098,"Workers":[{"Queued":0,"LastDuration":9000000},{"Queued":0,"LastDuration":41000000},{"Queued":0,"LastDuration":7000000},{"Queued":0,"LastDuration":7000000}]}
```

If there are some docs to understand these statistics that would be helpful.

Additional info.
- Running monstache with 3 workers all of them are printing failures.
- Also I see the document count in elastic search and Mongo DB is the same after the direct read is completed. (Maybe only the updates got failed?)
- failed count is increasing day by day.

**Comment by lakshmikanthadn** [comment]
@rwynn Could you please me help understand why there are failures?

**Comment by rwynn** [comment]
Are you running direct reads every day?  The failed count could be because the documents already exist in MongoDB.  There is a boolean configuration called `direct-read-stateful`.  If enabled it would only run the direct reads (full sync) once.
