### ISSUE TITLE
using monstache to import mongodb data into elasticsearch error

### ISSUE THREAD

**Issue by xiaoli-yang** [rwynn/monstache#607]
Hello, I'm using monstache to import mongodb data into elasticsearch. I have encountered two problems and don't know how to solve them. I hope I can get support

1. The document data in mongodb is a date in string format. There was a format problem when importing es

error.log
```
ERROR 2022/03/25 19:45:56 Bulk response item: {"_index":"company.comp20220209","_type":"_doc","_id":"ab5f415f8a78f76f36a78080782f3ee2","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [CheckDate] of type [long] in document with id 'ab5f415f8a78f76f36a78080782f3ee2'. Preview of field's value: '2021-03-16'","caused_by":{"reason":"For input string: \"2021-03-16\"","type":"illegal_argument_exception"}}}
```

I used script, but it didn't seem to work

config.toml
```
[[mapping]]
namespace = "company"
index = "company"
type = "_doc"

[[script]]
namespace = "company"
script = """
module.exports = function(doc) {
    var times = (new Date(doc.CheckDate)).getTime()/1000;
    doc.CheckDate = times;
    return doc;
}
"""
```

2. The data of one of the fields is relatively long, which exceeds the limit of ES. I don't know if the setting is solved.

error.log
```
ERROR 2022/03/25 19:45:56 Bulk response item: {"_index":"company.comp20220209","_type":"_doc","_id":"db016918348ea7a462b59146da1ca68e","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"reason":"Limit of total fields [1000] has been exceeded while adding new fields [908]","type":"illegal_argument_exception"}}}
```

**Comment by rwynn** [comment]
For 1 see the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) to establish `CheckDate` (or any other date fields in your data) as a date field in the index.  

For 2 see the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/flattened.html) to reduce the to reduce the number of fields Elasticsearch indexes for.

**Comment by xiaoli-yang** [comment]
Try these technologies for the first time. Thank you for your answer.

I also want to ask, can I define the field level index type before monstache synchronization? Or do you need to define the index model in elastic search before synchronization?

> For 1 see the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) to establish `CheckDate` (or any other date fields in your data) as a date field in the index.
>

**Comment by rwynn** [comment]
I think the order of steps would be
1. Create an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) specifying the settings for the indexes in Elasticsearch monstache would create.  By default a MongoDB collection like `db1`.`col1` gets mapped to an index named `db1.col1`. 
2. Delete your current index in Elasticsearch
3. Run monstache to re-index using the template from 1.

The problem with just creating an index template and then running monstache is that the index template settings are applied at index creation time.   So you need to delete the index so it gets re-created.

**Comment by xiaoli-yang** [comment]
> I think the order of steps would be
> 
> 1. Create an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) specifying the settings for the indexes in Elasticsearch monstache would create.  By default a MongoDB collection like `db1`.`col1` gets mapped to an index named `db1.col1`.
> 2. Delete your current index in Elasticsearch
> 3. Run monstache to re-index using the template from 1.
> 
> The problem with just creating an index template and then running monstache is that the index template settings are applied at index creation time. So you need to delete the index so it gets re-created.

Thank you very much. According to your suggestion, the data was successfully imported
