### ISSUE TITLE
direct-read-namespaces with pipeline that includes $project doesn't seem to work

### ISSUE THREAD

**Issue by porn** [rwynn/monstache#617]
Hi,
trying to set up the `direct-read-namespaces` with pipeline that includes `$project` stage but the initial sync doesn't seem to work.

Versions:
monstache: 6.7.7
opensearch: 1.2.4
mongoDB: 5.0.9

The `config.toml` file:

```toml
elasticsearch-urls = ["https://admin:admin@localhost:9200"]
elasticsearch-validate-pem-file = false  # localhost only: https://github.com/rwynn/monstache/issues/280

# compress requests to Elasticsearch
gzip = true
# generate indexing statistics
stats = true

direct-read-namespaces = ["production.emails"]
change-stream-namespaces = ["production.emails"]

[[pipeline]]
namespace = "production.emails"
path = "project.js"
```

Working `project.js`:
```js
module.exports = function(ns, changeStream) {
	return [
		{ $match: { 'fullDocument.body': { $exists: 1 } } },
	];
}
```

Failing `project.js`:
```js
module.exports = function(ns, changeStream) {
	return [
		{ $project: { 'fullDocument.subject': 0 } },
		{ $match: { 'fullDocument.body': { $exists: 1 } } },
	];
}
```

When running the working version all works as expected:
- full import is performed initially
- additional updates are propagated to ElasticSearch

When running the failing version the initial sync is not performed and no additional errors are produced by monstache:
```
$ monstache -f config.toml  -verbose
INFO 2022/06/16 17:04:01 Started monstache version 6.7.7
INFO 2022/06/16 17:04:01 Go version go1.17.4
INFO 2022/06/16 17:04:01 MongoDB go driver v1.8.0
INFO 2022/06/16 17:04:01 Elasticsearch go driver 7.0.28
INFO 2022/06/16 17:04:01 Successfully connected to MongoDB version 5.0.9
INFO 2022/06/16 17:04:01 Successfully connected to Elasticsearch version 1.2.4
INFO 2022/06/16 17:04:01 Listening for events
INFO 2022/06/16 17:04:01 Sending systemd READY=1
WARN 2022/06/16 17:04:01 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2022/06/16 17:04:01 Starting http server at :8901
INFO 2022/06/16 17:04:01 Watching changes on collection production.emails
INFO 2022/06/16 17:04:01 Direct reads completed
```
Expected behaviour is that initial sync is performed excluding the `subject` field.

Additional MongoDB updates are propagated to ElasticSearch correctly (excluding the `subject` field) with the failing version though.

Any advice what I'm doing wrong or did I find an actual issue?

**Comment by rwynn** [comment]
I **think** what you need is to alter the pipeline based on whether or not you are reading a change stream or a collection directly.  That is really the only reason `changeStream` is passed in.

```javascript
module.exports = function(ns, changeStream) {
        if (changeStream) {
          return [
	       { $match: { 'fullDocument.body': { $exists: 1 } } },
               { $project: { 'fullDocument.subject': 0 } }
	 ];
        }
	return [
		{ $match: { 'body': { $exists: 1 } } },
                { $project: { 'subject': 0 } }
	];
}
```

The result of reading a change stream will look like https://www.mongodb.com/docs/manual/reference/change-events/ as you have correctly configured. However, the direct reads will simply have your document at the root. 

Finally, you might want to try the `$project` as the last stage in the pipeline.  Although, from reading the docs I don't think that should be required.

**Comment by porn** [comment]
Oh @rwynn, thanks a zillion!

I was wondering what the `changeStream` parameter was about :slightly_smiling_face: Now it's clear!

Didn't read the documentation carefully enough :facepalm: 

> Finally, you might want to try the `$project` as the last stage in the pipeline. Although, from reading the docs I don't think that should be required.

...you're correct, in this case the order didn't matter
