### ISSUE TITLE
Multiple database connection

### ISSUE THREAD

**Issue by lgmf** [rwynn/monstache#619]
Hi

Because of an architectural decision we have two separate mongo clusters on Atlas.
I want to join information from both clusters to index them together on Elasticsearch

For example.:
```
// my-collection-transform-script.js
module.exports = function (doc) {
  function findDataFromAnotherCluster() {
    var filter = {};

    var options = {
      database: "DbFromAnotherCluster",
      collection: "some-collection"
    };

    return findOne(filter, options);
  }
  
  doc.dataFromAnotherCluster = findDataFromAnotherCluster();
  
  return doc;
}
```

Is there a way to connect to both on Monstache?

**Comment by rwynn** [comment]
Hi,
I think the only way to go about doing this in Monstache is to use a go plugin.  In the plugin `init` function you could establish a connection one of the MongoDB atlas clusters.  Then implement the plugin functions e.g. `Map`.  Inside this function you would be getting the created/updated document from whichever cluster was configured in Monstache (the other cluster).  You can then use the go driver api on the first cluster connection `client` to do any logic to combine the 2 documents.  Finally, set the result you want to send to Elastic in the return value. 

- https://github.com/rwynn/monstache/wiki/Go-plugin-guide
- https://www.digitalocean.com/community/tutorials/understanding-init-in-go
- https://github.com/mongodb/mongo-go-driver#usage

**Comment by lgmf** [comment]
Thanks for the answer
