### ISSUE TITLE
mongo OOM in 4.6.0 - too many connections

### ISSUE THREAD

**Issue by timansky** [rwynn/monstache#62]
new version leads to OOM mongoDB (primary)
monstache version 4.6.0
mongoDB 3.4
monstache opens hundreds of connections while direct-read, and this leading to OOM mongod

PS
i'm thinking the problem is with GTM, may be with SplitVector, there is no problem with 4.5.0 (from dockerhub), but exist with 4.5.0 (if manual build)

**Comment by rwynn** [comment]
Thanks. I think I took out the maxSplits in gtm after the 4.6.0 release and need to put that back in to reign in the number of connections produced. 

By the way does the split vector improve the performance for you using 3.6.0?

**Comment by timansky** [comment]
Nope, it was about 1.5x times slower, with 1000000 docs and 4.4.0 version
Ps
will bench later again

**Comment by a-magdy** [comment]
I tried v4.6.0, and it is not sending any data, but v4.5.0 is working fine

with v4.6.0, it is not even throwing errors, this is the log from it (I moved `trace` logs to a file):

```
INFO 2018/04/26 15:39:51 Successfully connected to MongoDB version 3.4.12
INFO 2018/04/26 15:39:51 Successfully connected to Elasticsearch version 6.2.4
INFO 2018/04/26 15:39:51 Sending systemd READY=1
INFO 2018/04/26 15:39:51 Entering event loop
INFO 2018/04/26 15:39:51 Starting http server at :8080
INFO 2018/04/26 15:39:51 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
```

**Comment by rwynn** [comment]
Actually, I've just turned off the split vector stuff until I can figure out what's going on.  And I don't like that it requires admin.  I think I'm seeing pretty good results with the paginating splitter.

**Comment by timansky** [comment]
docs count 1 150 000
```
time docker run --rm -ti -v $(pwd):/config rwynn/monstache:4.4.0 -f /config/config.toml

real	5m19.018s
user	0m0.136s
sys	0m0.023s
```

```
time docker run --rm -ti -v $(pwd):/config rwynn/monstache:4.5.0 -f /config/config.toml

real	9m9.005s
user	0m0.181s
sys	0m0.027s
```

```
time docker run --rm -ti -v $(pwd):/config rwynn/monstache:4.6.1 -f /config/config.toml
real	5m47.058s
user	0m0.152s
sys	0m0.038s
```

**Comment by rwynn** [comment]
Thanks for the numbers. The diff between 4.4.0 and 4.6.1 is basically the number of go routines and connections to Mongodb per direct read collection. That number should be going up which you can verify in mongostat. 

The question would be why does that make it slower.  In this test are mongo, es, and Monstache running on the same machine?

**Comment by timansky** [comment]
No, it was separate machine.
Separate sharded Mongo cluster and separate elastic cluster, and separate machine for monstache

**Comment by rwynn** [comment]
@timansky, when you get a chance can you try 4.6.2 and let me know if this issue has been fixed?
