### ISSUE TITLE
When mongodb deletes the collection documents during using monstache, how to judge whether we deleted the index document in ElastcSearch according to the certain time filed of documents?

### ISSUE THREAD

**Issue by ghcarlos** [rwynn/monstache#621]
Hello, can you answer the question described in the title? ElastcSearch does not delete when Mongo does

**Comment by rwynn** [comment]
If you run monstache with `--verbose` option you should be able to see the requests to Elasticsearch.  Can you verify a delete request is sent when the MongoDB document is deleted?

**Comment by keenancy** [comment]
> If you run monstache with `--verbose` option you should be able to see the requests to Elasticsearch. Can you verify a delete request is sent when the MongoDB document is deleted?

hi rwynn,
We want to delete the data one year ago from mongodb, but we don't want to delete the data in elasticsearch. What should we do? Thanks!

**Comment by rwynn** [comment]
You could disable deletes in monstache using
```toml
delete-strategy = 2
dropped-collections = false
dropped-database = false
```
Then delete the documents in MongoDB.  The delete operations will be ignored.  

N.B.: If you restarted monstache again with deletes re-enabled, then you must ensure that you are not setting `replay=true` or `resume=true` without purging those delete change events from the MongoDB oplog or that would cause those deletes to happen in Elasticsearch.

Another option would be to make a copy of your current indexes using the reindex API
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html
Carefully, read the docs on that as there are many options.

Once you have a backup you can delete the documents in MongoDB, and subsequently restore them to your original index from the backup using reindex with `op_type=create` and `conflicts=proceed`.  

Either way, make sure you test this procedure thoroughly before you do this with production data.

**Comment by ghcarlos** [comment]
Thank you very much for taking the time to answer questions. My real goal is to make a dynamic judgment interception before monstache deletes elasticsearch

The problem has been solved. I have added judgment logic to the doDelete method in monstache. The relevant code is as follows

```
if ic.config.ExpirationDeletionTime > 0 {
		var resp *elastic.GetResult
		var err1 error
		getService := ic.client.Get()
		getService.Index(indexType.Index).Type("_doc").Id(objectID)
		if resp, err1 = getService.Do(context.TODO()); err1 == nil{
			if resp.Found {
				var src map[string]interface{}
				if err2 := json.Unmarshal(resp.Source, &src); err2 == nil {
					expires := time.Now().Add(time.Hour * 24 *-time.Duration(ic.config.ExpirationDeletionTime))
					createdDate, _ := time.Parse(time.RFC3339, src["createdDate"].(string))
					if createdDate.Before(expires) {
						return
					}
					
				}
			}
		}
	}
```
