### ISSUE TITLE
Usage of change streams mongo 3.6+

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#63]
Mongo 3.6 now comes with change streams https://docs.mongodb.com/manual/changeStreams/

Any plans to move to that since I attended MongoDB.local event and they may change something in future in oplog.

Hence, now we have change streams to rescue.

**Comment by rwynn** [comment]
I think I'll take a look at change streams when the official MongoDB go driver gets released.  Looks like they already have support in there.  

Change streams look like they require a collection to be named before starting the watcher.  One nice thing about tailing the oplog is that new collections can be added/removed at any time and the event gets picked up.  

May do a hybrid approach where an event on the oplog triggers an upgrade to using a change stream once the collection is known to monstache.

**Comment by richiarora** [comment]
ah ok so you do have plans to figure it out in future. Great.
Anyhow I noticed a behavior as per my earlier comments 

I have 1 config like : 
stats = false
index-stats = false
elasticsearch-max-conns = 10
elasticsearch-client-timeout = 100
elasticsearch-retry = true
exit-after-direct-reads = true
namespace-regex = '^db\.(collection1|\$cmd)'
dropped-collections = true
dropped-databases = true
resume-write-unsafe = false
cluster-name = "cluster"
direct-read-namespaces = ["db.collection1"]
[logs]
info = "info.out"
error = "error.out"
[[mapping]]
namespace = "db.collection1"
index = "index-db.collection1"
type = "_doc"


it does not copy all the 52930 records in collection1.

But when I use the following config it copies all the 52930 records.
stats = false
index-stats = false
elasticsearch-max-conns = 10
namespace-regex = '^db\.(collection1|\$cmd)'
direct-read-namespaces = ["db.collection1"]
resume = true
resume-write-unsafe = false
cluster-name = "cluster"
exit-after-direct-reads = false
fail-fast=true
[logs]
info = "info.out"
error = "error.out"
[[mapping]]
namespace = "db.collection1"
index = "index-db.collection1"
type = "_doc"

**Comment by rwynn** [comment]
Can you remove elastic-max-conns CONFIG and make sure you’re using latest monstache and try again.

**Comment by a-magdy** [comment]
Hi 

Change streams would be nice, but will that be there by default?

I've tried to update to mongo:3.6 but I got some compatibility problems with "Meteor.js" and one other tool, I think the community doesn't fully support it yet, so if Monstache is going to use it, can we still support mongo:3.4 (without change streams) until 3.6 is widely supported :)

**Comment by richiarora** [comment]
yes change streams are available by default in 3.6
Plenty more is coming in 4.0 transaction support across collections and other important sql type functionalities.

**Comment by rwynn** [comment]
@richiarora initial support for change streams is in master now.  

```
direct-read-namespaces = ["test.test"]
change-stream-namespaces = ["test.test"]

[[pipeline]]
namespace = "test.test"
script = """
module.exports = function(ns) {
  return [
    { $match: {foo: 1} }
  ];
}
"""
```

The pipeline part is optional if you would like to perform an aggregation on both the direct read of the collection and the change events.

**Comment by richiarora** [comment]
@rwynn glad to hear that will definitely give it a try and update here.

**Comment by rwynn** [comment]
I’ve identified an issue with the pipeline part so you may want hold off on that a bit longer. Basically for change stream events you need to $match on fullDocument.foo instead of just foo. I will be adding a flag to indicate whether it’s a change stream or not so the $match can be built accordingly.

**Comment by rwynn** [comment]
With the latest code you can use something like this:

```
[[pipeline]]
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      { $match: {"fullDocument.foo": 1} }
    ];
  } else {
    return [
      { $match: {"foo": 1} }
    ];
  }
}
"""
```
