### ISSUE TITLE
Feature request:  mongo tags

### ISSUE THREAD

**Issue by timansky** [rwynn/monstache#64]
https://docs.mongodb.com/manual/tutorial/configure-replica-set-tag-sets/

it will be nice feature to implement Tags in mongo connections for workload isolation or multi-datacenter support

**Comment by rwynn** [comment]
Hi I’ll take a look into this. Have you tried 
readPreferenceTags in the connect string. Seems there is code to parse that in the driver already. 

https://github.com/globalsign/mgo/blob/master/session.go

Search for readPreferenceTags on that page. Looks like comma separated pairs then separated by colon.
