### ISSUE TITLE
How do I specify a field to be not_analyzed so I can do an exact match?

### ISSUE THREAD

**Issue by jiewmeng** [rwynn/monstache#647]
I want to do an exact match on certain text fields, I notice the default mapping used looks like 

```
    "type": "text",
    "fields": {
        "keyword": {
            "type": "keyword",
            "ignore_above": 256
        }
    }
```

How can I specify the index as `not_analyzed` like documented https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html. Isit possible to do so with Monstache?

**Comment by rwynn** [comment]
hi @jiewmeng please see details here:
https://github.com/rwynn/monstache/issues/487

the short story is that Monstache just sends the data and any [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) you would like to define for that data can be setup in Elasticsearch.

**Comment by jiewmeng** [comment]
Thank you @rwynn!
