### ISSUE TITLE
Strange Time Error

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#65]
I have recently ported from Javascript transform scripts to using a Go plugin, on the whole the plugin is a lot faster and allows for more precise data, which is great. However I have encountered an issue when indexing a larger amount of data (about 121,000 documents):

```shell
ERROR 2018/04/27 23:33:43 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:46 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:48 elastic: bulk processor "monstache" failed: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:48 Bulk index request with execution ID 14 failed: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:53 elastic: bulk processor "monstache" failed: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:53 Bulk index request with execution ID 15 failed: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:53 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:53 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:53 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
ERROR 2018/04/27 23:33:54 elastic: bulk processor "monstache" failed but may retry: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
```
I've tested with multiple documents, and it seems that all docs will write in smaller batches. Wondered if you new what would cause this? From my understanding this kind of error happens a lot when a Javascript time (ms) is transformed into a Go time (s). However the documents in question write ok, and only have ISO date fields.

```json
{
  "name" : "T-3-RtK",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "-iMH4cZtT7eSCa45znWBwg",
  "version" : {
    "number" : "6.2.3",
    "build_hash" : "c59ff00",
    "build_date" : "2018-03-13T10:06:29.741383Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
The only place that I can think of a timestamp being present is in the `monstache` collection for the `ts` delta. This has happened with `4.6.1` and `4.6.2` of monstache. Any pointers where to look would be great. Thanks!

**Comment by rwynn** [comment]
I remember someone else had a similar problem. I think they solved it by checking the date fields in Mongodb. I’ll need to check if it’s possible to create a date in Mongodb that does not parse to json.  

There is something about 0-9999 in the docs here https://docs.mongodb.com/manual/reference/method/Date

Unfortunately I think once a request does not serialize correctly then the driver goes into a failure loop.

**Comment by rwynn** [comment]
About small batches. If you have a max docs or max bytes in your configuration can you try removing them. The default in latest monstache should be to flush at 8mb. I based this on the recs here. 

https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html

**Comment by rwynn** [comment]
You might want to use -verbose mode to see exactly which document is failing.

**Comment by Crispy1975** [comment]
The config is as follows (aside from a few mappings also):
```
mongo-url = "mongodb://localhost:27017"
elasticsearch-url = "http://localhost:9200"
replay = false
resume = true
resume-name = "xxxxxx-local"
cluster-name = "xxxxxx-local"
namespace-regex = "^xxxxxx$"
gtm-channel-size = 512
gzip = true
stats = true
elasticsearch-retry = true
prune-invalid-json = true
dropped-databases = false
dropped-collections = false
verbose = true
```
I'll have a poke around the docs, and do some further testing. Oddly enough it didn't happen with the Javascript scripts...

On the verbose thing... it doesn't seem to stop on the same - or similar - docs, but will pursue that also again and see if I missed anything.

**Comment by Crispy1975** [comment]
You were right... one bad date out of those documents caused the error, and then it went into a kind of loop that it would not recover from. The whole collection in question now replicates... and at a very high speed also. Thanks!

Sorry for the bother. :)

**Comment by rwynn** [comment]
No problem. If you wouldn’t mind can you let me if you detect small batches coming across. They should be around 8mb as I mentioned. This is very important for performance as elasticsearch indexing is far slower than Mongodb reads. The whole pipeline backs if Es is not performing. At that point you start seeing low output (kB instead of mb) in mongostat because the cursor is not being exhausted at full speed. I noticed this when I turned off the indexing stage and noticed just how fast the docs would come out of Mongodb if there was no push back from an indexing stage.

**Comment by Crispy1975** [comment]
Sure, I'll do some runs with some larger document sets (millions) and see how that goes. Probably not this evening (well this morning now ;-).
