### ISSUE TITLE
Trying to update a specific field

### ISSUE THREAD

**Issue by miguelpedrotq** [rwynn/monstache#650]
I am trying to update a specific field using the [[pipeline]]

```
[[pipeline]]
namespace = "listening.mentions"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $project: {
          _id: 1,
          "operationType": 1,
          "fullDocument.profile.photo": 1,
          "ns": 1
        }
      }
    ]
  } else {
    return []
  }
}
"""
````

But everytime I make a change on mongo it trys to update, but tries to updates a document with the _id of ```<nil>```
Returning me this on logs:

```
{"update":{"_index":"allposts","_id":"\u003cnil\u003e"}}
{"doc":{"insertedTime":1665679033459,"profile":{"photo":""}},"doc_as_upsert":true}
```

If I update without the pipeline thig it updates with the correct Id, but I want to update some specific fields

Did anyone had this problem as well?

Best regards

**Comment by rwynn** [comment]
Do you also need the `_id` of the full document?  You currently have only the `_id` of the change event I believe.
```
"fullDocument._id": 1,
```

**Comment by miguelpedrotq** [comment]
The issue remains

**Comment by miguelpedrotq** [comment]
```
elasticsearch-max-seconds = 5
elasticsearch-max-conns = 6
relate-buffer = 2500
direct-read-namespaces = ["listening.mentions"]
change-stream-namespaces = ["listening.mentions"]
dropped-collections = true
dropped-databases = true
delete-strategy = 0
index-as-update= true
workers = ["1","2"]
verbose = true
[logs]
error = "./logs/logs.log"
warn = "./logs/logs.log"
stats = "./logs/logs.log"
info = "./logs/logs.log"
trace = "./logs/logs.log"
[[mapping]]
namespace = "listening.mentions" 
index = "allposts"
[[pipeline]]
namespace = "listening.mentions"
script = """
module.exports = function(ns, changeStream) {
  if (changeStream) {
    return [
      {
        $project: {
          "fullDocument._id": 1,
          "operationType": 1,
          "fullDocument.profile.photo": 1,
          "ns": 1
        }
      }
    ]
  } else {
    return []
  }
}
"""
[[script]]
path = "./scripts/collection_script.js"
``` 
here is the config
and this is the script
```
module.exports = function (doc,ns) {
doc.insertedTime = Date.now();
    var meta = { id: doc.unique };
    doc._meta_monstache = meta;
    return doc;
}
```

I have another question, is it possible to not run this script when its and update?

**Comment by rwynn** [comment]
What is `doc.unique` in your script?  I think now you are projecting 2 fields, `_id` and `profile.photo` in your document.  So I would expect doc.unique to be undefined.  

What happens when you make the script

```javascript
module.exports = function (doc,ns) {
    doc.insertedTime = Date.now();
    return doc;
}

```

There is actually a 3rd argument to the function you might be able to use to determine if it was an insert vs. an update.

```javascript
module.exports = function(doc, ns, updateDesc)
```

See `updateDescription` here -> https://www.mongodb.com/docs/manual/reference/change-events/update/#mongodb-data-update.

But, no it is not possible to not run the script at all when it's an update.

If you use a go plugin instead of javascript there is a `Process` function you can write that enables you to process events at a lower level.
https://github.com/rwynn/monstache/wiki/Go-plugin-guide
https://rwynn.github.io/monstache-site/advanced/#golang

**Comment by miguelpedrotq** [comment]
the doc.unique is a unique field that comes on the doc, the document are posts from multiple networks, so the unique value would be something like network|postId.
I manage to make it work, adding "fullDocument.unique": 1, to the pipeline.
I have another question, I have a field named userTags, that is an array of objects:

```
userTags : [
  {
       'key': 123
  },
  {
       'key': 1234
  }
]
```
if I update the doc with the userTags like : 


```
userTags : [
  {
       'key': 1235
  },
  {
       'key': 12346
  }
]
```
I want to increment thoose tags, not deleting the previous ones and add the new, is this possible?

**Comment by rwynn** [comment]
No, you wouldn't be able to do that without writing you own golang plugin for monstache and implementing the `Process` function which gives you control on how to update Elasticsearch.

**Comment by miguelpedrotq** [comment]
I am having some problems implementing the golang plugin, does this work with multiple workers and using docker-compose?
```version: '3.7'
services:
  monstache1:        
    #image: rwynn/monstache
    container_name: monstache1
    working_dir: /monstache1
    command: 
      -cluster-name apollo -worker 1 -f ./config.toml
    
    volumes:
      - ./monstache:/monstache1/
    environment:
      MONSTACHE_CLUSTER: apollo
      MONSTACHE_MONGO_URL: xxxxx
     build:
       context: .
       dockerfile: Dockerfile
    network_mode: x-network
  monstache2:        
    #image: rwynn/monstache
    container_name: monstache2
    working_dir: /monstache2
    command: 
      -cluster-name apollo -worker 2 -f ./config.toml
    
    volumes:          
      - ./monstache:/monstache2/
    environment:
      MONSTACHE_CLUSTER: apollo
      MONSTACHE_MONGO_URL: xxxxx
     build:
       context: .
       dockerfile: Dockerfile
    network_mode: x-network 
```
I only have to change the file plugin.go? Do I have to make any change on the config.toml like adding mapper-plugin-path.

Thanks for the help
