### ISSUE TITLE
Question: Orchestrate updating an search index definition

### ISSUE THREAD

**Issue by DagW** [rwynn/monstache#660]
Hello! 
I'm looking for a best practice for updating to a new index definition, and switch to using that without having search synchronization downtime.

For example;
We have monstache up and running and synchronizing a mongo collection `things.items` into the search index `items_index` by watching, and our service uses this index to serve search queries.
I then update the index definition to add a new indexed field (since my index is not dynamic), create the new index and reconfigure monstache to target that index.
Monstache now performs the full initial sync, and when that completes we can switch our search service to use the new index.
The problem I see is that before the new index is up-to-date and following changes, we cant switch our service the new index - and the data it uses to serve searches will get further from real time.

Is there a best practice to avoid search downtime and/or minimize the impact?

One solution I can imageine, is if it is possible to synchronize one mongo collection to two search indexes? Ex.
While maintaining the first index `things.items`->`items_index`,
is it possible to configure an additional sync of the same collection `things.items`->`items_index_2`?
That way we could use the old index until we know both are up to date, before switching to the new.

Maybe there are other solutions?
Thanks!

**Comment by rwynn** [comment]
Hi @DagW, like you mentioned it might be nice to be able to target more than one collection with monstache.  I'll look into the implications of a change like that.  

In the meantime, I wonder if you could work around by running 2 or more monstache processes with different output configurations.  And then maybe use index aliases in Elasticsearch for a quick switch over or to facilitate search over multiple indices.

https://www.elastic.co/guide/en/elasticsearch/reference/current/aliases.html

**Comment by DagW** [comment]
Thanks! I decided to go with a 2 process approach for now, but added support would be very welcome :-)
