### ISSUE TITLE
MongoClient missing in filter plugin input

### ISSUE THREAD

**Issue by pvkas** [rwynn/monstache#668]
Hey @rwynn I was exploring this tool and found there is missing `MongoClient` in input argument for `Filter` plugin.
Not sure if there was purpose for keeping the input partial. (Bug or Intentional ?)

There are some use cases where it can be very useful.
#### Example:
Suppose we have **users** collections to be synced and some data related to user is stored in different collection or database.
(ex. reports, pending actions, ...). 
If we want to allow users with certain criteria. Currently, we can not access `input.MongoClient` (`nil`) in **Filter** function to perform all database operations.

#### Solution
- add `*mongo.Client` with [filterWithPlugin](https://github.com/rwynn/monstache/blob/8998b9f7120e61524c0b34214c4aed0d30ef258e/monstache.go#L1407)

**Comment by rwynn** [comment]
Hi @pvkas, 

I think the initial reason behind not passing the client to the `Filter` in golang was to keep consistency with the javascript map/filter where we don't have access to the client.  However, I think at some point I added the client to the Golang Map function input, so now see no reason why not Filter also.  

Thanks for bringing to my attention and submitting a PR.  I will take a quick look and merge it.
