### ISSUE TITLE
linux/arm64 docker images

### ISSUE THREAD

**Issue by adoy** [rwynn/monstache#695]
Hi, would be nice to push on docker hub the linux/arm64 version of the Docker image. If you need help building it let me know.

**Comment by rwynn** [comment]
Hi, would you be able to submit a pull request for this?

**Comment by adoy** [comment]
I created a first PR https://github.com/rwynn/monstache/pull/696 to build binaries for multiple platforms.

**Comment by adoy** [comment]
And here is the second to publish docker images #697

**Comment by rwynn** [comment]
hey @adoy thanks this is an awesome contribution!  I will leave some comments on the PRs.  I will eventually merge it when I get some time.  I don't have much time to spend on this project these days.
