### ISSUE TITLE
Can I sync and tail only one collection?

### ISSUE THREAD

**Issue by yumengw** [rwynn/monstache#73]
I am using direct-read-namespaces and exit-after-direct-reads=false to sync one collection. However, when I change insert doc into another collection under the same mongodb, monstache also sync the changes. How can I limit monstache to tail only one collection?

My config:

mongo-url = "mongodb://db:27017"
elasticsearch-urls = ["http://elasticsearch:9200"]

gzip = true
direct-read-namespaces = ["data.test"]
exit-after-direct-reads = false
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
dropped-collections = true
dropped-databases = true

**Comment by rwynn** [comment]
You can use a regex

https://rwynn.github.io/monstache-site/config/#namespace-regex

```
namespace-regex = '^mydb\.(mycollection|\$cmd)$'
```

Or you can use a filter
```
[[filter]]
script = """
module.exports = function(doc, ns) {
    return ns === 'mydb.mycollection';
}
"""
```
The regex is faster since no javascript interpreter.
