### ISSUE TITLE
should i must start another process of monstache when i  have a new toml config file?

### ISSUE THREAD

**Issue by efvhi** [rwynn/monstache#76]
is there any auto-loaded of new config files functions supported? thanks a lot.

**Comment by rwynn** [comment]
Yes, you would need to start a new process as there is not support for dynamic configuration. 

What types of settings are you looking to update without a restart? Some may be more difficult than others to update once things are in motion.

**Comment by efvhi** [comment]
thanks for your response, sir.  i think i need a dynamic configuration when i save data into new db and collection in mongodb, maybe i could use regex to make something like "^db\.(.*)$" work, but when db is different, it will not work, maybe it should be somthing like ".*", this will make all data be synced,  i do not want synced origin data from mongodb like 'admin', 'local'.... so i think i will need a regex_exclude like "^(admin|local|)\..*$". anyway, if there we want to change config file,  i think we still need a dynamic configuration, will you support this in the future? thanks again.

**Comment by rwynn** [comment]
Monstache should not be syncing MongoDB system collections.  If it is doing that please create a separate issue.

**Comment by rwynn** [comment]
By default, all user db/collection is synced but not system collections.  You should be able to create new db and new collection after monstache is started, add some data and see index requests for collections added after monstache is started.  That is, by default, without any user configured include/exclude regex.
