### ISSUE TITLE
Problem, when try to go get: "unknown field 'CursorTimeout' in struct literal of type gtm.Options"

### ISSUE THREAD

**Issue by WallEnd** [rwynn/monstache#77]
go get 
# monstache-4.6.5
./monstache.go:2674:16: unknown field 'CursorTimeout' in struct literal of type gtm.Options

**Comment by rwynn** [comment]
Sorry for the inconvenience.  This should be fixed now with commit https://github.com/rwynn/gtm/commit/94610373fed2d99a91309d1ff64636f1c60af128

**Comment by WallEnd** [comment]
@rwynn This is great. Thank you very much
