### ISSUE TITLE
one mongodb record(modified many times) generated two es docs

### ISSUE THREAD

**Issue by efvhi** [rwynn/monstache#79]
sometimes the sync is not work. so i shutdown it and restart, but i found that there is two docs generated in elasticsearch

**Comment by rwynn** [comment]
I am not sure how this can happen being that the _id in mongo is mapped to the _id in Elasticsearch.  Each update should override previous. 

Can you explain a bit more about the 2 docs generated by monstache?  They have same or different _id?  They are in the same or different Elasticsearch index?

Are you able to reproduce this in a test?  Should I be able to simply update a document many times and see 2 docs generated or do I need the restart of monstache to make it happen.

**Comment by rwynn** [comment]
Also, what version of MongoDB are you using?  The only way I can think of this happening is it the _id of the update is not being parsed correctly from the oplog causing and index request without an _id thus inserting a new document into Elasticsearch instead of updating one.

For updates Monstache should be pulling the _id from the o2 field in the oplog.
```
"o2" : { "_id" : ObjectId("5b1a813e4feb0341de274ba8") }
```

**Comment by rwynn** [comment]
This sounds similiar to issue #74.

**Comment by efvhi** [comment]
unlucky i just shutdown the monstache process and delete the index in ES. and restart monstache made a direct-read-namespace. everything is fine now.  I use mongo 3.4 and es 6.x. monstache 4.6.5. the document in mongodb  is somthing like below:
`{ "_id" : ObjectId("5b1a813e4feb0341de274ba8") , "a": 1, "b":2, ...}` 
and i made some update make it become something like below:
`{ "_id" : ObjectId("5b1a813e4feb0341de274ba8") , "a": 3, "b":4, ..., "k":10}`
then i found there are two docs in ES:
`{ "_id" : ?, "a": 1, "b":2, ...}`
`{ "_id" : ?, "a": 3, "b":4, ..., "k":10},`
i do not remember what the situation about the _id in ES ...sorry for that. i think it won't happen now. just got some confused.

**Comment by efvhi** [comment]
another question, can I start multi processes to sync collection ? i found there is one process will work. when i start another process use the same toml file or another toml file, it is just hang on and did not do anything. could you show some `workers` example?  i found that the speed of the sync is not quickly. it spent 2~4 seconds from mongodb update to ES update. could all of this happen in 1~2 seconds?

**Comment by rwynn** [comment]
Could you being using cluster-name?  That would make only 1 process do syncing and others waiting for that process to stop before starting (it's for redundancy not performance).  

I think you just want workers (cluster-name unset).  Puts workers = ['a', 'b', 'c'] in a shared toml file.  Then start process a with monstache -f shared.toml -worker a.  Start process b with monstache -f shared.toml -worker b.  And so on.  
It is shown here -> https://rwynn.github.io/monstache-site/advanced/#workers

Are you customizing lots of options?  I've tried to tune the defaults for good performance.  I usually test a sync of 20 million docs and it takes about 20 minutes.  This is without workers, a single process with basically only 2 arguments.

```
monstache -direct-read-namespace test.test -exit-after-direct-reads
```

**Comment by efvhi** [comment]
yes,  cause i have ES cluster. so i used cluster-name in config file.  my config file has lines below: 
`workers = ["w1", "w2", "w3", "w4", "w5", "w6", "w7", "w8", "w9", "w10"]`
`direct-read-namespaces = ["sync.record"]`
`cluster-name = 'docker-cluster'`
`verbose = true`
`exit-after-direct-reads = false`
and then is start process by uising `monstache -f xx.toml -worker w1` and  `monstache -f xx.toml -worker w2`.
for now. there is some sync info pritnted in the screen in process "w1". but there is nothing happend in "w2". 
and w1 has a issue with my direct-read-namespace showing `version_conflict_engine_exception` , does this warning make process "w2" do not work?

**Comment by rwynn** [comment]
Cluster-name in monstache does not mean what you are thinking. It should not be the name of the elasticsearch cluster.   You should not be setting it at all.

**Comment by rwynn** [comment]
Also make sure you have replay = false. That is probably why you see version conflict.

**Comment by efvhi** [comment]
well, thanks a lot, sir.
`cluster-name`

When cluster-name is given monstache will enter a high availablity mode. Processes with cluster name set to the same value will coordinate. Only one of the processes in a cluster will sync changes. The other processes will be in a paused state. If the process which is syncing changes goes down for some reason one of the processes in paused state will take control and start syncing. See the section high availability for more information.

i read this secotion. so i used cluster-name argument, i thought muliprocess of monstache is async. i just want to make the real-time syncing as quickly as it could. l found the if i make a change on a mongodb collection record. there will be 2-4 seconds delay spreading to ES change. i think there should be a way to make the change on ES happen in 1 seconds?

**Comment by rwynn** [comment]
You can set the elastic-max-seconds to 1 but it is deliberately not that small because it causes monstache to flush in small batches instead of large batches.  Larger batches are better for performance.

**Comment by efvhi** [comment]
ok, got it, thanks for your response again, sir.
