### ISSUE TITLE
error tailing oplog files

### ISSUE THREAD

**Issue by richiarora** [rwynn/monstache#81]
Hi i wanted to know what to make out of following entries ? 

ERROR 2018/06/04 19:16:05 Unable to dial mongodb: dial tcp <mongo host>:27017: connect: connection refused
ERROR 2018/06/04 19:16:06 Unable to dial mongodb: dial tcp <mongo host>:27017: connect: connection refused
ERROR 2018/06/04 19:16:06 Unable to dial mongodb: dial tcp <mongo host>:27017: connect: connection refused
ERROR 2018/06/10 23:20:06 Error tailing oplog entries: EOF

**Comment by metanav** [comment]
I guess mongodb is not running at the localhost on default port.

**Comment by richiarora** [comment]
well mongo was working at that point of time. Though mongo is deployed in AWS i could think of it being network issue.

But when i replicated whole environment locally I got 

ERROR 2018/06/21 13:34:14 elastic: http://<elasticsearch host>:9200 is dead
But it was up though.. so couldnt understand why will i get that monstache cannot connect to elasticsearch host

**Comment by metanav** [comment]
Can you share the config.

**Comment by rwynn** [comment]
Can you make sure the URLs for Elasticsearch and MongoDB reported from `monstache -print-config` contain valid host names?  It seems strange that in both error messages there is no host before the `:9200` and `:27017`

**Comment by richiarora** [comment]
hi well hosts was intentionally hidden while pasting error here.

Here is config:

stats = false
index-stats = false
resume-write-unsafe = false
direct-read-namespaces = ["db.collection"]
exit-after-direct-reads = true
elasticsearch-retry = true
graylog-addr = "Richi.local:12201"
[logs]
info = "info.out"
error = "error.out"
[[mapping]]
namespace = "db.collection"
index = "db.collection"
type = "_doc"

Also if i use graylog then i dont get logs in logfiles. i guess its intended to be so.

Run command is 
docker run -it --name monstacheAddCollection -v $(pwd)/addCollection.toml:/config.toml rwynn/monstache -verbose -mongo-url mongodb://Richi.local:55555 -elasticsearch-url http://Richi.local:9200 -f config.toml

**Comment by richiarora** [comment]
Hi another thing to note : If graylog address is provided and say i start monstache but db is already down or elasticsearch is already down then i dont get those logs in Graylog.

**Comment by rwynn** [comment]
I’ve added a wait to the latest version in the scenario of a fatal error. Hopefully this will fix the issue of the logs not having enough time to flush to graylog.

**Comment by richiarora** [comment]
sure I will check and update here.
Also wanted to know if there is reelection in replica set then there wont be any loss of updates right?

**Comment by rwynn** [comment]
@richiarora the mgo driver has a [SYNC](https://github.com/globalsign/mgo/blob/master/cluster.go#L500) phase that runs every 30s to get the current status of MongoDB to react to changes in the cluster.  

See the MongoDB documentation for the connection string to specify different options for how the driver should read from replicas. Here is a link to the supported options in the connection string by the mgo driver:

https://github.com/globalsign/mgo/blob/master/session.go#L336
