### ISSUE TITLE
Unable to get collection names

### ISSUE THREAD

**Issue by SimonKempf** [rwynn/monstache#83]
Hello,
It's the first time I try to connect Elasticsearch and mongoDB together and have some difficulties doing it.
In my config.toml file I specified the collection that will be used by monstache with those parameters : 

namespace-regex = '^switchplus\.(collectePSI|\$cmd)$'
(additionally, if you need to seed an index from a collection and not just listen for changes from the oplog)
(you can copy entire collections from MongoDB to Elasticsearch)
direct-read-namespaces = ["switchplus.collectePSI"]

I'm getting the following error when I run monstache with the config.toml file : 

INFO 2018/06/26 09:38:53 Successfully connected to MongoDB version 3.4.10
INFO 2018/06/26 09:38:53 Successfully connected to Elasticsearch version 6.3.0
INFO 2018/06/26 09:38:53 Entering event loop
INFO 2018/06/26 09:38:53 Sending systemd READY=1
WARN 2018/06/26 09:38:53 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
panic: Unable to get collection names
                for database local: not authorized on local to execute command { listCollections: 1, cursor: { batchSize: 0 } }

Do you have an idea why I can't get the collection names ? Do I have to do something locally ? (ElasticSearch and my MongoDB are on separate server in my case)

Thanks, 
Simon

**Comment by rwynn** [comment]
It sounds like you have security enabled on MongoDB and the user in your Monstache connection string does not have permission to access the database named “local” which is where the oplog is stored. 

There are some details about requirements in getting started. 

https://rwynn.github.io/monstache-site/start/

**Comment by SimonKempf** [comment]
Alright, thank you for your quick response :)
I missed this part in the "getting started" tutorial.. I will edit my mongod.conf

I have another question :
To see if I understand properly, if in the collection of my mongoDB  I have indexes like "index1" and  "index2", using the "direct-read-namespaces" property in the configuration file I can tell monstache to don't copy the whole collection but only the indexes of the collection by doing this : 

direct-read-namespaces = ["switchplus.collectePSI", "collectePSI.index1", "collectePSI.index2"]

Is that right?

**Comment by SimonKempf** [comment]
Okay, thanks a lot for those info :)
