### ISSUE TITLE
Overwriting ES Document

### ISSUE THREAD

**Issue by andyh69uk** [rwynn/monstache#84]
I am using monstache to sync mongo to ES but making changes directly to ES in addition to changes through mongo. The problem I am having is that an update in mongo triggers an index operation in ES which overwrites the document. Is there a setting to make monstache do an update operation instead? Or any other solution to prevent changes being overwritten?

**Comment by rwynn** [comment]
There is no setting currently that would enable an update but I will look into it. 

It seems promising on reading to simply use an update request with an docAsUpsert flag set to true.  

I would need to test switching the current index request to this https://github.com/olivere/elastic/blob/release-branch.v6/bulk_update_request.go

**Comment by rwynn** [comment]
On a related note, Monstache does not support updating/sending only the fields that have changed in the MongoDB document. 

This is simply due to the complexity of doing it correctly across MongoDB and Elasticsearch releases.

**Comment by andyh69uk** [comment]
Thanks for the quick reply, cool I will await any changes :)

**Comment by rwynn** [comment]
@andyh69uk can you try with the new `index-as-update` setting set to true.  You can simply pass `-index-as-update` to the monstache command or put `index-as-update=true` in a config file.

**Comment by andyh69uk** [comment]
Awesome, I have a slight problem with building code on the destination system, any chance of getting a build for this commit?

**Comment by rwynn** [comment]
@andyh69uk just pushed new versions of monstache that have this new option.  Please let me know how that goes.

**Comment by andyh69uk** [comment]
Awesome, I'll check it out first thing Monday and let you know, thank you :)

**Comment by andyh69uk** [comment]
All working, thank you so much
