### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by philrogers** [rwynn/monstache#87]
Would be good to be able to fix a field that will become a AutoCreate index on Elasticsearch. I am dealing with some epoch ms date fields that look like this in mongo
"start_timestamp" : NumberLong("1530195683803000")

fields needs to be divided by 1000 and turned to a date data type before sent into elasticsearch. Would be good if you could set a rule in Config for a collection name fieldname

**Comment by rwynn** [comment]
@philrogers have you tried creating a date mapping in Elasticsearch for the field before indexing?  
https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html
From reading that link, Elasticsearch, by default, will use the format `strict_date_optional_time||epoch_millis` provided you have a explicit mapping indicating the field is a date.  

Alternatively, monstache allows defining a javascript mapping function in your config which may allow you to convert the long value to a javascript date.  Monstache should recognize dates and format as an Elasticsearch date string when indexing.

```
[[script]]
namespace = "mydb.mycollection"
script = """
module.exports = function(doc) {
    doc.start_timestamp = new Date(doc.start_timestamp);  // I think javascript date takes epoch ms
    return doc;
}
"""
```

But I would suggest trying the mapping first, for performance reasons. 

Just let me know if neither of these would work for you.

**Comment by rwynn** [comment]
@philrogers glad to hear you were able to use monstache to build your dashboard.  For some reason I was not able to view it, but I'm sure it's awesome :-)  I'll close this but please open another issue if you run into problems.

**Comment by philrogers** [comment]
Thank you for your help

**Comment by philrogers** [comment]
Hi Ryan,

 

I have a quick question

 

I have a mongo object that is big a subset of the data looks like this

 

"log" : [ { "status" : "requested", "timestamp" : ISODate("2018-05-28T03:27:37.840Z") }, { "status" : "delayed", "timestamp" : ISODate("2018-05-28T03:27:37.949Z") }, { "status" : "requested", "timestamp" : ISODate("2018-05-28T03:28:41.585Z") }, { "status" : "scheduled", "timestamp" : ISODate("2018-05-28T03:28:41.718Z") }, { "status" : "running", "timestamp" : ISODate("2018-05-28T03:28:41.820Z") }, { "status" : "succeeded", "timestamp" : ISODate("2018-05-28T03:29:13.685Z") } ]

 

I have a script like this

 

 

[[script]]

namespace = "st2.action_execution_d_b"

script = """

module.exports = function(doc) {

 

 

for (i = 0; i < doc.log.length; i++) {

        var d =  doc.log[i]['timestamp'];

         console.log("debug ->" + doc.log[i]['status'] + ": " + d);

  }

}

 

I am struggling to decode the timestamp object in ISODATE to a java script date as I need to do some date calcs across status codes

To work out lapse times.

 

Some other dates in the document are in epoch which decode fine with the date function. But cant work this one out

 

Thanks

Regards

Phil

**Comment by rwynn** [comment]
@philrogers maybe this will help.  Given docs in MongoDB with a createdAt ISODate field...

```
direct-read-namespaces = [ "db.collection" ]

[[filter]]
namespace = "db.collection"
script = """
// set threshold to 15 days ago in ms
var delta = 15 * 24 * 60 * 60 * 1000,
    thresh = (new Date()).getTime() - delta;
module.exports = function(doc) {
    var ts = doc.createdAt;  // createdAt is a MongoDB Date() field that you've stored
    return (ts.Unix()*1000) >= thresh;
}
"""

```

If you store the field in MongoDB as a Date or ISODate, is it surfaced to scripts as a Go **time.Time** object in javascript. That is why the above script is calling function (https://golang.org/pkg/time/#Unix).

If you create a Date() object in the script itself, then that has the properties of a normal javascript Date.  

I only just recently realized this while doing some investigation for someone else.  I'll need to document the behavior.

**Comment by philrogers** [comment]
Hi Ryan

Your a legend ts.Unix()*1000) did the trick.
 
Just one last question if I then calculated 2 new fields and wished to add to the doc object as integer is that possible. Sorry for all the questions.
 

Regards

Phil

**Comment by rwynn** [comment]
Yep as long as you are within a [script] function all new fields added to the doc in the script get indexed.

**Comment by philrogers** [comment]
That field was suppose to say Delaysecs 

just want to append that field to the doc object in the Javascript function

Assume the field exists in elasticsearch index

**Comment by rwynn** [comment]
@philrogers if I understand you correctly you want to add a new calculated field before indexing in Elasticsearch.  You can do that with a script.

```
[[script]]
namespace = "mydb.mycollection"
script = """
module.exports = function(doc) {
    // ensure existence of 2 ISODate fields from MongoDB
    if (doc.startDate && doc.endDate) {
        // add a calculated field for Elasticsearch only
        doc.Delaysecs = doc.endDate.Unix() - doc.startDate.Unix();
    }
    // return the updated doc so that it gets indexed instead of the original
    return doc;
}
"""
```

**Comment by swaddy** [comment]
hi rwynn,

The doc.endDate.Unix() can get the seconds timestamp, what function to use if I want to get the milliseconds timestamp.

very appreciate if you can reply.

**Comment by rwynn** [comment]
hi @swaddy, I am not aware of a simple solution.  You might want to try using a [golang plugin](https://rwynn.github.io/monstache-site/advanced/#golang) for more control.  

* git clone https://github.com/rwynn/monstache.git
* cd monstache
* git checkout v6.6.0
* go install
* vi myplugin.go
* go build -buildmode=plugin -o myplugin.so myplugin.go
* $GOPATH/bin/monstache -mapper-plugin-path ./myplugin.so

**Comment by swaddy** [comment]
@rwynn ok, thanks for your proposal

it seems there was already an argument with the time of golang

https://github.com/golang/go/issues/18935
