### ISSUE TITLE
Syncing deleted items

### ISSUE THREAD

**Issue by dischob** [rwynn/monstache#88]
I'm using MongoDB 3.4.5, ElasticSearch 6.3.1 and Monstache 4.8.0.
When I delete an item in MongoDB, it is not deleted in ElasticSearch.
I read about the oplog in MongoDB, that should be fine. I'm using the default settings for delete-strategy (0).

At the moment no clue why delete is not working. Anyone some help for me?
I included the conf file for Monstache.
![config](https://user-images.githubusercontent.com/25578817/43182676-986ab356-8fe2-11e8-9dac-726d2d3f3b3b.jpg)

**Comment by rwynn** [comment]
Does scoping the search to a specific index help?

delete-index-pattern = “someName-view-somedata”


Also try without any namespace regex applied.

**Comment by dischob** [comment]
I use the namespace regex to only sync the views in my MongoDB.
There are about 6 collections that need to be synced. Does the delete-index-pattern still work the same way then?

**Comment by rwynn** [comment]
When a delete operation is read from the oplog the namespace has to match the regex and only if that happens it proceeds to do a search in Elasticsearch for a doc with the same _id as the _id that was deleted. If that search returns exactly 1 document then a delete is issued to Elasticsearch.  The delete-index-pattern is the scope of that search. Defaults to all indexes.

**Comment by rwynn** [comment]
It actually doesn’t even do the search in Elasticsearch if a simple mapping is used like you have. The best thing to do would be to turn verbose on and try a manual delete. That will at least show if a request is made and what it is.  You will probably want to run with direct reads OFF since those will flood the log.

**Comment by rwynn** [comment]
I’ll take a look when I get some time. The tests are passing and they include verifying a delete. But they don’t test all possible configurations.  E.g. they don’t include a namespace filter or a mapping.

**Comment by rwynn** [comment]
It just dawned on me that you are using the view feature in MongoDB. I have not done any testing/research with views but I will look into it. Since views are read only I’m assuming you are doing the delete operation on the underlying collection not the view?

My guess is that the oplog will only contain namespaces that match collections not views since the views are a projection of this underlying data.

**Comment by dischob** [comment]
I am not using the view function. I call it view because it is a view of data from different collections. The view is build in the domain.

**Comment by rwynn** [comment]
Ok, I misunderstood.  Thought you were using the newish [view feature](https://docs.mongodb.com/manual/core/views/) of MongoDB which as it turns out is probably a use case I should handle.  I need to make a few changes to support that.  

Anyway, in that case I am not able to reproduce the problem with deletes yet then.  I tried to replicate your config (including the regex) and when I issued a manual delete I saw the following:

```
{"delete":{"_index":"somename-view-somedata","_type":"view-somedata","_id":"5b58dc791aa4d2b05966ef03","version":6582253482399498242,"version_type":"external"}}
```
And was able to verify that it got removed from Elasticsearch.

The MongoDB version I have is 3.6.0 though, so not sure that matters.

**Comment by rwynn** [comment]
I also cannot seem to replicate the issue on MongoDB server version: 3.4.16.  Are you using sharding by any chance?

Do you see the delete operations being logged in the oplog?

```
rs1:PRIMARY> use local;
switched to db local
rs1:PRIMARY> db.oplog.rs.find({op: "d"})
{ "ts" : Timestamp(1532554898, 1), "t" : NumberLong(1), "h" : NumberLong("-307242930596868568"), "v" : 2, "op" : "d", "ns" : "someName.view-somedata", "o" : { "_id" : ObjectId("5b58ee8b34daba3b43a9da97") } }
{ "ts" : Timestamp(1532554929, 1), "t" : NumberLong(1), "h" : NumberLong("-3332957909906056650"), "v" : 2, "op" : "d", "ns" : "someName.view-somedata", "o" : { "_id" : ObjectId("5b58eeb034daba3b43a9da98") } }
```

**Comment by dischob** [comment]
Maybe I should elaborate a bit more about the setup. Because I think it has something todo with the update to the new version of ElasticSearch.
My index in ElasticSearch looks as follows:
index: database name . collection name
type: collection name _1 (alias = collection name)
Each time the app starts, it checks the settings and mappings. If there is any change, an update is done. The type will become collection name _2 ...
The alias always stays the same so that there is no change for the code.

So actually Monstache is connecting to an alias. This was done so the app is not interrupted. Maybe the problem is situated there?

**Comment by rwynn** [comment]
I'm not sure what you mean by the type having an alias.  My understanding is that only indexes may be aliased.  Do you mean you are using index aliases?

At a basic level, you indicated that monstache does not even make a delete request at verbose level when you delete something in MongoDB.  If this is the case it would not matter how Elasticsearch is setup.  

By delete request I mean something like this in the monstache -verbose log...

```
{"delete":{"_index":"somename-view-somedata","_type":"view-somedata","_id":"5b58dc791aa4d2b05966ef03","version":6582253482399498242,"version_type":"external"}}
```

That request may be failing in Elasticsearch but I want to establish whether or not that request is being made and what the content of the request is.

**Comment by rwynn** [comment]
Also can you try the following in your config:

```
routing-namespaces = ["someName.view-somedata"]
```

That combined with a stateless delete with force monstache to do a **search** by id for the document before scheduling it for deletion. 
https://github.com/rwynn/monstache/blob/master/monstache.go#L2402

Sounds like you re-index to a new type and switch the index alias pointer on an update.  Problem is that monstache uses the type information in the [[mapping]] (which I'm assuming is not changing).  I tried to omit the type information from a delete request but Elasticsearch doesn't like that.

**Comment by dischob** [comment]
Ok I finally get a delete showing up in the verbose and it is working now. Looks like it was more a typo on my side. :(
The one thing that still bothers a bit is the speed. I delete an item in UI, the page is refreshed and the item is still there because the syncing is only done a second later. Is there anything I can do about that or not?
I tried playing with the gtm-channel-size and gtm-buffer-size and gtm-buffer-duration, but still get stuck with a second or 2 delay.

**Comment by rwynn** [comment]
Try elasticsearch-max-seconds setting.

**Comment by rwynn** [comment]
When you configure direct reads, the default for max-seconds gets bumped to 5s. This is because you don’t want to force flush too often when reading millions of documents. You would rather send large bulk requests than small. However you can override this by just explicitly setting max seconds to e.g 1.   After a second all changes to MongoDB will be flushed to Elasticsearch.

**Comment by dischob** [comment]
Ok thank you very much for your help! I don't think I need further assistence on this matter.

**Comment by rwynn** [comment]
Thanks. Just wanted to mention that you could use a 2 process approach.  

The first monstache process could be configured for realtime updates with an `elasticsearch-max-docs` set to 1 and no direct reads configured.  This will flush each change as soon as it reads from the oplog with no buffering.    

Then you can periodically run a 2nd monstache process with the defaults except for the addition of `direct-read-namespaces` added and `exit-after-direct-reads` to true.  This will read as fast as it can from MongoDB but buffer up to `elasticsearch-max-bytes` (8MB) of data before sending the bulk to Elasticsearch (optimize for throughput).  The time your choose between runs could be based on how much data you have and how long each run typically takes.

**Comment by rwynn** [comment]
Also for the real-time process you will probably want to increase elasticsearch-max-conns (# of concurrent clients) to maybe 20 since they will each by sending 1 update at a time.   

You would not want to increase the max conns for the 2nd case since each conn buffers up 8mb.  You could overload Elasticsearch that way.

**Comment by Harika-3196** [comment]
> Ok I finally get a delete showing up in the verbose and it is working now. Looks like it was more a typo on my side. :(
> The one thing that still bothers a bit is the speed. I delete an item in UI, the page is refreshed and the item is still there because the syncing is only done a second later. Is there anything I can do about that or not?
> I tried playing with the gtm-channel-size and gtm-buffer-size and gtm-buffer-duration, but still get stuck with a second or 2 delay.

Can you share your toml file Even Im not able to delete or update the changes in oplog to elastic search. Thanks in advance.Currently i have this one .      

mongo-url ="mongodb://localhost:27017"
elasticsearch-url ="http://localhost:9200"
namespace-regex ='youtube_db.^'
direct-read-namespaces = ["youtube_db.youtube_data"]
enable-oplog = true
gzip = true
stats = true
index-stats = true
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-name = "default"
resume-write-unsafe = false
verbose = true
elasticsearch-retry=true
elasticsearch-max-conns=20
[logs]
info = "/home/ubuntu/logs/info.log"
warn = "/home/ubuntu/logs/warn.log"
error = "/home/ubuntu/logs/error.log"
trace = "/home/ubuntu/logs/trace.log"
[[mapping]]
namespace = "youtube_db.youtube_data"
index = "youtube_index"
type = "youtube_index"

exit-after-direct-reads = false

**Comment by rwynn** [comment]
@Harika-3196 

Monstache buffers events in order to send them in bulk to Elasticsearch.  If you want Monstache to flush after each event you can set https://rwynn.github.io/monstache-site/config/#elasticsearch-max-docs.

```
elasticsearch-max-docs = 1
```

Also, since you have MongoDB 3.6, you can use change streams and not direct access to the oplog.

```toml
enable-oplog = false
change-stream-namespaces =  ["youtube_db.youtube_data"]
resume-strategy = 1
# you don't need a regex anymore
# namespace-regex ='youtube_db.^'
elasticsearch-max-docs = 1
```

**Comment by Harika-3196** [comment]
> ```toml
> elasticsearch-max-docs = 1
> ```

Thanks @rwynn everything is working perfectly including updation, deletion, automatic change of mappings . Very thankful to monstache.

**Comment by Harika-3196** [comment]
Thanks 

> @Harika-3196
> 
> Monstache buffers events in order to send them in bulk to Elasticsearch. If you want Monstache to flush after each event you can set https://rwynn.github.io/monstache-site/config/#elasticsearch-max-docs.
> 
> ```
> elasticsearch-max-docs = 1
> ```
> 
> Also, since you have MongoDB 3.6, you can use change streams and not direct access to the oplog.
> 
> ```toml
> enable-oplog = false
> change-stream-namespaces =  ["youtube_db.youtube_data"]
> resume-strategy = 1
> # you don't need a regex anymore
> # namespace-regex ='youtube_db.^'
> elasticsearch-max-docs = 1
> ```



> @Harika-3196
> 
> Monstache buffers events in order to send them in bulk to Elasticsearch. If you want Monstache to flush after each event you can set https://rwynn.github.io/monstache-site/config/#elasticsearch-max-docs.
> 
> ```
> elasticsearch-max-docs = 1
> ```
> 
> Also, since you have MongoDB 3.6, you can use change streams and not direct access to the oplog.
> 
> ```toml
> enable-oplog = false
> change-stream-namespaces =  ["youtube_db.youtube_data"]
> resume-strategy = 1
> # you don't need a regex anymore
> # namespace-regex ='youtube_db.^'
> elasticsearch-max-docs = 1
> ```




Thanks @rwynn  thanks for the reply everything is working perfect now both updation and deletion .Thanks a lot for monstache .
