### ISSUE TITLE
When MongoDB data contains values like +Infinity, -Infinity, NaN, or invalid dates

### ISSUE THREAD

**Issue by pet2016** [rwynn/monstache#95]
when MongoDB data contains values like +Infinity, -Infinity, NaN, or invalid dates，i don't want to drop the values，and synchronous values to elasticsearch, What am I supposed to do?

**Comment by rwynn** [comment]
You can use a script to change the values. The problem is that these values are not allowed by the go json serializer.

**Comment by pet2016** [comment]
Okay, thank you
