### ISSUE TITLE
MongoDB aggregation in Middleware?

### ISSUE THREAD

**Issue by metanav** [rwynn/monstache#96]
Can we do aggregation on the collection in the middleware (preferably in Javascript)? 
I want to sync a set of MongoDB documents as an aggregated document in Elasticsearch.

**Comment by rwynn** [comment]
Are you referring to doing an aggregation/pipeline call inside a script or do you mean reading a collection as the result of running a pipeline instead of as the set of all raw records?  The latter would be run before any scripts are invoked. The former inside a script.

**Comment by metanav** [comment]
I mean inside a script. When a document  is added/modified in mongodb, the middleware script gets a reference of the document and it would call an aggregation pipeline on the same collection for related documents of the current document and the result will be saved in elastic.

**Comment by rwynn** [comment]
Thanks. I will look into adding that.

**Comment by metanav** [comment]
Thanks @rwynn. One more thing you may consider: the aggregation pipeline can have a lookup stage to fetch documents from other collections.

**Comment by metanav** [comment]
I think this  can be done using the middleware go plugin? But I wanted to do in Javascript.

**Comment by rwynn** [comment]
Yes this should be possible today with a go plugin since it surfaces the mgo.Session providing access to the Pipeline function. 

For this issue I was planning to surface the Pipeline function via JavaScript like what it currently implemented for find, findOne, etc.

**Comment by rwynn** [comment]
@metanav I've added the ability to do this via a new `pipe` function to the master branch.  It looks like this...

```
[[script]]
namespace = "test.test"
script = """
module.exports = function(doc, ns) {
  doc.extra = pipe([
    { $match: {foo: 1} },
    { $limit: 1 },
    { $project: { _id: 0, foo: 1}}
  ]);
  return doc;
}
"""
```
The first argument to `pipe` is the aggregation pipeline to run.  The second optional argument allows you to set the db and collection like you can with the `find` function. e.g. `{ db: "db1", collection: "col2" }`.

**Comment by metanav** [comment]
@rwynn Thanks! I will test it later and let you know.

**Comment by rwynn** [comment]
@metanav  you can also now use change streams via `change-stream-namespaces` option.  Finally, you can apply aggregation to both direct reads and change streams via a definition like this....

```
[[pipeline]]
namespace = "test.test"
script = """
module.exports = function(ns) {
  return [
    { $match: {foo: 1} }
  ];
}
"""
```
