### ISSUE TITLE
Feature request: go plugin could access Elasticsearch or return several documents

### ISSUE THREAD

**Issue by VitaliStupin** [rwynn/monstache#99]
Monstache go plugins are able to access MongoDB session. It would be nice to be able to additionally have access to Elasticsearch session to perform custom inserts/updates/deletes.

For example I am currently using Monstache plugin to partition data based on a certain field values (monthly partitions based on timestamp). But sometimes this field value gets updated in MongoDB and the document needs to be moved to another index. This updated document gets to the new index nicely, but older version of this document is not deleted from old index. Because of that multiple documents with the same "_id" may appear in different Elasticsearch indexes.

Also there might be some use cases when MongoDB document needs to be splitted into several separate indexes in Elasticsearch. Or maybe some related documents in Elasticsearch need to be updated based on new document that was changed in MongoDB.

I see at least 3 ways that could be achieved:

1) Go plugin is given access to elastic.Client. Possibly the most universal solution because custom elasticsearch queries can be performed but might be slower.
2) Go plugin is given access to elastic.BulkProcessor. This way it would be possible to add multiple requests (delete/update/insert). But it would be strange to add some documents to Elasticsearch manually and return only one document to monstache.
3) Go plugin could return multiple documents. And monstache would just add all the results to the elastic.BulkProcessor. This solution is probably sufficient for most cases and the easiest for plugin writers, but it lacks additional flexibility elastic.Client can give.

**Comment by rwynn** [comment]
@VitaliStupin if you build from master you can now add a new function named `Process` to your golang plugin.  This function will get called with a new input, `ProcessPluginInput`, which gives you access to the elastic client and the bulk processor.  

https://github.com/rwynn/monstache/blob/master/monstachemap/plugin.go

The `Process` function signature should be `func(*monstachemap.ProcessPluginInput) error`

**Comment by VitaliStupin** [comment]
Process function is a great addition, but now I understood that it might be further improved. Mongo object id is not available for plugin (or I cannot find that?), and it is probably not necessary for "Map" function, because the addition to elastic is done by Monstache. But for Process func it might be useful if there is a need to update or delete items created by "Process" function.

**Comment by rwynn** [comment]
That sounds like a good idea. I think I will make available oplog Timestamp as well as that is used by default as the Elasticsearch version number.

**Comment by rwynn** [comment]
You should now be able to access at input.Document["_id"]. Thanks.

**Comment by VitaliStupin** [comment]
Thank you! This addition works for me perfectly.
